### PR TITLE
Added requirements.txt

### LINKED ISSUE #1661: Having a Requirements.txt or completing install_requires
While writing the script for appveyor, I realize that NetworkX misses a requirements.txt and hence does not avail the `pip install -r requirements.txt` option while installing. Some of the packages are optional but should be included in the `requirements.txt` to provide the option of *complete* installing of all the dependencies. In my opinion, populating `install_requires` of `setup.py` for this purpose is not a good idea.

### PR DESCRIPTION
**Pull request by karrtikr**
Fixes #1661

@chebee7i @jfinkels @hagberg Have a look on this. Also suggest modifications as I don't have much ideas of the dependencies being used by NetworkX.
Thank you

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Hi, Inspired by the problem of generating `requirements.txt` and dependencies analysis, I wrote a script to read all the modules and list out all the package imports. I'd like to share the result here for networkx. It's a dictionary of two dictionaries 'builtins' and 'nonbuiltins' where the number denotes the number of imports of the particular import.
```
{'builtins': {'StringIO': 1,
  '__future__': 12,
  'ast': 4,
  'bisect': 2,
  'bz2': 1,
  'cPickle': 1,
  'cStringIO': 1,
  'collections': 21,
  'contextlib': 1,
  'copy': 6,
  'fractions': 1,
  'functools': 6,
  'glob': 1,
  'gzip': 1,
  'heapq': 8,
  'htmlentitydefs': 1,
  'importlib': 1,
  'io': 1,
  'itertools': 53,
  'json': 1,
  'lib2to3': 3,
  'math': 11,
  'operator': 9,
  'os': 15,
  'pickle': 1,
  'random': 17,
  'setuptools': 1,
  'shlex': 1,
  'string': 1,
  'subprocess': 1,
  'sys': 11,
  'tempfile': 1,
  'time': 2,
  'timeit': 1,
  'types': 1,
  'uuid': 1,
  'warnings': 7,
  'xml': 10},
 
'nonbuiltins': {'decorator': 1,
  'html': 1,
  'matplotlib': 14,
  'nose': 32,
  'numpy': 61,
  'ogr': 1,
  'osgeo': 2,
  'pandas': 3,
  'pygraphviz': 6,
  'scikits': 1,
  'scipy': 64,
  'yaml': 3}

}
```

We can use the second dictionary to populate the `requirements.txt` ! :)

**Comment by SanketDG** [comment]
`html` module is built in.
`ogr` is an internal module from `osgeo`.
By scikits, its probably [`scikits.sparse`](http://scikits.appspot.com/scikits.sparse)

**Comment by OrkoHunter** [comment]
> html module is built in.

I don't think [html](https://pypi.python.org/pypi/html) is a builtin package. It's not available in `sys.builtin_module_names` or `pkgutil.iter_modules`.

> ogr is an internal module from osgeo.

Yes, `ogr` is not a package in itself. So, I think [this line](https://pypi.python.org/pypi/html) should be modified to
```py
from osgeo import ogr
```
like [this](https://github.com/networkx/networkx/blob/master/networkx/readwrite/nx_shp.py#L192).

> By scikits, its probably scikits.sparse

Yes, it should be `scikits.sparse`. Thanks ! I'll need to modify the script for such packages. Right now, it's just picking up what's before the first dot as a dependency.

**Comment by SanketDG** [comment]
> I don't think html is a builtin package. It's not available in sys.builtin_module_names or pkgutil.iter_modules.

If I `grep` for `import html` in the codebase:

```shell
networkx/readwrite/gml.py:53:    import htmlentitydefs
networkx/readwrite/gml.py:56:    import html.entities as htmlentitydefs
```
`import htmlentitydefs is from python2 and `import html.entities as htmlentitydefs` is for python3. They have the same functionality. The package you linked to is definitely different, I think.

**Comment by OrkoHunter** [comment]
You are right. `html` is a builtin module in Python 3.

**Comment by SanketDG** [comment]
Also for documentation, add `Sphinx` and `sphinx-rtd-theme`

**Comment by dschult** [comment]
I believe the osgeo (and thus ogr) come with gdal.  At least with conda I install gdal to get these features.

Also pyparsing needs to be a version before 2.0 for pydot to work. (not sure why neither of these came up in your search). pyparsing=1.5 seems to work.

**Comment by MridulS** [comment]
Note: pydot on pypi was last updated for python 2.6.

**Comment by SanketDG** [comment]
> Also pyparsing needs to be a version before 2.0 for pydot to work. (not sure why neither of these came up in your search). pyparsing=1.5 seems to work.

@dschult wasn't the `pyparsing` dependency removed?

> Note: pydot on pypi was last updated for python 2.6.

@MridulS `pydotplus` supports python3, which is used if `pydot` is not found.

**Comment by dschult** [comment]
I was using networkx-1.10 instead of dev.... so ignore my comment about pyparsing. 

Still true that gdal is the package that gives osgeo and ogr (I think)

**Comment by dschult** [comment]
I think the follow should do it.  At least with these installed, no tests get "skipped" and docs build.

decorator
numpy
scipy 
matplotlib
nose
pandas
gdal
pyyaml
pygraphviz
sphinx
sphinxcontrib-bibtex
sphinx_rtd_theme

For python2 we need
pydot
pyparsing=1.5

For python3 instead we need
pydotplus

**Comment by karrtikr** [comment]
@dschult Should I create two requirements file for different versions?

**Comment by dschult** [comment]
I don't actually know how pip handles that...  
Can you work through their help page?
Or maybe @OrkoHunter or @chebee7i know?

**Comment by SanketDG** [comment]
pip has a `-r` flag which takes any file as a argument.

The standard practice I have seen is having `py2-requirements.txt` and `py3-requirements.txt` along with proper documentation of using these separately with separate python versions.

On a sidenote, do we have to use `pydot`, given its not updated in a few years? If yes, will it possible to have a maintained fork?(I realize this calls for some extra work)

**Comment by OrkoHunter** [comment]
Generally, this problem is solved by having two or more requirements file as we can't really do any magic inside them, those are simply text files. We'll need to write in the documentation about separate usage and installation using `pip` and `pip3`.

But because of the repetitions in both the files, one another method is to have this
#### requirements.txt
```
the
long
list
of
common
dependencies
```
#### py2-requirements.txt
```
-r requirements.txt
pydot
```

#### py3-requirements.txt
```
-r requirements.txt
pydotplus
```

**Comment by dschult** [comment]
The [pydotplus webpage](https://pypi.python.org/pypi/pydotplus) says that pydotplus is compatible with python2.7-3.5.  Since we don't support python2.6 any more maybe we can get by with pydotplus for all our configurations. Has anybody tried pydotplus with python2.7?

It'd be nice to jettison pydot if we can use a single package to replace it (as @SanketDG notes).

**Comment by dschult** [comment]
See #1898 for a switch to using pydotplus instead of both pydot and pydotplus. Its a maintained version and works for all versions of python that we support.  So @karrtikr can your switch that name and remove the pyparsing line?

I think this means we have the same file for both python2 and python3.

**Comment by jfinkels** [comment]
I like to separate runtime dependencies from test dependencies and documentation dependencies. Three files: `requirements.txt`, `requirements-doc.txt`, and `requirements-test.txt`, with the last two recursively including the first one using `-r`. See https://github.com/jfinkels/flask-restless/ for example. This allows the user to only install a subset, plus it allows you to update documentation dependencies independently of runtime dependencies (like if you need to add a sphinx extension, for example). Is this sort of setup attractive to others?

**Comment by hagberg** [comment]
It's helpful to the packagers and maintainers to explicitly indicate dependencies so I don't mind being more detailed here in how those dependencies come about.   i.e. 3 files is OK with me.

**Pull request merged**
