### PR TITLE
Python syntax highlighting

### PR DESCRIPTION
**Pull request by EQt**
.. in README/Github front page

### CODE REVIEW

**Comment by dschult** [comment]
Do you know a way to see what this will look like on github before merging it?

**Comment by ericmjl** [comment]
@dschult I can confirm that this renders properly. 

To get there: "Files changed -> View file".

Screenshot attached.
screen shot 2019-01-09 at 2 57 19 pm

**Comment by ericmjl** [comment]
Because this change is minimal and renders properly, I am feeling comfortable doing the merge. Hope you don't mind, @dschult :smile:.

**Comment by dschult** [comment]
Thanks very much @ericmjl !!   :)

**Pull request merged**
