### PR TITLE
NXEP 0 and NXEP 1 - change status to Accepted

### PR DESCRIPTION
**Pull request by MridulS**
We should change the status of our governance NXEP to "Accepted".

### CODE REVIEW

**Comment by jarrodmillman** [comment]
I want to double-check that it is up-to-date before merging this.

**Comment by MridulS** [comment]
Just wanted to bump this up @jarrodmillman

**Comment by MridulS** [comment]
@jarrodmillman should we have this in before 3.0?

**Review by dschult — APPROVED** [review]

**Review by rossbar — APPROVED** [review]
Thanks @MridulS - there was [no objection on the mailing list](https://groups.google.com/g/networkx-discuss/c/ggOYGkb_vWk) so in this goes!

**Pull request merged**
