### PR TITLE
Extended Barabasi-Albert Model

### PR DESCRIPTION
**Pull request by bjammal**
The aim of this pull request is to include a new random graph model in the library. The model is described as extended Barabási–Albert model.

As described in "Albert, R., & Barabási, A. L. (2000). Topology of evolving networks: local events and universality. Physical review letters, 85(24), 5234.", the model introduces some probabilities. Based on the probabilities 'p' and 'q' with (p+q) < 1, the growing behavior of the graph is determined as follows:
    
    1) With 'p' probability, 'm' new edges are added to the graph, 
    starting from randomly chosen existing nodes and attached preferentially at the other end.
    
    2) With 'q' probability, 'm' existing edges are rewired
    by randomly chosing an edge and rewiring one end to a preferentially chosen node.
    
    3) With (1-p-q) probability, 'm' new nodes are added to the graph, with edges attached preferentially (using preferential attachment: a new node is more likely to connect to an existing node with a high node degree).
    
    And when p=q=0,the model behaves just like Barabasi-Albert model.

a method called _extended_barabasi_albert_graph_ is added to the file _networkx/random_graphs.py_ and a unit testing method _test_extended_barabasi_albert_ is added to the file _networkx/generators/test_random_graphs.py_.

For further information, please feel free to get back to us. We appreciate your feedback.

### CODE REVIEW

**Comment by mcognetta** [comment]
This is cool, but it is failing because you are using python2 print statements. Maybe also consider using fstrings instead of the old string formatting stuff as well.

**Comment by bjammal** [comment]
now it's passing.. we don't need the print here, does everything look ok for you?

**Comment by dschult** [comment]
This looks good. I tried to push some pep8 changes. The biggest changes are to shrink wording to 80 chars per line.  See if you agree with my rewording of comments.

**Comment by bjammal** [comment]
Perfect thank you, agree on your changes. I just corrected some typos in comments.

**Pull request merged**
