### PR TITLE
Add timing tests and baseline classes to compare to.

### PR DESCRIPTION
**Pull request by dschult**
This style of testing works with nose and compares to
previous code (v1.9) so it gives long term baseline.
Its a step toward v2.0 where base classes will change.

We can't overload this or tests will take too long.
As currently config'd it adds about 5 seconds.

The code also runs on its own and produces a timing report.
  python test_timing.py

### CODE REVIEW

**Comment by hagberg** [comment]
Looks like the numpy import failed with pypy.  It isn't so useful to test the performance of external packages anyway so maybe we should remove that one?  My understanding is that you want to capture the performance of the base classes with these tests.

**Comment by dschult** [comment]
Yes, the intent is to test the base classes. I have one test to convert to a numpy matrix though.
I've removed that. 

But I think Travis is unable to even find a scipy compatible with pypy and it used to be able to do that. Perhaps wheelhouse has changed the files it makes available.

I may be missing something else with the travis system too--a lot has changed there.

**Comment by hagberg** [comment]
I haven't been following pypy very closely but they might not have a numpy implementation that provides what we need.  Certainly no scipy package.

**Comment by hagberg** [comment]
I'm relying on @chebee7i  and @ysitu to help with the travis config.  It is fairly comprehensive/complicated now.

**Comment by chebee7i** [comment]
It looks like the wheelhouse we were using stopped providing Scipy for everything except py27. So we're going to have to find another source or disable testing of dependencies for everything except 2.7.

Perhaps we should consider using (mini)conda for TravisCI instead of wheels now? 
http://conda.pydata.org/docs/travis.html

**Pull request merged**
