### PR TITLE
Make nx.hits a wrapper around different implementations, use scipy one by default

### PR DESCRIPTION
**Pull request by MridulS**
Wrappers for HITS, https://github.com/networkx/networkx/issues/4371

### CODE REVIEW

**Review by rossbar — APPROVED** [review]
LGTM, thanks @MridulS !

Just to double check: the plan was to remove `hits_numpy` rather than leave it in as a (potentially private) reference implementation? That's what was done for pagerank but I just wanted to make sure that this is indeed the plan, and that there isn't really any value in keeping the numpy implementation around.

**Comment by MridulS** [comment]
I'm probably remembering this wrong but I think we decided on keeping all the implementations in the codebase but just removing them from the user facing API, so if someone wants to look at the code/use it they still can if they want explicitly.

[This ties in the abstract NX API proposal where if a numpy array like graph object is passed in we could dispatch it to the numpy function to do the computations]

**Comment by rossbar** [comment]
> but I think we decided on keeping all the implementations in the codebase but just removing them from the user facing API, so if someone wants to look at the code/use it they still can if they want explicitly.

Yeah this is what I thought too... so the plan in NX 3.0 will be to change `hits_numpy` to `_hits_numpy` rather than remove it entirely after the deprecation expires?

**Comment by MridulS** [comment]
>Yeah this is what I thought too... so the plan in NX 3.0 will be to change hits_numpy to _hits_numpy rather than remove it entirely after the deprecation expires?

Yeah :)

**Review by jarrodmillman — APPROVED** [review]

**Pull request merged**
