### PR TITLE
Enable mayavi in sphinx gallery.

### PR DESCRIPTION
**Pull request by rossbar**
Should generate images/thumbnails for the 3d drawing example that uses mayavi.

See: https://sphinx-gallery.github.io/stable/configuration.html?highlight=mayavi#image-scrapers

### CODE REVIEW

**Comment by rossbar** [comment]
Still have to figure out the magic recipe to get mayavi installed via pip on ubuntu.

**Comment by jarrodmillman** [comment]
It looks like pip tries to build the mayavi wheel before it installs anything from the requirements file.  It needs vtk and something , so I made ``example-requirements.txt`` with vtk and pyqt5.  It was also complaining about not having Qt, so I installed pyqt5 instead of pyside2. See cda9757

So mayavi is being installed and run now, but we have this error

```
make: Entering directory '/home/circleci/repo/doc'
sphinx-build -b html -d build/doctrees   . build/html
Running Sphinx v3.2.1
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

make: *** [Makefile:46: html] Aborted (core dumped)
make: Leaving directory '/home/circleci/repo/doc'
```

I failed to fix this in 5a52c5d, b725200, and bd7dfa4.  After you see what I tried feel free to get rid of those commits.

**Comment by rossbar** [comment]
Yup I was getting the same errors originally. I had no trouble, but my desktop environment is built with Qt, so I must've had all of the requirements installed by default. I'll take another stab before Thursday

**Comment by rossbar** [comment]
It seems like the error we were getting wasn't due to missing dependencies, but rather due to mayavi having trouble running headlessly (i.e. without a frame buffer). There is a work-around buried deep in the [mayavi docs](https://docs.enthought.com/mayavi/mayavi/tips.html?highlight=xvfb#rendering-using-the-virtual-framebuffer) for how to set things up with a virtual frame buffer. This seems to be the approach adopted by sphinx-gallery.

I borrowed [some of sphinx-gallery's CI configuration steps](https://github.com/sphinx-gallery/sphinx-gallery/blob/5511bbaed9235e0fe4183ad75911ad8cd0502d3d/.circleci/config.yml#L1-L22) which does the trick.

In the grand scheme of things, the extra dependencies (particularly pyqt5 and vtk) add ~30sec/1min to CI build time. IMO this is okay, but something to keep in mind if our build times get too long, since all of this extra stuff is basically just for a single gallery example.

I think squashing this down to 1 commit is fine, but if you'd like me to squash to 2 commits (one for the example, and a second for the CI config) so that we have it in the history I'm happy to do so.

**Review by jarrodmillman — APPROVED** [review]

**Pull request merged**
