### PR TITLE
Fix reference in line.py-inverse_line_graph

### LINKED ISSUE #6428: Reference for inverse_line_graph
There is a spelling mistake in the reference for the documentation of inverse_line_graph (latest version). 

https://networkx.org/documentation/stable/reference/generated/networkx.generators.line.inverse_line_graph.html

The author is "N. D. Roussopoulos" instead of N. Roussopolous (note the location of "ou"). Also, it would be nice to add a link or DOI to the article. The complete bibliographic info is below. 

@article{ROUSSOPOULOS1973108,
title = {A max {m,n} algorithm for determining the graph H from its line graph G},
journal = {Information Processing Letters},
volume = {2},
number = {4},
pages = {108-112},
year = {1973},
issn = {0020-0190},
doi = {https://doi.org/10.1016/0020-0190(73)90029-X},
url = {https://www.sciencedirect.com/science/article/pii/002001907390029X},
author = {Nicholas D. Roussopoulos},
keywords = {graph, maximal subgroup, complete graph, complete bipartite, automorphism}
}

### PR DESCRIPTION
**Pull request by Blueclaus13**
This is a pull request with the changes in the documentation to resolve "Reference for inverse_line_graph #6428   "

Closes #6428

### CODE REVIEW

**Review by rossbar — APPROVED** [review]
I took the liberty of pushing up a minor change to better conform to the docstring standard, as well as fix the linting error. LGTM, thanks @Blueclaus13 !

**Comment by Blueclaus13** [comment]
Thank you for the help! 
Could you help me to understand why failed the test in style-Test the external Hyperlink? 
Screen Shot 2023-02-15 at 11 33 15

**Comment by rossbar** [comment]
> Could you help me to understand why failed the test in style-Test the external Hyperlink?

Indeed the diff from the failed CI run is a little confusing... the reason it failed was because there was an extra whitespace at the end of the line (i.e. `_ `).

**Comment by Blueclaus13** [comment]
ooh got it! thank you! :) I'm excited, this was my first pull request in life haha

**Review by dschult — APPROVED** [review]
Thanks!!

**Pull request merged**
