### PR TITLE
Code coverage nonrandomness

### PR DESCRIPTION
**Pull request by cpurmessur**
Added two tests to improve code coverage of nonrandomness.py

### CODE REVIEW

**Review by dschult — APPROVED** [review]
Nice

**Review by rossbar — APPROVED** [review]
Looks good - if you feel up to it the docstring for `non_randomness` would probably benefit from adding something about these exceptions. There is no mention in the docstring that `non_randomness` won't work if `G` has self-loops or unconnected nodes. The simplest thing to do would be to add a `Raises` section to the docstring that highlights these cases.

I don't mean to pile more onto your plate though! I will leave this open for a day or so in case you want to take a crack at it, otherwise I'll put this in and create an issue to track the doc suggestion. As always thanks for the improvement @cpurmessur !

**Comment by cpurmessur** [comment]
Hi, I updated the docstring but for some reason, one of the tests has failed. I am not too sure what the issue is

**Comment by rossbar** [comment]
Awesome, thanks @cpurmessur - the test failure just looks like a CI problem and not anything related to your changes.

**Pull request merged**
