### PR TITLE
Fix inverse_line_graph.

### PR DESCRIPTION
**Pull request by hutchison**
Tests included.

### CODE REVIEW

**Comment by dschult** [comment]
Thanks for this!
Which test showed you that the current function has a bug?
I think the tests for line.py are in tests/test_line.py
Can you move your new tests in there?

**Comment by hutchison** [comment]
> Which test showed you that the current function has a bug?

`inverse_line_graph` had a bug. It produced a wrong root graph for "K_4 minus e".

> Can you move your new tests in there?

Sure, will do.

**Comment by hutchison** [comment]
Should I open up another pull request?

**Comment by dschult** [comment]
No new pull request needed. If you commit to your local and then push to your github copy of networkx it will update the PR on the networkx Github automatically.

Thanks!

**Comment by hutchison** [comment]
Is there anything else that I can/have to do, before this gets merged?

**Comment by dschult** [comment]
Thanks for the gentle bump. I was hoping to get time to check through that code and understand where/why the bug arose in the first place. But I don't think that is going to happen. So...

Can you change the line that you already changed from ```v not in G_partition.neighbors(u)``` to
```v not in G_partition[u]```?  Lookups on a dict are much better than lookups on an iterator that is created from the dict anyway... :} .  That's one reason I wanted to check through that code. It seems non-optimal and this might have other bugs...

Thanks very much!

**Comment by hutchison** [comment]
Done. In the run I replaced all calls to `neighbors()`.

**Comment by hutchison** [comment]
There's also another issue: `inverse_line_graph()` doesn't construct a root graph for isolated nodes or more generally a graph which is composed of components. We should loop over all components and construct a root graph by calling `inverse_line_graph()` for every component. But I have no idea how costly that would be.

**Comment by dschult** [comment]
Perhaps the multiple component version of inverse_line_graph should be included as a Notes section in the docstring telling people (in very general but clear terms) how to do it themselves.

I'm not sure how it would be done exactly... call inverse_line_graph on each component separately?

**Comment by hutchison** [comment]
> Perhaps the multiple component version of inverse_line_graph should be included as a Notes section in the docstring telling people (in very general but clear terms) how to do it themselves.

Okay, I'll try my best.

> I'm not sure how it would be done exactly... call inverse_line_graph on each component separately?

Yes, exactly. In the current implementation `inverse_line_graph` just chooses an arbritrary edge `e` and starts from there. This way only the component containing `e` gets inverted and the other components are being ignored.

Furthermore: currently an isolated node won't be inverted, but that's wrong, because L(K_2) = K_1. In that case `invert_line_graph` should just return a K_2, but how should the nodes be named? `networkx.utils.misc.generate_unique_node()` seems a bit ugly. Is there a better way?

**Comment by dschult** [comment]
Ack!  I hope I didn't mess this up completely.
Did you have more to change/address with this commit?
(maybe the K_1/K_2 case?)

**Comment by hutchison** [comment]
Thanks!

> Did you have more to change/address with this commit?

I was awaiting your thoughts on this. But I'll just write a quick patch to fix this edge case.

**Comment by dschult** [comment]
Great!   Thanks!

**Pull request merged**
