### PR TITLE
Add heuristics for Traveling Salesman Problem 

### PR DESCRIPTION
**Pull request by dschult**
From @Overriders work on #1508 and #1554

### CODE REVIEW

**Comment by dschult** [comment]
@rossbar 
This PR might be of interest because it shows some approximate algorithms involving e.g. simulated annealing.  

But, it also uses random numbers and you might be interested to see 
1) how we handle code using the built-in ```random``` package while maintaining ```numpy.random``` as out main tool.  The decorators @py_random_state and @np_random_state and supporting functions in ```networkx/utils/decorators.py``` handle that in a way that allows a single seed to control all random events.  
2) This is tested in ```networkx/tests/test_all_random_functions.py``` which feels very kludgy and is hard to ensure that it gets updated when it should.  You may have seen a better way in another package if you have worked with reproducible random numbers before.

**Comment by rossbar** [comment]
Thanks for the ping @dschult , it does indeed look interesting. NumPy recently introduced a whole new random API in v1.17, so that's another angle to consider as well :). I will take a look

**Comment by dschult** [comment]
We put this "new" treatment of random number generators in place after the v1.17.0 release. I think that release provided pressure on us through issues to standardize RNGs throughout the package. And to let people use a single RNG for all networkx routines, or (the default) use a separate RNG for each function so that it doesn't touch the state of any other RNGs.

**Review by dschult — COMMENTED** [review]
This add traveling salesman problem heuristic.

Seems a little silly to approve my own PR, but its actually not mine. It is my updating of @Overwriters from previous PRs.  Anyway, I think this is ready.

I can't officially approve these changes.    But I approve them. :)

**Comment by jarrodmillman** [comment]
I will review this and look at Christofides #3585 at the same time.  I would like to get them both in before 2.6.

**Comment by dschult** [comment]
This PR is now contained in #4607

**Pull request closed without merging**
