### PR TITLE
Remove unused variable in mycielski.py

### PR DESCRIPTION
**Pull request by katalinschmidt**
Removed unused variable in mycielski.py (prev line 55).
Thanks for the opportunity to make my first pull request - great project!

### CODE REVIEW

**Comment by dschult** [comment]
Congratulations on your first PR!  
Could you also move the line `n = M.number_of_nodes()` outside of the loop?
Or maybe just delete the one that is in the loop. :}

Also, the style-checker found that your editor removed the end-of-line character from the end of the file. Could you put that back in? (or run "black" on this file...   `pip install black` should work if you want to install it.)

**Review by rossbar — COMMENTED** [review]
I don't think this change is correct, `n` is used multiple times in the for-loop a few lines below.

**Comment by rossbar** [comment]
Whoops - I now see what you were getting at - `n` is *also* set in the loop. The question is: should this be done inside or outside of the loop...

**Comment by dschult** [comment]
Whoops.... my bad...  The value of n changes with each iteration of the loop.  I missed the fact that we add nodes to M inside the loop so n keeps increasing each time.

I guess this is fate's way of having you really learn about updating your PRs.  Could you change it back again to having n computed inside the loop?  Thanks!!

**Comment by katalinschmidt** [comment]
Hope that works now - sorry about that!

**Review by dschult — APPROVED** [review]
Looks good to me!

**Review by jarrodmillman — APPROVED** [review]

**Pull request merged**
