### PR TITLE
adding support for singleton in add_path and add_star

### PR DESCRIPTION
**Pull request by TanayGahlot**
WIP- I have added the support for adding an iterator with a single element(Singleton). I will add the test cases as well.

### CODE REVIEW

**Comment by dschult** [comment]
Don't worry about the test failures on travis. They are not related to your pull request. It looks like the version of numpy has changed on one of the builds in travis and so matrices are printing differently. That's the first failure. The second is a re-appearance of problems with testing kcomponents where valid random graphs never get generated. I restarted it, hoping it will work this time, but I'll look into that further in another PR.

Thanks for this!  looking forward to your tests.

**Comment by dschult** [comment]
Fixes #3277

**Comment by TanayGahlot** [comment]
Hi @dschult, I have added testcases as well, kindly review my contributions.

**Comment by dschult** [comment]
Looks good!  Can you also add a test for an empty list? That will cover the try/except clause.

**Comment by TanayGahlot** [comment]
Hi @dschult, 
  Thanks for the review. I have added the case of an empty iterator as well.
 Kindly review my contributions.

**Comment by dschult** [comment]
Excellent!  Thanks very much!

**Pull request merged**
