### PR TITLE
Rewrites quotient so it can implement block model

### PR DESCRIPTION
**Pull request by jfinkels**
This commit removes the `blockmodel()` function (and its containing
module `networkx.algorithms.block`) and adds code to the
`quotient_graph()` function so that it can handle the use cases for
`blockmodel()`.

This is a backwards-incompatible change; it removes a function.

This fixes issue #1580.

I can add an alias from `blockmodel` to `quotient_graph`, or vice versa, if preferred.

### CODE REVIEW

**Comment by MridulS** [comment]
This breaks the code, https://github.com/networkx/networkx/pull/1845 uses `blockmodel`. I guess we could add an alias for it.

**Comment by hagberg** [comment]
Yes, I missed that.
Let's add an alias for now anyway.

**Comment by dschult** [comment]
If we're going to remove blockmodel long term anyway, let's change the place in #1845 that uses it to use ```quotient_graph```. 

Putting in the alias for backward compatibility is fine too, but our codebase should use what we expect to exist long term.

**Comment by MridulS** [comment]
Using an alias still breaks backward compatibility as the arguments of the function `blockmodel` and `quotient_graph` are different. `nx.quotient_graph(G, partition, create_using=nx.MultiGraph())` has to be used instead of `nx.blockmodel(G, partition, multigraph=True)` .Should we remove `blockmodel` then?

**Comment by jfinkels** [comment]
One solution: I could add a `multigraph` keyword argument and document that
it should be used for backwards compatibility only.

**Comment by dschult** [comment]
We could also create a wrapper function ```blockmodel``` using old syntax which then calls quotient_graph with the correct arguments.

**Comment by MridulS** [comment]
I have added a wrapper function in https://github.com/networkx/networkx/pull/1886. I have also added a note in the documentation.
```
    Notes
    -----
    This function has been deprecated. Please use ``quotient_graph`` instead.
```

**Comment by sbenthall** [comment]
FYI, I've been looking for the `blockmodel` function (which I remember from a previous version) for about 20 minutes and wasn't able to determine what happened to it until I found this issue.

I was not able to find a reference to the function with the deprecation warning in the current documentation, and the deprecation notice isn't in the previous version docs either.

https://networkx.github.io/documentation/networkx-1.9.1/reference/generated/networkx.algorithms.block.blockmodel.html

Also, though I searched for it, I wasn't able to find a reference to this deprecation in any of the release notes.

**Comment by dschult** [comment]
A search for "Networkx blockmodel" returns an example from the gallery and the code points out that the relevant function is now called ```quotient_graph```.  The deprecation notice was put in [PR #1886](https://github.com/networkx/networkx/pull/1886).   A search for blockmodel on the networkx documentation page returns 4 items one of which is ```quotient_graph```, another is the example found above.    In the ```quotient_graph``` docstring  it explicitly shows how to implement the blockmodel idea using quotient_graph.

It looks like it is not in the release notes. But otherwise fairly well covered.  Want to put it in a release doc?

**Comment by sbenthall** [comment]
You are right, it's fairly well covered.
If you could point me to the right doc, I would make a PR with the edit.

**Pull request merged**
