### PR TITLE
Support GEXF version 1.3 schema definition

### PR DESCRIPTION
**Pull request by boofarzab**
Change the GEXF class to support GEXF file format version 1.3.

### CODE REVIEW

**Comment by dschult** [comment]
Is there more expected for this? 

You've added the label/webpage urls for a new version, but no changes to code?
Does it all work the same as before?
Also, the GEXF webpage does not mention version 1.3 at all...

**Comment by boofarzab** [comment]
I came up with version 1.3 when exporting a graph to GEXF from Gephi since current Gephi 0.9.2 seems to be exporting with 1.3 by default right now, although 1.3 is told to be work in progress (see [https://github.com/gephi/gexf/wiki](https://github.com/gephi/gexf/wiki) .

As far as I can tell everything seems to be working as expected, I can work on the graph as usual.

**Comment by dschult** [comment]
Thanks for the explanation. I didn't have that link.
It is interesting that the github GEXF primer you point to only talks about 1.3 on the Wiki and not in the repository. The Wiki examples all use 1.3draft instead of 1.3.
I wonder where Gephi is getting the specs for 1.3 to export 1.3 by default now...

**Comment by vlado-s** [comment]
I can confirm that when the graph nodes have the viz attributes (color, size, position), then the export via version 1.2draft cannot be read by Gephi 0.9.2 (latest release). If these attributes are not defined, then an export according to the 1.2draft version can be read (there will be a warning about deprecated format, but it will be opened) in Gephi 0.9.2.

The addition by @boofarzab does not help :) (I figured out the same "modification" independently, but no other change to code was done by me).

So, will the latest (and now default) version 1.3 be supported in NetworkX? Would be very useful.

If it will not be done in foreseeable time, can we get some hints about which parts of the code need to be fixed? So far I know about the networkx/readwrite/gexf.py module. But this itself does not define the exact format (as far as I could tell)?

Thanks

**Comment by dschult** [comment]
Yes, we need the specs for the format (and hopefully what changed between versions). 
Otherwise it is very hard to make code that mimics what Gephi is doing. 
I'm not sure why they are using a format that don't seem to be created yet for their file structure.

**Comment by MridulS** [comment]
1.3 is out now https://gexf.net/schema.html plus 1.1 is deprecated.

 @boofarzab let me know if you have the bandwidth to fix up this PR (merge conflicts and maybe also deprecate 1.1 support in networkx), if not I can build on top of your PR and get this into networkx :)

Thanks for you contribution!

**Comment by rossbar** [comment]
#5597 looks like it's probably related too.

**Comment by MridulS** [comment]
We need to make sure our gexf parser actually does conform with GEXF 1.3, I'll close this PR and keep #5597 as the tracking issue to check our compatibility with 1.3

**Pull request closed without merging**
