### PR TITLE
Fix layout.py and revert changes to default scales.

### PR DESCRIPTION
**Pull request by dschult**
The rescale function doesn't work as advertised due to
scaling based on biggest positive value (ignoring most
negative value). Other bugs include throwing out all
edge information if the incoming graph is not an instance
of nx.Graph.

Finally, the changes made to the API were made with
NetworkX 2.0 in mind. I guess they should have been
reverted when we made a v1.10 release to avoid surprises.
See issue #1750 and #1759

### CODE REVIEW

**Comment by AgostinoSturaro** [comment]
Thank you for this PR.

I notice a different behavior for `spring_layout`, the area nodes are spread upon appears significantly smaller in this PR than in 1.9.1.
I can't reproduce it in smaller examples, but it pops up when I use it in more complex situations.

I started swapping the `layout.py` in 1.9.1 and in this PR, remembering to erase the compiled `layout.pyc` too, and found out that they indeed behave differently.

Comparing the 1.9.1 layout module with the one in your PR, some interesting can be found.
The biggest one I see is that the second to last line of the functions `_fruchterman_reingold` and `_sparse_fruchterman_reingold` went missing.
Restoring that line fixes the problem for me when calling `spring_layout` in my larger programs.

        t-=dt
        pos=_rescale_layout(pos)
    return pos

Other differences I noted.
In function `fruchterman_reingold_layout`, `pos_arr` is defined and overwritten

    if pos is not None:
            dom_size = max(np.array(pos.values()).flatten())
            pos_arr=np.asarray(np.random.random((len(G),dim)))*dom_size
            pos_arr=np.asarray(np.random.random((len(G),dim)))

`t` is defined like this in `_fruchterman_reingold`, as in v1.10

    # compute this in case our domain becomes bigger than 1x1.
    t = max(max(pos.T[0]) - min(pos.T[0]), max(pos.T[1]) - min(pos.T[1]))*0.1

but it's defined like this in `_sparse_fruchterman_reingold`, as in v1.9.1

    # the initial "temperature"  is about .1 of domain area (=1x1)
    # this is the largest step allowed in the dynamics.
    t=0.1

There are probably other things I didn't caught.

**Comment by dschult** [comment]
I can't get it to be different between versions--but maybe I am not trying the right "more complex situations".  Are you using the ```fixed``` option or providing a starting position array? Or by more complex do you mean the graph is more complex?  

Also, is the difference seen with spring_layout (which is fruchterman_reingold) or another layout routine?
:)

**Comment by AgostinoSturaro** [comment]
By more complex I mean I used it in a bigger piece of code, but could not isolate the problem.
Now I found it and I edited my post to include a test case. I used `spring_layout`.

It would help reproducibility to add a `seed` parameter to these functions.
An instance of NumPy random generator could be initialized with that seed inside each functions, like this

    my_np_random = np.random.RandomState(seed)

**Comment by dschult** [comment]
It looks like you can set the seed for the default RandomState object using
```np.random.mtrand.seed(seed)```
Call that before ```nx.spring_layout``` and the results should be the same.

But this involves changing the global seed... might be good to have a seed argument for these methods so they don't impact other random processes going on.

I'll look at your test case.

**Comment by AgostinoSturaro** [comment]
Thank you for looking into this.

Declaring a separate instance of `RandomState` would avoid creating unwanted side effects.
Same goes for Python's `random` module, I usually create a separate instance

    my_random = random.Random(seed)

In fact, I just noticed that graph generators, like [this](https://github.com/networkx/networkx/blob/v1.10/networkx/generators/random_graphs.py#L47) and [this](https://github.com/networkx/networkx/blob/v1.10/networkx/generators/random_graphs.py#L602) change the default seed for `random`, which may be another thing worth looking into. Should I open an issue?

    if seed is not None:
        random.seed(seed)

**Comment by dschult** [comment]
OK... the trouble seems to be from removing those ```_rescale_layout``` lines in fruchterman_reingold.
We did that to fix a bug (keep the fixed nodes from being changed). I've reinstated it inside a check for fixed nodes.  I think this should fix your problems.

**Comment by AgostinoSturaro** [comment]
Thank you.
Would it be possible to add the `scale` parameter to `random_layout`?
It's the only layout lacking it.

The center from v1.10 parameter could be added back, IMHO.
All it takes is a call to a function `_recenter(node_pos, center)` at the end of the layout functions, and maybe a check for fixed positions.

This way we could keep functionalities introduced in 1.10, but make them compatible with v <= 1.9.1.
The default center would need to be 0.5, 0.5, and then scaled.

**Comment by dschult** [comment]
The decision that has to be made for centering is whether the points should be in the range [0, scale] with default center at scale/2, or in the range [center-scale, center+scale] with default center 0.
Notice that the second version is twice as large as the first.

How these parameters should affect the layout when some nodes are fixed is not clear...

I will try to fix the bugs in v1.10 and put the center feature back in with range [0,scale] and default center at scale/2.  Then we can have a discussion about what range to use for NetworkX 2.0.

Thanks for your other suggestions too.

**Comment by dschult** [comment]
OK... I think I've addressed each of your suggestions @AgostinoSturaro Can you try it one more time and see what you think?

All the bugs I know of (including missing doc references) are removed and the ```center``` and ```scale``` keywords are on each function. I've added a bunch of tests, but they still mostly qualify as smoke-tests.  More could be done here.

The different functions produce different domains for the positions (as they have in the past). I think we should keep it that way -- Some layouts are more naturally provided in domains centered on the origin and others make more sense in a unit square. We'll have to decide that for sure in v2.0, but I'm currently thinking it should stay different.

**Comment by AgostinoSturaro** [comment]
Thank you.
I tested this and it works for me.

Below are some tests I written, maybe you can turn them into proper unit tests.

    import numpy as np
    import networkx as nx
    import matplotlib.pyplot as plt
    
    def check_inside(layout_pos, scale, center):
        half_scale = scale / 2.0
        left_border = center[0] - half_scale
        right_border = center[0] + half_scale
        bottom_border = center[1] - half_scale
        top_border = center[1] + half_scale
    
        # check if positions are inside the box
        for node, pos in layout_pos.items():
            if not left_border <= pos[0] <= right_border:
                print('node {} pos x outside box'.format(node))
            if not bottom_border <= pos[1] <= top_border:
                print('node {} pos y outside box'.format(node))
    
    def check_center(layout_pos, scale, center, tolerance_perc):
        # calculate the actual area occupied by the nodes
        first_it = True
        for pos in layout_pos.values():
            x = pos[0]
            y = pos[1]
            if first_it is True:
                x_min = x
                x_max = x
                y_min = y
                y_max = y
                first_it = False
            else:
                if x > x_max:
                    x_max = x
                elif x < x_min:
                    x_min = x
                if y > y_max:
                    y_max = y
                elif y < y_min:
                    y_min = y
        x_span = x_max - x_min
        y_span = y_max - y_min
    
        # check if the center of the area occupied by the nodes is the intended one
        actual_center = np.array([x_min + x_span / 2.0, y_min + y_span / 2.0])
        if abs(actual_center[0] - center[0]) > scale * tolerance_perc:
            print('the x coordinate of the center is far from the intended one')
        if abs(actual_center[1] - center[1]) > scale * tolerance_perc:
            print('the y coordinate of the center is far from the intended one')
    
    
    G = nx.barabasi_albert_graph(99, 3, 5724916525465685432)  # create a densely connected graph
    
    G.add_edge(G.number_of_nodes(), G.number_of_nodes() - 1)  # add a new node connected by a single edge
    G.add_node(G.number_of_nodes())  # add a new unconnected node
    
    base_center = np.array([0.5, 0.5])
    scales = [0.5, 1.0, 1.5, 2.0]
    tolerance_perc = 0.1 # tolerance for comparing the final center and the intended one
    
    for scale in scales:
        print('scale = {}'.format(scale))
        center = base_center * scale
        # layout_pos = nx.random_layout(G, dim=2, scale=scale, center=center)
        # layout_pos = nx.circular_layout(G, dim=2, scale=scale/2.0, center=center)
        # layout_pos = nx.shell_layout(G, dim=2, scale=scale/2.0, center=center)
        layout_pos = nx.spring_layout(G, dim=2, scale=scale, center=center)
        check_inside(layout_pos, scale, center)
        check_center(layout_pos, scale, center, tolerance_perc)
        nx.draw_networkx(G, pos=layout_pos)
        plt.show()
        plt.close()

**Comment by AgostinoSturaro** [comment]
Thank you and congratulations for your work

What about adding a `seed` parameter, is that an option that was considered?
Thanks.

**Comment by dschult** [comment]
The seed parameter should probably be a separate issue... (see #1764  :)

**Comment by AgostinoSturaro** [comment]
Thanks, I guess we can close #1750 then.

**Pull request merged**
