### PR TITLE
Update installation test instructions

### PR DESCRIPTION
**Pull request by EricPostMaster**
Small text update to resolve [Issue 6302](https://github.com/networkx/networkx/issues/6302).

### CODE REVIEW

**Review by rossbar — COMMENTED** [review]
Better yet would be to recommend a test invocation that works regardless of environment setup. I'd vote for replacing the `PYTHONPATH=. pytest networkx` line with `pytest --pyargs networkx`, which should work for both conda-managed and traditional development environments.

**Comment by faze-geek** [comment]
As someone who just setup `networkx` locally, `PYTHONPATH=. pytest networkx` did not work for me too. I used the miniforge prompt and had to run `pytest networkx` .So this command would be used for a bunch for command line terminals like Anaconda prompt, Miniforge prompt, Command prompt.
+1 for `pytest --pyargs networkx` for consistency across all platforms !

**Comment by jarrodmillman** [comment]
Just checking since I don't use conda. You were able to successfully execute this command:
```
pip install -e .
```
And then at the same command prompt that you successfully executed that command, what error message did you get when you entered
```
PYTHONPATH=. pytest networkx
```

My understanding is that
```
pytest --pyargs networkx
```
should test the installed package and that
```
PYTHONPATH=. pytest networkx
```
should test the source directory.

It probably makes more sense to test the installed package, but I can't remember why we didn't recommend that originally.

**Comment by faze-geek** [comment]
> Just checking since I don't use conda. You were able to successfully execute this command:
> 
> ```
> pip install -e .
> ```
 Yes !
> And then at the same command prompt that you successfully executed that command, what error message did you get when you entered
> 
> ```
> PYTHONPATH=. pytest networkx
> ```
```

C:\Users\kunni\networkx>PYTHONPATH=. pytest networkx
'PYTHONPATH' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by rossbar** [comment]
Thanks @faze-geek - yet another reason not to recommend PYTHONPATH: windows

**Comment by EricPostMaster** [comment]
@rossbar - I got the same error as @faze-geek. I don't understand Conda and path stuff well enough to know why this solution worked, just that it did 😅

**Comment by MridulS** [comment]
+1 on using `pytest --pyargs networkx` all around. @EricPostMaster could you update the instructions to just that instead of `PYTHONPATH`? Thanks!

**Review by rossbar — APPROVED** [review]
I took the liberty of pushing up the suggested pytest incantation per the discussion here and in the NX meetings. Thanks @EricPostMaster

**Pull request merged**
