### PR TITLE
Fix: Louvain limit iterations in `_one_level`

### PR DESCRIPTION
**Pull request by vpipkt**
We used `louvain_communities` on a large number of graphs and found that 99.99% of cases it worked well. But in a small set of inputs we found the Louvain community algorithm failed to converged. This manifests as a long running process because the execution is stuck in an infinite loop.

With some debug logging in place we see that for certain inputs, `networkx.algorithms.community.louvain._one_level` will keep moving the same node between the same two communities, and never exit the loop `while nb_moves > 0`. 

This PR adds a unit test with one such graph and also proposes to break out of the loop if the number of moves exceeds the number of nodes ** 1.2.

### CODE REVIEW

**Review by rossbar — COMMENTED** [review]
Thanks for this,  a few thoughts:
 - I'm -1 on adding the logging/warning
 - What is the basis for the cumulative nodes limit? Is this just a heuristic that worked for the case that you ran into? Generally I'm -1 on heuristics as well and would prefer a different solution.
 - At first glance this seems like the root cause might be floating point precision in the weights. Could you try using integer weights instead (i.e. multiply the weights by a factor up to the precision that you care about, say 10**6) and see if you still have this problem?

**Comment by vpipkt** [comment]
@rossbar thanks so very much for taking a look so quickly, on this out-of-the-blue PR. 🙇 

* Absolutely logging can be removed  - no sweat ✂️ 
* The cumulative nodes limit is a heuristic that worked for our cases. I will work on a more thorough solution that tries to detect the behaviour we are interested in: which is the same node is moved among the same communities many times
* I will definitely try the integer weights. That had not occurred to me! If that fixes it, I will report back here

**Comment by vpipkt** [comment]
At least in the test graph I added to this PR,  `int(w * 1e6)` fixes the convergence error. I will test for more cases when I can.

**Comment by rossbar** [comment]
> At least in the test graph I added to this PR, int(w * 1e6) fixes the convergence error. I will test for more cases when I can.

Thanks for checking that - this is a general problem with [floating point comparisons](https://github.com/networkx/networkx/issues?q=label%3Afloating-point+). The typical recommendation for people who run into this problem is to use integer weights instead: this allows the user to scale to whatever level of precision truly matters for their problem.

Given that I'm -1 on this specific proposed change, but perhaps we can add a caveat in the docs about float weights, similar to #5171 ?

**Comment by vpipkt** [comment]
Okay I tested in all the cases we had errors with before. I used version 2.8.6. Multiploying our float weights by 1e4 and using integer weights in the graph runs successfully in all cases.

Closing this PR and thanks for your insight @rossbar ! 🙇

**Pull request closed without merging**
