### PR TITLE
Add nx.info to str dunder for graph classes

### LINKED ISSUE #4139: Add more useful ```__str__``` function for Graph objects
Currently the ```__str___``` function prints the ```G.name``` property which is ```G.graph["name"]```.
That is pretty rarely useful in my experience (often a blank string).

There is useful information in nx.info(G) and much less of it than there once was. Perhaps it would be reasonable to look at making something like ```nx.info(G)``` show for ```__str__```.  Are there reasons to avoid doing this? What implications does it have for ```__repr__```?  Issue #3956 requested a useful ```__repr__``` and so is related to this.

### PR DESCRIPTION
**Pull request by rossbar**
Follow up to #4193 to close #4139.

Replaces the original `__str__` method of Graph and friends with the output from the newly-modified `nx.info`, which summarizes the name, number of nodes, and number of edges in a nice narrative form.

Modifies the test suite to check the new `__str__` output.

### CODE REVIEW

**Comment by AndrewEckart** [comment]
Haha beat me to the punch! Just wrote nearly the exact same thing.

**Comment by rossbar** [comment]
> Haha beat me to the punch! Just wrote nearly the exact same thing.

Sorry, I should've pinged you!

> I think people working with many large graphs might be a little surprised when str(G) takes linear time, but hopefully this is a very small subset of users.

Agreed, though in terms of the challenges of working with large graphs, this is probably a pretty low-priority concern

> In any case it sounds like keeping track would require some type of distributed counter and significant engineering.

There are some minor changes that may improve this, but generally I agree. The improvements would come from changes to the underlying methods, which would better fit in separate PRs.

**Comment by rossbar** [comment]
FWIW the appveyor failure is unrelated (timeout when trying to clone) but I can't figure out how to relaunch the failed job. We can always close/reopen to retrigger all the CI processes, but that seems wasteful

**Comment by MridulS** [comment]
@rossbar `git commit --amend --no-edit && git push -f` my not so pretty way of re-trigging builds.

**Comment by dschult** [comment]
On my Appveyor page when I look at the list of all jobs run, there are 3 options in blue at the top right. The right one ("Re-run Incomplete") rebuilds only failed or cancelled jobs.  I selected the middle one ("Re-build PR") and it restarted all of them. *oops*.  Ah well...     At least its better than touching the PR branch to trigger the CI.

**Comment by dschult** [comment]
Is it better to have ```__str__``` call ```nx.info``` or to have ```nz.info``` call ```__str__```?
Two criteria I can think of: which is more efficient (shouldn't matter) and where will people look for the code (they'd probably look for ```__str__``` before looking for ```nx.info```... Are there other reasons/criteria?

**Comment by jarrodmillman** [comment]
Do we need/want to keep ``nx.info``?

**Comment by AndrewEckart** [comment]
> Do we need/want to keep `nx.info`?

`nx.info` has some functionality that `Graph.__str__` doesn't - you can pass it a specific node to find out information about that node (its degree and its neighbors). If that logic is redundant or can be given another home, I think `nx.info` could be deprecated - getting rid of it outright would create some back-compat issues.

**Comment by rossbar** [comment]
> Is it better to have __str__ call nx.info or to have nz.info call __str__?

Great observation - honestly, I hadn't even considered it but I do think that `__str__` is a more natural place for the implementation to live rather than the other way around. I agree that it's certainly the first place a curious user would look, and the extra indirection to the `info` function under-the-hood would be a bit annoying.

> Do we need/want to keep nx.info?

I agree with @AndrewEckart since `nx.info` has the extra branch for summarizing node info. Removing it would be noisy for users, and I don't think there's much advantage of churning the API to move the node-summarizing to a new/different function (unless there's already a good candidate somewhere).

**Comment by rossbar** [comment]
54ad6e9 swaps things around so that the implementation is in `Graph.__str__` and `nx.info` returns `str(G)`

**Review by dschult — APPROVED** [review]

**Comment by dschult** [comment]
Just want to flag @chebee7i on this ```nx.info``` issue :}

**Review by chebee7i — APPROVED** [review]

**Comment by Erotemic** [comment]
@dschult @jarrodmillman @rossbar 

I saw this merge in the git history I was really excited that the `__str__` was finally going to give some information about the graph, but then I was a little bit disappointed when I saw the prose-like formatting of the string and that `__repr__` still doesn't give any information. 

While I love that the str representation of a graph is now going to have some info associated with it, wouldn't it be better if it looked something more like `DiGraph(n_nodes=5, n_edges=4)` instead of the current `DiGraph with 5 nodes and 4 edges`? 

Also, wouldn't it be nice if the repr was similar and looked like `<networkx.classes.digraph.DiGraph(n_nodes=5, n_edges=4) at 0x7f2b41f72d30>`. 

I see there was some discussion of this in #4193 but I hope its not too late for me to chime in with a rather strong opinion that this formatting should change before this feature is published to pypi. When parsing logfiles and stdout having a more programming like style of summarizing information (i.e. having the parens encapsulate the info) makes it much easier to deal with. I feel like aving a prose-like string format will at best look out of place in log files and stdout and at worst cause issues with searching / parsing.

At the very least, It would be nice if the repr gave information like the way I described.

**Comment by rossbar** [comment]
@Erotemic these seem like reasonable suggestions. One minor consideration against formats like `Graph(n_nodes=X, n_edges=Y)` is that this *looks* like executable code that could be used to create a graph, so users might be tempted (especially in the case of `__repr__`) to copy/paste from the output into a terminal to try to create a new graph. The prosy output has the advantage that there should be no such confusion (however minor).

I think your points are valid though: the current (prose-like) output is probably better for interactive terminal users (especially newer users) whereas outputs along the lines you suggest would indeed look more natural in log files. Maybe it would be good to open an issue to try to track preferences? If users express a strong preference for one format over another, that'd be a great motivation to change it!

**Pull request merged**
