### PR TITLE
Gexf viz

### PR DESCRIPTION
**Pull request by Michael-E-Rose**
This finishes #1453.

All that was needed was to update the test files to the current version, it seems.  In particular it was about the meta tags with creator and the date created. See e.g. https://github.com/networkx/networkx/blob/master/networkx/readwrite/tests/test_gexf.py#L296
It wasn't implemented in 2015 when this PR originally started.

### CODE REVIEW

**Comment by MridulS** [comment]
Can you have a look at the merge conflicts?

**Comment by Michael-E-Rose** [comment]
What's best to do about them? Must I update the files and amend to this PR in order to avoid them?

**Comment by Michael-E-Rose** [comment]
The tests fail because `test_asyn_lpa.test_two_communities` fails. That's not related to this PR. What can I do about this?

**Comment by dschult** [comment]
I restarted the appveyor tests -- that test is one that sometimes fails... :{

**Pull request merged**
