### PR TITLE
Add remove attribute functions

### PR DESCRIPTION
**Pull request by mjschwenne**
With the addition of attribute based visualization, users may want to be able to remove visualization related attributes. I was a bit surprised that this functionality didn't already exist, but these are a pair of convenience functions to help with that.

### CODE REVIEW

**Review by dschult — APPROVED** [review]
These two functions seem pretty reasonable. They'll be definitely useful for tests. And probably quite useful for certain user tasks.

**Review by rossbar — COMMENTED** [review]
Agreed, generally LGTM - thanks @mjschwenne !

One thing that occurred to me while looking at this - do we want to support removing attributes from a subset of nodes/edges? The `set_*_attributes` support this via passing in mappings. Generally this would be the type of feature that could be added incrementally... I only bring it up here because it may be trickier (though still possible) to modify the signature going forward since it makes use of argument unpacking.

WDYT @mjschwenne ? I don't have a strong feeling either way...

**Comment by mjschwenne** [comment]
I hadn't thought about removing from a subset of the nodes or edges... I do think that it's a useful feature to have so I've added a parameter `nbunch` and `ebunch` keyword-only parameter to the functions to support this.

**Comment by dschult** [comment]
This has one approval and a nice review with all suggestions implemented (and tested). 
I'm going to merge it to help other PRs that depend on this one.
Thanks @mjschwenne and @rossbar

**Pull request merged**
