### PR TITLE
Fixed GEXF 'viz' XML Namespace in GEXFwriter

### PR DESCRIPTION
**Pull request by kmanninen**
I had a need to write a GEXF file that included the 'viz' attributes of nodes (position, color, size). I found that the current version of networkx generated a GEXF XML file with an incorrect namespace for the xmlns:viz (it returned 'ns0' tags instead of 'viz', see example below). I was able to correct this issue by:

1) Correcting the NS_VIZ URL (it was pointing to an incorrect URL).
2) Adding the "ET.register_namespace" method to the GEXFwriter **init** so that the namespace is properly registered.

Example:

The following code:

``` python
import networkx as nx

DG = nx.DiGraph()

DG.add_weighted_edges_from([("a", "b", 10)])

DG.node['a']['viz'] = {
    'position': {'x': 0, 'y': 0, 'z': 0},
    'size': 10,
    'color' : {'a': '1', 'r':"153", 'g':"153", 'b':"153"}}

DG.node['b']['viz'] = {
    'position': {'x': 50, 'y': 50, 'z': 0},
    'size': 10,
    'color' : {'a': '1', 'r':"153", 'g':"153", 'b':"153"}}

nx.write_gexf(DG, "gephi.gexf", version='1.2draft')
```

Creates the following <b>incorrect</b> XML file (note the 'ns0' tags instead of 'viz'):

``` xml
<gexf xmlns:ns0="http://www.gexf.net/1.2draft/viz" version="1.2" xmlns="http://www.gexf.net/1.2draft" xmlns:viz="http://www.gexf.net/1.2draft/viz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema-instance">
  <graph defaultedgetype="directed" mode="static">
    <nodes>
      <node id="a" label="a">
        <ns0:color a="1" b="153" g="153" r="153" />
        <ns0:size value="10" />
        <ns0:position x="0" y="0" z="0" />
      </node>
      <node id="b" label="b">
        <ns0:color a="1" b="153" g="153" r="153" />
        <ns0:size value="10" />
        <ns0:position x="50" y="50" z="0" />
      </node>
    </nodes>
    <edges>
      <edge id="0" source="a" target="b" weight="10" />
    </edges>
  </graph>
</gexf>
```

The new code that I'm proposing in this pull request fixes the "ns0" tags:

``` xml
<?xml version='1.0' encoding='utf-8'?>
<gexf xmlns:viz="http://www.gexf.net/1.2draft/viz.xsd" version="1.2" xmlns="http://www.gexf.net/1.2draft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema-instance">
  <graph defaultedgetype="directed" mode="static">
    <nodes>
      <node id="a" label="a">
        <viz:color a="1" b="153" g="153" r="153" />
        <viz:size value="10" />
        <viz:position x="0" y="0" z="0" />
      </node>
      <node id="b" label="b">
        <viz:color a="1" b="153" g="153" r="153" />
        <viz:size value="10" />
        <viz:position x="50" y="50" z="0" />
      </node>
    </nodes>
    <edges>
      <edge id="0" source="a" target="b" weight="10" />
    </edges>
  </graph>
</gexf>
```

Thank you for your consideration. I'm open to comments.

### CODE REVIEW

**Comment by chebee7i** [comment]
Should the same be done with `NS_XSI`? You'll also need to update the unit tests to reflect this change.

**Comment by chebee7i** [comment]
@kmanninen Any opinion on `NS_XSI`?

**Comment by hagberg** [comment]
Anyone interested in finishing this PR?

**Comment by Michael-E-Rose** [comment]
The problem still exists. Hence I would volunteer to finish the PR. Must I start a new PR or can I somehow add to this one?

**Comment by dschult** [comment]
It's not easy to add to someone else's PR. But you can fork the PR,
add/chage stuff and then submit it as a separate PR. Just make sure to say
so somewhere in the PR comments.

**Comment by Michael-E-Rose** [comment]
Then what's the advantage of forking this PR first given that is not easy?
As an alternative I could take @kmanninen's code here, update the test files, and add everything to the still open PR #2355 of mine, which deals with gexf as well.

**Comment by MridulS** [comment]
@Michael-E-Rose by forking the PR you will maintain the commit history.

**Comment by Michael-E-Rose** [comment]
Okay, I see, but after all it's "just" four lines of code in one file (https://github.com/networkx/networkx/pull/1453/files). Forking the PR and then resolving the merge conflict might outweigh the benefits?

**Comment by MridulS** [comment]
@Michael-E-Rose I understand but it's more about keeping the credit where it's due. :) You can open a new PR with a forked version of this one. (PRs are cheap)

**Comment by MridulS** [comment]
@Michael-E-Rose Checkout https://hub.github.com . It will make this easier.
```
hub checkout https://github.com/networkx/networkx/pull/1453
```
will create a new branch with the contents and you can add your commits on top of this. :)

**Comment by Michael-E-Rose** [comment]
Alright, I did it. What's strange is that all nosetests pass.

Now, how do I push & make the new PR?  I surely can't push to the branch of the OP, which is `kmanninen-master`, can I?  Guess I better ask beforehand instead of messing things up.

**Comment by MridulS** [comment]
`kmanninen-master` is the name of your local branch not the OP's branch. (This is the default name of the branch fetched using hub).

You can push it to GitHub using `git push origin kmanninen-master:branch_name` where you can decide the branch name, e.g.: `gexf_viz`,   `git push origin kmanninen-master:gexf_viz`.
Then it is business as usual, open a new PR :)

**Comment by dschult** [comment]
fixed in #2436

**Pull request closed without merging**
