### PR TITLE
Build documentation on ReadTheDocs

### PR DESCRIPTION
**Pull request by chebee7i**
This PR allows ReadTheDocs to build our documentation. They will be available here: https://networkx.readthedocs.org/en/latest/ once this is merged. After that, we will need to update networkx-website accordingly. There are also a number of places we need to cleanup the documentation, but that is another PR.

### CODE REVIEW

**Comment by chebee7i** [comment]
Demo is here: http://networkx.readthedocs.org/en/docdraft/

Because this relies on the current status of the repository, we will not be able to host old builds of the documentation on RTD. So we will still need to keep archival versions available.

**Comment by SanketDG** [comment]
I don't know why but the [assortavity](http://networkx.readthedocs.org/en/docdraft/reference/algorithms.assortativity.html) page is blank. I think this has something to do with napolean, because when I built the docs locally using napolean, the same thing happened.

**Comment by chebee7i** [comment]
If others agree, I'd like not to talk all potential problems with the documentation in this PR...there are a number of them, as you've probably seen with the build log. So I do want to open additional PRs.

**Comment by chebee7i** [comment]
I should clarify, many of these were also problems when building with the numpydoc sphinx extension too.

**Comment by chebee7i** [comment]
Also, if anyone turns on builds for their own clone of networkx, please make sure to set the privacy level of each branch to "protected" or "private" rather than "public". This will keep google results clean and pointing to the one true source.

**Comment by SanketDG** [comment]
@chebee7i I see that they break with `numpydoc` too. Then how are the latest doc builds on the website not displaying them? How is it fixed? Sorry, if I'm asking too many questions.

**Comment by chebee7i** [comment]
Not entirely sure...I think those are all good questions, but perhaps best suited for another pull request?

Could someone try following the instructions here: https://github.com/networkx/networkx/wiki/readthedocs

I'd like to know if that helps people set up their own documentation builds for their fork.

**Comment by OrkoHunter** [comment]
@chebee7i Maintaining fork of NetworkX documentation seems to be a very nice hackery for reviewing documentation related PRs. Let me follow the instructions.

**Comment by OrkoHunter** [comment]
I think I followed the steps but nothing showing up here at http://orkohunter-networkx.readthedocs.org/en/latest/ :(
There are many versions in the `versions` settings. And none of them are ticked in mine. Do I need a new commit to start the doc build?

**Comment by SanketDG** [comment]
@OrkoHunter You should use `napolean`. This pull request does that. To do that, just insert `sphinx.ext.napoleon` in your conf.py file . Look at the conf.py diff in the pull request and change accordingly.

**Comment by chebee7i** [comment]
Oh right, you'll probably need to work off this PR. Did you do that? Those instructions will not work from the current master.

**Comment by OrkoHunter** [comment]
I was trying out from the master itself.
Now I made another branch with changes made in this PR, and I think I've made some progress (new error).
```
Outcome: Failed (Status Code: 404)

Environment Standard Error
checkout
-----
Top-level Build Failure: 
```
Ref. https://readthedocs.org/builds/orkohunter-networkx/2963252

**Comment by SanketDG** [comment]
I am really not sure, but I think they can't match the folder stucture. This doesn't even have a traceback. It fails immediately.

**Comment by chebee7i** [comment]
I looked at your branch, but it doesn't look like it has the changes from my branch. Lastest commit is too old: https://github.com/OrkoHunter/networkx/commits/test_rtfd

Instead, try:

```
git checkout master
git remote add chebee7i https://github.com/chebee7i/networkx.git
git fetch chebee7i
git checkout -b test_rtfd2 chebee7i/docdraft
git push origin # if this doesn't push the branch, then do:
git push -u origin test_rtfd2
```

That will create a new branch `test_rtfd2, based off this PR, and push it up to GitHub. Then you need to enable builds on RFTD for that new branch. You might have to instruct it to reimport from GitHub to get an updated list of branches. Since you've already tried building, you'll almost certainly need to wipe the environment first.

**Comment by OrkoHunter** [comment]
It worked. Thanks.
http://orkohunter-networkx.readthedocs.org/en/test_rtfd2/

**Comment by hagberg** [comment]
Is this ready to merge?

**Comment by chebee7i** [comment]
Yep. We can get other pull requests going after this, especially the one for networkx-website. Also, would it be worthwhile to add these commits to 1.10 as well?

**Comment by hagberg** [comment]
Fine with me to add to 1.10.

**Pull request merged**
