### PR TITLE
Use newer osx on travis

### PR DESCRIPTION
**Pull request by jarrodmillman**
Closes #2614.

### CODE REVIEW

**Comment by jarrodmillman** [comment]
We are getting two errors:
```
FAILED networkx/drawing/tests/test_agraph.py::TestAGraph::test_multi_undirected
FAILED networkx/drawing/tests/test_agraph.py::TestAGraph::test_multi_directed
```

It looks like conda is still using an old, buggy version of graphviz and we are hitting this problem again #2852.  It looks like brew has been updated, so I will try it.  We will probably want conda to update before the next release.

**Comment by dschult** [comment]
I believe current Graphviz is v2.42, but the buggy version (v2.40) is still installed by conda. 
Once we get v2.42 the tests should pass.

**Comment by jarrodmillman** [comment]
@dschult The tests are passing now.  We no longer use conda and instead use brew to install graphviz-2.44.1 on travis-ci.

**Comment by dschult** [comment]
This looks good -- and a nice solution to the conda graphviz mess. Thanks!

**Pull request merged**
