### PR TITLE
Added .editorconfig according to pep-8 and the style used in files

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by rossbar** [comment]
This seems like something that is tooling-specific and not suitable for upstreaming.

**Comment by KOLANICH** [comment]
The same can be said about the most of the files in the repo root which names begin with a dot.

**Comment by rossbar** [comment]
I would argue that things like testing, CI, etc. are essential parts of the project infrastructure, whereas editor configuration is a personal choice. I'm -1 on forcing (or even recommending) project-specific editor configurations.

**Comment by KOLANICH** [comment]
>editor configuration is a personal choice

So, should I expect that you are +1 for accepting PRs using tabs instead of spaces?

**Comment by rossbar** [comment]
IMO editor configuration is not the best place to catch linting issues - there is better dedicated tooling for that (see the pep8speaks CI service that we're currently using, e.g.).

**Comment by KOLANICH** [comment]
@rossbar, it is not about linting. If a project uses n spaces instead of a tab and your editor inserts a tab, and reformats into tabs, or considers an indent as m ≠ n spaces and inserts them and reformats assumming it, for the languages like python, where indents are meaningful and tue interpreter forbids mixing tabs and spaces, one cannot just edit this code. For the langs like C++ one can edit the code, but there will be untidy mess.

So, at least for python + git formatting settings is not a personal preference: the code just won't work. In practice many projects mandate all the contributors to use either tabs or spaces and certain encodings and line endings. Differrent projects have different requirements, and they don't necessarily coincide to developer personal preferences. To clean up the mess, `.editorconfig` spec has been created. Every project encodes his requirements into a file, every developer uses an editor supporting the spec, the software deals with the differences automatically.

Of course the best way to treat non-meaningful stuff is a version control system that doesn't store text and stores AST, which doesn't depend on formatting, dumping it into text according to user's prefs on checkout and parsing on a commit, but IDK any of such version control systems.

**Comment by jarrodmillman** [comment]
-1 as well on this.

**Pull request closed without merging**
