### PR TITLE
Add approximation import

### PR DESCRIPTION
**Pull request by jg-you**
This submodule is not accessible when one imports networkX with `import networkx as nx`.
Is there a particular reason *not* to import this submodule with the rest of the package?

### CODE REVIEW

**Comment by hagberg** [comment]
Yes, we chose not to import those algorithms with the main package.  There are some others too.
This is certainly up for discussion.  

Some of the reasons not to import everything are - namespace gets too large to easily inspect,  speed of ` import networkx`, and memory usage.

**Comment by jg-you** [comment]
Sound decision.

**Comment by jtorrents** [comment]
Also, there are some name collisions (eg `node_connectivity`), the tests pass because the exact version is imported after the approximation. I agree we should document this. Maybe as a docstring at the top of `networkx/algorithms/approximation/__init__.py`? so it will show up here:

https://networkx.github.io/documentation/development/reference/algorithms.approximation.html

**Comment by hagberg** [comment]
I like the idea of not importing the approximation package automatically.  Perhaps we can suggest in the docs using `from networkx.algorithms import approximation`?

**Comment by jg-you** [comment]
Something of the sort?

**Comment by jg-you** [comment]
Bump? Seems like a simple issue.

**Pull request merged**
