### PR TITLE
In all_simple_paths(). Replace list with OrderedDict for speedup

### PR DESCRIPTION
**Pull request by winni2k**
See discussion of this at https://github.com/networkx/networkx/issues/2975#issuecomment-406354042

### CODE REVIEW

**Comment by dschult** [comment]
Looks like Codecov wants a test of the multigraph cases. (which wasn't there before but now that we touched that code, it is flagging it.  I'll add that soon...

**Comment by dschult** [comment]
Thanks for doing this!!

**Comment by winni2k** [comment]
np

**Comment by winni2k** [comment]
This fix should remove a major roadblock in my work...

**Pull request merged**
