### PR TITLE
Removed internal use of deprecated np.matrix type.

### PR DESCRIPTION
**Pull request by NeilGirdhar**
See #3107.

### CODE REVIEW

**Comment by ericmjl** [comment]
@NeilGirdhar I updated your comment so that we can take advantage of special keywords the GitHub uses to link PRs to issues (and auto-close them when done). Hope you don't mind! :smile:

**Comment by NeilGirdhar** [comment]
@ericmjl Nice, but it doesn't resolve the issue.  It's just a couple of the instances of the problem.  There are a few more places to fix:
```
networkx/algorithms/link_analysis/pagerank_alg.py:    M = nx.to_numpy_matrix(G, nodelist=nodelist, weight=weight)
networkx/algorithms/link_analysis/hits_alg.py:    M = nx.to_numpy_matrix(G, nodelist=nodelist)
networkx/algorithms/link_analysis/hits_alg.py:    M = nx.to_numpy_matrix(G, nodelist=nodelist)
networkx/algorithms/centrality/subgraph_alg.py:    A = nx.to_numpy_matrix(G, nodelist)
networkx/algorithms/centrality/subgraph_alg.py:    A = nx.to_numpy_matrix(G, nodelist)
networkx/algorithms/centrality/subgraph_alg.py:    A = nx.to_numpy_matrix(G, nodelist)
networkx/algorithms/communicability_alg.py:    A = nx.to_numpy_matrix(G, nodelist)
networkx/algorithms/communicability_alg.py:    A = nx.to_numpy_matrix(G, nodelist)
networkx/algorithms/bipartite/spectral.py:    A = nx.to_numpy_matrix(G, nodelist, weight=weight)
networkx/algorithms/shortest_paths/dense.py:            "to_numpy_matrix() requires numpy: http://scipy.org/ ")
networkx/algorithms/shortest_paths/dense.py:    A = nx.to_numpy_matrix(G, nodelist=nodelist, multigraph_weight=min,
networkx/tests/test_convert_numpy.py:        A = nx.to_numpy_matrix(self.G1)
networkx/tests/test_convert_numpy.py:        A = nx.to_numpy_matrix(self.G1)
networkx/tests/test_convert_numpy.py:        A = nx.to_numpy_matrix(self.G2)
networkx/tests/test_convert_numpy.py:        A = nx.to_numpy_matrix(self.G2)
networkx/tests/test_convert_numpy.py:        A = nx.to_numpy_matrix(self.G3)
networkx/tests/test_convert_numpy.py:        A = nx.to_numpy_matrix(self.G3)
networkx/tests/test_convert_numpy.py:        A = nx.to_numpy_matrix(self.G4)
networkx/tests/test_convert_numpy.py:        A = nx.to_numpy_matrix(self.G4)
networkx/tests/test_convert_numpy.py:        A = nx.to_numpy_matrix(P4, nodelist=nodelist)
networkx/tests/test_convert_numpy.py:        A = nx.to_numpy_matrix(P4)
networkx/tests/test_convert_numpy.py:        np_assert_equal(A, nx.to_numpy_matrix(WP4, weight=None))
networkx/tests/test_convert_numpy.py:        np_assert_equal(0.5 * A, nx.to_numpy_matrix(WP4))
networkx/tests/test_convert_numpy.py:        np_assert_equal(0.3 * A, nx.to_numpy_matrix(WP4, weight='other'))
networkx/tests/test_convert_numpy.py:        A = nx.to_numpy_matrix(G)
networkx/tests/test_convert_numpy.py:        A = nx.to_numpy_matrix(G, multigraph_weight=min)
networkx/tests/test_convert_numpy.py:        A = nx.to_numpy_matrix(G, multigraph_weight=max)
networkx/tests/test_convert_numpy.py:        A = nx.to_numpy_matrix(G, dtype=int)
networkx/tests/test_convert_numpy.py:        A = nx.to_numpy_matrix(G, dtype=int)
networkx/convert_matrix.py:    M = to_numpy_matrix(G, nodelist=nodelist, dtype=dtype, order=order,
networkx/convert_matrix.py:def to_numpy_matrix(G, nodelist=None, dtype=None, order=None,
networkx/convert_matrix.py:    >>> A = nx.to_numpy_matrix(G)
networkx/convert_matrix.py:    >>> nx.to_numpy_matrix(G, nodelist=[0, 1, 2])
networkx/generators/spectral_graph_forge.py:    A = nx.to_numpy_matrix(G)
networkx/linalg/algebraicconnectivity.py:    from numpy import array, asmatrix, asarray, dot, ndarray, ones, sqrt, zeros
networkx/linalg/algebraicconnectivity.py:    W = asmatrix(ndarray(X.shape, order='F'))
networkx/linalg/algebraicconnectivity.py:        res = dasum(W * asmatrix(Y)[:, 0] - sigma[0] * X[:, 0]) / Lnorm
networkx/linalg/algebraicconnectivity.py:            X = asmatrix(seed.normal(size=(q, L.shape[0]))).T
networkx/linalg/algebraicconnectivity.py:                X = asarray(asmatrix(x).T)
networkx/linalg/algebraicconnectivity.py:                sigma, X = lobpcg(L, X, M=M, Y=asmatrix(Y).T, tol=tol,
networkx/linalg/attrmatrix.py:    M = np.asmatrix(M)
networkx/algorithms/assortativity/correlation.py:    M = numpy.asmatrix(M)
networkx/convert_matrix.py:    M = np.asmatrix(A, dtype=dtype)
```

**Comment by NeilGirdhar** [comment]
Some of these are public methods, and I don't have time to go through the back and forth of figuring out how you will address the deprecation.  This was an easy internal fix (and it appears that there are many more easy internal fixes) that bit me, so I thought I would eliminate it.

**Comment by NeilGirdhar** [comment]
@ericmjl That sounds very reasonable!

**Comment by dschult** [comment]
Sounds great!

**Pull request merged**
