### PR TITLE
Use peek(S) instead of next(iter(S)).

### PR DESCRIPTION
**Pull request by jfinkels**
As of the date of this commit, there is no way to get an arbitrary
element of an iterable like a set without modifying it (for example, as
in `set.pop()`). The `peek()` function is more readable than writing

    next(iter(S))

whenever an arbitrary element of an iterable is required.

This commit also makes a couple of PEP8 changes, but not many.

### CODE REVIEW

**Comment by chebee7i** [comment]
Note, this is only non-consuming if the iterable passed to `peek` is not already an iterator:

```
In [1]: x = {1,2,3}

In [2]: y = iter(x)

In [3]: next(iter(y))
Out[3]: 1

In [4]: list(y)
Out[4]: [2, 3]
```

**Comment by jfinkels** [comment]
Oh, right. I guess I should make that more clear in the documentation string for the function.

**Comment by hagberg** [comment]
I'm not so enthusiastic about this idea.  Using peek() might mean less characters (more readable?) but also means those that read it have to look up somewhere else what the function does.

**Comment by jfinkels** [comment]
Yes, that's true; it is certainly a tradeoff.

**Comment by dschult** [comment]
This might be better proposed to Python.set() as a new method.
But also see [stackoverflow](http://stackoverflow.com/questions/59825/how-to-retrieve-an-element-from-a-set-without-removing-it) on this issue.

**Comment by jfinkels** [comment]
I do think it should probably be a built-in method, but it won't be for the foreseeable future, and there are quite a few places in the code that use this functionality.

**Comment by chebee7i** [comment]
Interesting that the for/break approach was so fast!

**Comment by chebee7i** [comment]
Any interest in changing this to use the for break paradigm instead?

**Comment by jfinkels** [comment]
I guess it makes sense: it's about as unreadable as `next(iter(S))` and seems faster, if we trust StackOverflow. I'll make the change.

**Comment by hagberg** [comment]
Actually what I like about next(iter(foo)) is that you can look up the terms up in a Python book.
peek() would require first looking into the NetworkX code and then figuring out the for/break idiom.
Do we really need this to be fast?

**Comment by jfinkels** [comment]
> Actually what I like about `next(iter(foo))` is that you can look up the terms up in a Python book.
> `peek()` would require first looking into the NetworkX code and then figuring out the for/break idiom.

Well, I thought "peek" was a reasonable name indicating the behavior of the function (at least for English speakers), and it follows the convention for [peeking][1] at the top of a stack.

[1]: https://en.wikipedia.org/wiki/Peek_%28data_type_operation%29

> Do we really need this to be fast?

Well, I'm willing to do whatever here, I just wanted to suggest the "peek" abstraction. I guess I'm not sure how much I trust the rigor of the StackOverflow answer linked above.

**Comment by dschult** [comment]
I prefer next(iter(S)) because it uses standard python names (peek is only familiar to those who were taught peek as a method name for stacks).  I would argue that the loop/break idiom is harder for humans to parse and not much faster.

**Comment by chebee7i** [comment]
Ok, I'm fine staying with the existing `next(iter(S))`.

**Comment by jfinkels** [comment]
This is also how David Eppstein does it: https://github.com/jfinkels/PADS/blob/master/pads/Util.py#L8

**Comment by hagberg** [comment]
Link didn't work - 
```python
def arbitrary_item(S):
    """
    Select an arbitrary item from set or sequence S.
    Avoids bugs caused by directly calling iter(S).next() and
    mysteriously terminating loops in callers' code when S is empty.
    """
    try:
        return next(iter(S))
    except StopIteration:
        raise IndexError("No items to select.")
```

I like this approach - good name.  Bonus corner case error handling.

**Comment by chebee7i** [comment]
Any chance we could test if S is already an iterator and raise an exception if so? In that case, the operation consumes, which is probably not what was desired.

**Comment by jfinkels** [comment]
The only thing I could think of for testing if an object is an iterator is if there is an `__iter__` and a `__next__` method, the two methods that make up the [iterator protocol][1]. However, this doesn't make sense because, for example, a `Graph` instance (or a list, or a set) also has these methods, and I want to allow peeking at them.

[1]: https://docs.python.org/3/library/stdtypes.html#iterator-types

**Comment by dschult** [comment]
The Graph protocol does not have a __next__ method.
(And that's all you need to check for to see if it is an iterator.  The
__iter__ method returns an iterator, and any iterator object should just
return itself, but any iterable will have an __iter__ method.  Only an
iterator will have a __next__ method.)

**Comment by chebee7i** [comment]
Opps...I thought I commented on this, but I must have forgotten to click "Comment". Here goes again:

We need to make sure we are good for 2.x/3.x. But @dschult's comment suggets:

```
def is_iterator(it):
    hasnext = hasattr(it, '__next__') or hasattr(it, 'next')
    return iter(it) is it and hasnext
```

**Comment by hagberg** [comment]
isinstance(x, collections.Iterator)?

**Comment by jfinkels** [comment]
I'm thinking that `isinstance(x, collections.abc.Iterator)` would only work for instances of classes that explicitly inherit from `collections.abc.Iterator`, but any object with a `__next__` and an `__iter__` method is considered an "iterator". I'll try out @chebee7i's suggestion above.

**Comment by jfinkels** [comment]
Okay, check it out now. Has

    def is_iterator(it):
        hasnext = hasattr(it, '__next__') or hasattr(it, 'next')
        return iter(it) is it and hasnext

as a check for an iterator, function is named `arbitrary_element()`, and uses `next(iter(x))`.

**Comment by hagberg** [comment]
Looks fine to me.

**Comment by chebee7i** [comment]
Same.

**Comment by jfinkels** [comment]
Cool!

**Comment by chebee7i** [comment]
Aside, I think @hagberg's suggestion to use `isinstance` would work. The abc classes in `collections` implement `__subclasshook__`, which enables `isinstance` to work as desired in this case. The only issue is that the abc module is not written to be simultaneously 2/3 compatible and so it only tests for `__next__` xor `next`.

**Pull request merged**
