### PR TITLE
Remove pdf latex builds of docs

### PR DESCRIPTION
**Pull request by MridulS**
This has been discussed before and it's currently a blocker of moving to myst_nb from nb2plots for code block directives in our documentation. Opening this just so we can get the ball rolling on this one and have a decision :)

### CODE REVIEW

**Review by dschult — COMMENTED** [review]
I'm +1 to no longer generating the pdf. 
But it'd be nice to continue to support making the pdf locally... but may that is difficult.

Would this change mean that its very likely that we would not be able to create a latex version of the docs fairly soon -- mostly because we aren't testing that feature?  I think this PR uses that approach.  But perhaps the reason for this request is to avoid having to store/produce the old pdf versions for every release. In that case we can remove the pdfs storage from the archive, but still continue to test that making the pdf works.  

I'm probably Ok with this either way, but I'd like to understand the goal of the change.
:}

**Comment by rossbar** [comment]
>  it's currently a blocker of moving to myst_nb from nb2plots for code block directives in our documentation.

FWIW there was a recent PR to myst-nb that may have fixed this: see executablebooks/myst-nb#375. I haven't tested it yet but we should double check!

>  But it'd be nice to continue to support making the pdf locally... but may that is difficult.

Agreed. Generating the pdf via latex should continue working, but I also agree that building the pdf on each push/PR is wasteful. Some other options might be:
 1. Setup a cronjob to build the pdf every so often (say weekly or biweekly) to verify that everything still works.
 2. Make the pdf-building part of the release process and only worry about it at release-time.

I think either is probably fine, but generally +1 for decoupling the build from the workflows that are run at PR open/push/merge time!

**Comment by jarrodmillman** [comment]
If we are going to continue supporting building PDFs, I would prefer to build them regularly. If we only do it before a release, making releases is going to be harder. So I prefer one of these options:

1. Don't change anything.
2. Don't support PDF building.
3. Setup a cronjob to build the pdf every so often (say weekly or biweekly) to verify that everything still works.

**Review by rossbar — APPROVED** [review]
LGTM, thanks @MridulS !

**Review by dschult — APPROVED** [review]

**Comment by rossbar** [comment]
I went ahead and rebased to fix the merge conflicts.

Re: CI times, I did a quick comparison of two arbitrarily selected CircleCI jobs: one [with the pdf docs](https://app.circleci.com/pipelines/github/networkx/networkx/6236/workflows/3bfa38fa-107a-40c9-8207-505c52be8092/jobs/9199) and [one without](https://app.circleci.com/pipelines/github/networkx/networkx/6240/workflows/853076f0-46fe-4e8a-9deb-70b85f2e9213/jobs/9208). To summarize, it looks like ~4 minutes total are saved, reducing the total job time from 13 min down to 9.

Let's give this a shot! If there is major demand for the pdf docs we can always add them back.

**Pull request merged**
