### PR TITLE
Nobody is in IRC

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@hagberg can you enable gitter?

**Comment by hagberg** [comment]
I could do that - what would we use it for? (so we don't get another PR that says "nobody is in gitter")

**Comment by graingert** [comment]
Can you just enable it, but don't advertise it?

**Comment by hagberg** [comment]
By why should we?  It's one more moving part to maintain and I'd like to have a reason to add communication complexity.

**Pull request merged**
