### PR TITLE
Adds an edge-induced subgraph method

### PR DESCRIPTION
**Pull request by jfinkels**
Fixes issue #330.

### CODE REVIEW

**Comment by jfinkels** [comment]
This new function can be used in pull request #1538, and can be used in the function `_optimum_spanning_tree` in `algorithms.tree.mst`.

**Comment by jfinkels** [comment]
This can also be used in #1703, so that a copy of the graph will not be required.

**Comment by jfinkels** [comment]
I think this is an extremely useful function for implementing other algorithms, I'd like to push for its inclusion!

**Comment by dschult** [comment]
I am looking at this and thinking about the best implementation in terms of
views vs new graph structures, etc.  This implementation looks pretty good
if we go the route of creating a shallow copy of the graph.  I'm playing
with views generally. Aric has been a proponent for a long time of a
subgraph view as well.

Something like:

    restrict_to_edges = lambda u,v: return u != v
    G.edge_subgraph(restrict_to_edges)

And it should be lightweight (low ram) and fast.  :}

**Comment by dschult** [comment]
I was hoping to find a nice light-weight "view approach" to edge-subgraph.  But this is a good implementation of creating a new shallow graph copy with only those edges.  I'm going to merge and if/when we come up with a "view" version we can morph this at that time.  Thanks @jfinkels

**Comment by hagberg** [comment]
How is this different from G = nx.Graph(subedges)?

**Comment by chebee7i** [comment]
Node information is preserved (if the node is the head or tail of one of the edges).

**Comment by dschult** [comment]
The edge data is "shallow copied" in that the subgraph uses the same datadict as the graph.
I guess this method violates the "one way to do it" principle.

**Pull request merged**
