### PR TITLE
Add seeds to gallery examples for reproducibility

### PR DESCRIPTION
**Pull request by rossbar**
Adds seeds (or other deterministic layouts) to the gallery examples so that the generated figures are reproducible across runs. In some cases this includes seeding both the layout as well as the graph generation (if any graphs in the example are created with a random graph generator).

Other minor improvements to some examples include:
  * using canonical naming for imports (`import numpy as np` insteady of `import numpy`)
  * Add axis padding/change axes layout for examples where nodes and/or labels are being clipped.

### CODE REVIEW

**Comment by dschult** [comment]
Where more than one random number generator is used in the same example, is it best practice to use a single RNG with seed set once, or multiple seeds -- one for each part of the code where the RNG is used?  One example is ```plot_directed```.

**IF** it is best practice to use a single RNG for the whole example, (and I don't know that it is), then the examples should probably create an RNG, set it's seed and pass it into each function that uses an RNG.  Here's [a post about RNG in numpy](https://albertcthomas.github.io/good-practices-random-number-generators/). 
```python
RNG = np.random.default_rng(14365)
G = nx.random_k_out_graph(10, 3, 0.5, seed=RNG)
pos = nx.spring_layout(G, seed=RNG)
```

**Comment by dschult** [comment]
A separate comment...  We mostly make our functions available from ```nx.``` and without a long trail of folders to get to the function: ```nx.generators.directed.random_k_out_graph```.  The idea is to relieve the user from having to learn the path structure of the codebase and also to allow us to refactor the folders without messing up people's code.

In the examples, should we remove unnecessary path syntax? Then this example (from plot_directed.py) becomes ```nx.random_k_out_graph```.

**Comment by rossbar** [comment]
>  then the examples should probably create an RNG, set it's seed and pass it into each function that uses an RNG

AFAIK there is no downside/best-practice associated re-seeding generators multiple times, though it's probably useful to show the single-seed approach in the examples as it's generally more common to only set a single seed once per "chunk" (script, run, etc.). I think this is a good idea :+1: 

In principle, there *may* be scenarios where you'd want independently seeded instances for layout and random graph generation, but certainly not in these examples.

> Here's a post about RNG in numpy.

Yes that's a nice article! NumPy introduced new random number generation machinery in v1.17. Some of the main points in the article reference features that are only available with the new numpy random interface (e.g. the point about the global instance). It would be great to use the new numpy random API, but this will need a lot of consideration (I would likely vote for an NXEP :) )

> In the examples, should we remove unnecessary path syntax? 

Definitely. There are a lot of other ways that the examples could be improved, but I *mostly* tried to focus on seeding. This is a good idea though, so I'll add it in :+1:

**Comment by dschult** [comment]
We actually did a lot of work to include the numpy 1.17 features alongside the python random features. So, NetworkX currently allows RNGs or integers for every seed argument for every function.  Furthermore, if the code requires/uses Python's random RNG interface, we allow either numpy's RNG or Python random RNG or an integer to be passed in. (we wrap the numpy RNG in an object to allow Python's API to access the numpy RNG.)  If the code requires/uses the numpy RNG interface, we allow either a numpy RNG or an integer and if someone uses a Python random RNG we raise an exception.

So, I think we've already gone through the NXEP work...  It's all there. We just need to use it.
And we should use the numpy RNG interface whenever we can.    :}

**Comment by dschult** [comment]
Sorry for spam... I should also say that the current NetworkX functionality is provided by code in the utils/misc.py and utils/decorators.py modules and consists of the last three functions/classes in each of these modules.

**Comment by rossbar** [comment]
>  (we wrap the numpy RNG in an object to allow Python's API to access the numpy RNG.) 

Sorry, I should've been more clear about the numpy 1.17 distinction: In 1.17 numpy introduced a new interface for random number generation with new `BitGenerator` and `Generator` classes to replace the `RandomState` interface. So for instance instead using the global RandomState object at `numpy.random.mtrand._rand`, the new preferred way would be to construct a `Generator` instance ([this article](https://numpy.org/doc/stable/reference/random/new-or-different.html#new-or-different) has a nice quick summary).

The reason I mentioned a NXEP is because the `Generator` interface is not backwards compatible with the older numpy `RandomState` interface. This is all waaay tangent to the original point about seeds --- sorry for sprinting off into the weeds!

**Review by dschult — APPROVED** [review]
Changes to code look good. (I haven't looked at the pictures much. I assume they look good.)

**Review by jarrodmillman — APPROVED** [review]

**Pull request merged**
