### PR TITLE
DOC: Fix links, use DOI links, wayback machine where required

### PR DESCRIPTION
**Pull request by MridulS**
After a bunch of grep-ing, regex-ing and URL checking found a bunch of places where links where broken in the codebase and documentation. I'm sure I would have missed a bunch of them.

For slides, I have linked to a copy from wayback machine where possible.
For papers, I have linked to DOI where available.

PS: Maybe a tool like this exist? go through all the codebase and outputs broken links?

### CODE REVIEW

**Comment by jarrodmillman** [comment]
You could try `cd doc ; make linkcheck`.

**Review by rossbar — COMMENTED** [review]
Some of the external links can be replaced with roles/link targets (+intersphinx) which should help make them more robust against future breakage. I'm going to go ahead and push some suggestions up when I get a chance to look at it more closely.

+1 for DOI links where possible though!

**Review by jarrodmillman — APPROVED** [review]

**Review by rossbar — APPROVED** [review]
I went ahead and updated two links to use intersphinx & added nx-guides to the intersphinx mapping (along with updating the matplotlib target, which avoids a redirect).

Thanks @MridulS !

**Comment by jarrodmillman** [comment]
I am temporarily marking this a draft, so I can keep from merging it for about 30 minutes.  I am going to work on the documentation repo so I want to merge this when I am done.  Just so I can manually confirm everything works after I make my changes.

I am going to remove `from networkx import networkx` stuff from the old docs.

**Pull request merged**
