### PR TITLE
don't assume nodes are sortable when running dag_longest_path

### PR DESCRIPTION
**Pull request by cmtm**
The `dag_longest_path function` can raise an TypeError Exception when the nodes of the DiGraph passed to it aren't sortable (i.e. don't define the `__lt__` method). The algorithm creates a list of `(length, u)` tuples, where u is a node. It then runs the `max()` function on said list. Ordering of tuples is defined by comparing corresponding elements lexicographically. So if ever there's a case where two lengths are equal, the nodes will be compared a `TypeError: unorderable types` is raised. I suspect that this would occur for very frequently when using unsortable nodes considering how the algorithm works.

### CODE REVIEW

**Comment by cmtm** [comment]
I just saw   #1989 which reported the same bug.
In the discussion of that issue, @jfinkels said:

> This seems to be fixed in a newer version of NetworkX, in commit 1dc1602.

But I don't think that's the case. I tested the latest code and it had the same issue.

**Comment by cmtm** [comment]
The checks are failing because the tests aren't recognizing two solutions as equivalent. Should I modify the test to have only one solution?

**Comment by jfinkels** [comment]
The test should definitely be changed so that there is a unique longest weighted path.

As for the unorderable nodes issue, the suggested change should come with a test case that fails for the current code but is fixed with the suggested change. Can you provide a minimal working example that demonstrates the issue?

**Comment by cmtm** [comment]
It looks like there's already a test for unorderable nodes, it just doesn't catch the error properly. It's test graph is just a linked list, and this degenerate graph doesn't hit the error case. On top of that, the code that's supposed to hit the error case has a TypeError in it since it tries to `raise NotImplemented`, but `NotImplemented` isn't an `Exception`. I'll fix that test instead of adding a new one.

A minimal working example that demonstrates the issue:
```
import networkx as nx
nodes = [object() for _ in range(4)]
G = nx.DiGraph()
G.add_edge(nodes[0], nodes[1])
G.add_edge(nodes[0], nodes[2])
G.add_edge(nodes[2], nodes[3])
G.add_edge(nodes[1], nodes[3])
nx.dag_longest_path(G)
```

**Comment by jfinkels** [comment]
I just want to totally clarify this for myself: `NotImplemented` and `NotImplementedError` are different, and the former has a special meaning for comparison methods, see https://docs.python.org/3.6/library/constants.html#NotImplemented. Since I don't quite understand what the difference is in this situation, could you explain why that needs to be changed? Thanks.

**Comment by ProgVal** [comment]
@jfinkels NotImplementedError is an exception meaning that part of the **code** was not written yet, which should be raised to the user.
NotImplemented is not an exception (it should be `return`ed, not `raise`d!), it means that this class doesn't know how to be compared with the other one, and that the other one should be called for the comparison.

**Comment by cmtm** [comment]
To add to what ProgVal said, the current code raises `NotImplemented`. This is absolutely wrong as [it's a constant](https://docs.python.org/3.5/library/constants.html#NotImplemented), not an exception. This is a bug in the testing code that exists independently of my change.

We then have 2 choices, we can `return NotImplemented`, or we can `raise NotImplementedError`. Both would technically work, but the latter fails in a much more direct way. The former fails in a way that's described in the python doc:

> When NotImplemented is returned, the interpreter will then try the reflected operation on the other type, or some other fallback, depending on the operator. If all attempted operations return NotImplemented, the interpreter will raise an appropriate exception.

Since the latter fails in a more direct way, I went with it.

**Comment by jfinkels** [comment]
Awesome, thanks for explaining. Since class is there specifically to test the behavior on Python 2 (see the comment above the class definition of `Unorderable`), let's make it match the default behavior of `object.__lt__` in Python3, i.e., raise a `TypeError`:

```sh
$ python3 -c "object() < object()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: unorderable types: object() < object()
```

**Comment by cmtm** [comment]
@jfinkels Done. I have it raise `TypeError: < not supported between instances of Unorderable and Unorderable` because cpython [changed to that since 3.5](https://github.com/python/cpython/commit/6aea3c26a22c5d7e3ffa3d725d8d75dac0e1b83b).

**Comment by jfinkels** [comment]
Needs a space after the colon in the lambda expression, after that it looks good to me. Thanks for all your work on this!

**Comment by cmtm** [comment]
Done. And you're welcome. Thank you for providing networkx!

**Pull request merged**
