### PR TITLE
Forces PEP8 style recommendations on Python files

### PR DESCRIPTION
**Pull request by jfinkels**
This branch was created using the [autopep8][1] tool. [PEP8][2] compliance is important because PEP8 is an almost-universal style convention, and universality implies predictability. Predictability is as important in coding style as it is in rules of the road: it prevents confusion and therefore prevents "dangerous" behavior. In this environment, that mostly just means improved readability.

[1]: https://pypi.python.org/pypi/autopep8/
[2]: https://www.python.org/dev/peps/pep-0008/

### CODE REVIEW

**Comment by Midnighter** [comment]
That's gonna be one hell of a review... Things I noticed so far: Can you configure the behavior of autopep8? I really dislike the opening parenthesis and the next line to be on the same level, it potentially wastes so much horizontal space, for example,

```python
variable = call_to_a_really_long_function_name_as_often_in_networkx(
                                                                                                                  a=1, b=2)
```

I much prefer one or two levels of indentation.

Networkx uses the one letter variable name `G` all over the codebase. This violates two principles of PEP8: variables should be lowercase, variables should be descriptive. So maybe something like `graph` or `net` would be a better fit. As far as I can tell autopep8 did not touch this issue at all.

**Comment by chebee7i** [comment]
My opinion of pep8 is that is should mostly be followed, but that we should be practical about it.  Using `u` and `v` from the tail and head of an edge is *now* standard in NetworkX. While I can see that it makes the code more readable to use something like `from_node` and `to_node`, it is also a bit ugly for one-liner list comprehensions. I'm also with @Midnighter on indentation in those cases.

**Comment by chebee7i** [comment]
And actually, I don't think we can even review this PR: "Sorry, we could not display the entire diff because it was too big."  

Note also that other projects, of which NumPy and Matplotlib (iirc) are included, have a policy where PEP8 changes are only applied on source files that were touched in the process of making other changes or adding new features. The result is a slow progression to PEP8 compliance. A big PR like this has a high probability of creating merge conflicts with existing PRs.

**Comment by chebee7i** [comment]
It looks like >99% of the changes are just whitespace issues around operators and commas etc, of which I'm generally in favor of. So I'm generally ok with the changes and think it's probably safe from the code perspective to merge this, but I'm just not sure if we *should* merge this. Potential conflicts with existing PRs are a concern for me, and my general preference is that we do these changes in the process of editing files for non-PEP8 reasons, rather than all at once.

**Comment by jfinkels** [comment]
This pull request is just a suggestion, of course. I just get tired of the extra effort required to read non-PEP8 code (because, yes, most of the issues are whitespace issues).

**Comment by ysitu** [comment]
You can break this into multiple PRs by package.

**Comment by hagberg** [comment]
I agree with @chebee7i on this.   I don't think changing a bunch of old working code just to follow a new standard is a compelling argument.  

For new code, or when modifying old code to fix bugs or add/change functionality, following PEP-8 is good (though not slavishly please).  Separate commits for style changes are helpful to be able to easily review substantive v cosmetic changes.

According to PEP-8 Guido's insight was (essentially) that readability counts.  As a mathematician I like reading thinks like

```python
for u in G
```
or
```python
(u,v) = e
```

but maybe I am in the minority.

**Comment by hagberg** [comment]
Style does matter but overall I suggest we spend our time working on other things in the code base.
E.g. the documentation can be improved in many many places.  So if someone updated the documentation in a package, and, in a related commit to those changes, made some PEP-8 (especially whitespace) changes I would review and approve that ASAP.

**Comment by MridulS** [comment]
As a newbie to networkx (started using it a month back), I think we need more documentation and maybe more examples. I got stuck some times at very trivial things.

**Comment by hagberg** [comment]
@MridulS it would be very helpful if you pointed out the confusing parts for beginners (separate issue or issues from this PR).

**Comment by RONNCC** [comment]
lol you should break this into lots and lots of small changes.

**Comment by RONNCC** [comment]
also @jfinkels  using autopep8 without looking at it's results is not a good idea. it attempts formatting with ASTs, that doesn't mean it does anything for how it visually looks - e.g. it breaks groups of objects in the middle sometimes which isn't necessarily the best thing to do and is also mentioned in pep8

**Comment by jfinkels** [comment]
@RONNCC Fair enough. I've never used the tool before, so I'm unfamiliar with how well it performs.

**Comment by hagberg** [comment]
Maybe my comments here are misunderstood.  There is plenty of work to be done  - and sincere thanks for everyone's help - but fixing whitespace and formatting isn't even close to the top 100 list of things that could be done to improve this package.  So carry on people.  Over and out.

**Comment by RONNCC** [comment]
hmm, what about having future packages compliant? > slow integration as suggested

**Comment by hagberg** [comment]
I wrote above
"For new code, or when modifying old code to fix bugs or add/change functionality, following PEP-8 is good (though not slavishly please). Separate commits for style changes are helpful to be able to easily review substantive v cosmetic changes."

**Comment by RONNCC** [comment]
darn missed it, sorry :)

**Comment by chebee7i** [comment]
@jfinkels Btw, please don't be discouraged. We definitely appreciate the efforts (here and also in #1347 etc) that you are making to `networkx`, and are looking forward to future contributions!

**Comment by jfinkels** [comment]
@chebee7i Of course, no worries!

**Pull request closed without merging**
