### PR TITLE
Fixing typo in bridges module

### PR DESCRIPTION
**Pull request by Yomguithereal**
Just fixing a tiny typo.

### CODE REVIEW

**Comment by dschult** [comment]
That ```iff``` stands for "if and only if", which is an abbreviation common in math theorems and proofs.
Could you replace the ```iff``` with ```if and only if```?  Thanks!

**Comment by Yomguithereal** [comment]
Oh. I did not know that. Good to know :). I will update the PR then if you feel it still make sense.

**Comment by Yomguithereal** [comment]
Done. I broke the line also not to overcome 80 chars.

**Comment by dschult** [comment]
Excellent -- Thanks!

**Pull request merged**
