### PR TITLE
Fix negative edge cycle function raising exception for empty graph and added test function

### PR DESCRIPTION
**Pull request by PurviChaurasia**
In reference to #6465, fixed the `negetive_edge_cycle` function by handling an empty graph. Also added `test_negative_cycle_empty` test function in `test_weighted.py`.

### CODE REVIEW

**Comment by PurviChaurasia** [comment]
Could someone please point out where I'm going wrong with this?

**Comment by dschult** [comment]
You can click on "Show all checks" and then the "Details" link to the right of any check that has a red X indicating that it didn't pass the tests. The "style/format" test usually means that you didn't run the "precommit" suite of style checking programs on your commit.  That can be automated by installing precommit (see the contributer guide at the end of step 1 for how to do that). It looks like in this case, the style checker is complaining about extra parentheses. 

But it also looks like you may have other errors showing up and I'm not sure why...
You can run the test locally using `pytest --doctest-modules weighted.py tests/test_weighted.py` to check for those test errors.  Then commit any changes and push to your branch and it should update the PR and rerun the tests.

**Comment by PurviChaurasia** [comment]
Okay, I'll look into this.

**Comment by PurviChaurasia** [comment]
Hi, so I ran the test suite and here is where it's failing - 
FAILED networkx/algorithms/flow/tests/test_mincost.py::TestMinCostFlow::test_exceptions - Failed: DID NOT RAISE <class 'networkx.exception.NetworkXError'>

**Comment by PurviChaurasia** [comment]
@dschult Any Idea as to why this exception might be raised?

**Comment by PurviChaurasia** [comment]
@MridulS It would be a great, if you could help in figuring out where I'm going wrong and why I'm getting this error.

**Comment by dschult** [comment]
First, can you fix the precommit errors?

Second, other functions use `negative_edge_cycle` and apparently one of them (it looks like `nx.capacity_scaling` relies on the old error behavior -- rather than returning `False`.  So, this change is more delicate than expected.  You will need to find those parts of the code, understand why they used to give a NetworkXError, and make sure that they now give a reasable other type of error.  If that is the case, then you just have to change the error type that **those tests of the other function** look for.  For example if it now raises a `NetworkXUnbounded` error instead of a `NetworkXError` then you will need to change the test that is currently failing to make it look for a `NetworkXUnbounded` error.  Hope this makes sense.

**Comment by PurviChaurasia** [comment]
Hey! Yes it's passing all the test cases now, thanks a lot!

**Comment by PurviChaurasia** [comment]
Woohoo! Finally figured it out. Thanks a lot @dschult and @MridulS :)
Kindly merge the PR!

**Review by dschult — APPROVED** [review]
This looks good to me.
Note that the test in `test_mincost` is only commented out because the other tests in that test function are commented out whenever `nx.capacity_scaling` doesn't raise an exception. I'm not sure of the history there, but by commenting it out, we are following whatever reasoning we had when building that test suite. It might be good to go through and delete the commented out tests, but I'm not sure and that's really a separate issue from this PR.

I approve this PR

**Comment by PurviChaurasia** [comment]
Yes, I had a similar question. I noticed that other tests for `nx.capacity_scaling` are also commented out. @dschult Should I raise a separate issue for this? Perhaps I can look into why it is happening and delete/comment out other tests which may be redundant in nature.

**Review by rossbar — APPROVED** [review]
I don't understand the test commenting either, but I agree with @dschult that we can leave that for a separate investigation.

LGTM thanks @PurviChaurasia !

**Pull request merged**
