### PR TITLE
Fix to_vertex_cover

### LINKED ISSUE #3306: hopcroft_karp_matching / to_vertex_cover bug
`to_vertex_cover` must give the **minimum vertex cover** as documented. Wasn't it fixed in #2384 ?
The following code gives random results:

```python
import networkx as nx

nodesU = ['r1','r2','r3','r4','r5','r6','r7','r8']
nodesV = ['c1','c2','c3','c4','c5','c6','c7','c8']
edges = [
        ('r1','c2'),('r1','c4'),('r1','c5'),('r1','c8'),
        ('r2','c1'),('r2','c2'),('r2','c3'),('r2','c6'),('r2','c7'),
        ('r3','c4'),('r3','c5'),
        ('r4','c2'),('r4','c8'),
        ('r5','c2'),('r5','c8'),
        ('r6','c1'),('r6','c2'),('r6','c3'),('r6','c5'),('r6','c6'),('r6','c7'),
        ('r7','c2'),('r7','c8'),
        ('r8','c2'),('r8','c4')]

G = nx.Graph()
G.add_nodes_from(nodesU, bipartite=0)
G.add_nodes_from(nodesV, bipartite=1)
G.add_edges_from(edges)
M = nx.bipartite.hopcroft_karp_matching(G, top_nodes = nodesU)
print('matchings M = ', M)
print('|M|  = ', len(M))

K = nx.bipartite.to_vertex_cover(G, M, top_nodes = nodesU)
print('minimum cover K = ', K)
print('|K|  = ', len(K))
```

Here are the results of multiple runs:
```
matchings M =  {'c1': 'r6', 'r7': 'c2', 'r5': 'c8', 'r1': 'c5', 'r8': 'c4', 'r6': 'c1', 'c5': 'r1', 'c8': 'r5', 'r2': 'c7', 'c7': 'r2', 'c2': 'r7', 'c4': 'r8'}
|M|  =  12
minimum cover K =  {'c1', 'c5', 'c7', 'c2', 'c8', 'c4'}
|K|  =  6

matchings M =  {'c6': 'r6', 'r6': 'c6', 'r1': 'c4', 'r4': 'c2', 'c3': 'r2', 'r5': 'c8', 'c5': 'r3', 'r3': 'c5', 'c8': 'r5', 'r2': 'c3', 'c4': 'r1', 'c2': 'r4'}
|M|  =  12
minimum cover K =  {'c6', 'r6', 'c4', 'c5', 'c2', 'c3', 'c8', 'r2'}
|K|  =  8

matchings M =  {'c8': 'r7', 'r7': 'c8', 'c1': 'r2', 'r3': 'c4', 'r6': 'c7', 'c5': 'r1', 'c2': 'r4', 'c7': 'r6', 'r4': 'c2', 'r2': 'c1', 'c4': 'r3', 'r1': 'c5'}
|M|  =  12
minimum cover K =  {'r2', 'c8', 'c4', 'c2', 'c5'}
|K|  =  5

matchings M =  {'r3': 'c4', 'r6': 'c1', 'r1': 'c5', 'c2': 'r7', 'r7': 'c2', 'c8': 'r5', 'r2': 'c7', 'c5': 'r1', 'r5': 'c8', 'c1': 'r6', 'c7': 'r2', 'c4': 'r3'}
|M|  =  12
minimum cover K =  {'c8', 'c5', 'c7', 'r6', 'c2', 'c4'}
|K|  =  6
```

I'm using networkx 2.2 on debian/python3 and windows miniconda3.
The graph is from: [http://tryalgo.org/en/matching/2016/08/05/konig/](http://tryalgo.org/en/matching/2016/08/05/konig/)

Also why `hopcroft_karp_matching` returns matchings and opposite edges ?

### PR DESCRIPTION
**Pull request by studentofkyoto**
The issue is well-described in #3306.

This code change consists of:
- style change from lazy to eager
- Test addition for reproduction

I tried not to invade original intention of code.

Closes #3306

### CODE REVIEW

**Comment by dschult** [comment]
Nice!  Thank you!

I'll leave it up to you to say which is more clear, but you might consider (inside of list lookup) an if/else structure like:
```get_valid_edge = lambda depth: unmatched_edges if (depth % 2) else matched_edges```
Or you could even remove the function call `get_valid_edge` by putting the if/else where the function is used and shifting `depth` to start at 1/0 based on `along_matched`.

The test is very helpful!!
Thanks!

**Comment by rossbar** [comment]
> Or you could even remove the function call get_valid_edge by putting the if/else where the function is used and shifting depth to start at 1/0 based on along_matched.

IMO this would make things much more readable: +1 for this idea!

I also second the sentiment on the test - very nice!

**Comment by studentofkyoto** [comment]
Thanks a ton for the kind and prompt review.

If a bit more aggressive change is allowed, however, I would let the function simply recurse.
Worst case has O(n) depth when n is the number of vertices in the graph in interest, and I am kind of guessing the original intention is not to raise MaximumRecursionDepth but average-case should be O(log k n) where k is number of edges.

I understand the initial implementation was recursive before #2384 and #2386, but it seems like the reason that it was changed to iterative style is not because of `MaximumRecursionDepth`. As far as readability is concerned, I guess bringing recursive style back makes sense.

Also, I find it rather hard to write tests for function `_is_connected_by_alternating_path`. Guide me through with some advices and suggestions, will be much appreciated.

**Comment by dschult** [comment]
Recursion is not a good idea for algorithms in Python. Not only is there recursion depth issues (especially if it is O(n)... ), but there are memory and speed concerns. Recursion pushes the stack and loop programming into function and namespace programming, which might work fine in a compiled language setting, but is not ideal in interpreted languages like Python. We've been trying to remove recursive parts of the codebase.

Besides, most graph algorithms deal with stack and loops, so we're used to it. The recursion is not even that much easier to read. But I might be biased there. 

Anyway, if you could return to a stack/loop form instead of recursion I would appreciate it. 

As far as tests for `is_connected_by_alternating_path`, what difficulties are you having? Can you set up a small graph that should return True and another that should return False? Even better is to test each possible way that it could return False or True. But I haven't worked through the logic of the problem to figure out what they all are. That might be too much for a simple unit test setting.

**Comment by studentofkyoto** [comment]
Thanks a lot for the guidance.

> We've been trying to remove recursive parts of the codebase.

That was the part that I was wondering the most. Thanks for clearing it out for me.

> Besides, most graph algorithms deal with stack and loops, so we're used to it. The recursion is not even that much easier to read. But I might be biased there.

I understood. I will keep that in mind!
I stripped one commit from the top and force-pushed it.
(Newbie Question: Is it recommended to `reset && push --force` to revert, or make reverting commit?)

> As far as tests for is_connected_by_alternating_path, what difficulties are you having? 

Due to the symmetricity of following line, it will not be able to be tested if `along_matched=True` corresponds to `depth % 2 == 0`:
 https://github.com/networkx/networkx/blob/d9cb95edfad840302288f8a52d4df73beeeee713/networkx/algorithms/bipartite/matching.py#L372-L374

The private function call chain `to_vertex_cover` -> `_connected_by_alternating_paths` -> `_is_connected_by_alternating_path` -> `_alternating_dfs` seemed a bit awkward to me because they are not called anywhere else. But they are useful for sure (at least in my application), and I wish to impose more tests on them. I will make separate PR for them though.


> Even better is to test each possible way that it could return False or True. But I haven't worked through the logic of the problem to figure out what they all are. That might be too much for a simple unit test setting.

If I understood correctly, I ran the test you mentioned in my local:
```python3
import itertools as it
import networkx as nx
import pytest

@pytest.mark.parametrize('n_row, n_col', [(5, 5)])
def test_all_cases(n_row: int, n_col: int):
    # make all possible combination of bipartite graph
    for rights4left in it.product(*([[rs for i in range(1, n_col + 1) for rs in it.combinations(range(n_col), i)],] * n_row)):
        edges = [(i, j) for i, js in enumerate(rights4left) for j in js]

        G = nx.Graph()
        G.add_edges_from([((i, "L"), (j, "R")) for i, j in edges])

        try:
            matching = nx.bipartite.maximum_matching(G)
        except nx.exception.AmbiguousSolution:
            # covered by test cases with smaller `n_row, n_col`
            # Don't have to worry about it
            continue
        vertex_cover = nx.bipartite.to_vertex_cover(G, matching)
        for u, v in G.edges():
            assert u in vertex_cover or v in vertex_cover
```

I agree that it is not nice to include such test in CI.

**Comment by dschult** [comment]
It is usual to **revert** and **force push**, but in fact either way is fine because github (by default anyway) squashes all the commits into a single commit when we merge it into the repository.

Writing tests for private functions is a good idea!  And we'd love to have those tests.
To access the functions within the tests, use something like:
```python
nx.bipartite.matching._is_connected_by_alternating_path(...)
```

Your nice exhaustive test everything approach certainly covers all small cases and can be easily made bigger.  It gives me an error on case ```test_all_cases(3,3)``` and larger cases too. Is the error for 3,3 and bigger a problem with the test or a problem with the function?  

Takes a long time to run the test of course too (4,4) gives 50K times through the loop, (5,5) gives 28 million -- gotta love combinatoric explosion. I was envisioning a more selective test based on all logical possibilities in the algorithm -- rather than an exhaustive test everything approach. But this worked for this problem!  We got an error that we didn't expect.

**Comment by studentofkyoto** [comment]
> Is the error for 3,3 and bigger a problem with the test or a problem with the function?

It doesn't give me an error. Am I missing something?

```bash
(default) JAESEUNGs-MacBook-Pro:networkx jasonhan$ pytest tmp.py 
======================================================================= test session starts =======================================================================
platform darwin -- Python 3.8.8, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/jasonhan/Documents/opensource/networkx
plugins: dash-1.19.0
collected 1 item                                                                                                                                                  

tmp.py .                                                                                                                                                    [100%]

======================================================================== 1 passed in 7.73s ========================================================================
```

Please tell me if there is anything that is needed to make the merge smoother.

**Comment by rossbar** [comment]
FWIW I wouldn't get too hung up on structuring tests to cover the private functions in their current form. `_is_connected_by_alternating_paths` is basically a one-liner: `return _alternating_dfs(u, condition_1) or _alternating_dfs(u, condition_2)`. The whole purpose seems to be to map an (arguably) convenient set of parameters to the `_alternating_dfs` function. It is typically hard to write good tests for such "interface" functions - the function that implements most of the behavior is actually `_alternating_dfs`. In terms of unit testing, it would be much more valuable to have good tests for `_alternating_dfs`.

All this said, I'm +1 for getting the PR in it's current form (fixing 3306 + the nice test that illustrates a case that this fixes) and addressing the issue of more robust unit testing of the private functions in the bipartite matching module to another PR. That's a bit murkier and shouldn't block this nice improvement!

**Comment by dschult** [comment]
Interesting that your pytest run takes 7 secs for the 5,5 case and mine takes 12 secs for the 4,4 case and 500 times that long for the 5,5 case (I haven't run it till it stops.)  So, I've been running that function outside of pytest.  More troubling, when I run it in pytest with 4,4 parametrized, it passes in 12 seconds. But when I call the function outside of pytest it fails. And so does the 3,3 case.

Any idea why it would behave differently in pytest than outside of pytest?
input:
```python
import networkx as nx
import itertools as it
def test_all_cases(n_row: int, n_col: int):
    # make all possible combination of bipartite graph
    for rights4left in it.product(*([[rs for i in range(1, n_col + 1) for rs in it.combinations(range(n_col), i)],] * n_row)):
        edges = [(i, j) for i, js in enumerate(rights4left) for j in js]

        G = nx.Graph()
        G.add_edges_from([((i, "L"), (j, "R")) for i, j in edges])

        try:
            matching = nx.bipartite.maximum_matching(G)
        except nx.exception.AmbiguousSolution:
            # covered by test cases with smaller `n_row, n_col`
            # Don't have to worry about it
            continue
        vertex_cover = nx.bipartite.to_vertex_cover(G, matching)
        for u, v in G.edges():
            assert u in vertex_cover or v in vertex_cover
test_all_cases(4,4)
```
with output:
```python
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-16-9d81ec4a9a1f> in <module>
----> 1 test_all_cases(4,4)

<ipython-input-5-346799795eb1> in test_all_cases(n_row, n_col)
     15         vertex_cover = nx.bipartite.to_vertex_cover(G, matching)
     16         for u, v in G.edges():
---> 17             assert u in vertex_cover or v in vertex_cover
     18 

AssertionError:
```

**Comment by studentofkyoto** [comment]
That sounds very confusing!
I ran the test out of an isolated environment,
but I was not able to reproduce the behavior.

```python3
import networkx as nx
import itertools as it
import time

def test_all_cases(n_row: int, n_col: int):
    ...

for n in [3, 4, 5]:
    s = time.time()
    test_all_cases(n, n)
    print(n, time.time() - s)
```

Output:
```bash
3 0.03021693229675293
4 7.848700046539307
```

**Review by dschult — APPROVED** [review]
Sorry about that. It looks like I was testing the wrong version of NetworkX.
The 3,3 and 4,4 cases fail for the unfixed code (not surprising).
The fixed code does just fine.

This is good to be merged in my opinion.  Sorry for the delay!
Thank you for this fix!!

**Review by rossbar — APPROVED** [review]
LGTM, thanks @studentofkyoto - very nice solution to #3306 and thanks for the additional evaluation in PR discussion!

**Pull request merged**
