### PR TITLE
Bugfix (or simplification) of the size method in the Graph class

### PR DESCRIPTION
**Pull request by emilienkofman**
Hi,

I was wondering if it makes sense to simplify the size method like this:
- In the case no weight argument is passed, it returns an int anyway
- In the case a weight argument is passed, it returns its sum (as long as `__add__` is defined for the weight). By the way it's not always possible to convert weights to floats, which makes this fix convenient in that situation.

### CODE REVIEW

**Comment by dschult** [comment]
This is a strange github quirk-- maybe a bug.  When I look at the diff for your PR I see old code as the supposed code from networkx's master branch.  It should be:

        s = sum(dict(self.degree(weight=weight)).values()) / 2
        if weight is None:
            return int(s)
        else:
            return float(s)

I think your idea for getting rid of the coercion to float or int is fine, but
your code won't work with the latest version of Graph.degree() because 
it has been changed to an iterator.  
Perhaps you could start from a fresh branch off the latest master.
If you prefer, I can make your submitted changes in a different PR.

**Comment by jfinkels** [comment]
Two suggestions:

1. Try doing

       git checkout master

**Comment by jfinkels** [comment]
Yes, try making your changes in a new branch. See information on collaborating in the [GitHub help][1].

Also, you should add `from __future__ import division` to the head of the file, since the `float`/`int` difference appears when using (real) division.

[1]: https://help.github.com/articles/creating-a-pull-request/

**Comment by emilienkofman** [comment]
So, I did the changes you suggested on a new branch https://github.com/emilienkofman/nx.
But I don't get why `from __future__ import division` is necessary, can you explain? A number of edges is an integer anyway. May I ask for a new PR on this new branch?

**Comment by jfinkels** [comment]
> So, I did the changes you suggested on a new branch https://github.com/emilienkofman/nx. [...] May I ask for a new PR on this new branch?

That's a new *repository*, which is different from a new *branch* of an existing repository. Read some of the [GitHub help pages][1] for working with forks and branches.

> But I don't get why `from __future__ import division` is necessary, can you explain? A number of edges is an integer anyway.

In Python 2, `2 / 3` is `1` but in Python 3, `2 / 3` is `0.666`. Since you are using the `weight` attribute to compute the "degree", the result there might not be an even number.

[1]: https://help.github.com/categories/collaborating/

**Comment by dschult** [comment]
See #1798

**Pull request closed without merging**
