### PR TITLE
Adds planar graph class

### PR DESCRIPTION
**Pull request by tinloaf**
As mentioned in https://groups.google.com/forum/#!topic/networkx-discuss/YpulBDPTBls I currently work on supporting some operations that are only defined on planar graphs (stuff about faces, dual graphs, ...) in NetworkX.

This pull requests adds the first version of the graph data structure that I would like to use. Some comments:
- Anwering the question from Google Groups: Yes, I need a class for this, since lots of internal data must be computed, invalidated on changes and updated when requests are made.
- I'm not sure yet whether I like the fact that faces are computed whenever neighbors are accessed. This way, neighbors will be traversed in order of the embedding, but actually, faces are not needed for this.
- Obviously, all the methods that were only slightly modified from the base Graph need to inherit documentation..

### CODE REVIEW

**Comment by tinloaf** [comment]
Oh, also one big thing that I'm not sure I'm happy about: Since I need a pseudo-orientation on the edges (for storing which face is left or right of it), I need the vertices to be comparable. A type that's hashable but not ordered (i.e. "<" is not defined) would not work in this case. I can neither think of such a type nor of a solution how to fix this nicely, though...

**Comment by jfinkels** [comment]
So the intended usage is to instantiate the class, then add vertices, edges, and/or faces using the combinatorial definition of planar graph (that is, a set of discrete faces)? What happens when the user attempts to make an addition that would cause the graph to become non-planar?

**Comment by tinloaf** [comment]
Currently, things will just break, i.e. weird faces are computed. The user does not really specify the faces, but the order of adjacencies for every vertex.

This certainly is a point that should be improved. I'm currently thinking (or: researching) what's the most performant way of verifying a given embedding.

**Comment by jfinkels** [comment]
By the way, I brought up the issue of testing for planarity in #1603.

**Comment by tinloaf** [comment]
There is a significant difference between testing for planarity and testing a given embedding whether it's a planar one.. but yes. Later one could also add some functionality to compute some planar embedding for a planar graph without known embedding.

**Comment by hagberg** [comment]
This is an interesting idea.  I looked around some at the way others have implemented planar graphs.  It seems the most efficient data structure is not the dict-of-dict approach that networkx uses.  Have you considered using other data structures?  It may be simpler to do that.

**Comment by tinloaf** [comment]
@hagberg What implementations did you look at? They probably used some sort of sorted adjacency list? That might make sense for planar graphs, since they are relatively sparse, but that still leaves you with some O(deg(v)) complexity for edge access. In planar graphs, deg(v) is small on average, no question. On the other hand I'm not sure how efficient the hashtables behind python dicts are.

I also wanted to stay relatively close to the implementation of the graph classes that are already present. Would you prefer such an adjacency list implementation?

**Comment by hagberg** [comment]
I don't remember the details of where I looked.  It seemed that keeping track of nodes, edges, and faces was a good approach and I remember some discussion about doubly linked edge lists.  

My general comment was more to suggest starting from the point of how you would want a planar graph class to look and work and then see how it may or may not overlap with a general graph class.  The Python dictionary hash implementation is very good so I wouldn't worry about that first.

**Comment by dschult** [comment]
Some pointers to data structure descriptions for planar graphs:
A Dynamic Data Structure for Planar Graph Embedding, Roberto Tamassia
https://www.ideals.illinois.edu/bitstream/handle/2142/74258/B37-ACT_83.pdf?sequence=2

Doubly connected edge list data structure for planar graphs.
https://en.wikipedia.org/wiki/Doubly_connected_edge_list

**Comment by tinloaf** [comment]
Thanks, that Tamassia paper actually has been on my reading list for two weeks now.. I'm currently a bit buried in work (building software that actually already uses this "first shot" of mine here), I'll try to get to it as soon as possible, please bear with me. ;)

**Comment by MridulS** [comment]
Just wanted to revisit this, if we are planning on adding more planar algorithms we should look into this as part of our 4.0 roadmap. This could be one of the new base classes.

**Pull request closed without merging**
