### PR TITLE
Returns iterators instead of lists for Graph.nodes(), Graph.edges(), etc.

### PR DESCRIPTION
**Pull request by jfinkels**
This pull request is work-in-progress for a fix to issue #572.

With this first commit, I have changed `nodes()` to behave like `nodes_iter()` and removed `nodes_iter()`. This was a huge pain. When I get the courage to do the rest of the functions, I will update this pull request.

I ran into one problem that I did not dig deeply enough to fix; see the `TODO` comment marked in `graph.py`.

### CODE REVIEW

**Comment by MridulS** [comment]
Thanks for doing this :), I will be updating the rest of the functions as part of my GSoC project.

**Comment by jfinkels** [comment]
Okay, great. I was really not looking forward to doing that :)

**Comment by MridulS** [comment]
@jfinkels I think we can close this now. https://github.com/networkx/networkx/pull/1586

**Comment by jfinkels** [comment]
Closing because this is superceded by #1586.

**Pull request closed without merging**
