### PR TITLE
generate_unique_node: Switch to uuid4 and improve docstring.

### PR DESCRIPTION
**Pull request by rossbar**
Related to #4224 

`nx.utils.generate_unique_node` uses the `uuid` module to generate a unique string that can be used as a node. The idea (I think) is to have a function that generates a node that is guaranteed not to already be included in a graph. I've updated the docstring to try to capture this sentiment and provide examples.

I also changed the default uuid function from `uuid.uuid1()` to `uuid.uuid4()` based on the opening paragraph of the [uuid docs](https://docs.python.org/3/library/uuid.html) which notes "uuid1 may compromise privacy".

It is another untested one-liner that is only used in a few places in the library:

<details>
<pre>
./networkx/generators/line.py:from networkx.utils import arbitrary_element, generate_unique_node
./networkx/generators/line.py:        a = generate_unique_node()
./networkx/generators/trees.py:from networkx.utils import generate_unique_node
./networkx/generators/trees.py:            new_head = generate_unique_node()
./networkx/generators/trees.py:    root = generate_unique_node()
./networkx/algorithms/flow/capacityscaling.py:from ...utils import generate_unique_node
./networkx/algorithms/flow/capacityscaling.py:    s = generate_unique_node()
./networkx/algorithms/lowest_common_ancestors.py:    generate_unique_node,
./networkx/algorithms/lowest_common_ancestors.py:        super_root = root = generate_unique_node()
./networkx/algorithms/shortest_paths/weighted.py:from networkx.utils import generate_unique_node
./networkx/algorithms/shortest_paths/weighted.py:    newnode = generate_unique_node()
./networkx/utils/misc.py:def generate_unique_node():
./networkx/utils/misc.py:    >>> G.add_nodes_from([generate_unique_node() for _ in range(3)])
</pre>
</details>

but I do think the name ~~`generate_random_node`~~ `generate_unique_node` is much more clear than having calls to uuid functions scattered throughout the library. In the long run maybe it's worth auditing the uses to see if it can't be remove/reimplemented.

### CODE REVIEW

**Comment by dschult** [comment]
This is a corner case need. The UUID generates effectively unique nodes, but they aren't human readable. I think we should not spread the uuid library throughout the code. But it's not clear to me that we need to use this as much as we do. 

This should *not* be named anything with `random` in the name. It does not have a distribution. It is not random. Indeed, the results are not independent because they can't repeat. `unique` is the right meaning -- perhaps there is a better word, but I don't know of one.

**Comment by stefanv** [comment]
Current usage:

```
networkx/generators/line.py
6:from networkx.utils import arbitrary_element, generate_unique_node
291:        a = generate_unique_node()

networkx/generators/trees.py
5:from networkx.utils import generate_unique_node
131:            new_head = generate_unique_node()
141:    root = generate_unique_node()

networkx/algorithms/flow/capacityscaling.py
11:from ...utils import generate_unique_node
18:    s = generate_unique_node()

networkx/algorithms/shortest_paths/weighted.py
9:from networkx.utils import generate_unique_node
1931:    newnode = generate_unique_node()

networkx/algorithms/lowest_common_ancestors.py
11:    generate_unique_node,
220:        super_root = root = generate_unique_node()
```

**Comment by rossbar** [comment]
>This should not be named anything with random in the name.

Oops, that was a slip up on my part (I had "random" on the mind from the discussion in #4452) - Agreed, I meant to say `generate_unique_nodes` above - I've adjusted with a strikethrough to indicate the edit.

**Comment by dschult** [comment]
Thanks @stefanv for that list.  I suspect many/most of those don't need a unique node. They probably only need an unused node.  

For example, the line graph usage here is only for the `inverse_line_graph` function when the input graph has no edges. We want to return an empty_graph with 1 node. The PR #3538 changed the code to make the 2 node case avoid `generate_unique_node` but punted on the 1 node case.

I think that rather than use `generate_unique_node` we should construct a node
```python
a = 0
while a in G:
    a = a+1
```
or fancier would be
```python
a = len(G) if 0 in G else 0
while a in G:
    a = a + 1
```

The `uuid` nodes are not very user-friendly.  I'd prefer to avoid it if possible -- and the submitter of #3538 agreed.

[Side note: the `inverse_line_graph` code uses `list(G)[0]` to get an arbitrary node from G.
There are other fixes needed in  `line.py` like the `_edge_func` is now `G.edges` as of version 2.0.  I'll open a new issue for that.]

I believe the other uses of `generate_unique_node` are most likely similar and probably should use it.

**Comment by dschult** [comment]
While looking into #4458 I see that `lowest_common_ancestors` also does not need a unique node, just an unused node.

**Review by dschult — APPROVED** [review]

**Comment by rossbar** [comment]
Closing in favor of #4545 (and #4537, which removes uses of `generate_unique_node` from NetworkX).

**Pull request closed without merging**
