### PR TITLE
Fixes #1325. Moved nx_pyplot.py out of drawing package.

### LINKED ISSUE #1325: Remove matplotlib drawing to separate package
Maybe it violates the _batteries included_ philosophy - but how about removing the nx_pylab.py code to a separate package?  Maybe it will get more attention that way or people would be inspired to write a better version?  I'd suggest keeping it at github networkx/networkx-matplotlib so then it could be _batteries included but contained in separate packaging_.  Comments?

### PR DESCRIPTION
**Pull request by OrkoHunter**
As discussed in #1325, I moved the the `nx_plab.py` out of the drawing package to the main networkx package for making it easier to maintain. As suggested by @hagberg we should not put it in `networkx.addons` to keep the drawing separate from the algorithms and data structures which will make both easier to develop and maintain.

I manually tried drawing a graph as

    >>>import matplotlib.pyplot as plt

    >>>nx.draw(G)
    >>>plt.show()

And it worked fine.

Suggestions?

### CODE REVIEW

**Comment by SanketDG** [comment]
You will need to change the documentation `doc/reference/drawing.rst`. It needs to be moved or changed to fit yours.

**Comment by OrkoHunter** [comment]
@SanketDG I don't see any changes to be made in `doc/source/reference/drawing.rst`. All those fuctions still work. 
Can you point out the line(s) you think to be changed?

**Comment by SanketDG** [comment]
Um, shouldn't the line under Matplotlib section `.. automodule:: networkx.drawing.nx_pylab` changed since it's moved to `networkx_matplotlib.py`? Correct me if I'm wrong.

**Comment by OrkoHunter** [comment]
@SanketDG Oh yes. Earlier, I was checking out the webpage which had no mention of it. I corrected the rst file. Thanks!

**Pull request closed without merging**
