### PR TITLE
Document additional imports required for building the documentation

### PR DESCRIPTION
**Pull request by paulbrodersen**
…with example gallery

This implements the changes to doc/README.md discussed with @rossbar [here](https://github.com/networkx/networkx/issues/6764).

### CODE REVIEW

**Comment by paulbrodersen** [comment]
Not sure why any tests are failing as I only modified the documentation. Open to any suggestions.

**Comment by rossbar** [comment]
> Not sure why any tests are failing as I only modified the documentation. Open to any suggestions.

The test failures are unrelated to these changes - the failing tests stem from changes in scipy, which had a new release yesterday.

**Review by rossbar — COMMENTED** [review]
The content changes look good, but I'd vote to add them CONTRIBUTING.rst under the `Documentation` heading rather than the `doc/README.md`. The CONTRIBUTING.rst document is included in the rendered documentation whereas the readme is not, AFAICT.

In fact, I wonder if we can't get away with removing `doc/README.md` altogether, but that's a discussion for another time!

**Comment by paulbrodersen** [comment]
> In fact, I wonder if we can't get away with removing doc/README.md altogether, but that's a discussion for another time!

As a recent, sort-of-first time contributor to networkx, doc/README was the first place I looked for instructions for building the docs, and I didn't go back to CONTRIBUTING.rst to check if there were any other instructions there. I would suggest that if you do keep it around, then it should be at least as comprehensive w.r.t. building the docs as CONTRIBUTING.rst.

**Review by rossbar — APPROVED** [review]
Yeah let's worry about re-organization elsewhere. This LGTM, thanks @paulbrodersen

**Review by dschult — APPROVED** [review]
I'm going to approve this and merge -- with the idea that this documentation should be merged with the docs currently in the CONTRIBUTING.rst file as described in #6770.

**Pull request merged**
