### PR TITLE
Added cluster_layout method to layout.py

### PR DESCRIPTION
**Pull request by metalcorebear**
Cluster_layout will create a position dict where nodes within the same clusters are closer together than nodes in different clusters.  Gaussian noise is used to introduce positional variation both within and outside of clusters.

### CODE REVIEW

**Comment by metalcorebear** [comment]
Not entirely sure why the "style / format" test is failing.  It might be an issue with black.  Any help or suggestions would be greatly appreciated.  Thanks.

**Comment by rossbar** [comment]
> Not entirely sure why the "style / format" test is failing. It might be an issue with black. Any help or suggestions would be greatly appreciated. Thanks.

The easiest way to tackle linting is to use `pre-commit`. See [the contributor guide](https://networkx.org/documentation/latest/developer/contribute.html#development-workflow) for more info, particularly bullets 1 and 4!

**Comment by metalcorebear** [comment]
Thanks so much. Since the pre check has already fixed the formatting issues, the documentation says I can just add and commit again to accept them. Would that overcome the test issue I am seeing?

**Comment by dschult** [comment]
Yes -- that should overcome the style complaint of the "linters" :}

**Review by rossbar — COMMENTED** [review]
Thanks for the proposal @metalcorebear - having taken a quick look at this, my initial impression is that this is not so general that it is worth adding specialized API for. The majority of the work is in the clustering itself, which is something I think we'd want the users to have the flexibility to do on their own.

However, showing how to do "clustered" layouts with existing functionality would be worthwhile IMO! My vote would be to either add or update an existing [gallery example](https://networkx.org/documentation/latest/auto_examples/index.html#algorithms). The Davis club example might be a good target, for instance.

**Comment by metalcorebear** [comment]
> Thanks for the proposal @metalcorebear - having taken a quick look at this, my initial impression is that this is not so general that it is worth adding specialized API for. The majority of the work is in the clustering itself, which is something I think we'd want the users to have the flexibility to do on their own.
> 
> However, showing how to do "clustered" layouts with existing functionality would be worthwhile IMO! My vote would be to either add or update an existing [gallery example](https://networkx.org/documentation/latest/auto_examples/index.html#algorithms). The Davis club example might be a good target, for instance.

Thanks so much @rossbar.  If that is ultimately what is decided, I'd be happy to update or create a gallery example.  However, I have no idea how to do that and would need some guidance.  I'd like to note that the function I am proposing is flexible enough that a user can specify their own cluster dictionary, or they can use the default setting, which automatically calculates clusters using the community detection algorithm.

**Comment by rossbar** [comment]
> I'd like to note that the function I am proposing is flexible enough that a user can specify their own cluster dictionary, or they can use the default setting, which automatically calculates clusters using the community detection algorithm.

Agreed - I didn't mean that there was anything wrong with your implementation! My sense is that a clustered layout is relatively straightforward to achieve with existing functionality, and therefore a "teach someone to fish" approach might be better. For example, I'd probably approach a 1D hierarchical-clustered layout like (using the Davis club graph as an example):

```python
import networkx as nx
G = nx.davis_southern_women_graph()  # Example graph, there are probably better to illustrate this!
communities = nx.community.greedy_modularity_communities(G)  # Get some "clusters"
# Compute positions of the clusters as if they were themselves
# nodes in a supergraph, with a larger scale factor
supergraph = nx.cycle_graph(len(communities))
superpos = nx.spring_layout(supergraph, scale=3)
# Use those "supernode" positions as the center of each cluster
centers = list(superpos.values())
pos = {}
for center, comm in zip(centers, communities):
    sg = nx.subgraph(G, comm)
    pos.update(nx.spring_layout(sg, center=center))
# Nodes colored by cluster
for nodes, clr in zip(communities, ("tab:blue", "tab:orange", "tab:green")):
    nx.draw_networkx_nodes(G, pos=pos, nodelist=nodes, node_color=clr)
nx.draw_networkx_edges(G, pos=pos)
```

The key concept here is the whole clusters-as-nodes in a hierarchical layout scheme. This has some nice properties:
 1. It's relatively easy to reason about and code (~5 LOC for the actual cluster positioning)
 2. It's extensible! For example, if a user wanted to do hierarchical clustering (i.e. clusters-of-clusters, ad infinitum) it's relatively straightforward to do so by expanding the number of "supergraphs".

Anyways, just my two cents.

> I'd be happy to update or create a gallery example. However, I have no idea how to do that and would need some guidance.

The [developer guide](https://networkx.org/documentation/latest/developer/contribute.html#adding-examples) has a brief section on how to add gallery examples which (hopefully) covers the basic pattern.

**Comment by rossbar** [comment]
I went ahead and turned the suggestion above into a [gallery example](https://networkx.org/documentation/latest/auto_examples/drawing/plot_clusters.html#sphx-glr-auto-examples-drawing-plot-clusters-py).

Thanks for bringing this up @metalcorebear ! I will go ahead and close this now that the example is in. Feel free to follow up if you'd like to push this further!

**Comment by metalcorebear** [comment]
Awesome, thanks Ross!

**Pull request closed without merging**
