### PR TITLE
Fix location of graphviz_layout in draw_graphviz

### PR DESCRIPTION
**Pull request by nicktimko**
Lost in a rename/rearrange? Added a basic smoke-test that just calls the function with a graph to verify names are valid.

### CODE REVIEW

**Comment by dschult** [comment]
Ugh -- you are correct... it was an oversight on the rename/relocation process.
Unfortunately it is more tricky than your fix covers because graphviz_layout is supplied by both the nx_pydot and nx_agraph modules.  So the "nx_pydot" text you added will only work if they have pydot installed. If they only have pygraphviz then you will need to put nx_agraph there.  Maybe it's best to try one and when it fails go to the other...

**Comment by dschult** [comment]
Maybe @Michael-E-Rose or @jfinkels (or others) could put together some tests of the graphviz_layout function in nx_pylab.py (and non-test code in the function itself). Anybody looking for some coding fun?

We need to make sure the function works in each installation case: 1) pydot and no pygraphviz, 2) pygraphviz and no pydot, 3) both, 4) neither.

**Comment by hagberg** [comment]
This function just does
```python
    pos = nx.drawing.graphviz_layout(G, prog)
    draw(G, pos, **kwargs)
```

Can we just avoid the complexity of all of the possible graphviz installations and simply remove it?

**Comment by dschult** [comment]
Removing it sounds good to me. :)

**Pull request closed without merging**
