### PR TITLE
Use pydocstyle autoformatting

### PR DESCRIPTION
**Pull request by jarrodmillman**
There are 6285 remaining errors:
```
D100 Missing docstring in public module
D101 Missing docstring in public class
D102 Missing docstring in public method
D103 Missing docstring in public function
D104 Missing docstring in public package
D105 Missing docstring in magic method
D106 Missing docstring in public nested class
D205 1 blank line required between summary
D206 Docstring should be indented with spaces,
D210 No whitespaces allowed surrounding docstring text
D400 First line should end with a
D401 First line of docstring should be
D404 First word of the docstring should
D414 Section has no content ("Notes")
D414 Section has no content ("References")
D414 Section has no content ("See Also")
```

### CODE REVIEW

**Comment by Peiffap** [comment]
Thanks for taking a look at this! It'd be nice to get this over the line eventually, but that's a monumental amount of (boring) work if it needs to be done manually.

Is there some way that you know of to see how many violations each rule found? I can try to see if there's a way to implement autofixes for some of the more common ones to save us some of the trouble.

**Comment by rossbar** [comment]
There is a lot of overlap here with the [numpydoc validation checks](https://numpydoc.readthedocs.io/en/latest/validation.html#built-in-validation-checks), which I've never really wanted to enable for the same reason :)

**Comment by rossbar** [comment]
FWIW I was recently looking at pydocstyle and noticed that [it no longer seems to be maintained](https://pypi.org/project/pydocstyle/#history), at least not at the pace of other linting tools.

**Comment by rossbar** [comment]
I'm going to go ahead and close this one - AIUI the purpose of the PR is to demonstrate the difficulties in adopting automated doc linting. That's not to say it's not worthwhile, but I don't think anyone's like to make progress with the "turn everything on at once" approach! Feel free to reopen if you disagree!

**Pull request closed without merging**
