### PR TITLE
Remove neighbors_iter, G.neighbors() now returns an iterator instead of list

### PR DESCRIPTION
**Pull request by MridulS**

### CODE REVIEW

**Comment by MridulS** [comment]
Travis fails for timingclasses.py, I have skipped these tests as suggested by @dschult for now. This should be merged after https://github.com/networkx/networkx/pull/1587

**Comment by chebee7i** [comment]
Since you are working on a branch, can disable the tests for timingclasses.py so that your TravisCI results are positive?  We could re-enable the timing tests once the branch is ready for merging.

**Comment by MridulS** [comment]
@chebee7i I have disabled these tests in #1587

**Comment by dschult** [comment]
I've gone through #1586 #1587 #1588 and made a few comments.
We're getting close to a merge... :)

**Comment by MridulS** [comment]
This PR is failing the timingclasses.py tests, these tests are to be skipped as discussed and that is implemented in #1587. This should be ready to merge.

**Pull request merged**
