### PR TITLE
Try to make regenerating requirements unnecessary.

### PR DESCRIPTION
**Pull request by Carreau**
Point back at `pyproject.toml` this might avoid a pre-commit and avoid out of sync things.

### CODE REVIEW

**Comment by Carreau** [comment]
See if readthedocs like it.

**Review by rossbar — COMMENTED** [review]
This pattern makes sense to me and AFAICT eliminates the need for `generate_requirements` - I'm not familiar with all of the subtleties though so I'm curious what @jarrodmillman and @stefanv think!

**Comment by Carreau** [comment]
The extra step woudl be to remove any mention of `-r requirements/<target>` and  replace by `pip install  .[target]` and similar.

**Comment by stefanv** [comment]
Ah, neat, this saves a lot of trouble. Can propagate the same pattern to skimage.

**Review by MridulS — APPROVED** [review]

**Comment by stefanv** [comment]
As @lagru mentioned at https://github.com/scikit-image/scikit-image/pull/7435#pullrequestreview-2097490328 this approach is not equivalent because it *also* installs the library in question.

**Pull request closed without merging**
