### PR TITLE
WIP : removing parallelisation related TODO comments

### PR DESCRIPTION
**Pull request by Schefflera-Arboricola**
removing `#TODO` comments from algorithms that are implemented in [nx-parallel](https://github.com/networkx/nx-parallel) repo

### CODE REVIEW

**Comment by MridulS** [comment]
Maybe we should also make sure that the parallel implementation is also linked with the docs of these functions here.

**Comment by Schefflera-Arboricola** [comment]
> Maybe we should also make sure that the parallel implementation is also linked with the docs of these functions here.

[Here](https://github.com/networkx/networkx/pull/7219/files#diff-c4eb5c5ed400367ad75c488a4e71bcccc81cd658066833c832e734fd5d2b0b1aR1009) I've already proposed to link the parallel function in the backend section. It would also be useful in future if the backend functions will have their own webpages.

**Review by rossbar — APPROVED** [review]
+1 for this - we can either keep this open as a running list as more things are implemented, or merge and open a new one as additional parallel functions are implemented - either is fine with me! Thanks @Schefflera-Arboricola !

**Comment by Schefflera-Arboricola** [comment]
I think we can keep it open for now :)

**Pull request merged**
