### PR TITLE
Moved the metadata into setup.cfg

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by jarrodmillman** [comment]
What is the advantage of this?

**Comment by KOLANICH** [comment]
`setup.cfg` has a rigid declarative structure. It makes the following advantages:
1. One can parse `setup.cfg` file without exechting any code in it, because there is no code in it. `setup.py` can also be parsed into AST, but that AST has to be executed in order to get data correctly. This causes security issues. using `setup.cfg` can allow:
    a. building packages securely. We can whitelist a hash of a trivial `setup.py` non-malicious by design, and `setup.cfg` by design doesn't contain executable code.
    b. creating tools mass-scanning GitHub repositories for issues like vulnerable libraries and sending PRs. Not quite it isn't possible with `setup.py` for some widespread special cases, but in general for `setup.py` it is impossible.
2. It is easier to read.

**Comment by MridulS** [comment]
Isn't setup.cfg supposed to be deprecated in favour of pyproject.toml? https://github.com/pypa/setuptools/issues/1688

**Comment by KOLANICH** [comment]
It is only a deprecation.

There are issues ([1](https://github.com/pypa/setuptools/issues/1160), [2](https://github.com/pypa/setuptools/issues/1688)) in `setuptools` repo about moving contents of `setup.cfg` into `pyproject.toml`  for more than 2 years. Still not implemented.

I guess everybody is OK with `setup.cfg` so I don't expect it to be implemented in any near future.

So we can move the metadata to `setup.cfg` now, and when someone implemented setuptools support for `pyproject.toml` it would be trivial to move the metadata there.

**Comment by jarrodmillman** [comment]
I am still not sure this is a good idea.  But before I spend time looking into this more, do you know why all the tests fail now.  Is that easy to fix?

Also it looks like you removed the
```
sys.version_info[:2] < (3, 6)
```
check in `setup.py` and didn't put it anywhere else.

**Comment by KOLANICH** [comment]
>`sys.version_info[:2] < (3, 6)`

https://github.com/networkx/networkx/pull/3794/files#diff-380c6a8ebbbce17d55d50ef17d3cf906R66

**Comment by jarrodmillman** [comment]
I believe we already had something like `python_requires = >=3.6`, the `sys.version_info[:2] < (3, 6)` was for older system that don't support `python_requires`, which I believe was introduced more recently.

**Comment by jarrodmillman** [comment]
Does this
https://github.com/networkx/networkx/pull/3794/files#diff-354f30a63fb0907d4ad57269548329e3R87
mean that users will need `wheel setuptools setuptools_scm` installed to install `networkx` after this change?

**Comment by KOLANICH** [comment]
>Does this
https://github.com/networkx/networkx/pull/3794/files#diff-354f30a63fb0907d4ad57269548329e3R87
mean that users will need `wheel setuptools setuptools_scm` installed to install `networkx` after this change?

`setuptools_scm` is needed to get the version from git and generate the version file. `wheel` is needed to build a wheel and is likely to be already installed, it and `setuptools` were updated just to be sure that if a build fails that it is not because of rotten versions usual for Travis.

All of these is needed only to build a wheel. Users using prebuilt wheels (the stuff that should go to pypi) don't have to have these packages.

**Comment by qlixed** [comment]
Hello!, there is some update for this PR? Is blocked for some particular reason? I think that is the last thing pending to fully integrate pyproject.toml with setup.cfg/py, right?

**Comment by rossbar** [comment]
I'm -1 on replacing the setup.py with setup.cfg - the primary reason being that, AFAICT, `setup.py` still seems to be the standard way of doing things, at least within the scientific Python ecosystem. IMO, the motivations in the top comment aren't strong enough to deviate from this standard.

**Comment by KOLANICH** [comment]
[There are currently no tools complying with the standard.](https://staging.python.org/dev/peps/pep-0621/#reference-implementation)

**Comment by rossbar** [comment]
To be clear: I'm -1 on both `setup.cfg` **and** `pyproject.toml` (at this point in time at least) and am in favor of sticking with `setup.py`

**Comment by jarrodmillman** [comment]
-1 on both ``setup.cfg`` and ``pyproject.toml`` as well.

**Pull request closed without merging**
