### PR TITLE
added resolution parameter to modularity

### PR DESCRIPTION
**Pull request by gveltri**
Added resolution parameter, gamma, to modularity in algorithms.community.quality.modularity.

See [Statistical Mechanics of Community Detection](https://arxiv.org/abs/cond-mat/0603718)

#3153

### CODE REVIEW

**Comment by dschult** [comment]
Thanks -- 
Would it be possible to add a simple test that makes sure we don't mess this up later?
Even just computing one very simple case with resolution=2 and checking values would be helpful.

**Comment by dschult** [comment]
This addresses one major part of #3153. It implements the generalized case for the ```modularity`` function. 

Does it make sense to generalize other functions in this module? 
What about in the ```modularity_max.py``` module? 
If you'd prefer those changes to be in another PR thats fine.

**Comment by gveltri** [comment]
It looks like Xiaoylu has added it along with the modularity maximization change. I could add a test to this if we want to split out the modularity resolution change from xiaoylu's pull request #3153.

**Comment by dschult** [comment]
Let's work on getting #3260 merged

**Pull request closed without merging**
