### PR TITLE
Simplifies rich-club coefficient code.

### PR DESCRIPTION
**Pull request by jfinkels**
Uses enumerate and heapq instead of more complicated code constructions.

Also updates documentation and makes PEP8 style fixes.

### CODE REVIEW

**Comment by jfinkels** [comment]
Updated due to pull request #1868.

**Comment by hagberg** [comment]
Is it faster to use heapq like this instead of sorting?

**Comment by jfinkels** [comment]
Oh, I guess perhaps it doesn't make sense to use heapq since all elements are being sorted once and then popped in order, with no additional insertions. I'll update this pull request.

**Comment by jfinkels** [comment]
Okay, should be better now.

**Pull request merged**
