### PR TITLE
Refactor subgraph and communicability measures (#1239)

### PR DESCRIPTION
**Pull request by Michael-E-Rose**
* Correct names of functions (communicability centrality was really subgraph centrality)
* Split subgraph centrality measures (including communicability betweenness centrality) and communicability, as the latter is not a centrality
* Update documentation and correct references
* Update doc tree

### CODE REVIEW

**Comment by chebee7i** [comment]
Since this is renaming functions that already existed, it will be important to mention this in the release notes. Can you update those? And feel free to add yourself to credits.rst if you'd like and haven't already.

**Comment by Michael-E-Rose** [comment]
Sure, I'll do that. But please tell me first where these files are.

**Comment by SanketDG** [comment]
@Michael-E-Rose The release notes file is `api_2.0.rst` and credits is in `credits.rst`. Both of the files are present in `doc/source/reference/`

**Comment by Michael-E-Rose** [comment]
Done - thanks for the invitation to add my name to the contributors!

**Comment by Michael-E-Rose** [comment]
BTW: I couldn't find a proof for Estrada index being the sum of all subgraph centralities ([new file](https://github.com/Michael-E-Rose/networkx/blob/patch-for-1239/networkx/algorithms/centrality/subgraph_alg.py)). Only en.Wikipedia states it, but without reference as well. Shouldn't we add a reference and change the definition in case we can't find one?

**Comment by Michael-E-Rose** [comment]
This one is redundant to #1950 and can be closed.

**Pull request closed without merging**
