### PR TITLE
remove to/from_scipy_sparse_matrix

### PR DESCRIPTION
**Pull request by mjschwenne**
Remove deprecated `to_scipy_sparse_matrix` and `from_scipy_sparse_matrix`.

### CODE REVIEW

**Comment by mjschwenne** [comment]
The documentation build is failing here because of a circular dependency in our gallery examples. The dataset from `libpysal` is being converted into a nx graph with a function that is part of their library and it still uses `from_scipy_sparse_matrix`.

**Comment by jarrodmillman** [comment]
We should create an issue:
- https://github.com/pysal/libpysal/issues
 
Or better still a PR:
- https://github.com/pysal/libpysal/pulls

**Comment by mjschwenne** [comment]
I will try to create a PR for them.

**Comment by mjschwenne** [comment]
See https://github.com/pysal/libpysal/pull/472

**Review by MridulS — APPROVED** [review]
Let's get this in :)
I've skipped building geospatial examples for now.

**Review by jarrodmillman — APPROVED** [review]

**Pull request merged**
