### PR TITLE
Computes approximate Ramsey number using maximum size of sets

### PR DESCRIPTION
**Pull request by renoust**
Fixing python 2.7 invalid max

### CODE REVIEW

**Comment by OrkoHunter** [comment]
@renoust You can always use `git commit -a --amend` to update your last commit if you made any error. However as of now, two commits is unnecessary, try squashing both into one meaningful commit.

**Comment by renoust** [comment]
@OrkoHunter I was trying directly from the github web interface indeed, thanks a lot for the tip!

**Comment by jfinkels** [comment]
As in #1531, these should be `max([c_1, c_2], key=len)`.

**Comment by renoust** [comment]
Alright, sorry guys for being clumsy! I'm kind of new to this.
Point is I didn't just want to complain on a weird behaviors of this
algorithm, but give back by fixing it.
Thanks again for your tips and patience!

--
Benjamin

**Comment by chebee7i** [comment]
No worries and keep up the good work. Your help is much appreciated!

**Comment by jfinkels** [comment]
This was fixed in pull request #1579.

**Pull request closed without merging**
