### PR TITLE
DOC: Add banner for user survey annoucement

### PR DESCRIPTION
**Pull request by MridulS**

### CODE REVIEW

**Review by rossbar — APPROVED** [review]
I'm in favor of the doc banner to increase visibility. I tried the link in the [doc preview](https://output.circle-artifacts.com/output/job/7f4910e3-f9c7-471e-87b6-7ce21d10ab89/artifacts/0/doc/build/html/index.html) and everything looks/functions properly AFAICT.

Should we also add a blurb to the README? If so, it probably makes sense to squash these all into one PR so we can revert it when it's time to close the survey.

**Review by dschult — APPROVED** [review]
I agree that this look good. Also, that it might be good to put it in the readme.
What about the networkx.org landing page?   And then maybe an email to the networkx-discuss email list.

It'll be good to see the results.

**Comment by MridulS** [comment]
The landing page changes should go to https://github.com/networkx/website, I can create a PR there.

**Comment by MridulS** [comment]
https://github.com/networkx/website/pull/16 should matches the documentation banner.

**Comment by dschult** [comment]
That looks good!   

Q:  is it obvious enough?  The link is similar color to the background and at the end of the sentence.  
I don't think it will matter much...  But we could make the link more obnoxiously noticeable and lead with it.

[NetworkX Survey 2023!!](https://forms.gle/NUGcBxyjx5onbAgc8) 🎉 Fill out the survey to tell us about your ideas, complaints, praises of NetworkX!

(I'm not sure how to do the coloring.)  (And this comment is probably just asking for wasted time -- please ignore if you feel that happening.  Rabbit holes are often hard to avoid.

**Comment by MridulS** [comment]
The lint job failure is due to https://github.com/PyCQA/isort/issues/2077, I'll go ahead and self merge this one.

**Pull request merged**
