### PR TITLE
pytest port

### LINKED ISSUE #3102: Test names not found by nose for some tests doubled for others
Some of our tests are not being found and others are being found more than once.
This is especially noticeable in ```classes/tests/test_special.py```
Time for an overhaul... maybe time to move to ```pytest``` too sinc nose isn't supported anymore?

### LINKED ISSUE #3245: Use pytest instead of nose
We should probably move to ``pytest`` at some point in the near future.  Development of nose has stopped and they recommend moving to a new package.  NumPy and SciPy have switched to pytest:
https://docs.scipy.org/doc/numpy-1.15.0/reference/testing.html

### PR DESCRIPTION
**Pull request by stefanv**
Fix #3102 and fix #3245.

We could probably use more idiomatic pytest fixtures etc., but for now just trying to get it to run.

### CODE REVIEW

**Comment by jarrodmillman** [comment]
Travis and AppVeyor are running pytest now.  For some reason, it is taking much longer (e.g., 27 min vs. 3 min) to run the tests now.  Until we sort things out, I reduced the number of builds.  We may need to reduce it further.

## Pytest
https://travis-ci.org/networkx/networkx/jobs/594894127

```
$ source tools/travis/script.sh
/home/travis/venv/lib/python3.8/site-packages/networkx

collected 3606 items / 2 skipped / 3604 selected
251 failed, 2970 passed, 358 skipped, 3 xfailed, 5744 warnings, 26 error in 1656.92s (0:27:36)
```

## Nose
https://travis-ci.org/networkx/networkx/jobs/594301427

```
$ source tools/travis/script.sh
/home/travis/venv/lib/python3.8/site-packages/networkx

Ran 3764 tests in 201.532s
OK (SKIP=94)
```

**Comment by dschult** [comment]
I believe the extra time comes from the ```test``` function imported using ```from networkx import *``` in a few of the test modules.

In a number of files, we use the idiom ```from networkx import *```.  One example is in ```generators/tests/test_classic.py```.  When I run ```pytest -v``` from the command line, it stops for a long time and reports that it is running ```networkx/testing/test```.

I think we need to remove ```from networkx import *``` from the test files.

**Comment by dschult** [comment]
Perhaps it is not good to have a function called ```test``` in our main namespace...
We didn't until recently. It allows people to run the tests using  ```nx.test()```.   Thoughts?

**Comment by stefanv** [comment]
We removed it in `scikit-image`, because most users no longer ran the test suite, and developers tended to call `pytest` directly.  `scipy` has `runtests.py`, that is their entrypoint to executing the test suite on a clean copy of the library.  I have no strong opinions on the matter.

**Comment by stefanv** [comment]
```
= 45 failed, 3544 passed, 22 skipped, 3 xfailed, 7737 warnings, 3 error in 217.17 seconds =
```

**Comment by stefanv** [comment]
Remaining failures are in `vf2userfunc`, `mst` and `reportviews`.

**Comment by stefanv** [comment]
@dschult Do you have any idea what could cause the `mst` failures?

```
ValueError: NaN found as an edge weight. Edge (0, 12, {'weight': nan})
```

**Comment by stefanv** [comment]
We are down to 4 failures.

**Comment by jarrodmillman** [comment]
I am working on getting rid of some of the warnings.  @dschult could you take a look at the 4 remaining failures?

**Comment by stefanv** [comment]
@jarrodmillman Think I got it.

**Comment by stefanv** [comment]
```
3555 passed, 59 skipped, 3 xfailed, 7779 warnings in 134.84s (0:02:14)
```

**Comment by jarrodmillman** [comment]
With all optional dependencies installed:

> 3614 passed, 3 xfailed, 9365 warnings in 768.21s (0:12:48)

**Comment by dschult** [comment]
Wow -- you guys are fantastic -- go out for an evening and you've got all the tests working!
Way to go!

What's next? Do we need to look for better tests to take advantage of pytest features?

Can we figure out a way to avoid rerunning tests in a superclass for every subclass? Maybe that's just a matter of removing "test" from the name... but not sure.

**Comment by jarrodmillman** [comment]
> 3614 passed, 3 xfailed, 9054 warnings in 808.61s (0:13:28)

@dschult Stefan and I are about to lose power soon, so we won't be online for a day or so:
- https://www.sfgate.com/california-wildfires/article/pge-potential-power-outage-map-wind-fire-14501332.php
- https://www.sfgate.com/bayarea/article/school-closure-PG-E-power-shutoff-Bay-Area-14502007.php

Hopefully it will just be a day, but it may be longer.  If you have time and interest, it would be great if you could make progress on these tasks while we are offline:

## Fix warnings

We need to go through the warnings and fix as many as we can.  Pytest is ignoring some of our tests (e.g., tests with an `__init__` constructor and yield tests):

```
=============================== warnings summary ===============================

algorithms/centrality/tests/test_degree_centrality.py:10

  /home/travis/venv/lib/python3.7/site-packages/networkx/algorithms/centrality/tests/test_degree_centrality.py:10: PytestCollectionWarning: cannot collect test class 'TestDegreeCentrality' because it has a __init__ constructor (from: algorithms/centrality/tests/test_degree_centrality.py)

    class TestDegreeCentrality:

algorithms/coloring/tests/test_coloring.py:41

  algorithms/coloring/tests/test_coloring.py:41: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_basic_cases will be ignored

    def test_basic_cases(self):
```

## Remove nose imports

I started removing the nose imports, but there are still several remaining.  The main issue here will be dealing with assert_almost_equal, SkipTest, raises, and assert_raises.

For assert_almost_equal, I noticed
```
def almost_equal(x, y, eps=0.5):
    if abs(x - y) < eps:
        return True
    return False
```
in networkx/generators/tests/test_internet_as_graphs.py.  Maybe move that to somewhere like networkx/testing/utils.py.  Then you can replace assert_almost_equal with assert almost_equal.  You may want to implement almost_equal(x, y, places=7,err_msg='') or something similar.

You may want to take a look at:
https://github.com/numpy/numpy/blob/master/numpy/testing/_private/utils.py

I don't know if there is anything useful there, but there might be.

These might be worth skimming:
- http://doc.pytest.org/en/latest/assert.html
- https://docs.pytest.org/en/latest/nose.html
- http://doc.pytest.org/en/latest/goodpractices.html

## Double check coverage

Just to make sure we aren't missing any tests.

**Comment by jarrodmillman** [comment]
And it looks like there is another test failure now that I have reenabled all the test platforms.  I will leave this to you @dschult .  I will take another look on Friday.

**Comment by dschult** [comment]
Great -- I will take a look.  I've been trying replacing ```__init__``` with ```setup_method``` and it seems to work, but I'm not sure on distinction between cls.G and self.G variables. Will read more.

Have a great couple of days!  Best wishes and Thanks For All the Fish!
Dan

**Comment by jarrodmillman** [comment]
Power wasn't down yet, so I made one final documentation commit that also fixes #2574.  I am done for now, so feel free to work on anything.

**Comment by stefanv** [comment]
@jarrodmillman Would it make sense to adopt `numpy.testing.assert_*`?

**Comment by stefanv** [comment]
I love your enthusiasm about the new tests :)

> Great -- I will take a look. I've been trying replacing `__init__` with `setup_method` and it seems to work, but I'm not sure on distinction between cls.G and self.G variables. Will read more.

When you want to set up a class once and once only, then you use

```
@classmethod
def setup_class(cls):
   cls.G = ...
```

Everything that gets stored on `cls` will, once that class is instantiated, also be accessible on `self`.

If, however, you have test data that needs to be refreshed between each test, then you do it using:

```
def setup_method(self):
    self.G = ...
```

The first invocation is really only useful if you do not modify the data during testing.

With pytest, there is a nicer way of providing test data, namely [fixtures](https://docs.pytest.org/en/latest/fixture.html):

```
@pytest.fixture
def G():
    g = Graph()
    g.add_edges(...)
    return g
```

Then:

```
def test_graph_connectivity(g):
    assert len(list(g.edges)) == 3
```

You can set whether `g` is recreated once per module, function call, etc.:

```
@pytest.fixture(scope='function')  # or `class`, `module`, `package` or `session`
```

**Comment by jarrodmillman** [comment]
We probably don't want to depend on `numpy.testing.assert_*` for testing, since numpy is currently an optional dependency and the only thing we may need that it provides is `assert_almost_equal`.  For that, I was imaging that all we need is something like:
```
def almost_equal(x, y, places=7, err_msg=None):
    if err_msg is None:
        assert round(abs(x - y), places) == 0
    else:
        assert round(abs(x - y), places) == 0, err_msg
```
Then just replace the non-NumPy `assert_almost_equal`, with `assert almost_equal`.  For tests like
`networkx/algorithms/shortest_paths/tests/test_dense_numpy.py`, we would continue using `from numpy.testing import assert_equal, assert_almost_equal`.

If we end up needing a bunch of other stuff from `numpy.testing.assert_*`, then we may need to rethink this.

**Comment by dschult** [comment]
Looks like ```pytest.raises``` can replace ```nose.assert_raises```

As for ```setup_method``` vs ```setup_class```, if I understand correctly, couldn't we just use setup_method in all cases and not have to figure out when the contents get changed by the test? I guess it costs slightly more time testing. But it would avoid difficult bugs in the tests, no?

**Comment by stefanv** [comment]
> Looks like `pytest.raises` can replace `nose.assert_raises`

Yes, except that it looks as though `assert_raises` somehow could catch multiple exceptions raised, whereas `pytest.raises` only checks for the "outermost" exception—but I think this is actually what you want to test anyway.

> As for `setup_method` vs `setup_class`, if I understand correctly, couldn't we just use setup_method in all cases and not have to figure out when the contents get changed by the test? I guess it costs slightly more time testing. But it would avoid difficult bugs in the tests, no?

Yes, I'd say use fixtures as commented above, or `setup_method`.

**Comment by dschult** [comment]
The doc build seems to be failing because it is running nose on the newly pytest tests.
Is a nose tester built into the doc build?

**Comment by jarrodmillman** [comment]
After we get the test count from 3696 back to 4321, I will add doctest to our coverage report.

## Nose

Python: 3.7 OPTIONAL_DEPS=1 MINIMUM_REQUIREMENTS=1 REPORT_COVERAGE=1
https://travis-ci.org/networkx/networkx/jobs/595217966
Ran 4321 tests in 797.599s

## Pytest

Python: 3.7 OPTIONAL_DEPS=1 MINIMUM_REQUIREMENTS=1 REPORT_COVERAGE=1
https://travis-ci.org/networkx/networkx/jobs/595908324
========== 3696 passed, 9158 warnings in 770.60s (0:12:50) ==========

Python: 3.7 OPTIONAL_DEPS=1 DOCTEST=1 PIP_FLAGS="--pre"
https://travis-ci.org/networkx/networkx/jobs/595908325
========== 4206 passed, 5 skipped, 7500 warnings in 273.98s (0:04:33) ==========

**Comment by dschult** [comment]
I put an example treatment for doctests into convert_matrix.py.  See what you think.

Most of the warnings are about deprecated idioms in our code. Some include our own deprecated function from 2.1 which were "supposed" to be removed in v2.2. I squashed a number of these. I believe all of our own deprecated functions are now gone. There are still some warnings about deprecations from other packages that I haven't gotten to.

Hope you have power soon... :)

**Comment by dschult** [comment]
Any thoughts on how to handle the numpy.matrix deprecations? I guess we could have lots of warnings and leave the code as is. But maybe its better to rewrite the code using arrays (still leaving the matrix creation functions available, but maybe deprecating some e.g. to_numpy_matrix)...

**Comment by jarrodmillman** [comment]
@dschult I think it would be reasonable to leave the deprecations from other packages to a subsequent PR (unless you want to quickly take care of them now).  In particular, let's leave the numpy.matrix deprecations to a separate PR.

I managed to get into my office, which has power.  So I am going to work on removing the assert_raises.  Are you working on anything right now?  I just want to make sure we don't step on each others toes.

**Comment by jarrodmillman** [comment]
I am having the following problem with `networkx/generators/spectral_graph_forge.py`:

```
$ PYTHONPATH=. pytest  --doctest-modules generators/

===================================================================================================== FAILURES =====================================================================================================
_____________________________________________________________________ [doctest] networkx.generators.spectral_graph_forge.spectral_graph_forge ______________________________________________________________________
065         Graph Generation Targeting Modularity", IEEE Infocom, '18.
066         https://arxiv.org/abs/1801.01715
067     ..  [2] M. Newman, "Networks: an introduction", Oxford university press,
068         2010
069 
070     Examples
071     --------
072     >>> import networkx as nx
073     >>> G = nx.karate_club_graph()
074     >>> H = nx.spectral_graph_forge(G, 0.3)
UNEXPECTED EXCEPTION: ModuleNotFoundError("No module named 'numpy'")
Traceback (most recent call last):

  File "/usr/lib64/python3.7/doctest.py", line 1329, in __run
    compileflags, 1), test.globs)

  File "<doctest networkx.generators.spectral_graph_forge.spectral_graph_forge[2]>", line 1, in <module>

  File "</home/jarrod/.venv/nxmin/lib64/python3.7/site-packages/decorator.py:decorator-gen-606>", line 2, in spectral_graph_forge

  File "/home/jarrod/src/networkx/networkx/utils/decorators.py", line 400, in _random_state
    random_state = create_random_state(random_state_arg)

  File "/home/jarrod/src/networkx/networkx/utils/misc.py", line 339, in create_random_state
    import numpy as np

ModuleNotFoundError: No module named 'numpy'

/home/jarrod/src/networkx/networkx/generators/spectral_graph_forge.py:74: UnexpectedException
===================================================================================== 1 failed, 250 passed, 2 skipped in 7.83s =====================================================================================
```
but
```
$ PYTHONPATH=. pytest  --doctest-modules generators/spectral_graph_forge.py
=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.7.4, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
rootdir: /home/jarrod/src/networkx
plugins: cov-2.8.1
collected 1 item                                                                                                                                                                                                   

generators/spectral_graph_forge.py s                                                                                                                                                                         [100%]

================================================================================================ 1 skipped in 0.18s ================================================================================================
```

**Comment by stefanv** [comment]
@jarrodmillman Are you still seeing that problem?

Here's my output:

<details>

```
$ PYTHONPATH=. pytest  --doctest-modules networkx/generators/
================================================================================ test session starts ================================================================================
platform linux -- Python 3.7.4+, pytest-4.3.1, py-1.8.0, pluggy-0.12.0
Using --randomly-seed=1570752168
rootdir: /home/stefan/src/networkx, inifile:
plugins: randomly-2.1.1
collected 253 items                                                                                                                                                                 

networkx/generators/tests/test_mycielski.py ...                                                                                                                               [  1%]
networkx/generators/tests/test_geometric.py .......................                                                                                                           [ 10%]
networkx/generators/tests/test_nonisomorphic_trees.py .....                                                                                                                   [ 12%]
networkx/generators/tests/test_cographs.py .                                                                                                                                  [ 12%]
networkx/generators/tests/test_internet_as_graphs.py .....                                                                                                                    [ 14%]
networkx/generators/tests/test_directed.py ........                                                                                                                           [ 17%]
networkx/generators/tests/test_stochastic.py ......                                                                                                                           [ 20%]
networkx/generators/tests/test_classic.py ..............................                                                                                                      [ 32%]
networkx/generators/tests/test_triads.py ..                                                                                                                                   [ 32%]
networkx/generators/tests/test_joint_degree_seq.py ....                                                                                                                       [ 34%]
networkx/generators/tests/test_atlas.py .....                                                                                                                                 [ 36%]
networkx/generators/community.py .                                                                                                                                            [ 36%]
networkx/generators/joint_degree_seq.py .                                                                                                                                     [ 37%]
networkx/generators/geometric.py .                                                                                                                                            [ 37%]
networkx/generators/random_clustered.py .                                                                                                                                     [ 37%]
networkx/generators/geometric.py .                                                                                                                                            [ 38%]
networkx/generators/degree_seq.py .                                                                                                                                           [ 38%]
networkx/generators/classic.py .                                                                                                                                              [ 39%]
networkx/generators/degree_seq.py .                                                                                                                                           [ 39%]
networkx/generators/community.py .                                                                                                                                            [ 39%]
networkx/generators/geometric.py .                                                                                                                                            [ 40%]
networkx/generators/small.py .                                                                                                                                                [ 40%]
networkx/generators/lattice.py .                                                                                                                                              [ 41%]
networkx/generators/community.py ..                                                                                                                                           [ 41%]
networkx/generators/random_graphs.py .                                                                                                                                        [ 42%]
networkx/generators/directed.py ..                                                                                                                                            [ 43%]
networkx/generators/random_graphs.py .                                                                                                                                        [ 43%]
networkx/generators/classic.py .                                                                                                                                              [ 43%]
networkx/generators/tests/test_atlas.py .                                                                                                                                     [ 44%]
networkx/generators/community.py .                                                                                                                                            [ 44%]
networkx/generators/geometric.py .                                                                                                                                            [ 45%]
networkx/generators/small.py .                                                                                                                                                [ 45%]
networkx/generators/degree_seq.py .                                                                                                                                           [ 45%]
networkx/generators/tests/test_atlas.py .                                                                                                                                     [ 46%]
networkx/generators/degree_seq.py .                                                                                                                                           [ 46%]
networkx/generators/community.py .                                                                                                                                            [ 47%]
networkx/generators/classic.py .                                                                                                                                              [ 47%]
networkx/generators/geometric.py .                                                                                                                                            [ 47%]
networkx/generators/trees.py .                                                                                                                                                [ 48%]
networkx/generators/classic.py .                                                                                                                                              [ 48%]
networkx/generators/degree_seq.py .                                                                                                                                           [ 49%]
networkx/generators/community.py ..                                                                                                                                           [ 49%]
networkx/generators/classic.py .                                                                                                                                              [ 50%]
networkx/generators/line.py .                                                                                                                                                 [ 50%]
networkx/generators/joint_degree_seq.py .                                                                                                                                     [ 50%]
networkx/generators/tests/test_atlas.py .                                                                                                                                     [ 51%]
networkx/generators/community.py .                                                                                                                                            [ 51%]
networkx/generators/spectral_graph_forge.py .                                                                                                                                 [ 52%]
networkx/generators/community.py .                                                                                                                                            [ 52%]
networkx/generators/directed.py .                                                                                                                                             [ 52%]
networkx/generators/line.py .                                                                                                                                                 [ 53%]
networkx/generators/social.py .                                                                                                                                               [ 53%]
networkx/generators/tests/test_ego.py ..                                                                                                                                      [ 54%]
networkx/generators/tests/test_line.py ............................                                                                                                           [ 65%]
networkx/generators/tests/test_degree_seq.py ...................                                                                                                              [ 73%]
networkx/generators/tests/test_spectral_graph_forge.py .                                                                                                                      [ 73%]
networkx/generators/tests/test_lattice.py ....................                                                                                                                [ 81%]
networkx/generators/tests/test_expanders.py ...                                                                                                                               [ 82%]
networkx/generators/tests/test_harary_graph.py ..                                                                                                                             [ 83%]
networkx/generators/tests/test_trees.py ..                                                                                                                                    [ 84%]
networkx/generators/tests/test_intersection.py ...                                                                                                                            [ 85%]
networkx/generators/tests/test_random_clustered.py ....                                                                                                                       [ 86%]
networkx/generators/tests/test_community.py ................                                                                                                                  [ 93%]
networkx/generators/tests/test_small.py ...                                                                                                                                   [ 94%]
networkx/generators/tests/test_duplication.py .......                                                                                                                         [ 97%]
networkx/generators/tests/test_random_graphs.py .......                                                                                                                       [100%]

================================================================================= warnings summary ==================================================================================
networkx/generators/spectral_graph_forge.py::networkx.generators.spectral_graph_forge.spectral_graph_forge
networkx/generators/spectral_graph_forge.py::networkx.generators.spectral_graph_forge.spectral_graph_forge
networkx/generators/spectral_graph_forge.py::networkx.generators.spectral_graph_forge.spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
networkx/generators/tests/test_spectral_graph_forge.py::test_spectral_graph_forge
  /home/stefan/envs/py37/lib/python3.7/site-packages/numpy/matrixlib/defmatrix.py:71: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
    return matrix(data, dtype=dtype, copy=False)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
====================================================================== 253 passed, 26 warnings in 6.08 seconds ======================================================================
```

</details>

**Comment by jarrodmillman** [comment]
Do you have numpy installed?  The problem occurs when NumPy isn't installed.

**Comment by stefanv** [comment]
> Do you have numpy installed? The problem occurs when NumPy isn't installed.

I see the issue, please hold.

**Comment by stefanv** [comment]
Actually, I think this problem is all over the place, anywhere where you currently have "from nose import SkipTest"

**Comment by stefanv** [comment]
I could not find an easy fix: you basically want `importorskip` but for doctests, but I'm not sure such a thing exists.  I might just use the `+SKIP` directive on that one test.  Or otherwise use a plugin like https://pypi.org/project/pytest-doctestplus/

**Comment by jarrodmillman** [comment]
I am tempted (for now) to just require our doctests to pass if you have all the dependencies installed.  We can look at using something like `pytest-doctestplus` in a future PR.

**Comment by jarrodmillman** [comment]
BTW my power just came back on, so I plan to work on this for the next few hours.  I will try to remove the remaining nose bits.

**Comment by stefanv** [comment]
@jarrodmillman What do you think of that fix?

**Comment by dschult** [comment]
I'm offline till Saturday. Good stuff here.. :}

**Pull request merged**
