### PR TITLE
Adding examples to docstring in clique.py

### PR DESCRIPTION
**Pull request by ManasviEmmadi**
Sorry for the unwanted commits that are visible!

### CODE REVIEW

**Review by dschult — COMMENTED** [review]
Thanks for this...   I have two main comments:

1) It might be better to use a graph that we know the shape of for these examples. Using a `gnp_random_graph` doesn't give the reader any sense of what the graph looks like. A nice graph for showing how `cliques` are affected is a `barbell_graph`, or a `lollipop_graph`.  They have two or one clique respectively with a path connected to the cliques. You get to pick how many nodes are in the clique(s) and the path.  You could add isolated nodes to make it relevant for the independent_set routines.

2) instead of importing a 4th level module and calling a function from within that module, it might be cleaner to use the approximation namespace directly from `nx` as:
```python
>>> G = nx.<graph_creation_function>
>>> nx.approximation.max_clique(G)
```
Then no long import statement is needed.

**Review by rossbar — COMMENTED** [review]
+1 for adding examples, a few thoughts:

1. Using random graphs as inputs is not particularly enlightening as there's no indication of the structure of the underlying graph that is going into the computation. The best example would use the *simplest possible* input graph that still illustrates the demonstrated functionality well.
2. Just a nit, but the underlines on the Examples section must be made of `-`, not `_` and should have the same length as the `Examples` header.

**Comment by rossbar** [comment]
Gentle ping @ManasviEmmadi - are you still working on this?

**Comment by MridulS** [comment]
Closing this for now, thanks for opening the PR @ManasviEmmadi!

**Pull request closed without merging**
