### PR TITLE
Matrix market io

### PR DESCRIPTION
**Pull request by hcars**
The MatrixMarket format is used in several major network repository such as Network Repository and SuiteSparse to store graphs. The format has existed for some time, and it should be easy to integrate into NetworkX. Scipy already has parsers for MatrixMarket; these only need to interact with existing NetworkX methods.

### CODE REVIEW

**Review by rossbar — COMMENTED** [review]
I guess the big question for me is whether this is necessary - adding thin wrappers around the scipy parsing feels like an unnecessary layer of indirection. Maybe adding a tutorial or gallery example illustrating the scipy functionality could be an alternative? Overall I'm very much +1 about adding support for the format, just curious whether adding something explicit like this is the best solution since parsers are already available in commonly used scientific Python libraries.

I'm happy to hear what others think!

**Comment by hcars** [comment]
> I guess the big question for me is whether this is necessary - adding thin wrappers around the scipy parsing feels like an unnecessary layer of indirection. Maybe adding a tutorial or gallery example illustrating the scipy functionality could be an alternative? Overall I'm very much +1 about adding support for the format, just curious whether adding something explicit like this is the best solution since parsers are already available in commonly used scientific Python libraries.
> 
> I'm happy to hear what others think!

You may be right that these thin wrappers are unnecessary. If you just want to go with a tutorial in the documentation on this, would this just be part of the _readwrite_ section of the documentation?

**Comment by rossbar** [comment]
> You may be right that these thin wrappers are unnecessary.

There's obviously a tradeoff - on the one hand having our own I/O functions that wrap scipy would likely be more convenient for users, but OTOH I'm a big fan of this stanza from PEP 20:

> There should be one— and preferably only one —obvious way to do it.
> Although that way may not be obvious at first unless you're Dutch.

Using the existing scipy parsing facilities feels more in line with this maxim, and in principle it shouldn't be *that* much worse for users to write e.g. `nx.from_numpy_array(scipy.io.mmread(fname))` than `nx.read_matrix_market(fname)` as long as they know to do so (which we can explain in docs w/ examples).

Bear in mind though this is just one opinion! I tend to skew towards solutions that require adding less code at the expense of user convenience, so I wouldn't undo your PR until we've had more opinions shared. It's very possible others will prefer the new module to updating docs.

> If you just want to go with a tutorial in the documentation on this, would this just be part of the readwrite section of the documentation?

I think so --- the first thing I'd try is creating a `matrix_market.rst` file in https://github.com/networkx/networkx/tree/main/doc/reference/readwrite and then adding it to the `toctree` in `index.rst`.

**Comment by jarrodmillman** [comment]
I agree with @rossbar.  We just removed a few IO functions that were just minor wrappers.  I started adding a section about readwrite to the tutorial, but maybe it should also be put in the reference manual #4283.

**Comment by rossbar** [comment]
I'm going to close this as the MM format was addressed in the docs instead in #4934 . Please feel free to raise issues/open PRs to improve the [matrix market docs](https://networkx.org/documentation/latest/reference/readwrite/matrix_market.html). Many thanks @hcars for raising awareness about MM & the scipy functions!

**Pull request closed without merging**
