### PR TITLE
make layouts accept nodelists and center argument

### PR DESCRIPTION
**Pull request by dberenbaum**
Proposing two changes to the layout functions:

1. Making functions accept a list of nodes instead of an entire Graph.
2. Adding center as an argument to allow for a layout centered around a point other than the origin.

The idea is to give users more control to use the layouts to plot subsets of graph points.

### CODE REVIEW

**Comment by Midnighter** [comment]
Silly question: You have seen [this layout function](http://networkx.github.io/documentation/networkx-1.9.1/reference/generated/networkx.drawing.nx_pylab.draw_networkx_nodes.html#networkx.drawing.nx_pylab.draw_networkx_nodes)?

**Comment by dberenbaum** [comment]
Yeah, it was using that function that led me to want to implement this functionality. I could draw selected nodes, but I couldn't set a layout for just those nodes using the built-in functions. 

For example, using this modification, it would be simple to draw a subset of nodes in a circular layout:

    nodes=nx.draw_networkx_nodes(G,nodelist=node_subset,pos=nx.spring_layout(node_subset))

This is especially helpful for drawing each group of nodes in a network separately. 

Let me know if I'm missing something.

**Comment by dberenbaum** [comment]
Is there any interest in this?

I've updated to pass tests for python3. There's still one Travis build failure, but it's hard for me to tell if it has anything to do with these updates.

**Comment by dschult** [comment]
What does this do for layout algorithms that actually use the graph structure?
If you replace G with a list of nodes, you have lost the graph structure.
That works for a few of the layout algorithms that don't use the structure.
But beyond those very simplistic layouts this interface won't work. Am I missing something?

**Comment by chebee7i** [comment]
Yeah it seems like if you want to draw a subset, then you create a subgraph and then call the standard draw function.

**Comment by dschult** [comment]
For the "center" keyword, we have some FIXME comments in the code about adding normalization. Perhaps we should provide a separate function to normalize positions with specified center and specified width (std dev?  radius?).

```
pos = nx.spring_layout(G.subgraph(nodelist))
pos = nx.normalize_layout(pos, center, width)
```

**Comment by hagberg** [comment]
There is layout._rescale_layout()

**Comment by dberenbaum** [comment]
Passing in a node list will create a simple, undirected graph within the function to deal with more complex layouts (you can also still pass in an actual graph and nothing will change). The only features of the graph that are accessed by the layout functions are getting the nodes and checking whether the graph is directed, so I can't see any functionality that's being lost. 

Besides saving you the step of having to create a new graph from a subset of nodes, this also allows you to keep the overall graph attributes intact, including the edges between the subsets. 

Simple example that draws the entire graph but splits the nodes into two groups:

    G = nx.karate_club_graph()
    officer_nodes = [n for n,d in G.nodes_iter(data=True) if d['club'] == 'Officer']
    mr_hi_nodes = [n for n,d in G.nodes_iter(data=True) if d['club'] == 'Mr. Hi']
    pos = nx.circular_layout(officer_nodes)
    pos.update(nx.circular_layout(mr_hi_nodes,center=(3,0)))
    nx.draw(G,pos)

**Comment by chebee7i** [comment]
Ah. That is pretty neat, and very useful.

**Comment by chebee7i** [comment]
+1 from me. Somehow I completely misunderstood what this PR was doing. 
Your example clarified quite a bit.

**Comment by dberenbaum** [comment]
I like the idea of putting the center argument into the _rescale_layout function. I'm happy to update with this and attempt to address the FIXME in the shell_layout function if others agree it makes sense. It looks like an issue with the current _rescale_layout function is that it creates a layout with its minimum coordinates at the origin rather than centered at the origin.

**Comment by dberenbaum** [comment]
After looking at it again, I think it's better to keep the centering outside of  _rescale_layout().

I did change _rescale_layout() to be centered around the origin with a range from (-scale,scale), rather than scaling from 0 to the scale value. I think this is closer to expected behavior and allows for an easy solution to the FIXME issue in rescaling shell layouts (the FIXME is resolved in the latest commit).

**Comment by dberenbaum** [comment]
Should I keep this request open? Anything else you'd like to see here?

**Comment by chebee7i** [comment]
Yeah, just waiting to hear back from others.

**Comment by dberenbaum** [comment]
Thanks! Just checking.

**Comment by chebee7i** [comment]
Could you add a note to the release notes? `doc/source/reference/api_2.0.rst`. Also, consider adding any information you'd like to `credits.rst`. Otherwise, this is probably good to merge.

**Comment by dberenbaum** [comment]
Note added!

**Comment by chebee7i** [comment]
I've sent you a PR with some refactorings. Please review it.

**Comment by chebee7i** [comment]
Funny that github included discussion from an unrelated commit. Oh well.

Assuming this passes, was there anything else you wanted to put into this PR?

**Comment by dberenbaum** [comment]
Huh, that is weird.

I don't have anything else to add. Let me know if you see anything else. Hope I can find more ways to contribute in the future!

**Comment by chebee7i** [comment]
Yes, your contributuon is much appreciated! Looking forward to more in the future.

**Pull request merged**
