### PR TITLE
Structured labelled array 4217

### PR DESCRIPTION
**Pull request by aliveevie**
**Construction of adjacency-like matrices**
Now, we explore how we can construct the adjacency-like matrices.

It's possible to construct a wide range of adjacency matrices on which message passing can be performed. For example, one might want to do message passing on the 1-degree adjacency matrix, or do it on a 2-degree adjacency matrix where anything within two degrees of separation are given a "1". One may want to leverage the graph Laplacian matrix too. As such, more than just a matrix, we might want to generate an adjacency tensor. A proposed function we could include in the library, or propose to the NetworkX library, is as follows

`def generate_adjacency_tensor(
    G: nx.Graph, funcs: List[Callable], return_array=False
) -> xr.DataArray:
    mats = []
    for func in funcs:
        mats.append(func(G))
    da = xr.concat(mats, dim="name")
    if return_array:
        return da.data
    return da
`

### CODE REVIEW

**Comment by rossbar** [comment]
Did you perhaps intend to open this PR to the `networkx/outreachy` repo instead?

**Comment by aliveevie** [comment]
> Did you perhaps intend to open this PR to the `networkx/outreachy` repo instead?

yes

**Comment by MridulS** [comment]
I will close this PR here, feel free to open the PR to the outreachy repository https://github.com/networkx/outreachy/ when the example is ready.

**Comment by aliveevie** [comment]
ok

**Pull request closed without merging**
