### PR TITLE
When exporting to GML, write non 32-bit numbers as strings.

### PR DESCRIPTION
**Pull request by tobiasblass**
According to the GML technical report, integers in GML must fit into a
signed 32-bit integer. Values outside this range have to be written as
strings instead.

### CODE REVIEW

**Comment by dschult** [comment]
Looks like a good idea.
I think the < operator won't work if ```value is None```.
Maybe we need a test to check that this works and a fix if it doesn't.

**Comment by tobiasblass** [comment]
> I think the < operator won't work if `value is None`.
> Maybe we need a test to check that this works and a fix if it doesn't.

You're right (I didn't notice this because it only occurs in the `literal_stringizer` case). However, I think there is a different problem: `literal_stringizer` translates None to 'None', which is also invalid GML, isn't it? Shouldn't None be translated to '"None"' (i.e., within quotes)?

**Comment by tobiasblass** [comment]
Looking at the problem in more detail, I noticed that `literal_stringizer` does not have to output valid GML.  It is intended to be used as the `stringizer`-argument for `generate_gml`, and the output of this stringizer is put into quotes anyway.
This means that we don't need a range check in `literal_stringizer`

**Comment by dschult** [comment]
Ahh...  good... thank you!!

**Pull request merged**
