### PR TITLE
Update geospatial readme

### PR DESCRIPTION
**Pull request by jarrodmillman**
Co-authored-by: Brendan Ward <bcward@astutespruce.com>
Co-authored-by: Martin Fleischmann <martin@martinfleischmann.net>
Co-authored-by: Geoff Boeing <gboeing@users.noreply.github.com>
Co-authored-by: Ross Barnowski <rossbar@berkeley.edu>

### CODE REVIEW

**Comment by ljwolf** [comment]
Yes, sorry, missed your PR about #4366, sorry! Will draft the stubbed points.

**Comment by jarrodmillman** [comment]
I am still not sure where this should live.  It looks out of place in the gallery.  I am considering moving it to the tutorial or reference guide and then pointing to that from the gallery examples.  If anyone has any suggestions or preferences, let me know.

@ljwolf I think we should move ``examples/drawing/plot_knuth_miles.py`` to ``examples/geospatial/plot_knuth_miles.py``:
https://networkx.org/documentation/latest/auto_examples/drawing/plot_knuth_miles.html
Does that seem reasonable?  If so, would it make sense to use GeoPandas rather than Cartopy?  We used Cartopy because it is just the first way we figured out how to do it.  If you have time, it would be wonderful if you made any changes you see fit to the ``plot_knuth_miles.py`` example in a separate PR.

**Comment by rossbar** [comment]
>  If anyone has any suggestions or preferences, let me know.

The only thing I don't like about having it in the top-level geospatial README is that it drops a big wall of text in the gallery. One option to avoid this might be to move the more detailed descriptions to an orphaned document that we link to from the README. It would look something like the following:

`examples/geospatial/README.txt`:

```
Geospatial
----------

The following geospatial examples showcase different ways of performing
network analyses using packages within the geospatial Python ecosystem.
Example spatial files are stored directly in this directory. See
:doc:`extended_description` for more details.
```

With the remainder of the content moved to a new file, e.g. `examples/geospatial/extended_description.rst`:

```
:orphan:

Dependencies
~~~~~~~~~~~~

`GeoPandas <https://geopandas.readthedocs.io/>`__ provides
...
```

That at least makes the additional info readily available (and keeps it tightly coupled to the gallery) without adding all of the text directly to the gallery landing page.

**Comment by jarrodmillman** [comment]
I think this is ready to merge.  @ljwolf still needs to fill in some stubs and maybe give it a light edit.  But he can make a PR against master.

The text is incomplete, but it is much better than what we currently have.  I will make sure either @ljwolf or I clean it up before the next release.

@rossbar I couldn't find a clean way to get ``examples/geospatial/extended_description.rst`` converted to html using the standard sphinx and sphinx_gallery options.  The simplest solution I could find was to copy the rst file to the correct location before running sphinx-build.  You can see what I did in the Makefile.  I also opened an issue with sphinx_gallery to see if there is a cleaner way.  If not, I will try to get them to provide one.  For now, I don't think it is too bad and it works.

**Review by rossbar — APPROVED** [review]
Ack yeah I hadn't considered the distinction between sphinx-gallery and sphinx. The description can likely be added to the main documentation as an orphan (e.g. in `doc/geospatial_examples.rst`) and then it will be picked up by sphinx build, but your solution is fine as well.

LGTM - I'm fine with an "incomplete" document (e.g. the momepy section) being pushed to latest - it would be great if we could finish rounding it out prior to the next release.

**Pull request merged**
