### PR TITLE
MAINT: Disable building delaunay geospatial example temporarily

### PR DESCRIPTION
**Pull request by MridulS**
Fix to make our CI happy for now. Should be reverted as soon as there is a new contextily release https://github.com/networkx/networkx/issues/6980

### CODE REVIEW

**Comment by dschult** [comment]
Looks like both contextily and nbconvert changed versions on our CI between the success and failures.
My recent update here leads to an nbconvert exception.  I see that they released 7.9.0 12 hrs ago and then 7.9.1 just after this ran, so I'm going to start it again to see if 7.9.1 fixes what we need.

**Comment by dschult** [comment]
Yes -- the new release for nbconvert is causing the 'no attribute "exporter"' error in 7.9.1 and not in 7.8.0.
Should we pin contextily and nbconvert versions for a week or so?  

We might see more release issues as package push to release for Python 3.12 support.

**Comment by MridulS** [comment]
I think we should maybe let this fail for a bit then 😅 
The `contextily` failure is due to an underlying tile asset provider put up a paywall/login, so we need a new release anyway. I'll investigate `nbconvert` a bit more, it doesn't seem very obvious from the changelog https://github.com/jupyter/nbconvert/compare/v7.8.0...0e36347f31ee0b06d461aaa845e458eb7c9f8fc0 what has changed wrt to `exporter`

**Comment by dschult** [comment]
I think the exporter package/module is still there. But they switch the `__init__.py` file to list specific entries to import instead of star.  So -- PR 2040 https://github.com/jupyter/nbconvert/pull/2040
no longer imports the exporter module. Only its contents.  So the code that is using it (inside nb2plots?) just needs to remove `.exporter` from their code and it should work.

**Comment by MridulS** [comment]
Yeah that seems to be the issue, @jarrodmillman just pinned it https://github.com/networkx/networkx/pull/6983

**Review by jarrodmillman — APPROVED** [review]

**Pull request merged**
