### PR TITLE
added pipenv support

### PR DESCRIPTION
**Pull request by aijanai**
Added Pipfile and Pipfile.lock as it is a more robust and proven virtualenv manager

### CODE REVIEW

**Comment by aijanai** [comment]
Fixes #3898

**Comment by rossbar** [comment]
Users should already be able to use `pipenv` to install networkx if that's their preferred environment manager, e.g. `pipenv install networkx` or, if building for development, `pipenv install -e .` from the top-level directory. AFAICT the files included in this PR simply specify a single, particular environment (though be no means the *only* valid environment for networkx).

**Comment by aijanai** [comment]
Of course it's a particular lock version, but the idea is to supersede the requirements.txt dependency format, as it creates troubles.

**Comment by rossbar** [comment]
> but the idea is to supersede the requirements.txt dependency format, as it creates troubles.

I'm -1 on *replacing* the requirements files - this is a standard way for specifying dependencies for Python projects (note that `pip` (`ensurepip`) and `venv`, both part of the Python standard library) and they are universally supported by other package managers like `conda` and `pipenv`. 

Introducing multiple files for keeping track of dependencies (e.g. a Pipfile for pipenv, an environment.yml for conda, etc.) creates a maintenance burden to ensure that they are always in sync with each other - it is much more straightforward to rely on the format that is supported by all the package/environment management tools.

If you are having specific problems installing/setting up an environment, please open an issue on it so we can fix the specific problem in the requirements files.

**Comment by jarrodmillman** [comment]
I am -1 on this as well, so I am closing this PR.

**Pull request closed without merging**
