### PR TITLE
Implemented subgraph monomorphism

### PR DESCRIPTION
**Pull request by diogo-cruz**
It is now possible to search for subgraph monomorphisms by using `subgraph_is_monomorphic()` and `subgraph_monomorphisms_iter()` in the same way that `subgraph_is_isomorphic()` and `subgraph_isomorphisms_iter()` is used, respectively.

### CODE REVIEW

**Comment by diogo-cruz** [comment]
travis-ci is throwing an error in the function `random_degree_sequence_graph`, which is in no way related to my commits, so I don't know what is causing the issue.

**Comment by dschult** [comment]
The error for the random test is because someone (probably me) merged the test without making it set a seed for the RNG. So occasionally it doesn't pass the test.  It should be investigated further -- but not as part of your PR. 

The codecov test complaint that is showing up now is because many of the lines of code which ```return False``` aren't being tested. Can you add tests that make sure each way to make it fail is tested?  

Thanks for this!

**Comment by diogo-cruz** [comment]
Thanks for the feedback.
I've added some tests for multigraphs. I don't know enough about the subject to write non-trivial tests, unfortunately.

**Comment by dschult** [comment]
Non-trivial tests are probably beyond the scope for this sort of github interface anyway. I'm not looking for anything beyond very simple tests that just test one thing at a time (unit-tests).  For example, if you look at the Codecov report "diff" for this PR: https://codecov.io/gh/networkx/networkx/pull/3435/diff
It shows each line as green if the line was executed as part of the tests. Red means it wasn't executed and Yellow means it is an "if" statement (or other branch) where only one of the two possibilities was encountered in the tests.

The first line that is red is line 371 and that simply means you don't have any tests which cause this criteria for ```subgraph_is_monomorphic``` to return False. The fix is to add a test using this function where the subgraph is not monomorphic. Scanning through the report it looks like lots of criteria that make the routine return False are not tested.  Coming up with tests should amount to finding simple cases where they aren't monomorphic. (that's not always easy-- but it shouldn't be too tricky for most of those cases.

**Comment by diogo-cruz** [comment]
I think I've added the necessary tests. The if's left untested were already so before my changes.

**Comment by dschult** [comment]
Thanks very much!  Is there anything else for the code itself?

I know the docs are not very complete in this module -- they don't follow the usual style of other NetworkX functions. And I don't think we should try to fix that in this PR. But I hate to add code without some basic additions to the docs.

Can you add a paragraph in the module's head doc_string about monomorphisms, what they are and when they would be of interest? Also, for each function with a new argument ```mono```, could you add a line in the docstring stating what it means and how to use it.

Finally, can you check pep8 compliance using ```pycodestyle``` (installable via pip).
Thanks for all this!

**Comment by diogo-cruz** [comment]
Thanks! I actually rewrote the code, since it made more sense for `mono` to be an option for `self.test` instead of being an argument.

I put a small explanation in the doc_string about monomorphisms, and added an explanation of the `self.test` new option where the previous options appeared.

I checked the pep8 compliance, whatever was not following it before my PR is still not following it. They are mostly if statements that, if fixed, would become harder to read. All else should be fixed now.

**Comment by dschult** [comment]
If someone requests a monomorphism_iter, that changes ```self.test```. Can they later request an isomorphism_iter?

**Comment by diogo-cruz** [comment]
Yes, both `isomorphisms_iter` and `subgraph_isomorphisms_iter` change the `self.test` variable to the appropriate string, when they're called.

**Comment by dschult** [comment]
Ahh... I see now -- I was only looking at the diff... not the whole file.   Good...  But now I have another question:

Might someone want to do a graph-graph monomorphism? Or is that just a graph-subgraph monomorphism and we don't have to worry about that showing up some day.
(I just want to make sure "mono" is sufficient rather than using "mono_subgraph" or something.

**Comment by diogo-cruz** [comment]
Yes, it is the same thing, in fact it might also be referred to as graph monomorphism. I'm not aware of any situation where they are different.

**Comment by dschult** [comment]
OK.. I think this is ready to merge. Anything else to add before I do that?

**Comment by diogo-cruz** [comment]
Thanks! No, go ahead, I think everything is here.

**Pull request merged**
