### PR TITLE
Added lowest common ancestor algorithm for trees and DAGs.

### PR DESCRIPTION
**Pull request by calmofthestorm**
This adds LCA for trees and DAGs, using Tarjan's offline lowest common ancestors algorithm and the DAG algorithm described in Bender et al (2005).

In addition to the  included unit tests, this was tested against a naive algorithm on a bunch of random graphs, and run (not compared to a naive) in on a ~40,000 node subgraph of the Wikipedia category graph to check for crashes and sanity of output (this was done as 40,000 different compute tasks on PiCloud; I need the data anyway.)

Two points of interest for the code review:
1) I have attempted to follow the style of many NetworkX algorithms of minimizing names (even _ ones) in the namespace. As such, this file is two long functions. If appropriate, I could split them into smaller, focused private helpers to make the code more clear.
2) Please take a look at lines 64 and 165; this is my attempt to balance generality and efficiency (especially since the DAG algorithm makes use of the tree algorithm). I know it violates the spirit of duck typing, but I would like to avoid an unnecessary double copy of large data structures.

### CODE REVIEW

**Comment by jfinkels** [comment]
Maybe these functions should be separated and put in the `networkx.algorithms.tree` and `networkx.algorithms.dag` packages.

**Comment by calmofthestorm** [comment]
Sure, no problem I'd be happy to clean up the merge conflict and move those around if you feel that makes the most sense. Will any other changes be necessary? It's easiest for me to do as much as possible at once.

If I do so, do you think you'd be able to consider this for inclusion in the near term? I submitted this PR over two years ago, and between updating the code and clearing the IP issues with my new employer (won't be an issue but needs to be done before I can modify this), I'd hope resolve any back-and-forth soon, especially since any changes to the algorithm will require me to page that paper back into my understanding which will take a day or two:-)

**Comment by Erotemic** [comment]
@calmofthestorm Any chance this PR might be finished? This might help speed up one of my algorithms in #2572

**Comment by calmofthestorm** [comment]
@Erotemic to the best of my knowledge it's done, but hasn't gotten traction from the maintainers to get merged.

I'm happy to make the requested separation, but since this has been open for four years I was hoping to get some buy in from the maintainers to work with me toward merge before going through the necessary process with my current employer which is required to approve open source contributions.

@jfinkels If I fix the merge conflict and separate the functions into tree and dag as requested, do you think you'd be ready to merge this in the near term? Would you need any other changes? It's easiest for approval if I batch them all at the same time.

**Comment by dschult** [comment]
Hello @calmofthestorm 
Sorry for the big delay. I'm afraid there is a backlog of good code waiting to come in.
I can try to get this merged before V2.0 is released (very soon).  If it takes a while to get approval we might need to wait until v2.1.

I don't think you should split this code. The DAG function relies on the tree version and it fits nicely together in the module you have provided.

Looking through the code and starting to get a feel for the algorithm I notice many small changes will be needed for v2.0. Things like ```G.nodes_iter()``` doesn't exist anymore. 

If I rewrite the existing module for v2.0 and merge it, will you still need to get approval? What restrictions are there on your end?

**Comment by calmofthestorm** [comment]
Thanks for the response! This pull request in its current form predates my employment, so I hold clear title, and can release copyright if necessary without requiring any approval.

In order for me to change the code in any way I would require approval. If you rewrite it and merge it, no approval would be necessary.

Thanks again for looking at this, I do appreciate it. I put a ton of work into this back in the day, and it would make me very happy to see it become part of networkx:-)

**Comment by dschult** [comment]
Great!  Thanks very much. I will work on it.

**Comment by dschult** [comment]
merged in #2597

**Comment by calmofthestorm** [comment]
Thanks for merging this and making the changes to bring it up to date!

**Pull request closed without merging**
