### PR TITLE
Add fast approximation for k-(node)-components.

### LINKED ISSUE #580: k-components approximation (migrated from Trac #589)
Original ticket https://networkx.lanl.gov/trac/ticket/589
Reported 2011-07-07 by @jtorrents, assigned to @jtorrents.

New version of the algorithm. To run it you'll need the code for vertex connectivity approximation #538, the antigraph data structure #608. For accuracy tests you will also need the flow based connectivity code #625 

A k-component is a maximal subgraph that cannot be disconnected removing less
than k nodes (along with their incident edges). By Merger's theorem, this is 
equivalent to a maximal subgraph in which all pairs of nodes are connected 
by at least k node-independent paths which each run entirely within the 
subgraph. Note that a k-component must be a subset of a (k-1)-component or
be a (k-1)-component itself. Thus, they have an inherent hiearchical structure.
Components of level k can overlap in k-1 nodes.

Following White and Harary (2001) and Moody and White (2003), the cohesive 
structure of a network can be conceptualized as increasingly cohesive groups 
nested inside each other. Those groups can be operacionalized as the 
k-components of the network. A common structural pattern in large networks is 
an hierarchical nesting of increasingly cohesive groups at low connectivity 
levels and non-overlapping highly cohesive groups at higher connectivity levels. 

Those highly cohesive groups play a key role in the diffusion of the 
consequences of social interactions among actors in networks. It is usually 
assumed that the transmission through the network of knowledge, influence 
and resources generated by social interactions is limited to people 2 or 3 
steps away from the initiator of such interactions. However, strongly cohesive 
subsets of nodes allow repetition of information and reinforcement of influence 
because they are characterized by multiple independent pathways that 
compensate the decay effects of the transmission of knowledge, 
influence and resources.

An exact solution for the computation of the complete k-component structure 
(Moody & White, 2003) is impractical for large networks. This approximation 
is based on the proposal of White and Newman (2001) of a fast approximation
for finding node independent paths (implemented in #538). It allows us to 
compute the approximate k-component structure for moderately large networks, 
in a reasonable time frame.

The algorithm consists in 6 steps:

1. k-core computation (time O(E)): Compute the core number for each node. A k-core is a maximal subgraph that contains nodes of degree k or more. The core number of a node is the largest value k of a k-core containing that node. This is a baseline for k-components because \kappa(G) <= \lambda(G) <= \delta(G)

2. bicomponents computation (time O(V+E)): Compute the biconnected components of the graph. (k>2)-components are a subset of (or are themselves also) a bicomponent. Besides, the exact computation is faster than the approximation because usually bicomponents are quite large. Thus we start computing the approximation for k=3. (same for tricomponents but it is not implemented in NetworkX yet)

3. for each k from 3 to the maximum core number of a node of the graph we repeat the following steps:

4. For each bicomponent we create a subgraph with all nodes with core level = k. Compute the connected component of the k-core sugraph (note that the k-core could be disconnected) and then compute the approximation for vertex connectivity (proposed by White and Newman (2001)) between all pairs of nodes. Implemented in ticket #538. 

5. Build an auxiliary graph with all nodes in the subgraph analyzed and edges between two nodes if the local vertex connectivity (ie number of node independent paths between them) is greater or equal than the level k of the main for loop. Note: we actually use a complement graph data structure to save memory because usually a big part of the k-core is actually a k-component.

6. Each connected component of the auxiliary graph is a candidate to be a k-component. But we need to do a final check: we create the induced subgraph of candidate nodes from the input graph and discard any node that, in this induced subgraph, has core number less than k. The remaining nodes are assumed to be a k-component.

References

    White, Douglas R., and Mark Newman. 2001 
    A Fast Algorithm for Node-Independent Paths. 
    Santa Fe Institute Working Paper 01-07-035  
    http://eclectic.ss.uci.edu/~drwhite/working.pdf

    White, D. R., and F. Harary. (2001) 
    The cohesiveness of blocks in social networks: Node
    connectivity and conditional density,
    Sociological Methodology 31:305--59.
    http://eclectic.ss.uci.edu/~drwhite/sm-w23.PDF

    Moody, James and Douglas R. White. 2003. 
    Social Cohesion and Embeddedness. American Sociological Review. 68:103-127
    http://www2.asanet.org/journals/ASRFeb03MoodyWhite.pdf

### PR DESCRIPTION
**Pull request by jtorrents**
This is an approximation approach to compute the k-component structure
of a graph (#1414 is the exact, and slow, version of this). I wrote a
paper to explore this approach in detail, see http://arxiv.org/abs/1503.04476

The logic of the approximation algorithm for computing the `k`-component
structure is based on repeatedly applying simple and fast algorithms
for `k`-cores and biconnected components in order to narrow down the
number of pairs of nodes over which we have to compute White and Newman's
approximation algorithm for finding node independent paths (implemented at #1405).
More formally, this algorithm is based on Whitney's theorem, which states
an inclusion relation among node connectivity, edge connectivity, and
minimum degree for any graph G. This theorem implies that every
`k`-component is nested inside a `k`-edge-component, which in turn,
is contained in a `k`-core. Thus, this algorithm computes node independent
paths among pairs of nodes in each biconnected part of each `k`-core,
and repeats this procedure for each `k` from 3 to the maximal core number
of a node in the input graph.

Because, in practice, many nodes of the core of level `k` inside a
bicomponent actually are part of a component of level k, the auxiliary
graph needed for the algorithm it's likely to be very dense. Thus, we use
a complement graph data structure to save memory (`_AntiGraph` see #599
for an earlier dicussion about this). AntiGraph only stores information
of the edges that are *not* present in the actual auxiliary graph.
However, when applying algorithms to this complement graph data structure,
it behaves as if it were the dense version. So it can be used directly
in several NetworkX algorithms, this version is only tested for the
algorithms needed here: `connected_components`, `k-cores`, and
`biconnected_components`. I used a `ThinGraph` for building the `AntiGraph`
and the memory consumption is quite small compared with a regular `Graph`.

I think `AntiGraph` is not useful enough to be a top level class in NetworkX,
but it could be a good example of a `Graph` subclass. I'll add to the
examples folder.

This PR supersedes and closes #580.

### CODE REVIEW

**Comment by jtorrents** [comment]
This last commit simplifies the approximation to `k_components` by removing the exact parameter. This was useful in my experiments but in practice is slower than the exact `k_components` build on top of `all_node_cuts` for most graphs.

In my experiments and practical applications I found out that this function can be applied to sparse graphs with tens of thousands of nodes, While the exact implementation at #1414 can only be applied to sparse graphs of thousands of nodes. Also, in my tests, pypy cuts in half the execution time compared to CPython.

**Comment by jtorrents** [comment]
Added this to API changes and rebased to solve merge conflicts in `api_2.0.rst`. Also removed a test for `approximation.connectivity` that was failing in pypy2 because it was depending on the iteration order when searching for paths following White and Newman algorithm. With this I think this is ready. Any comment welcome.

**Comment by ysitu** [comment]
We need to rename `api_2.0.rst` to `api_1.10.rst` as we prepare for a 1.10 release.

**Comment by jtorrents** [comment]
@ysitu, maybe we can do that when we have all PR marked for 1.10 merged? If it helps for the release to rename it before I can update this PR (and other pending PR for 1.10).

**Comment by jtorrents** [comment]
I also think this should be in 1.10

**Pull request merged**
