### PR TITLE
Add option to use Bellman-Ford in generic shortest-path functions

### PR DESCRIPTION
**Pull request by gfetterman**
Addresses #2346 

This is one possible way to do this. I reworked some of the machinery to reduce conditional nesting, but there's still redundant code.

Some verbosity is inevitable - we're trying to value-dispatch on multiple parameters, which isn't usually elegant.

Another approach would be a more dramatic refactor in favor of a more functional style of passing functions around and closing them over values as needed. I've briefly sketched this out for myself, and I can share it in a gist if there's interest. My concern is that it would add complexity (at least for the casual reader) for somewhat questionable gain - how likely is it that the generic shortest-path functions will need to be extended similarly soon?

Finally: this module raises `NetworkXNoPath`, `NetworkXPointlessConcept`, and `NetworkXError` exceptions - should I factor them out, per #1705 ? It's not entirely clear to me from that issue when such refactors should occur, since they're potentially interface-breaking.

### CODE REVIEW

**Comment by dschult** [comment]
If you take out the check for ```source in G``` then I think an input ```v``` that ```is not in G``` gives a ```KeyError``` instead of ```NodeNotFound```.  Is that what we want? I guess we should be testing all these errors...:}

**Comment by gfetterman** [comment]
Good point. I should have checked that more exhaustively:

* unweighted functions (path and length) raise `nx.NodeNotFound` errors, but
* there are no checks in the weighted functions (neither Dijkstra nor Bellman-Ford, neither path nor length), so they raise a `KeyError`, as you point out. (There are checks in `goldberg_radzik()` and `bidirectional_dijkstra()`, though.)

Seems like the minimal answer here is to put that check back into `shortest_path_length()`, and also add it in the same place to `shortest_path()`, which did not have it before. I've now done this.

Would a standardization of the shortest-path function input checking be worthwhile at some point? It could break interfaces ...

**Comment by dschult** [comment]
This looks ready to merge.  Anything else planned for this PR?

**Comment by gfetterman** [comment]
Just a couple of things:

1. Now that #3103 is merged, I could re-remove the absent-source guards in `shortest_path()` and `shortest_path_length()`, since `nx.NodeNotFound` will get raised by the innermost functions.
2. I'm still not hitting the coverage delta target - I'd like to fix that.
3. There is the potential refactor of the `NetworkXNoPath`, `NetworkXPointlessConcept`, and `NetworkXError` throws I mentioned above.

I can throw the first two in later today; for the third I'll wait on a response.

**Comment by dschult** [comment]
I added a short description in the release notes for the change in API and I (hopefully) improved the coverage delta target by changing ```elif``` to ```else``` in some places. 

So, you can remove the absent-source guards...

When you talk about a potential refactor of the exceptions. What do you have in mind?
The #1705 isn't very specific in what to do -- other than remove NetworkX from the exception names. And we shouldn't do that until v3.0 due to potential backward compatibility issues.

**Comment by gfetterman** [comment]
Re exceptions: got it - I'll leave them be.

I've removed the absent-source guards, and so I think this PR is ready.

(Apologies for the rebase, by the way - was trying to avoid a merge commit.)

**Pull request merged**
