### PR TITLE
Increased efficiency of UnionFind.__getitem__ slightly.

### PR DESCRIPTION
**Pull request by simonsteinberg**
The last element in `path` is the `root` itself.

### CODE REVIEW

**Comment by boothby** [comment]
Are you sure this increases efficiency?  A microbenchmark tells me otherwise.
```
In [1]: def original(parents, path): 
   ...:     for node in path: 
   ...:         parents[node] = None 
   ...: def improved(parents, path): 
   ...:     for node in path[:-1]: 
   ...:         parents[node] = None 
   ...: path = list(range(10)) 
   ...: parents = {} 
   ...: print("original:") 
   ...: %timeit original(parents, path) 
   ...: print("improved:") 
   ...: %timeit improved(parents, path) 
   ...: print()                                                                                          
original:
623 ns ± 18 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
improved:
701 ns ± 31.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

It should be a tiny bit faster top call `path.pop` or avoid appending the root in the first place

**Comment by dschult** [comment]
Yes, it looks like the faster method is to construct the path without the last node.  
Something like:
```python
        path = []
        root = self.parents[object]
        while root != object:
            path.append(object)
            object = root
            root = self.parents[object]
        # Note that root is not added to the path
```

**Comment by rossbar** [comment]
Gentle ping @simonsteinberg - do you want to give the above suggestion a try? No worries if you don't have time - we can always convert this to an issue to be picked up later!

**Comment by MridulS** [comment]
Thanks for opening this @simonsteinberg, I've created a new PR with the suggested change in https://github.com/networkx/networkx/pull/5844. I'll go ahead and close this :)

**Pull request closed without merging**
