### PR TITLE
added example to closeness.py

### PR DESCRIPTION
**Pull request by Lukong123**

### CODE REVIEW

**Review by dschult — APPROVED** [review]
This looks good to me.

**Review by rossbar — COMMENTED** [review]
The example looks good, but while I was looking at the rest of the docstring I was confused by the specification of `n`; specifically this part:

> and `n` is the number of nodes that can reach `u`.

However, in the text above it is noted that the number of nodes reachable from `u` is actually `n-1`, which also agrees with the formula and the result in the example. Is there a better way to phrase this? Or maybe my confusion is a result of overthinking things...

**Comment by Lukong123** [comment]
> 
 


> The example looks good, but while I was looking at the rest of the docstring I was confused by the specification of `n`; specifically this part:
> 
> > and `n` is the number of nodes that can reach `u`.
> 
> However, in the text above it is noted that the number of nodes reachable from `u` is actually `n-1`, which also agrees with the formula and the result in the example. Is there a better way to phrase this? Or maybe my confusion is a result of overthinking things...

Sir do you prefer it should be rewritten as 
> > and `n-1` is the number fo nodes reachable from `u`
?

**Comment by rossbar** [comment]
@Lukong123 that seems like an improvement to me! :+1:

**Comment by Lukong123** [comment]
> @Lukong123 that seems like an improvement to me! +1

okay, sir.

**Pull request merged**
