### PR TITLE
CI: Pin scientific-python/upload-nightly-action to 0.2.0

### PR DESCRIPTION
**Pull request by matthewfeickert**
## PR Summary

The [`scientific-python/upload-nightly-action`](https://github.com/scientific-python/upload-nightly-action/) action has received stability updates in [`0.2.0`](https://github.com/scientific-python/upload-nightly-action/releases/tag/0.2.0) that provide a reproducible runtime environment for the action, which should mitigate issues with stability.

Using stable known releases provides additional protection from service disruption incidents (like https://github.com/scientific-python/upload-nightly-action/issues/43). Future releases will get picked up automatically by Dependabot

https://github.com/networkx/networkx/blob/364e20eca8f270b9d364fab7f73ea63338790d98/.github/dependabot.yml#L2-L8

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@MridulS @jarrodmillman this is ready for review once you add an appropriate label. Please let me know if you have any questions.

**Review by MridulS — APPROVED** [review]
Thanks!

**Review by jarrodmillman — APPROVED** [review]

**Comment by jarrodmillman** [comment]
Thanks!!

**Comment by matthewfeickert** [comment]
Thanks for the fast review and merge. :+1: Hopefully things will be pretty quiet on this from now on and just work. :)

**Pull request merged**
