### PR TITLE
Adds functions for computing number of walks.

### PR DESCRIPTION
**Pull request by jfinkels**
This commit creates a new module, `networkx.algorithms.walks`,
containing three functions related to counting the number of walks in a
graph.

This commit is also part of the pull request #1307, so this one should be reviewed and merged before that one.

### CODE REVIEW

**Comment by hagberg** [comment]
Would it be more efficient (at least for larger graphs and longer length `k` walks)  to use the adjacency matrix representation? 
Something like  `W = nx.adjacency_matrix(G)**k` with a wrapper to handle labeling and returning results.

**Comment by jfinkels** [comment]
Yes, I could do that. Basically that moves the decision about whether to use SciPy out of pull request #1307 and into this one.

**Comment by hagberg** [comment]
I'm not enthusiastic about reading through #1307 on graph powers again (I don't think we came to a conclusion there).  But for the purpose of counting walks the matrix approach seems best.  It wouldn't be too hard to implement that in Python without scipy but I'd expect the CSC matrix representation in scipy to do this calculation fairly efficiently (didn't actually look at the code).

**Comment by jfinkels** [comment]
Okay, I can add a SciPy implementation for `number_of_walks`. Should I also keep the non-SciPy implementation here?

**Comment by hagberg** [comment]
If it isn't too complicated or confusing we could keep both versions.  I didn't look carefully at the computational complexity of the algorithm you implemented but it seemed like it might be trouble for larger length walks.

**Comment by jfinkels** [comment]
I'm not very familiar with NumPy, how should I convert a matrix into a dictionary of dictionaries representation? I want something like `{u: {v: A[u][v] for v in A.cols()} for u in A.rows()}`, assuming the nodes of the graph are the integers {0, ..., n}. Is there a smart way of doing this?

**Comment by hagberg** [comment]
There are some strategies to convert scipy sparse matrices to networkx graphs in https://github.com/networkx/networkx/blob/master/networkx/convert_matrix.py
The basic approach there is to make edge triples and is a little complicated because of the different sparse matrix formats it has to to handle efficiently.  Since you can control that you only need to choose one (CSR) so that makes it simpler. 

Maybe some version of 

```python
    nrows = A.shape[0]
    data, indices, indptr = A.data, A.indices, A.indptr
    for i in range(nrows):
        for j in range(indptr[i], indptr[i+1]):
            yield i, indices[j], data[j]
```

**Comment by jfinkels** [comment]
I see I already dealt with this problem, see the `_generate_weighted_edges` function in `convert_matrix.py`. I'll use that.

**Comment by jfinkels** [comment]
Okay, check it out now. Had to update (and rename) `_generate_weighted_edges` a bit. Maybe it should live elsewhere, as it is now used in `convert_matrix.py`, in `bipartite/matrix.py`, and in `walks.py`?

**Comment by hagberg** [comment]
That is pretty complicated for a simple feature and not quite what I had in mind.  I'll add more comments when I get a chance.

**Comment by jfinkels** [comment]
Oh, well this is how I thought to do it to minimize duplication of effort in different places in the code. I'm happy to do something else, just let me know what you think!

**Comment by dschult** [comment]
Fixed by #5908

**Pull request closed without merging**
