### PR TITLE
Fix for issue #2427

### PR DESCRIPTION
**Pull request by md0000**
Bug was in deviation finding part of algorithm.  Instead of ignoring first (i - 1) vertices in path, algorithm ignored i-th vertex in path.

### CODE REVIEW

**Comment by dschult** [comment]
It looks like all those vertices are already added to ```ignored_nodes``` in previous iterations (except the last). Perhaps a solution like adding ```root[-1]``` at the end of the loop would work the same way without having to add the entire path each iteration. 

Also, can you include a test that shows the error and then ensures that it works with the fix?

**Comment by md0000** [comment]
Changed fix and added tests.

Also, there was a slight bug in _bidirectional_dijkstra and _bidirectional_shortest_path which sometimes cloaked bug in shortest_simple_paths. Fixed it and added some tests.

**Comment by dschult** [comment]
This looks good to me.  Anything else you are planning for this PR?

**Comment by md0000** [comment]
No, thats all.

**Pull request merged**
