### PR TITLE
Add igraph example

### PR DESCRIPTION
**Pull request by jarrodmillman**
igraph recently added functions to convert to/from networkx:
https://github.com/igraph/python-igraph/pull/242

### CODE REVIEW

**Comment by jarrodmillman** [comment]
We should look into adding a RAPIDS cuGraph example as well.

**Comment by MridulS** [comment]
Will CuGraph work with our CI? (It needs cuda)

**Comment by dschult** [comment]
It looks like github actions might provide cuda support but I haven't looked closely:
 - https://github.com/ptheywood/cuda-cmake-github-actions
 - https://github.com/FLAMEGPU/FLAMEGPU2_dev/issues/290

**Comment by jarrodmillman** [comment]
@iosonofabio we (i.e., the NetworkX developers) are adding gallery examples of how to use external libraries with NetworkX.  We were very excited to see your recently merged function to convert between igraph and NetworkX graphs (https://github.com/igraph/python-igraph/pull/242).  I added a very basic example of using this functionality in this PR.  The result looks like:  https://966-890377-gh.circle-artifacts.com/0/doc/build/html/auto_examples/external/plot_igraph.html

It would be great if you could take a quick look and let us know if you have any suggestions.  If you want to improve this example to show off more cool features of igraph that would be wonderful.  Since this is run as part of our CI, we would like to make sure the example doesn't take too long to run.

In particular, I would like to be able to include a plot from igraph.  But I had to comment out the plotting, since it was hanging the CI.  Do you know how to fix this so it can run in a headless mode?  Any help would be greatly appreciated!

**Comment by iosonofabio** [comment]
Hi @jarrodmillman 
Thank you for reaching out. Excited to see these two amazing projects come towards one another to the benefit of network scientists all around the globe!

Btw @szhorvat will be our speaker at the CZI EOSS conference, will you be there? (I will probably skip re time zone in Australia).

I'll take a look, I'm reworking igraph's plotting interface these very days. @vtraag or @ntamas might know too

**Comment by jarrodmillman** [comment]
Thanks for the response!  @stefanv and I will be at the CZI EOSS conference.  I speaking about NetworkX in the same session as @szhorvat, I think.  I am looking forward to talking to the igraph team at the meeting.

We use [sphinx-gallery](https://sphinx-gallery.github.io/stable/index.html) to generate our plots from the Python scripts in our [examples](https://github.com/networkx/networkx/tree/master/examples) directory.  I haven't looked into it much but we may need to write a [custom image scrapper](https://sphinx-gallery.github.io/stable/advanced.html#write-a-custom-image-scraper):

> If you wish to capture output from other python packages, first determine if the object you wish to capture has a _repr_html_ method. If so, you can use the configuration capture_repr (Controlling what output is captured) to control the display of the object, without the need to write a custom scraper. This configuration allows capture of the raw html output, in a process similar to other html-based displays such as jupyter. If the first option does not work, this section describes how to write a custom scraper.

An increasing number of scientific Python projects are using sphinx-gallery:
https://sphinx-gallery.github.io/stable/projects_list.html

It is really nice and it would be good to figure out how to get it to capture igraph plots.  I haven't tried to contribute anything to that project yet (other than maybe an issue or two), but once we figure out how to get it working we should see if we need to contribute anything upstream.

**Comment by iosonofabio** [comment]
Alright, so folks correct me if I'm wrong or you have a different opinion.

First, the current version of igraph's plot function tries a little too hard to create a temporary file and then use the "default" image viewer on the machine to open it. No surprise, it does not work great on CI where the concept of "opening" is fuzzy anyway. I am working on igraph/python-igraph#341 to include matplotlib axes as outputs. If you can wait the few days until that PR goes in, you can then pull igraph from master (or wait for the next release) and use the default matplotlib scraper in sphix-gallery (I think there is one??).

Second, as an alternative, `igraph` can save the plot to a file quite easily:

```python
ig.plot(g, layout=layout, target='/my_folder/my_file.png')
```
so you can simply point to the folder with the static assets (e.g. images) of your HTML sphinx output and then embed an `` tag into your documentation. I've not used sphinx-gallery before but this seems like a pretty easy bypass.

Unfortunately I can't help you scrap pixels out of a PNG or nodes out of an SVG (the two default representations by the current Cairo backend of igraph plotting), but options 1 or 2 look like better alternatives to me anyway.

Keep me posted!

**Comment by stefanv** [comment]
@iosonofabio I think the matplotlib plotter is going to do the trick for us.  Thanks very much!

**Comment by iosonofabio** [comment]
Fantastic! The PR is ready AFAICT, @ntamas will have a look this or next week and then I can fix the last few things if needed, but it should be good enough to be useful.

That PR also includes some convoluted but potentially useful code to enable seamless autoscaling of directed edges (arrows) upon zoom in/out in matplotlib, especially via interactive backends (e.g. Qt5, Gtk) or via `ax.set_xlim(...)` and friends. Take a peek and search Ctrl+F for `callback` if you are interested in having something along those lines in networkx too :-)

**Comment by ntamas** [comment]
Hi everyone, thanks for reaching out. I'll take a look at the Matplotlib plotting PR in igraph today and we'll merge it soon once we're happy with it.

**Comment by iosonofabio** [comment]
That PR has been merged into python-igraph master, feel free to pull from it or wait for the next official release.

**Comment by stefanv** [comment]
@iosonofabio I am trying to compile igraph from source as per https://igraph.org/python/doc/tutorial/install.html#compiling-igraph-from-source, but the details are a bit lacking :)  Do you have a set of notes somewhere on how to build master?

**Comment by iosonofabio** [comment]
On my system (linux 64 bit python 3.8) I just run:

```bash
git clone https://github.com/igraph/python-igraph.git
cd  python-igraph
python setup.py build
(press enter when prompted)
```
then you'll have the compiled library in `build/lib.<system>-<python>`, in my case `build/lib.linux-x86_64-3.8` and you can add that to your `PYTHONPATH` and import (or move it and do whatever you want with it).

If that does not work, feel free to paste the commands and errors here and I'll try my best to assist. I am in the process of overhauling documentation, but it's far from perfect still ;-)

**Comment by stefanv** [comment]
Alright!  I had to do `pacman -S igraph` on my Arch system, and then `pip install .` did the trick.

**Comment by iosonofabio** [comment]
Awesome. I have arch too (since 2006, man it's been a whlie) so debugging should be easier in the feature.

**Comment by stefanv** [comment]
@iosonofabio I now see:

```
Traceback (most recent call last):
  File "/home/stefan/src/networkx/examples/external/plot_igraph.py", line 34, in <module>
    ig.plot(g, layout=layout)
  File "/home/stefan/envs/py38/lib/python3.8/site-packages/igraph/drawing/__init__.py", line 463, in plot
    result = Plot(target, bbox, background=kwds.get("background", "white"))
  File "/home/stefan/envs/py38/lib/python3.8/site-packages/igraph/drawing/__init__.py", line 121, in __init__
    self._surface_was_created = not isinstance(target, cairo.Surface)
  File "/home/stefan/envs/py38/lib/python3.8/site-packages/igraph/drawing/utils.py", line 396, in __getattr__
    raise AttributeError("plotting not available")
AttributeError: plotting not available
```

**Comment by iosonofabio** [comment]
Yep you are not trying to use the matplotlib interface. I've written the docs but chances are they aren't on the live doc server yet:

```python
import matplotlib.pyplot as plt

# First make a pyploy.Axes (this is a good idea in general)
fig, ax = plt.subplots()
ig.plot(g, layout=layout, target=ax)
```

You can modify your plot post facto using the `ax` variable.

**Comment by stefanv** [comment]
I'm trying:

```
f, ax = plt.subplots()                                                                                                                                                   
layout = g.layout()                                                                                                                                                      
ig.plot(g, layout=layout, target=ax)  
```

And I'm getting a bit further:

```
Traceback (most recent call last):
  File "plot_igraph.py", line 35, in <module>
    ig.plot(g, layout=layout, target=ax)
  File "/home/stefan/envs/py38/lib/python3.8/site-packages/igraph/drawing/__init__.py", line 457, in plot
    result.draw(obj, *args, **kwds)
  File "/home/stefan/envs/py38/lib/python3.8/site-packages/igraph/drawing/graph.py", line 1147, in draw
    start = shrink_vertex(ax, (x2, y2), (x1, y1), vsizes[src])
TypeError: 'NoneType' object is not subscriptable
```

Maybe I need to look into layout a bit deeper.

**Comment by iosonofabio** [comment]
Haha that's a bug. I'll fix it ASAP, in the meanwhile you can try:

```python
ig.plot(g, layout=layout, target=ax, vertex_size=[5] * g.vcount())
```
Sorry about that.

**Comment by stefanv** [comment]
That doesn't quite do it, but I'll wait for the fix and then try again.  Thanks!

```
Traceback (most recent call last):
  File "plot_igraph.py", line 35, in <module>
    ig.plot(g, layout=layout, target=ax, vertex_size=[5] * g.vcount())
  File "/home/stefan/envs/py38/lib/python3.8/site-packages/igraph/drawing/__init__.py", line 457, in plot
    result.draw(obj, *args, **kwds)
  File "/home/stefan/envs/py38/lib/python3.8/site-packages/igraph/drawing/graph.py", line 993, in draw
    vsizes **= 2
TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'
```

**Comment by iosonofabio** [comment]
Of course, I pushed the PR through a little hastily so it's suffering from a few youth issues. I'll push a fix in a few minutes.

**Comment by stefanv** [comment]
No worries at all, we are very appreciative of the work you are putting in. :pray:

**Comment by iosonofabio** [comment]
Alright, I pushed a fix for this and closely related issues onto igraph/master (commit 90e5625) right now, if you could git pull (or reclone) and retry it should work better (hopefully not worse!)

**Comment by stefanv** [comment]
Yes, it works!

**Comment by stefanv** [comment]
Works with 90e56251af00b30540fd06951a7423de249b8fd0 of python-igraph.

**Review by rossbar — APPROVED** [review]
I think this is a really valuable example for illustrating NX/igraph interop. I just wanted to add my two cents that I don't think the igraph plotting should be a blocker - I'd be happy to see this go in and address the igraph plotting in a follow-up so that there's no time pressure on the igraph devs (though huge thanks to @iosonofabio , @ntamas , et. al. for pushing so hard on this!)

**Comment by jarrodmillman** [comment]
@dschult I would like to merge this now.  It isn't necessary, but it would be nice to have this in master before the EOSS meeting starts tomorrow.  Once python-igraph 0.9 is released, we should improve this example to show off their new matplotlib-based plotting functionality.

**Review by dschult — APPROVED** [review]

**Pull request merged**
