### PR TITLE
distance_measures

### PR DESCRIPTION
**Pull request by Lukong123**

### CODE REVIEW

**Comment by Lukong123** [comment]
Please I had a problem running `nx.extrema_bounding(G, compute="eccentricities")` 

It returns `[TypeError: cannot convert dictionary update sequence element #0 to a sequence]()` 
It looks like I am missing something but I cannot figure it out

**Comment by Lukong123** [comment]
Hello sir, @dschult  @rossbar  @MridulS please, sirs, I need your review on this notebook:
https://github.com/Lukong123/outreachy/blob/main/2022-round-1/Lukong123/distance_measures.ipynb
And also on the examples on distance measures so that I can adjust it where need be.
Thanks.

**Comment by MridulS** [comment]
> Please I had a problem running nx.extrema_bounding(G, compute="eccentricities")

> It returns [TypeError: cannot convert dictionary update sequence element #0 to a sequence]()
> It looks like I am missing something but I cannot figure it out

Can you provide more information about this? What's the graph `G` you are using?
Also `extrema_bounding` will be removed in NetworkX 3.0 so don't worry too much about adding an example for it :)

**Comment by rossbar** [comment]
> Also extrema_bounding will be removed in NetworkX 3.0 so don't worry too much about adding an example for it :)

If you're running on a development version of networkx (i.e. installing from `main`) then you should see a `DeprecationWarning` when you try to call `extrema_bounding` directly. "Deprecated" means that the function is planned to be removed in the future, and the warning is in place to warn users against using it so that their code continues working with future versions. Indeed we don't want to add anything to this function since it slated for removal.

**Comment by Lukong123** [comment]
Okay, sir. I will remove the examples on extrema bounding.

**Review by rossbar — COMMENTED** [review]
Hm it looks like this PR got conflated with others that add examples to the chains and covering modules. It'd be good to focus on a single set of docstring examples per PR!

**Comment by Lukong123** [comment]
> Oh okay sir, I don't know for sure but I am guessing is as a result of me having to clone back my forked repository which made me lose the branches I worked on previously.  Please, sir, what are my options to undo any mix made on this pull request, will I have to remove the other examples on covering made on this pull request?.

**Comment by MridulS** [comment]
It's always recommended to create Pull Requests in small modular batches, it's harder to review a lot of changes in one single Pull Request. It also helps the maintainers to merge the pull request quicker.

This pull request also contains the changes from https://github.com/networkx/networkx/pull/5478/ (the covering.py file). You can look at the changes in a PR by going to the `Files Changed` tab just above, next to `commits` and `checks`.

I think this happened because of branches being mixed together locally on your computer. (BTW this is just fine! no need to worry, `git` is tricky to work with and this still happens with me :) )

Some personal recommendations while working with git.
- Make sure that you never work on the local `main` branch, it should always be synced up with the `main` branch on github.com/networkx/networkx. You can sync up using `git pull upstream main` while you in the `main` branch.
- If you want to make any change (even one line change) create a new branch with `git checkout -b name_of_the_new_branch` and make sure this command is run from the `main` branch.
- For example: if you are currently working in `branch_a` and now you want to work on a new thing, make sure you go back to `main` (`git checkout main`), sync it up (`git pull upstream main`) and then create the new branch (`git checkout -b branch_b`.  You can directly do this with `git checkout -b branch_b main` but you will miss the sync up.
- A mistake that I used to make was to directly create a new branch (`branch_b`) while I'm working on a branch (`branch_a`), so what ends up happening is that the new branch (`branch_b`) contains all the changes from the old branch too! (`branch_a`)

This PR is titled `distance_measures` so it should only contain the changes that are made to the `distance_measures` file, not other files. It is also recommended to add a more descriptive title for a PR, just `distance_measures` doesn't give us enough information until we look at the changes. Something like "Added new examples in the documentation of distance measures"

**Comment by Lukong123** [comment]
> It's always recommended to create Pull Requests in small modular batches, it's harder to review a lot of changes in one single Pull Request. It also helps the maintainers to merge the pull request quicker.
> 
> This pull request also contains the changes from #5478 (the covering.py file). You can look at the changes in a PR by going to the `Files Changed` tab just above, next to `commits` and `checks`.
> 
> I think this happened because of branches being mixed together locally on your computer. (BTW this is just fine! no need to worry, `git` is tricky to work with and this still happens with me :) )
> 
> Some personal recommendations while working with git.
> 
> * Make sure that you never work on the local `main` branch, it should always be synced up with the `main` branch on github.com/networkx/networkx. You can sync up using `git pull upstream main` while you in the `main` branch.
> * If you want to make any change (even one line change) create a new branch with `git checkout -b name_of_the_new_branch` and make sure this command is run from the `main` branch.
> * For example: if you are currently working in `branch_a` and now you want to work on a new thing, make sure you go back to `main` (`git checkout main`), sync it up (`git pull upstream main`) and then create the new branch (`git checkout -b branch_b`.  You can directly do this with `git checkout -b branch_b main` but you will miss the sync up.
> * A mistake that I used to make was to directly create a new branch (`branch_b`) while I'm working on a branch (`branch_a`), so what ends up happening is that the new branch (`branch_b`) contains all the changes from the old branch too! (`branch_a`)
> 
> This PR is titled `distance_measures` so it should only contain the changes that are made to the `distance_measures` file, not other files. It is also recommended to add a more descriptive title for a PR, just `distance_measures` doesn't give us enough information until we look at the changes. Something like "Added new examples in the documentation of distance measures"

Thanks a lot sir, I will re work on it.

**Comment by MridulS** [comment]
The changes were merged in https://github.com/networkx/networkx/pull/5608, closing this one.

**Pull request closed without merging**
