### PR TITLE
Add test for matrix option in nonisomorphic trees generator

### PR DESCRIPTION
**Pull request by MridulS**

### CODE REVIEW

**Comment by MridulS** [comment]
Travis is failing for some reason https://travis-ci.org/networkx/networkx/jobs/69421856#L3453

**Comment by chebee7i** [comment]
Do you mean the `test_richclub.test_richclub_normalized` failure?  Probably a seed value needs to be set.

**Comment by chebee7i** [comment]
I'll reset the test and hope we succeed this time, but a ticket should be opened.

**Comment by chebee7i** [comment]
That job was restarted. So the link you sent is no longer showing the error.

**Comment by MridulS** [comment]
@chebee7i Sure :) We make sure next time. I also found a test failing in approximation/kcomponents https://github.com/networkx/networkx/issues/1637

**Comment by chebee7i** [comment]
I think we should close this or update the description though. As it is now, only you really know what this ticket is for.

**Comment by chebee7i** [comment]
Opps...for some reason, I thought you had opened a new ticket. Ignore what I just wrote above.

**Comment by jtorrents** [comment]
Sorry, maybe it was me who restarted the tests. I restarted the one related to k_components (which now it passes). I'll look at that.

**Comment by MridulS** [comment]
BTW Do the changes in this PR look okay?

**Pull request merged**
