### PR TITLE
Fix module docstring format for ismags reference article.

### LINKED ISSUE #6547: Layout of website page for ISMAGS needs fixing
The website documentation page for [ISMAGS algorithm](https://networkx.org/documentation/stable/reference/algorithms/isomorphism.ismags.html) is not rendering properly. The layout of components is messed up.

image

image

### PR DESCRIPTION
**Pull request by rossbar**
Closes #6547 

Improperly formatted Notes/References sections was causing a sphinx parsing error which led to a very poorly formatted html page.

Fixing the numpydoc formatting for the module docstring + minor munging of the heading levels should fix the issue.

### CODE REVIEW

**Comment by dschult** [comment]
This looks fine for content -- but the ISMAGS Object section has no space before it (the References section runs right up to it, while the other sections get some breathing room).  I don't mind merging this as is, but is there an easy way to make the space between sections?  (maybe just a blank line at end of doc_string? but maybe different autodoc magic in the .rst file?)

**Comment by rossbar** [comment]
>  the ISMAGS Object section has no space before it (the References section runs right up to it, while the other sections get some breathing room).

Good point - I'm not sure why this happens. I'll try adding some newlines (in isomorphism.ismags.rst and/or the ismags module docstring) to see if I can't get an extra line break in there. There's still likely something funky with the numpydoc module docstring parsing so it may not be possible, but let's check!

**Comment by rossbar** [comment]
Okay, I've tried with adding extra newlines in both the reference doc as well as the module docstring and unfortunately that doesn't make any difference. I suspect this is something that will have to be fixed upstream.

**Review by dschult — APPROVED** [review]
Thanks for trying out the newlines -- I didn't know if there was something about sphinx I didn't know about.

Let's merge these and we can fix minor stuff later.

**Pull request merged**
