### PR TITLE
Adds a graph "walk" power operation.

### PR DESCRIPTION
**Pull request by jfinkels**
This adds the `networkx.algorithms.operators.product.pow` function, which
computes a power of a given a graph. If SciPy is available, this
function computes the power of the adjacency matrix of the graph. If
SciPy is not available, it falls back to a naive (and slow)
exponentiation-by-squaring implementation using only the graph
primitives provided by NetworkX.

### CODE REVIEW

**Comment by hagberg** [comment]
I like the idea of including this but we need to come to a conclusion on the function design first.

**Comment by jfinkels** [comment]
I'll work on implementing the suggestions by @chebee7i now and I'll let you know when I've updated the pull request.

**Comment by jfinkels** [comment]
Okay, let me explain what's going on here.

This pull request now adds a function of the form

    networkx.pow(graph, exponent, parallel_edges=True, create_using=networkx.MultiGraph())

If `parallel_edges` controls whether or not parallel edges are created in the output graph. It only matters when `create_using` is a multigraph.

The pull request also adds the ability to do

    G ** 2

There's one catch: the changes made here rely on the pull request #1310 (I originally came across that issue while working on this feature). That's why you see the changes to `from_numpy_matrix`, etc. in this pull request. So these changes should be added only after those are.

**Comment by jfinkels** [comment]
And it appears there's an error, so I'll keep working on this. Sorry for all the messages.

**Comment by jfinkels** [comment]
It's too complicated for me to deal with implementing a graph power operation without using SciPy, so I've just updated the pull request so that an attempt to call the `networkx.pow()` function raises an error if SciPy is not importable. I'll leave the frustrating work of coding a pure NetworkX fallback to someone else (although it would be unreasonably slow, and therefore basically pointless).

Also, I could not figure out how to mark doctests to be skipped if SciPy is not installed, so those will show up as build errors in Travis.

**Comment by hagberg** [comment]
I was thinking of a Python implementation something like this. (But with the correct handling of self-loops and parallel edges).  Untested...

```python
import networkx as nx
from itertools import izip_longest
def pow(G,k):
    H = nx.Graph()
    for n in G:
        p = nx.single_source_shortest_path_length(G,n,cutoff=k)
        H.add_edges_from(izip_longest([n],p,fillvalue=n))
    return H

if __name__=='__main__':
#    G = nx.cycle_graph(5)
    G = nx.grid_2d_graph(5,3)
    H = pow(G,2)
    print H.edges()
```

**Comment by hagberg** [comment]
I don't agree that this is too complicated or slow to do in Python without Scipy.  Anyone want to finish this PR?

**Comment by MridulS** [comment]
Looks interesting @hagberg will be happy to take this up. :)

**Comment by MridulS** [comment]
@hagberg Should we return self loops in the graph power operation.

**Comment by jfinkels** [comment]
Yes, if `A` is the adjacency matrix of even a simple graph, then `A ** 2` may have self loops. Consider the path graph on two vertices, for example.

The way I attempted to do this was by essentially writing two functions.

1. A `compose` function (different from the `compose` function in `networkx.algorithms.operators`) that computes the composition of two graphs when considered as a binary relation. One step in the composition corresponds to a step in the first graph followed by a step in the second graph (so the two graphs must have the same vertex set). Composing a graph with itself is the same as squaring the graph.
2. Using that `compose` function, write an [exponentiation by squaring][1] function to compute the power of a graph (replacing the "squaring" by graph composition as described in part 1 above).

This turned out to be sort of complicated with all the different cases of multigraphs and directed graphs, so I left it out of the pull request.

[1]: https://en.wikipedia.org/wiki/Exponentiation_by_squaring

**Comment by jfinkels** [comment]
One more thing: now that `from_scipy_sparse_matrix` has a `parallel_edges` option, this code can be simplified a little bit at, for example, [line 143][1]

[1]: https://github.com/networkx/networkx/pull/1307/files#diff-414eaa09098b00206eecbff1d545bbf4R143

**Comment by dschult** [comment]
I'm not sure that all the machinery with compose functions is needed. I think @hagberg's code above is almost enough. It uses shortest_paths while the power function needs all_paths. But I think pulling the breadth first search part of shortest_path into this function and changing it to track all paths would give an efficient algorithm--more network oriented than algebra oriented but that's intentional.

**Comment by jfinkels** [comment]
Added a work-in-progress for a pure NetworkX implementation of graph powering. I still haven't quite gotten down which vertices to add to the final graph once all the numbers of paths are counted, so if anyone sees the fix, let me know.

I introduced two functions that may be better off living in a different module: `single_source_number_of_walks` and `all_pairs_number_of_walks`.

**Comment by jfinkels** [comment]
It seems that I have actually resolved the issue I was having, let's see if the build passes.

**Comment by MridulS** [comment]
While calculating the power graph, the kth power of G has vertices adjacent if the **distance** between them is less than equal to k. And **distance** is the shortest path between two vertices. While calculating number of walks this implementation has considered a walk from 0->1->0 having a distance of 2, but the shortest distance from the vertex 0 to vertex 0 is zero. 
For example
``` python
G=nx.path_graph(4)
pow(G,2).edges() should return
[(0,0),(1,1),(2,2),(3,3),(0,1),(1,2),(2,3),(0,2),(1,3)]

pow(G,3).edges() should return
[(0,0),(1,1),(2,2),(3,3),(0,1),(1,2),(2,3),(0,2),(1,3),(0,3)]
```

http://en.wikipedia.org/wiki/Graph_power
http://en.wikipedia.org/wiki/Distance_(graph_theory)

**Comment by MridulS** [comment]
The code suggested by @hagberg works perfectly fine for Graphs, I am working on modifying the single_source_shortest_path for taking into account MultiGraphs.

**Comment by dschult** [comment]
It seems that the definition of graph power from Wikipedia and MathWorld is
unclear whether self loops should be included. Both sites use the same
definition but it does not say whether the result is a simple graph or not.
The examples (figures) on both sites suggest that self loops are NOT
included in the power graph. A quick search did not yield any power graphs
with self loops.

Does anyone have a good source for the definition? If not, we can use the
Wikipedia version and my interpretation including examples is that power
graphs should not include self loops.

**Comment by jfinkels** [comment]
In https://github.com/networkx/networkx/pull/1307#issuecomment-67363873, the three sources I listed for graph powering allow (and in fact *require*) that a graph power refers to a graph in which 1. number of parallel edges corresponds to the number of walks of length exactly *k*, not at most *k*, and 2. self-loops are allowed. (The definitions are a little more formal than this, but this is the interpretation.) If you want to implement, for example, the zig-zag product so that you can construct explicit constant-degree expanders, you need this form of the power operation.

I believe the code I have can be modified to work with the "walks of length at most *k*" definition by changing `if distance == walk_length:` to `if distance <= walk_length:` and requeueing the nodes neighbors unless `distance == walk_length`.

**Comment by MridulS** [comment]
@jfinkels Your implementation considers a walk from node 0->1->0 as walk of length 2, but the distance between the same nodes is always zero.
d(u,v) = 0 if u==v

**Comment by jfinkels** [comment]
We're not trying to compute the shortest path distance metric, to which you refer, we're trying to compute the graph power. In the definitions to which I linked above, a walk of length two, regardless of the initial and terminal vertices, yields an edge in the graph's square.

**Comment by MridulS** [comment]
@jfinkels I found this on wikipedia:
If A is an adjacency matrix for the graph, **modified to have nonzero entries on its main diagonal**, then the nonzero entries of Ak give the adjacency matrix of the kth power of the graph, from which it follows that constructing kth powers may be performed in an amount of time that is within a logarithmic factor of the time for matrix multiplication.

Can you point me towards the definition you are using?

**Comment by dschult** [comment]
Sounds like the definition you are using can be stated as: the graph with
adj matrix equal to the power of the adjacency matrix of the graph.  I see
why you think of using matrix operations to compute it.

Which graph power operation should we implement? I like @jfinkels argument
about expander graphs. Are there any use-cases for the wikipedia definition?

**Comment by jfinkels** [comment]
@dschult Yep, maybe I didn't make that clear enough initially: the adjacency matrix of `G ** k` is `A ** k`, where `A` is the adjacency matrix of `G`.

If you just want to know if there *exists* a walk from a source node to a target node within a certain number of steps, you would use Wikipedia's "logical graph power". If you want to know how *many* walks exist, you can use my more general definition. (Mine is more general because if you know the number of walks, then you know if there are greater than zero walks; this is basically what I'm doing at https://github.com/networkx/networkx/pull/1307/files#diff-414eaa09098b00206eecbff1d545bbf4R212; something similar happens in `from_scipy_sparse_matrix`, due to changes I suggested in other pull requests.)

**Comment by jfinkels** [comment]
This is one way of determining whether a graph is connected: compute the *n*th power and check if there are any zeros in the matrix.

**Comment by dschult** [comment]
I think it is more than just logical versus counting number of walks.

One definition adds a 1 (or any nonzero) to the main diagonal before
raising to a power while the other does not. By leaving the diagonal zero
the "walk" must keep moving each timestep. By adding the 1 it allows walks
with pauses at any node.

Consider the graph with two nodes connected by one edge. G**2 has two
self-loops. But does it have the edge connecting the two nodes?  In one
definition it does and in the other it doesn't.

**Comment by MridulS** [comment]
@dschult In all definitions I read, it explicitly states that it is the distance not the number of walks :/. 

I agree with @jfinkels for using matrix operations but it is on the modified adjacency matrix.

**Comment by chebee7i** [comment]
This reminds me a bit of a previous discussion with the diagonals of a matrix, and how the convention differed with undirected and directed graphs. Is that discussion relevant here? I'll see if I can find it.

**Comment by jfinkels** [comment]
@dschult What you're describing is essentially the "lazy random walk" (see, for example, [Jon Kelner's lecture notes on lazy random walks][1] for a more precise description), where you take a graph without self-loops, add a self-loop to each vertex, and then start counting walks. That's a different thing, and the responsibility of adding self loops before computing the power should be on the user.

@MridulS The shortest path distance between two nodes is the length of the shortest path joining them. The set of walks of length at most k joining two nodes includes as a subset the set of paths of length at most k joining the nodes.

[1]: http://ocw.mit.edu/courses/mathematics/18-409-topics-in-theoretical-computer-science-an-algorithmists-toolkit-fall-2009/lecture-notes/MIT18_409F09_scribe4.pdf

**Comment by dschult** [comment]
The definitions you cite are for regular graphs, and it's not transparent that the printed definitions there are what you are computing (though they may be). Perhaps we can find a different name for what you are computing because it doesn't seem to be what many people call the power graph.

**Comment by jfinkels** [comment]
Fair enough, although I don't know what to call it, then :). If you want to keep the algorithm I've implemented here, the modifications in my comment https://github.com/networkx/networkx/pull/1307#issuecomment-77589956 above should suffice I think.

**Comment by MridulS** [comment]
Should we include a power function for MultiGraphs, I couldn't find any literature on power of MultiGraphs. 
@dschult For excluding self loops we can modify @hagberg code to:
``` python
import networkx as nx
from itertools import izip_longest
def pow(G,k):
    H = nx.Graph()
    for n in G:
        p = nx.single_source_shortest_path_length(G,n,cutoff=k)
        for key,value in p:       #remove self loops
             if value == 0:
                 del p[key]
        H.add_edges_from(izip_longest([n],p,fillvalue=n))
    return H

if __name__=='__main__':
#    G = nx.cycle_graph(5)
    G = nx.grid_2d_graph(5,3)
    H = pow(G,2)
    print H.edges()
```

Should I send in a patch with tests and documentation?

**Comment by jfinkels** [comment]
One last comment: the strategy I suggested in https://github.com/networkx/networkx/pull/1307#issuecomment-77387717 with the exponentiation-by-squaring algorithm, though more complicated, is more efficient in time complexity than computing.

**Comment by jfinkels** [comment]
Here's a definition of graph power from Exercise 3.1.6 of [_Graph Theory_][1] by Bondy and Murty:

> The *k*th power of a simple graph *G* = (*V*, *E*) is the graph *G<sup>k</sup>* whose vertex set is *V*, two distinct vertices being adjacent in *G<sup>k</sup>* if and only if their [shortest path] distance in *G* is at most *k*.

So there's a concrete, written definition from a contemporary graph theory textbook. If you want to rename my "power" function, maybe I would call it "walk power". I have updated this pull request with that name.

[1]: http://www.amazon.com/Graph-Theory-Graduate-Texts-Mathematics/dp/1849966907

**Comment by dschult** [comment]
That definition matches the wikipedia and mathworld definitions (where the
examples show the result as a simple graph).

1) does it allow self-loops? (it doesn't say the result is a simple graph,
though maybe it is implied and the examples may be needed to know). G is a
simple graph, but the definition doesn't say whether G^k is.
2) The distance is "at most" k which implies that we make the diagonal
entries nonzero before raising the adj matrix to a power.

If I understand correctly, that is not the definition you have implemented.
But maybe Im missing something.

**Comment by MridulS** [comment]
@dschult I could't find anything on power of MultiGraphs, so I think that self loops should be ignored along with MultiGraphs (power should only be defined for graphs) . And @jfinkels has renamed the function to `walk_power` instead of ```pow```.

**Comment by MridulS** [comment]
@dschult @jfinkels #1399

**Comment by chebee7i** [comment]
With #1399 in, are we moving forward with also having a `walk_power` function?

**Comment by jfinkels** [comment]
I'd like to rework this a little bit before any more review goes into it.

**Comment by jfinkels** [comment]
I just uploaded an updated version of this pull request. It adds a new module `networkx.algorithms.walks` to store the functions that compute the number of walks between pairs of nodes, and implements the function I was originally imagining as `walk_power` in the module `networkx.algorithms.operators.product`.

**Comment by jfinkels** [comment]
I have separated the "counting walks" part of this algorithm into pull request #2066, so that one should be reviewed and merged before this one.

**Comment by dschult** [comment]
This Issue is largely closed by #5908.  That `number_of_walks` function provides all-pairs number of walks of given input `walk_length`. This provides the functions from this PR: `single_source_number_of_walks`, `all_pairs_number_of_walks` and `number_of_walks`, and it is faster since it uses scipy instead of pure python.

Other items here:  `walk_power` which creates a multigraph with the number of multiedges indicating how many walks go from those two nodes. But I think it is better to represent the number of walks with a number than with multiedges. A user could construct the walk_power graph using nested for loops something like:
```python
walks = nx.number_of_walks(G, walk_length=5)
MG = nx.MultiGraph()
for n, nbrs in walks.items():
    for nbr, nw in nbrs.items():
        for _ in range(nw):
            MG.add_edge(n, nbr)
```
It's not a one-liner, but it is fairly straightforward and I think it would be rarely wanted.

So, I'm going to close this issue unless someone comments soon.  :) (it can be reopened of course)

**Comment by dschult** [comment]
Closing this "walk" issue. As previously described: it has been largely implemented and the other functionality is declared not worth implementing. 
We can still post here and reopen if needed.

**Pull request closed without merging**
