### PR TITLE
Enhancements change default join trees 6947

### PR DESCRIPTION
**Pull request by yadomkar**
This PR addresses GitHub Issue #6947, improving the default behavior of `join_trees`. Now, node attributes won't store old labels unless specified with `label_attribute`. It also introduces a `first_label` argument for specifying the root node's label. Tests for no `label_attribute` and custom `first_label` are included, enhancing flexibility while minimizing attribute creation. Additionally, it fixes a regression where the code depended on old labels.

### CODE REVIEW

**Comment by yadomkar** [comment]
Not sure how to add a label to the PR.

**Review by dschult — COMMENTED** [review]
Ack -- it looks like our suggestion of not keeping the old label for the nodes makes it difficult to keep track of the roots. We need to know how the roots have been relabeled in order to connect them to the new uber-root (now called `first_label`).  We used to loop through all the nodes and look for a node attribute `label_attribute` that equalled the original name of the `root` for that tree.  But when `label_attribute` is None, those old node labels will not be stored.

Comments:
- The default `label_attribute` value should be `None` now instead of `custom_label`.
- The new_roots can be found before the relabeling -- but we would have to accumulate twice if we don't store the first_labels as a list... So:
    - make the first_labels a list of the accumulate expression.
    - go through the trees, roots, and first_labels and find the new label of the original roots. Use code something like: 
```python
        new_roots = []
        for r, T, first_node in zip(roots, trees, first_labels):
            for i, n in enumerate(tree, start=first_node):
                if n == r:
                    new_roots.append(i)
                    break
```
Notice that this must be done with the `trees` list **before** relabeling -- or just rename `trees` as `new_trees` which is probably more clear anyway. 

I also notice that you found where we use `nx.join` and fixed that call. I think we should rename that call `join_trees` because `join` has been renamed to `join_trees`.

Note on the last test:  I think it is not testing the case when `label_attribute` is `None`. The string `custom_label` is currently set as the default label_attribute. So, I'm not sure what it is testing.  But when you change that default to None it will change. I request that you test that the data is empty for all the nodes when `actual_without_labels` (that is, `len(data)==0`) and for the case with labels: `len(data) ==1`.

**Comment by yadomkar** [comment]
@dschult Thank you for your feedback and insights. Here are my changes based on your comments:

1. **Default Label Attribute:** This was already set to `None`, it was only `custom_label` in one of the tests. I have changed the names of the test functions to make it more clear.
2.  **Identifying new roots:** I have made the adjustments to find the new roots before relabelling. Thank you for the clarification.
3. **Function Renaming:** I have renamed the function call I found. It now calls `join_trees` instead of `join`.
4. **Test Cases for `label_attribute`:** There are now 2 separate functions `_check_custom_label_attribute` and `_check_no_label_attribute` which test `label_attribute` for each case.

**Review by rossbar — COMMENTED** [review]
I went ahead and merged #6956 into this to make the non-graph parameters for `join_trees` keyword-only.

I'm also +1 on using this opportunity to rename the `label_attribute` kwarg to `label`, but I leave that decision to others!

Thanks for this @yadomkar !

**Review by dschult — APPROVED** [review]
Looks like `label_attribute` is used fairly widely in NetworkX:
grid_graph, join_trees, convert_node_labels_to_integers, 
The keyword `label` doesn't appear as much:
parse_gml.  
There are many examples where we use an edge attribute that we name `label`. But not many keywords.  So, let's leave that as it is.  I think this is ready for merging then.  

Thanks @yadomkar !  and Thanks @rossbar for merging the other PR into this one!

**Pull request merged**
