### PR TITLE
make identified_nodes an alias for contracted_nodes

### PR DESCRIPTION
**Pull request by SanketDG**
#1541

### CODE REVIEW

**Comment by OrkoHunter** [comment]
+1 for this change. @jfinkels However, this seems a little strange. Why don't we just deprecate `contracted_nodes`?

**Comment by jfinkels** [comment]
Well, I've seen both names used. Apparently so has Wikipedia, "[Vertex identification][1] (sometimes called vertex contraction) [...]". I don't have a strong opinion about this, so I proposed allowing both names.

[1]: https://en.wikipedia.org/wiki/Edge_contraction#Vertex_identification

**Comment by SanketDG** [comment]
Node/vertex contraction is a pretty common name I guess.

**Comment by OrkoHunter** [comment]
Got it.

**Pull request merged**
