### PR TITLE
Bugfix (or simplification) of the size method in the Graph class

### PR DESCRIPTION
**Pull request by emilienkofman**
Although I am still not a Git master, I think this one is correct.

### CODE REVIEW

**Comment by dschult** [comment]
Actually the single calculation for both ints and floats breaks the tests here...
Looks like the tests were imposing that we return ```int``` when ```weight is None``` and ```float``` when ```weight is not None```.

The ```from future``` stuff isn't needed because integer sums when ```weight is None``` always divide an even number by 2.  So we can remove that.

But.... now we need to decide whether to change the API as defined by the tests.
Should ```G.size()``` return an int?
Should ```G.size(weight='weight')``` always return a float?

Thoughts?

**Comment by emilienkofman** [comment]
Yes, that's exactly what I meant in the previous pull request (https://github.com/networkx/networkx/pull/1782). In my opinion, the `from future` is not necessary, and `G.size()` should return an int as it's a "number of edges" (and a "number of something" is an int). Most importantly as I explained, it should not cast to float in the other case, it should keep the type of the elements of the sum, they will sum correctly if they have an __add__ method and return the correct type.

**Comment by jfinkels** [comment]
Imagine a graph with a single edge with a weight attribute equal to `2` (not `2.0`). Then the difference appears between Python 2 and 3:

    $ python3 -c "print(4 / 2)"
    2.0
    $ python2 -c "print(4 / 2)"
    2
    $ python2 -c "from __future__ import division; print(4 / 2)"
    2.0

The difference is that in Python2, division by two integers results in an integer whereas in Python 3, real division results in a float.

As for API design, I'm not sure.

**Comment by emilienkofman** [comment]
Still, with the explicit call to  `float()` one is not able to get the size of a graph where the weights of the edges are summable but not convertible to float.

Example with complex numbers:
```python
>>> import networkx as nx
>>> G = nx.Graph()
>>> G.add_node('A')
>>> G.add_node('B')
>>> G.add_edge('A', 'B', weight=1j)
>>> G.size()
1
>>> G.size(weight='weight')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "networkx/classes/graph.py", line 1591, in size
    return float(s)
TypeError: can't convert complex to float
```

**Comment by dschult** [comment]
The original implementation (way back) allowed size to sum anything.
Let me look through the logs to see why it was changed to be int or float.

The int/float difference for unweighted size is a separate issue. Clearly the number of edges is an integer. But python3 will return a float because we use division (not tested). The code is smoother if we let python choose to return a float. 

Question: do we care if the size returns a float even though the value returned will be an integer?

**Comment by emilienkofman** [comment]
I'm not sure if we care. Somoene who uses the function without looking at the documentation would expect an int :) but if it makes the code too complex it's probably not worth. However I feel it's just about using integer division in the right place:
```python
>>> from __future__ import division
>>> 4/2
2.0
>>> 4//2
2
```

**Comment by dschult** [comment]
It is more than using integer division in the correct place.
For weighted edges, ```sum(weights) / 2``` in python 2 can create ints OR floats whereas in python 3 we always get floats. The python 2 case that gives ints occurs if all weights are ints.

Allowing sums of arbitrary weight objects requires that the result of their sum allow division by 2.  So weights that are lists or strings won't work. Your complex value case would allow division, but does it provide anything sensible to sum complex edge weights?

I'm fine merging this with:
1) ```from __future__ import division``` back in 
2) splitting based on whether ```weight is None``` and using // 2 for the unweighted case.

Then we get int and float in the same cases we had before and we allow custom weights that can sum with the result of the sum divisible by 2 (which I think was your point).  Is this what you were thinking @jfinkels?

**Comment by jfinkels** [comment]
Yes, I think this makes sense:

    from __future__ import division
    s = sum(d for v, d in self.degree(weight=weight))
    # If `weight` is None, the sum of the degrees is guaranteed to be
    # even, so we can perform integer division and hence return an
    # integer. Otherwise, the sum of the weighted degrees is not
    # guaranteed to be an integer, so we perform "real" division.
    returns s // 2 if weight is None else s / 2

In any case, it is important to document the type of the output in the docstring for this function: "If a weight keyword argument is provided, the output will be a float, regardless of whether all the weights are integers."

**Comment by hagberg** [comment]
Fixed in #1782

**Comment by emilienkofman** [comment]
Hi, it's not been merged neither fixed in #1782 (this pull request was supposed to be merged).

**Pull request merged**
