### PR TITLE
Add pydot_ng as a supported pydot lib

### PR DESCRIPTION
**Pull request by prmtl**
pydot_ng is a another pydot fork

URL: https://pypi.python.org/pypi/pydot-ng

### CODE REVIEW

**Comment by chebee7i** [comment]
Simple enough. Does this fork differ substantially from pydotplus? What's the motivation for YAPP (yet another pydot package)? 

While we can add this, note that we are trying to import in order, so people might complain that their pydot fork has lower precedence than other pydot forks. This whole pydot situation is a mess...

**Comment by prmtl** [comment]
Well, pydot_ng is a pydot working with Python 2.6 to 3.4 and actually has working CI/tests when pydotplus do not work with Python 2.6 and CI actually do not work.

If you have any concerns about adding next library (and you clearly had some valid points) you can just ignore my Pull Request, right now it's easy enough to just monkey-patch PYDOT_LIBRARIES and add the one that you need in your code (probably I should consider adding info how to do it in docs instead of this change?).

I hope that in the end we will get the whole pydot problem fixed.

**Comment by chebee7i** [comment]
Ah ok, that's good to hear. Maybe pydot_ng will be the winner! I don't have an issue merging it, especially since it's just another item to the list. Did anyone else want to chime in?

**Comment by ysitu** [comment]
We should use `importlib.import_module` instead of `__import__`.

**Comment by chebee7i** [comment]
@prmtl  can you make that change too?

I'm not sure why we went with `__import__` at all. It might have been because I had forgotten that we weren't supporting 2.6 anymore.

**Pull request merged**
