### PR TITLE
Generalized degree

### PR DESCRIPTION
**Pull request by jklaise**
Added the functionality to compute the [generalized degree](https://arxiv.org/abs/1101.2435) which returns the number of edges a node has that participate in a given number of triangles.

P.S. Is there a way to test the documentation generated from docstrings before merging to see if the maths markdown has rendered correctly?

### CODE REVIEW

**Comment by mcognetta** [comment]
I had the same question. https://groups.google.com/forum/m/?source=mog&gl=us#!topic/networkx-discuss/hI_yLRDBc04

**Comment by jklaise** [comment]
@mcognetta I managed to build the docs, but the latex hasn't been parsed to images, so the html pages just have raw latex. The build process returned some warning, is there any place I can find a log?

**Comment by mcognetta** [comment]
> @mcognetta I managed to build the docs, but the latex hasn't been parsed to images, so the html pages just have raw latex. The build process returned some warning, is there any place I can find a log?

The log should be somewhere in the build or doc directory but I don't know exactly where. Did the error not say where the log could be f?

I'm not sure if sphinx supports full LaTeX but you can do some math markup with the :math: tag. You can see my changes in #2218 where I use it.

**Comment by jklaise** [comment]
@mcognetta It seem that building the docs with "make html" renders display maths as Mathjax (viewable in my browser) but doesn't render any inline math in `` quotes at all, yet the official networkx docs have both inline and and display maths as .png images. Am I missing some additional options?

**Pull request merged**
