### PR TITLE
readwrite.parse_pajek(): allow multi-word network name

### PR DESCRIPTION
**Pull request by kernc**

### CODE REVIEW

**Comment by kernc** [comment]
Got it wrong the first time around! :relieved:

**Comment by kernc** [comment]
Umm... still might not work with `bytes` lines. How does one `shlex.split` bytes?

**Comment by hagberg** [comment]
Are "multi-word" network names allowed in the specification?

**Comment by kernc** [comment]
[What specification?](http://list.fmf.uni-lj.si/pipermail/pajek/2008-April/000073.html) :stuck_out_tongue_closed_eyes: But I have a few \*.net files in my possession that feature a `"`-enclosed multi-word label in a `*network` header, so they might exist in the wild. Just tried it with [Pajek](http://mrvar.fdv.uni-lj.si/pajek/) (.exe) and it writes out multi-word labels even without any quotes when saving a project file. Not that it's a big deal anyway. :]

**Comment by hagberg** [comment]
Sure, let's make it work then.  I think your fix is fine.

**Pull request merged**
