### PR TITLE
Add support for finding maximal cliques containing a set of nodes

### PR DESCRIPTION
**Pull request by ANazaret**
### Adapt `find_clique` to accept a set of starting nodes that all cliques must contain
Finding clique has an exponential running time.

It is common to want to find maximal cliques containing a **specific set of nodes**.
There **exists actually already a function**: `algorithms.clique.cliques_containing_node`.

Unfortunately, this function `cliques_containing_node` simply computes all cliques and filters them down to the ones containing the target node. This is very naive and unusable in practice.
Yet, the original clique algorithm of `algorithms.clique.find_cliques` can be quite easily adapted to start with our desired set of nodes. 

I adapted the initialization of the algorithm in `find_cliques` to use such a set of starting nodes. `find_cliques` now accepts a `nodes` argument, the same `cliques_containing_node` has.
There is no overhead complexity compared to a normal call where `nodes` is not provided and if `nodes` is specified, the clique algorithm is exponentially faster.

If this contribution seems appropriate, I would like to hear your thoughts on:
* `find_cliques` also has a recursive implementation; I should also adapt it to accept `nodes` to be consistent
* This enhancement makes `cliques_containing_node` obsolete [it was unusable and naive anyway]. It should be deprecated.

Thanks;

### CODE REVIEW

**Comment by rossbar** [comment]
I have a (possibly naive) question - does this behave any differently than if you were to run `find_cliques` on the subgraph containing `nodes`, i.e. `nx.find_cliques(G.subgraph(nodes))`?

**Comment by ANazaret** [comment]
> I have a (possibly naive) question - does this behave any differently than if you were to run `find_cliques` on the subgraph containing `nodes`, i.e. `nx.find_cliques(G.subgraph(nodes))`?

Good question: yes it is quite different as the cliques containing `nodes` are likely to have other nodes outside `G.subgraph(nodes)`. Let's take the following graph.
  - - - - - - -
|                  |
1  ---  2 --- 5
|    \   |
3 ---4

If I am only interested in cliques containing nodes [1, 2], then the maximal cliques are [1,2,4] and [1,2,5].

If I restrict to the subgraph you mentioned, then I will only be left with nodes [1,2], which is not a very informative graph.

**Review by dschult — APPROVED** [review]
OK... This one is ready for another set of eyes. :}

**Review by rossbar — APPROVED** [review]
I took the liberty of adding a `Raises` section to the docstrings to call out the new ValueError when `nodes` (if given) isn't a clique (even though this info was already in the parameter description).

This LGTM - thanks @ANazaret and @dschult !

**Comment by dschult** [comment]
Thanks @rossbar 

Question:   I don't see any artifact for the circleci build of the docs on a couple of the recently push/ci-tested PRs. Like this one.  Is there a new way to get to the docs that a PR would create? Or is something wrong with circleci or am I just missing something?  :}

**Pull request merged**
