### PR TITLE
Refactor examples

### PR DESCRIPTION
**Pull request by jarrodmillman**
@dschult , @hagberg I am going through the examples to make the auto-generated gallery nicer (this already does that, but I plan to work on this a bit more before we merge it).

I have some questions:

1. I am not sure what the Blockmodel plot should show.  Currently it looks lackluster.  I started modifying the code, but decided to stop and see if anyone knows what it should look like or what to change to make it look that way.

2. I would like to make a nice plot of the bipartite graph in `examples/algorithms/plot_davis_club.py`.  I am not that familiar with networkx yet and I don't do a lot of plotting in general.  So I thought I'd check if there are any examples of plotting bipartite graphs that I could look at before spending too much time trying to figure it out myself.

3. Some of the examples have data files.  Should any of these be moved into the library?  For example,
```
nx.hartford_drug_use_graph()  # examples/algorithms/plot_blockmodel.py
nx.sampson_monastery_graph()  # examples/drawing/plot_sampson.py
```
For the `hartford_drug_use_graph()`, I don't see an advantage in having the file in the examples directory and would just use the `nx.hartford_drug_use_graph() `.  However, for `sampson_monastery_graph()`, it seems the code would be kept.  In this case, we could add something like the following to the docstring:
```
The file ``sampson_data.zip`` can be download from `here
<https://github.com/networkx/networkx/raw/master/examples/drawing/sampson_data.zip>`_.
We have also provided this data as a built-in example, which you can access via ``nx.sampson_monastery_graph() ``.
```
Are there any other datasets hidden in the examples directory, for which we should provide loaders?  Alternatively, are there any datasets, which we should definitely not provide data loaders for?

Any other suggestions or thoughts?

### CODE REVIEW

**Comment by jarrodmillman** [comment]
A couple more issues:

```
$ python examples/advanced/plot_parallel_betweenness.py 

Computing betweenness centrality for:
Name: barabasi_albert_graph(1000,3)
Type: Graph
Number of nodes: 1000
Number of edges: 2991
Average degree:   5.9820
        Parallel version
Traceback (most recent call last):
  File "examples/advanced/plot_parallel_betweenness.py", line 72, in <module>
    bt = betweenness_centrality_parallel(G)
  File "examples/advanced/plot_parallel_betweenness.py", line 52, in betweenness_centrality_parallel
    node_chunks))
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed
```

and

```
$ python examples/subclass/plot_antigraph.py 
Traceback (most recent call last):
  File "examples/subclass/plot_antigraph.py", line 174, in <module>
    assert G.degree(node) == A.degree(node)
AssertionError
```

**Comment by dschult** [comment]
I don't get the error with ```parallel_betweenness``` on python2.7 or python3.6.

The antigraph error is because ```A.degree``` returns a generator while ```G.degree``` returns a singleton degree value.  I think it is an oversight bug due to changing the base classes. Even if both returned generators the code wouldn't work.  I'll look at that one.

**Comment by dschult** [comment]
I added a PR to your branch to fix the AntiGraph example.

Are you still getting the error for the parallel_betweenness.py code?

**Comment by jarrodmillman** [comment]
Perfect, that fixed the antigraph issue.  I am still getting the ``cPickle.PicklingError`` for ``examples/advanced/plot_parallel_betweenness.py ``.

**Comment by dschult** [comment]
Which python version?

**Comment by jarrodmillman** [comment]
I am running the default Python on Fedora 24:
```
$ python --version
Python 2.7.13
```

I created a virtualenv to test just now.  I removed ``gdal`` from ``requirements.txt``, since there is a header file missing from this version of Fedora (its fixed in newer releases, but I haven't upgraded yet.)

Here is what my ``requirements.txt`` file looks like: 
```
$ cat requirements.txt 
decorator>=3.4.0
matplotlib
scipy
numpy
nose
nose-ignore-docstring
pandas
lxml
pyyaml
pygraphviz
sphinx
sphinx_rtd_theme
pydot >= 1.2.3
```

Then I did:
```
$ pip install -r requirements.txt
$ pip install -e .
```

Here's my environment:
```
$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
alabaster (0.7.10)
Babel (2.4.0)
certifi (2017.4.17)
chardet (3.0.4)
cycler (0.10.0)
decorator (4.1.1)
docutils (0.13.1)
functools32 (3.2.3.post2)
idna (2.5)
imagesize (0.7.1)
Jinja2 (2.9.6)
lxml (3.8.0)
MarkupSafe (1.0)
matplotlib (2.0.2)
nose (1.3.7)
nose-ignore-docstring (0.2)
numpy (1.13.1)
pandas (0.20.3)
pip (9.0.1)
pydot (1.2.3)
Pygments (2.2.0)
pygraphviz (1.3.1)
pyparsing (2.2.0)
python-dateutil (2.6.1)
pytz (2017.2)
PyYAML (3.12)
requests (2.18.1)
scipy (0.19.1)
setuptools (36.2.0)
six (1.10.0)
snowballstemmer (1.2.1)
Sphinx (1.6.3)
sphinx-rtd-theme (0.2.4)
sphinxcontrib-websupport (1.0.1)
subprocess32 (3.2.7)
typing (3.6.1)
urllib3 (1.21.1)
wheel (0.30.0a0)
```

And my error:
```
$ python examples/advanced/plot_parallel_betweenness.py

Computing betweenness centrality for:
Name: barabasi_albert_graph(1000,3)
Type: Graph
Number of nodes: 1000
Number of edges: 2991
Average degree:   5.9820
        Parallel version
Traceback (most recent call last):
  File "examples/advanced/plot_parallel_betweenness.py", line 72, in <module>
    bt = betweenness_centrality_parallel(G)
  File "examples/advanced/plot_parallel_betweenness.py", line 52, in betweenness_centrality_parallel
    node_chunks))
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed
```

**Comment by jarrodmillman** [comment]
Just to check my sanity, the same error appears for me on the (i.e., upstream networkx) master branch:
```
$ python examples/advanced/parallel_betweenness.py

Computing betweenness centrality for:
Name: barabasi_albert_graph(1000,3)
Type: Graph
Number of nodes: 1000
Number of edges: 2991
Average degree:   5.9820
        Parallel version
Traceback (most recent call last):
  File "examples/advanced/parallel_betweenness.py", line 70, in <module>
    bt = betweenness_centrality_parallel(G)
  File "examples/advanced/parallel_betweenness.py", line 50, in betweenness_centrality_parallel
    node_chunks))
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed
```

**Comment by dschult** [comment]
Ack -- I was sure I tested with Python2.7 but apparently I didn't.

Anyway, it doesn't work for me in python2.7.13 either.  It does work in 3.6, 3.5, 3.4 ,3.3.  So maybe it is a python2 vs 3 issue.  

Looks like its a known issue for 2.7:
https://stackoverflow.com/questions/1816958/cant-pickle-type-instancemethod-when-using-multiprocessing-pool-map

**Comment by jarrodmillman** [comment]
Maybe we should just leave it failing for now.  I added a link to ``stackoverflow`` in the docstring just so it is easy to find.  If it fails, ``sphinx-gallery`` will just insert a thumbnail saying "BROKEN", which seems like a reasonable solution.  Given that it works on 3.3-3.6, I don't think it is worth spending too much time getting some fix just to handle 2.7.

There are already a lot of changes in this PR.  It
1. makes the imports more standard
2. updates all copyrights
3. reduces the code in the examples
4. fixes a couple documentation issues
5. creates thumbnails for 14 more examples (though one of those is a "BROKEN" thumbnail)
6. fixes two existing thumbnails (``unix_email`` and ``blockmodel``)

So it is a serious improvement and I am getting a little bored working on the gallery.

If this seems reasonable to you, this is ready to merge.

**Pull request merged**
