### PR TITLE
See also-correction

### LINKED ISSUE #1176: DOC: plain text vs. links in "See Also" sections of docstrings
In the generated sphinx documentation, the functions mentioned in the "See Also" section of the [`is_semiconnected`](http://networkx.github.io/documentation/development/reference/generated/networkx.algorithms.components.semiconnected.is_semiconnected.html) docstring are plain text rather than links.  Although I have not made a detailed study, this seems to be the case for several but not all docstrings in networkx.  I don't know which conditions are required for sphinx to add the links, and I'm not sure what would be the preferred way to change the docs so that sphinx would provide links instead of plain text.

### PR DESCRIPTION
**Pull request by Michael-E-Rose**
This is an attempt to fix #1176, which is about missing links to methods in other modules. Working on the docstrings, I added some references in text and added `raises` statements where they were missing.

Furthermore, I updated the tops of the modules to current standards and applied PEP8 in the code.

### CODE REVIEW

**Comment by dschult** [comment]
To check whether this works, you'll need to build it (ReadTheDocs only builds the master branch).

With pip, use ```pip install sphinx sphinx-rtd-theme```  (It is possible I am forgetting others, but you'll get an error if you don't have what sphinx needs.)  

Then go to the ```./doc``` directory and use ```make html```.  The results are built and put in ./doc/build/html where you can try them locally. 

BTW I see that Errors in the ReadTheDocs documentation builds were introduced in one of the merges this morning. You can avoid that by using python3+ when you do the ```make html```.  I will correct those errors in another PR soon.

**Comment by Michael-E-Rose** [comment]
Sorry, I can't build it. Using Python 3.4, the error is as follows:
```
Traceback (most recent call last):
  File "make_gallery.py", line 62, in <module>
    execfile(example)
NameError: name 'execfile' is not defined
degree_histogram.py make: *** [build/generate-stamp] Error 1
```

Using Python 2.7, the error is as follows:
```
degree_histogram.py Traceback (most recent call last):
  File "make_gallery.py", line 62, in <module>
    execfile(example)
  File "degree_histogram.py", line 12, in <module>
    degree_sequence=sorted([d for n,d in G.degree()], reverse=True) # degree sequence
TypeError: 'int' object is not iterable
make: *** [build/generate-stamp] Error 1
```
Any suggestions what to do?

**Comment by dschult** [comment]
Yes, it looks like make_gallery won't work with python3 due to the ```execfile``` in make_gallery.py

I think the error you are getting with python2.7 means you are using an older version of networkx. Perhaps you need to set your PYTHONPATH environment variable?  But even with that I am getting an error on the dergee_histogram example because of namespace collision for ```nx.generators```.  I'll open an issue about that.

**Comment by dschult** [comment]
Looks like it worked!

**Comment by dschult** [comment]
Or maybe it didn't work.....  can you check it?  Thanks...
http://networkx.readthedocs.org/en/latest/reference/algorithms.component.html

**Comment by Michael-E-Rose** [comment]
It did not :-/

The first four entries in
http://networkx.readthedocs.org/en/latest/reference/generated/networkx.algorithms.components.connected.is_connected.html#networkx.algorithms.components.connected.is_connected
should be links.
Am 18.04.2016 07:32 schrieb "Dan Schult" <notifications@github.com>:

**Pull request merged**
