### PR TITLE
Correct see also links

### LINKED ISSUE #1176: DOC: plain text vs. links in "See Also" sections of docstrings
In the generated sphinx documentation, the functions mentioned in the "See Also" section of the [`is_semiconnected`](http://networkx.github.io/documentation/development/reference/generated/networkx.algorithms.components.semiconnected.is_semiconnected.html) docstring are plain text rather than links.  Although I have not made a detailed study, this seems to be the case for several but not all docstrings in networkx.  I don't know which conditions are required for sphinx to add the links, and I'm not sure what would be the preferred way to change the docs so that sphinx would provide links instead of plain text.

### PR DESCRIPTION
**Pull request by Michael-E-Rose**
This is to (hopefully finally) fix #1176 by adding the full prefix to methods in other moduls in order to link them from any "see also" section.

In PR #2082 we discovered that prefixing with `components.` is not enough. Here I prefix with the full path `networkx.algorithms.components.connected.` I am still unable to build the docs myself (both with Python 2.7 and Python 3.4).

### CODE REVIEW

**Comment by dschult** [comment]
These changes still do not have the full path in the ```see also``` section. 
You need the module name at the end. e.g.:

    networkx.algorithms.components.weakly_connected.is_weakly_connected

These make the name of the reference quite long (and potentially confusing because the reader may expect to have to type that long string just to call the function). 

I'm looking for a way to make the text of the link be just the function name while still telling Sphinx where to link to...

**Comment by jfinkels** [comment]
In plain Sphinx, you can do `` `:func:`~networkx.algorithms.components.weakly_connected.is_weakly_connected` `` (i.e. prepend a tilde) to have the rendered output as just the (hyperlinked) function name `weakly_connected`, but I don't know how that plays out with Napoleon.

**Comment by dschult** [comment]
Thanks @jfinkels.   I found a description of that at: 
http://www.sphinx-doc.org/en/stable/markup/inline.html

I've tested it and it seems to work. So I have for the "See Also" section of "connected_component_subgraphs".

    See Also
    --------
    :func:`connected_components`
    :func:`~networkx.algorithms.components.strongly_connected.strongly_connected_components`
    :func:`~networkx.algorithms.components.weakly_connected.weakly_connected_components`

Note:  once I add the ```:func:`name` ``` to any line, the other lines don't produce links without :func:`name` even if they are in the current module.

@Michael-E-Rose is this enough to go on?

**Comment by Michael-E-Rose** [comment]
Good evening! We can go for this, albeit it has the disadvantage of being too long and possibly confusing. But let me try tweaking the `__init__.py` (as explained in https://github.com/networkx/networkx/issues/1176#issuecomment-212023206) first.

**Comment by Michael-E-Rose** [comment]
I got it. The trick was to remove `currentmodule` in `algorithms.component.rst` and list `automodule` only once.

**Comment by dschult** [comment]
This looks like it works! :)
I'm going to merge it so we can check the readthedocs sphinx versions. 
If all is good we can take stock of how much else needs to be converted.

**Pull request merged**
