### PR TITLE
Deprecate dag longest path length

### LINKED ISSUE #6383: Deprecate the `dag_longest_path_length` helper function?
The `nx.dag_longest_path` function has a helper `dag_longest_path_length` which essentially calls `dag_longest_path` then does a little post-processing to derive the length from the result. This generally matches a pattern established by the `shortest_path` functions (i.e. having a `_length` helper), but I thought I'd make the case for breaking that pattern here.

For non-multigraphs, `nx.dag_longest_path_length` essentially boils down to:

```python
sum(G[u][v].get(weight, default_weight) for u, v in pairwise(path))
```

where `path` is the result of `nx.dag_longest_path`. This one-liner is idiomatic and easy to understand (and would be simplified even further in the case of e.g. unweighted edges). The case of multigraphs is trickier, as there is the matter of how to reduce weighted multiedges into a single value. `dag_longest_path_length` makes the (sensible) decision to use `max` to select the maximum edge weight. There's no reason to be this rigid however - users should be able to use whatever reduction function they want (`sum` e.g.) and IMO it's easier to bake in this flexibility by using Python comprehensions directly rather than expanding the API to support passing in a `callable`.

Like most of my deprecation suggestions, this is very subjective. I prefer a teach-a-person-to-fish approach when dedicated API can generally be replaced with a one-line list comprehension, but that has to be weighed against the potential disruption from deprecating, as well as the breaking of the `_length` helper-function API pattern established by the `shortest_path` package. Please LMK what you think!

See also #6311

### PR DESCRIPTION
**Pull request by rossbar**
Closes #6383

### CODE REVIEW

**Review by dschult — DISMISSED** [review]
This looks good to me.
:}

**Review by jarrodmillman — APPROVED** [review]

**Comment by MridulS** [comment]
I'm kind of -0.5 on this change but I won't fight it :)

I like super quick helper functions show up with a `tab` hit when I do `nx.dag_`, without me trying to wrangle a dictionary structure and remembering where to call `sum`. Yes I like python but still I like my quick helper functions.

**Comment by dschult** [comment]
Looking at the `dag_longest_path` function a little more, it looks like that function first finds the path length and then builds the path as a last step before returning.  Then the current `dag_longest_path_length` calls that function and takes the result and builds the length from the path.  

I propose that we "just" refactor the two functions so that either the `_path` version calls the `_length` version and then builds the path, or they both call a helper function that returns the data structures from the search and the main routines either build a path or compute a length. 

I don't think it makes sense to have the length, not return it and then have the user compute the length.  Also, the path functions elsewhere typically have a `_path` version and a `_path_length` version. So maybe its good to keep that here?  Anyway, I hope to get a PR that would make this better (and as a side effect probably won't deprecate the function).

**Comment by rossbar** [comment]
This sounds good to me - I certainly understand the trepidation re: API churn. I'll go ahead and close this in favor of refactor rather than a removal!

**Pull request closed without merging**
