### PR TITLE
Delete warning in approximation documentation

### PR DESCRIPTION
**Pull request by paulitapb**
On the approximation main page, there was a warning about how to import the functions because they are not part of the `networkx` base namespace. As discussed in another PR, warnings are unsuitable for this purpose. So I change it to delete the warning.

### CODE REVIEW

**Review by MridulS — APPROVED** [review]
I think we just need to be consistent with this 😅

**Review by rossbar — COMMENTED** [review]
+1 for consistency! I may just be reading the diffs wrong, but doesn't this *remove* a warning in one module and *add* it in the other? I don't have strong preference for whether to warn or not, but it should be the same. Apologies if I'm somehow interepreting this incorrectly!

**Comment by paulitapb** [comment]
> +1 for consistency! I may just be reading the diffs wrong, but doesn't this _remove_ a warning in one module and _add_ it in the other? I don't have strong preference for whether to warn or not, but it should be the same. Apologies if I'm somehow interepreting this incorrectly!

You're right! I had that on my main branch for a while by mistake. I will update it to undo the unwanted changes.

**Comment by paulitapb** [comment]
I removed the unwanted changes @MridulS @rossbar

**Review by rossbar — APPROVED** [review]
Thanks @paulitapb ! I pushed up a few minor formatting changes, but LGTM.

FWIW the failing CircleCI job is unrelated - that's a bad interaction between Sphinx v6 and the current pydata-sphinx-theme: see pydata/pydata-sphinx-theme#1094

**Comment by rossbar** [comment]
Same with the failing lint job... see #6407

**Pull request merged**
