### PR TITLE
Minor Python 2 cleanup

### PR DESCRIPTION
**Pull request by rossbar**
Use dict.keys() for set operations rather than explicitly creating sets, as recommended in the comment.

### CODE REVIEW

**Review by MridulS — APPROVED** [review]

**Review by jarrodmillman — APPROVED** [review]

**Comment by dschult** [comment]
This change does work -- and you'd think it might be faster, but it looks like it is actually slower -- even for large sets. 

Probably sticking with builtin python objects is faster than using the same tools via the NetworkX views. The collections.abc tools are nice, but not optimized for speed -- rather for ease of implementation I suspect.

Anyway, if anyone is thinking of propagating use of `keys` instead of sets throughout the library (and there are many other places it could be used), it probably isn't worth the effort. :{  It is probably slightly less readable too.

**Comment by rossbar** [comment]
Thanks @dschult , I didn't bother to check the performance which was an oversight on my part!

In that case, I think the original is unquestionably better as it was a) shorter, b) more performant, and c) explicit (i.e. readers don't have to know that `keys` support set operations in order to understand the code). I'm going to undo the change less the comment.

**Comment by dschult** [comment]
Getting rid of the comment is a Good Thing!
One more "ToDo" out of the codebase! :)

**Comment by rossbar** [comment]
> Getting rid of the comment is a Good Thing!

Just doing it the hard way ;)

**Pull request merged**
