### PR TITLE
Add approximation for minimal feedback vertex set

### PR DESCRIPTION
**Pull request by JamesClough**
First attempt at adding an approximation for finding a minimal feedback vertex set. Solves issue #2270 
Review and feedback very welcome.

### CODE REVIEW

**Comment by jfinkels** [comment]
I think you are using the `cycle_basis` function as if it returned a list of all cycles in the graph, but that is not the correct usage of the function (it returns the "cycle basis" of the graph, a minimum set of cycles from which all other cycles can be constructed via "exclusive or").

**Comment by JamesClough** [comment]
@jfinkels Yes you are correct. Do you have any ideas on the best approach to check for semidisjoint cycles? The ```simple_cycles``` method is only for directed graphs.
It does not matter what order we find them in so perhaps it is best to start with the cycles in the cycle basis, and once they are all checked then go through their exclusive-or combinations? That should hopefully minimises the number of times we have to go through that slow process.

**Comment by jfinkels** [comment]
I'm about to create a pull request that has my attempt at an implementation of this. It is not quite working yet, but the code matches the paper's pseudocode fairly closely, so a fresh set of eyes should be able to determine where my code is incorrect. I'll cc you @JamesClough so you can take a look at it.

**Comment by hagberg** [comment]
See #2316

**Pull request closed without merging**
