### PR TITLE
Add IRC channel to README.rst

### PR DESCRIPTION
**Pull request by harlowja**
A IRC channel has been made where discussion can be performed
about networkx, using the popular opensource freenode servers
so it might as well be mentioned in the README.rst so people
can find it as needed.

https://freenode.net/

### CODE REVIEW

**Comment by dschult** [comment]
Should we add a line to the client webchat.freenode.net for those who don't know/want to install a client?

**Comment by hagberg** [comment]
Don't we want to use Slack like all of the cool kids?

**Comment by MridulS** [comment]
Sounds good

**Comment by SanketDG** [comment]
Slack will be overkill for a repository. It does have some "cool" features that IRC doesn't have, but IRC will suffice for most of the time.

**Comment by MridulS** [comment]
Cool kids use gitter here ;)

**Comment by hagberg** [comment]
I think the Slack folks will be amused to hear it called "overkill."

**Comment by harlowja** [comment]
I like IRC, ha, since that's what I use for other opensource projects.

Will update to have the webchat link though.

**Comment by MridulS** [comment]
I think now is a good time to decide on a chat/discussions forum. IRC / Slack/ Gitter, we should decide on one.

@chebee7i @ysitu @jfinkels

**Comment by harlowja** [comment]
I'm pretty sure GNU uses freenode, http://lwn.net/Articles/8508/ and how much more free can it get than that :-P openstack also uses it...

**Comment by SanketDG** [comment]
Just putting my opinion here about Slack: (been in 3 channels)

First of all, you have to add members by invite, specifically by email address. There are tools out there that help you automate this process, but still each and everyone who wants to join the discussion will have to request an invite and then wait for an approval (also create an account if he does not have one). It's overkill because there are channels, integrations(with Github, Travis CI) and whatnot, half of which we will never use. (all of these features are also available in Gitter too) It's great for project based stuff, but just not for a repository. Just my personal opinion.

I am with Gitter too, if IRC is too old school. I am okay with either.

**Comment by harlowja** [comment]
'IRC is too old school', damn I feel old, ha.

**Comment by OrkoHunter** [comment]
For IRC, people have to set up loggers to see the messages when they are offline and to be honest, it troubles a lot (in case proxies.. sigh!). This is the main advantage of gitter and slack which I feel. Also, there are lot more plus points for using Gitter for a GitHub organization
* Mention of PRs
* Activities ticker
* Code formatting/Link with gists

So, using gitter won't be that bad. Just my $0.02

**Comment by harlowja** [comment]
Some of those sound nice (github integration); the logging I've always been 'meh' on, since I sorta agree with the following from the freenode folks: http://freenode.net/channel_guidelines.shtml

* **If you're considering publishing channel logs, think it through.** The freenode network is an interactive environment. Even on public channels, most users don't weigh their comments with the idea that they'll be enshrined in perpetuity. For that reason, few participants publish logs.

  * If you're publishing logs on an ongoing basis, your channel topic should reflect that fact. Be sure to provide a way for users to make comments without logging, and get permission from the channel owners before you start. If you're thinking of "anonymizing" your logs (removing information that identifies the specific users), be aware that it's difficult to do it well—replies and general context often provide identifying information which is hard to filter.

  * If you just want to publish a single conversation, be careful to get permission from each participant. Provide as much context as you can. Avoid the temptation to publish or distribute logs without permission in order to portray someone in a bad light. The reputation you save will most likely be your own.

**Pull request merged**
