### PR TITLE
Added data keyword in G.neighbors

### PR DESCRIPTION
**Pull request by MridulS**
@dschult 
Hey, I am new to networkx and interested in contributing to it. 
As mentioned in #1246. I have tried implementing a API 2.0 feature on G.neighbor

neighbors(n, data=None) - iterator over neighbors of n.
       If data is True: iterator over (nbr, eattr_dict)
       if data not in (None,True): iterator over (nbr, eattr_dict[data])

Please have a look. Needs Review.

### CODE REVIEW

**Comment by dschult** [comment]
@MridulS

It looks like you should make sure nosetests is set up and working on your
machine to run the tests before creating the pull request. On the pull
request page you can see what the automated testing service Travis-CI found
for failures.  But these are often easier to find on your own machine.

The command: nosetests test_file.py
can let you run a single test file at a time.

You change a number of test files where we use assert_raises(). I think
these changes break the test code. Look at the original code to see how the
function should be used. We need the function to be called followed by the
arguments to be given to that function. By putting the arguments into the
function, you are running the function before calling assert_raises. The
interpreter calls the function with the given argument, gets the result and
sends the result to assert_raises() as if it is a function to be tested.

Also while we are talking about testing, these methods are core routines
for the graph classes so you should do some performance testing to see the
difference in speed. With all the for loop construction in the new code, I
suspect it is much slower than the previous code. But Python speed is often
surprising.

The tests and speed checks are more demanding for code in the core graph
classes. It might be easier to start contributing with less critical code.
But if you want to learn about nosetests and Timer, this feature will need
it. :)
Dan

**Comment by MridulS** [comment]
@dschult Updated the test cases.Passing travis build. I tried to add new test cases for G.neighbors, but some previous test cases are failing. I think this is because neighbors_iter now returns <generator object  > instead of <dictionary-keyiterator object>.
Can I start working on #1343 to get more familiar with the codebase.

**Comment by dschult** [comment]
The PR now changes 7 files, but only 2 files have substantive changes. The changes to the test files don't seem to affect behavior. I guess you should either remove those changes or explain why you request them.
I think #1345 would help you learn the codebase and is more likely to be feasible.

**Comment by MridulS** [comment]
@dschult I was going through the proposed NX 2.0 iterator API as mentioned in #1246. 
```
neighbors(n, data=None) - iterator over neighbors of n.
     If data is True: iterator over (nbr, eattr_dict)
     if data not in (None,True): iterator over (nbr, eattr_dict[data])
```
I think this could be implemented in a way I did.
But by doing that I am returning a different type of object.

**Comment by MridulS** [comment]
@dschult In the design specification for G.neighbors
```
MultiGraph
If data is True: combine all edges between neighbors using combine_multiedges(keydict.values())
If data is not in (False,True): combine all edges between neighbors using combine_multiedges(dd[data] for dd in keydict.values())
```

shouldn't it be ``` If combine_multiedges is True: ``` instead of ``` If data is True:```

**Comment by dschult** [comment]
Actually, I did mean ```if data is True:```

The data we return for ```neighbors()``` when multiedges are present has to be combined if there is more than one edge between the same pair of nodes.

**Comment by MridulS** [comment]
Got it. Read through #1246. What is the common consensus regarding the API design specification?  

BTW Can you look at #1350

**Comment by dschult** [comment]
What do you mean by "common consensus"? It's not clear we have one.

**Comment by MridulS** [comment]
Is the API design specification made with other backends(matrix graphs) in mind? Will it have OrderedDicts? The ANY() method? Should we have general api for Di/Multi/Graphs?

**Comment by hagberg** [comment]
Those are interesting questions but maybe they shouldn't all be addressed/discussed in one pull request.

**Comment by MridulS** [comment]
@dschult @hagberg Updated the neighbors method as discussed in #1246 and in the design specification wiki.
``` python
In [2]: G = nx.MultiGraph()

In [3]: G.add_edge(1,2,weight=1)

In [4]: G.add_edge(1,2,weight=2)

In [5]: G.add_edge(1,3,weight=2)

In [6]: G.neighbors(1)
Out[6]: [2, 3]

In [7]: G.neighbors(1,data=True)
Out[7]: [(2, {'weight': 1}), (2, {'weight': 2}), (3, {'weight': 2})]

In [8]: G.neighbors(1,data='weight')
Out[8]: [(2, 1), (2, 2), (3, 2)]

```
How should we combine the data for multiedges? I have implemented such that output is Out[8]. Where each tuple is the neighbor followed by its respective weight.

**Comment by dschult** [comment]
Returning more than one edge per neighbor should be the job of G.edges()
For G.neighbors() we should combine the multiedges between the neighbors.
I think we should include an argument G.neighbors(n, data=False, combine_edges=min)

The networkx codebase seems to use min and sum to combine multiedges depending
on whether the weight represents a length or a capacity. I like the default of min.

It's not clear to me whether we should allow different arguments for MultiGraph from Graph. Of course Graph doesn't have multiedges, so why include that argument? But including the argument and ignoring it would allow algorithm code to call the method with the same syntax for both Graph and Multigraph.

**Comment by MridulS** [comment]
But what if the data in graph edges are different from length or capacity (some arbitrary string) ? How to represent that. 
According to me including the argument and ignoring for Graph should be way to go as Multigraph inherits from graph, so it doesn't really makes a difference. 

Just to confirm: By min you mean the minimum weight of the length or capacity in the multiedges, right?

**Comment by MridulS** [comment]
On a different note:

``` python
In [2]: G = nx.MultiGraph()

In [3]: G.add_edge(1,2,weight=1)

In [4]: G.add_edge(1,2,weight=2)

In [5]: G.add_edge(3,2,weight=1)

In [6]: H= nx.Graph(G)

In [9]: H.edges(data=True)
Out[9]: [(1, 2, {'weight': 2}), (2, 3, {'weight': 1})]
```

nx.Graph(G) should add the weights of all the multiedges instead of just assigning the weight of the latest  edge.

**Comment by chebee7i** [comment]
Add, mean, max, min...all seem valid. I think we need to provide a way to specify how the decision is made or raise an Exception if if nx.Graph(G) is called and G has multiple edges.

**Comment by hagberg** [comment]
I am typically not in favor of adding more keywords to the core methods.
In this case I'm already not very enthusiastic about adding `neighbors(data=True)` .  I feel it could be confusing which data is returned.  It isn't unreasonable to assume that since `neighbors` are nodes that you would return the data with those nodes (not the edge data).

Can we really not simply use `edges(data=True)`?
It's a one-liner to get the edge data and process it any way you want.

```python 
[(v,d) for u,v,d in G.edges(1,data=True)]
```

And just to throw another wrench into the works :smiley: 
Shouldn't `neighbors` take an `nbunch`?

**Comment by MridulS** [comment]
I guess the most obvious solution would be to add the edges and it is possible that user wants to convert a multigraph to graph. 
@hagberg gave a way to do this in http://stackoverflow.com/questions/15590812/networkx-convert-multigraph-into-simple-graph-with-weighted-edges.

**Comment by hagberg** [comment]
Different note = different issue please.

**Comment by hagberg** [comment]
Voting again for no `neighbors(data=)` keyword.  Instead use `edges(data=True)`.

**Comment by MridulS** [comment]
Honestly, even I am not very enthusiastic about adding new keywords. I think we should just remove the list generator and keep the iterator ( for NX 2.0). ``` edge(data=True) ``` does the work just fine.

PS. Why should ```neighbors``` take in a ```nbunch``` ?

**Comment by hagberg** [comment]
I guess the reason for `neighbors` to take a container  is that other methods do (edges, degree, etc).
Though it isn't very hard to implement that as a one-liner either.

**Comment by chebee7i** [comment]
I'll add my vote to not adding a keyword to `G.neighbors()`.

That said, I can see the value of being able to specify an attribute and getting all the  `(nbr, eattr_dict[data])` tuples, potentially with a user-specified combinator. This is a common query and if we can remove the boilerplate of having to deal with multiple graph classes, etc, then I think it might be worth it, but perhaps as a separate function not at the top-level. `nx.algorithms.neighbor_combinator(G, n, data=None, combine=min)` ?

**Comment by dschult** [comment]
@hagberg, are you really saying we should use one method for all graph queries?
To get G[u] we can use edges() in a 1-liner. To get G.neighbors(n) its a 1-liner with edges().
To get G.self_loop_edges() its a one liner with edges(). To get G.degree() its a 1-liner with edges().
I don't think you really mean we should reduce the interface to one method (or maybe 2--one for nodes() and one for edges()). 

What criteria can we use for when to:
1) add a keyword to change the output behavior
2) add a new method that provides that output behavior
3) only output general data that requires the user to post-process with a 1-liner

**Comment by hagberg** [comment]
I don't have any clear philosophy on when to add a method or keywords.  I like simple. And I generally prefer adding a method than making a more complicated single method with a keyword.  I would also say that it makes sense to have methods that "agree" with general graph terminology.  So predecessors, successors, edges, degree, neighbors are good.  

For the case of `neighbors()` I don't like that the method would get significantly more complicated (I'd advocate for another method like @chebee7i  suggests) and that 'neighbor data' is potentially confusing  - why isn't it the data return that for the neighbor nodes (instead of the edges)?

**Comment by hagberg** [comment]
Maybe @chebee7i's idea is the genius compromise here.  Keep the graph methods simpler but make a module that provides some basic one-liner like functions.  We are already doing that for nx.get_node_attributes() and others.  I don't remember anyone suggesting adding those as methods to the graph container classes but I might have missed it.

**Comment by dschult** [comment]
I see the confusion for asking for edge data with a method called neighbors. And I think the idea of keeping methods close to the graph theory terminology is also powerful. Functions outside the class are currently present for get_edge_attributes and so maybe that is a good way to go. But these functions will depend on the data structure -- that's why I prefer they be methods.

Maybe the way to proceed is to look through the algorithms and find common query paradigms that can be packaged into functions. I'm sure one of them is to return (nbr, edge_weight) as it is used in the shortest_path routines. There are quite likely to be others.

**Comment by chebee7i** [comment]
@dschult If we do the function route for helpers and *+1* features, we can have separate implementations for each class (if necessary), just as we'd do in methods. There will be no performance penalty if core functions query for the appropriate function ahead of time. Yes, it does seem a bit messy on one hand, but there are also benefits: all variants of the function appear in a single (small) file making maintenance easier. 

```
__all__ = ['funcname']

def common_stuff():
     pass

def funcname__graph(...):
    common_stuff()
    ...

def funcname__digraph(...):
    common_stuff()
    ...

def funcname(...):
    func = get_funcname(G)
    return func(...)

def get_funcname(G):
    # Core algorithms call this once to avoid inner loop penalties.

    directed = G.is_directed()
    multigraph = G.is_multigraph()

    if directed and not multigraph:
        return funcname__graph
    ....
```

Sometimes a single docstring will suffice for `funcname` instead of 4 different docstrings. When that is not possible, we can programmatically construct customized docstrings from a template---which also reduces docstring repetition.

**Comment by MridulS** [comment]
I agree with @chebee7i. An implementation like this will be efficient and the code will be easier to read and maintain. 
@dschult I think we should implement all possible methods for which a user can have output data but not inside the core class but in something like ```nx.algorithms.get_something``` like we have have for ```nx.get_node_attributes()``` as suggested by @hagberg. The user should be able to use networkx with minimal knowledge.

**Comment by hagberg** [comment]
I suggest we close this PR as 'declined'.  Adding functions as suggested by @chebee7i  or @dschult should be a separate issue.

**Pull request closed without merging**
