### PR TITLE
Update shortest_path_length

### PR DESCRIPTION
**Pull request by MridulS**
I was messing around with `single_source_shortest_path_length` and `all_pairs_shortest_path_length`. Now `single_source_shortest_path_length` returns a (node, distance) two tuple iterator and `all_pairs_shortest_path_length` returns a (node, dict) two tuple iterator.
This is a messy PR. I have just added a dict() in front of required code. This PR will fail Travis as there are few things I need to work out.

I am just looking for opinion on the `shortest_paths` algorithms, and what should they return.

### CODE REVIEW

**Comment by MridulS** [comment]
https://github.com/MridulS/networkx/blob/traversal/networkx/algorithms/shortest_paths/unweighted.py

**Comment by MridulS** [comment]
```python
def single_source_shortest_path_length(G,source,cutoff=None):
    seen={}                  # level (number of hops) when seen in BFS
    level=0                  # the current level
    nextlevel={source:1}  # dict of nodes to check at next level
    while nextlevel:
        thislevel=nextlevel  # advance to next level
        nextlevel={}         # and start a new list (fringe)
        for v in thislevel:
            if v not in seen:
                seen[v]=level # set the level of vertex v
                nextlevel.update(G[v]) # add neighbors of v
                yield (v, level)
        if (cutoff is not None and cutoff <= level):  break
        level=level+1
    del seen  # return all path lengths as dictionary
```
```python
def all_pairs_shortest_path_length(G, cutoff=None):
    length = single_source_shortest_path_length
    # TODO This can be trivially parallelized.
    for n in G:
        yield (n, dict(length(G, n, cutoff=cutoff)))
```

**Comment by MridulS** [comment]
@dschult @hagberg @jfinkels @chebee7i

**Comment by dschult** [comment]
I think the single_source_... is good... certainly what I was envisioning.
The all_pairs has a question.... which is probably why you included it.
Building the dict for each single source takes memory that people may not want to use.

You could ```yield (n, single_source_shortest_path_length(G, n, cutoff=cutoff))```
so the usage would look like e.g. diameter:

    path_length = nx.all_pairs_shortest_path_length(G)
    diameter = max( max(length for v,length in spl) for u,spl in path_length)
    # or for a dict of dicts
    all_path_lengths = dict( (v,dict(spl)) for u,spl in path_length)

This makes the default be lower memory, but is it too tricky for users to easily grok? what do you think is better?

**Comment by MridulS** [comment]
If we return (node, iterator) iterator, the user needs to tweak around a lot get the desired results but it takes up less memory initially.
On the other hand (node, dict) iterator makes it easier for users to handle this but it takes up more memory. This is a tradeoff we need to discuss.

I think we should keep (node, dict) iterator as it is easier for python beginners users to use this and the code looks cleaner IMO.

**Comment by MridulS** [comment]
@hagberg @dschult @jfinkels @chebee7i @ysitu Should I stick with (node, dict) and move forward?

**Comment by dschult** [comment]
Yes, I think sticking with (node, dict) for all_pairs is a reasonable way
forward. :)

**Comment by MridulS** [comment]
https://github.com/networkx/networkx/pull/1715

**Pull request closed without merging**
