### PR TITLE
Rename `_dispatch` to `_dispatchable`

### PR DESCRIPTION
**Pull request by eriknw**
How do people like the name `_dispatchable`? Once there is better documentation for it (for users, backend developers, and networkx developers), then I think we should consider changing the name one last time to `dispatchable`.

### CODE REVIEW

**Comment by eriknw** [comment]
This addresses one of the issues @JDLH raised in #7189 and goes with the suggestion by @rlratzel from https://github.com/networkx/networkx/issues/7189#issuecomment-1870680690

**Comment by JDLH** [comment]
Should the name remain prefixed with an underscore forever?  I know very little about backend dispatching in NetworkX, but I think I remember reading that they underscore prefix was to signal that this decorator being preliminary and in flux. If this change is "one last time", then maybe the name is no longer preliminary or in flux?

**Comment by rossbar** [comment]
> Should the name remain prefixed with an underscore forever?

Definitely not - we should have a discussion on the dispatching roadmap, which I won't dump so as not to distract from the PR.

> If this change is "one last time", then maybe the name is no longer preliminary or in flux?

I will say however that this is likely not the last change that would motivate removing the underscore!

**Comment by eriknw** [comment]
To clarify, when I said "consider changing the name one last time to `dispatchable`", I meant to do this _after_ renaming to `_dispatchable`, and only once it's ready. So, yeah, what @rossbar said :)

**Review by rossbar — COMMENTED** [review]
Personally, I like the proposed name change. I feel that it better captures that the "dispatchability" is a property of the decorated function, rather than some internal indirection that impacts the actual networkx implementation. This should hopefully help alleviate some of the concerns for readers of the source code highlighted in #7189 .

@JDLH what do you think - is the proposed name change more clear IYO?

**Comment by JDLH** [comment]
@rossbar I think "dispatchable" is an improvement on the previous name "dispatch". It has the advantage that, as you say, it reads like a property of the decorated function.  It has the disadvantage of being opaque to most readers about what that property actually means.  The word "dispatchable" does not by itself quite tell most readers what they need to know. 

Thus I think the new name needs to be paired with an explanation of the decorator, under the name "dispatchable", in the function reference documentation. When I was looking for an explanation of this decorator, the function reference is where I searched for the name "_dispatch". There was no text under that heading. I suggest that the explanation include a message to readers who don't care about backends, and are not using networkx as a front end to other libraries, that this decorator is of no concern to them.  Then it should have a reference to the place in the documentation where dispatching and backends are explained. 

Maybe after that it has the normal reference documentation about the decorator, its parameters, its effects, etc. A lot of this reference documentation is presently located in the [module utils/backends.py](https://github.com/networkx/networkx/blob/1168afca385dab8cbda8be3aa479a22581e94988/networkx/utils/backends.py).

**Comment by rossbar** [comment]
> Thus I think the new name needs to be paired with an explanation of the decorator, under the name "dispatchable", in the function reference documentation.

Agreed - the renaming here is certainly not sufficient to address #7189 on its own. There should definitely be a very visible and easily discoverable reference with the explanation you describe. In addition to reference docs, it might also be worth adding a term to the glossary and using the `:term:` role liberally throughout the documentation to link to the high-level overview page of the `_dispatchable` decorator.

**Review by rossbar — APPROVED** [review]
Everyone who's weighed in on the topic (either here or in community meetings) has general agreed the new name is an improvement, so I approve!

**Comment by eriknw** [comment]
Great 🚀 !

Yeah, docs should be updated too, but they should be updated in a separate PR. A substantial change (updating docs) shouldn't be buried with the large but simple change in this PR.

And online docs for `_dispatch` shows up now:
https://networkx.org/documentation/latest/reference/generated/networkx.utils.backends._dispatch.html

And also `_dispatchable` in this PR:
https://output.circle-artifacts.com/output/job/966e4ee2-c0bc-455d-ac98-f7ab2343201e/artifacts/0/doc/build/html/reference/generated/networkx.utils.backends._dispatchable.html

**Review by dschult — APPROVED** [review]

**Pull request merged**
