### PR TITLE
Removed prefixes

### PR DESCRIPTION
**Pull request by kpetridis24**
Removed the 'NetworkX' prefix throughout the entire networkx repository.

### CODE REVIEW

**Comment by kpetridis24** [comment]
So if we remove the prefix from NetworkXException, this leaves us with 'Exception(Exception)'. Cyclic definitions are not yet supported by mypy as it seems. How should i resolve this? Should we maybe change the error names (for example XException, XError or smth like this)? Any suggestions are welcome!

**Comment by MridulS** [comment]
@kpetridis24 thanks for this but I am not too sure where we stand on this right now. We should have a look at https://github.com/networkx/networkx/issues/1705 again. If we remove the `NetworkX` prefix does the rest of the exception name still make sense? and mypy correctly complains about the cyclic exceptions.
These changes should also not be made inside the old documentation of releases.

Also reviewing this PR is pretty much impossible in one go and it looks like you have also committed the `venv` folder 😅

**Comment by kpetridis24** [comment]
So what your are suggesting is that we take a look at the names of every error again, and maybe discuss about changing them to be more meaningful, right?

I will fix the rest of what you pointed out!

**Comment by rossbar** [comment]
> We should have a look at https://github.com/networkx/networkx/issues/1705 again

I agree - this needs discussion and an adoption plan before moving forward.

**Comment by rossbar** [comment]
Given the conclusion in #1705 I'm going to go ahead and close this. Thanks for looking at this @kpetridis24 and helping to kickstart the stagnant conversation!

**Pull request closed without merging**
