### PR TITLE
Prim from list to set

### PR DESCRIPTION
**Pull request by Pascal-Ortiz**
Fixes issue #3502. 

Made the lists into sets. Prim and Kruskal implementations have now equivalent time execution.

### CODE REVIEW

**Comment by dschult** [comment]
It looks like this branch has the Floyd-Warshall optimization changes in it too. Can you create a branch starting from the current networkx master branch and just include your last commit?
Thanks!

**Comment by dschult** [comment]
Looks like there is a bug in minimum_spanning_tree that is showing up when the first node in a graph is connected to the rest by an edge with edge-weight NaN.

**Comment by Pascal-Ortiz** [comment]
Hi Dan

You are right, there is a bug using NaN weights with the Prim's algorithm. But the bugs seems unrelated to my pull request and is present in previous version. For instance, with the NetworkX on my machine, the following code:


```python
import networkx as nx

print("NetworkX version:", nx.__version__)

NaN=float("NaN")
    
def bug_NaN():

    edges=[(0,1,NaN),(0,2,4),(1,2,NaN)]
    G=nx.Graph()
    for a,b,w in edges:
        G.add_edge(a,b,weight=w)
    print("kruskal :", nx.minimum_spanning_tree(G, ignore_nan=True, algorithm='kruskal').edges(data=True))        
    print("prim :", nx.minimum_spanning_tree(G, ignore_nan=True, algorithm='prim').edges(data=True))

    print("----------------------")

    edges=[(0,1,NaN),(0,2,NaN),(1,2,4)]
    G=nx.Graph()
    for a,b,w in edges:
        G.add_edge(a,b,weight=w)
    print("kruskal :", nx.minimum_spanning_tree(G, ignore_nan=True, algorithm='kruskal').edges(data=True))        
    print("prim :", nx.minimum_spanning_tree(G, ignore_nan=True, algorithm='prim').edges(data=True))    
    
bug_NaN()
```

generates the output below:


```
NetworkX version: 2.3
kruskal : [(0, 2, {'weight': 4})]
prim : [(0, 2, {'weight': 4}), (1, 2, {'weight': nan})]
----------------------
kruskal : [(1, 2, {'weight': 4})]

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-5873980f2288> in <module>
     23     print("prim :", nx.minimum_spanning_tree(G, ignore_nan=True, algorithm='prim').edges(data=True))
     24 
---> 25 bug_NaN()

<ipython-input-3-5873980f2288> in bug_NaN()
     21         G.add_edge(a,b,weight=w)
     22     print("kruskal :", nx.minimum_spanning_tree(G, ignore_nan=True, algorithm='kruskal').edges(data=True))
---> 23     print("prim :", nx.minimum_spanning_tree(G, ignore_nan=True, algorithm='prim').edges(data=True))
     24 
     25 bug_NaN()

~/.local/lib/python3.6/site-packages/networkx/algorithms/tree/mst.py in minimum_spanning_tree(G, weight, algorithm, ignore_nan)
    546     T.graph.update(G.graph)
    547     T.add_nodes_from(G.nodes.items())
--> 548     T.add_edges_from(edges)
    549     return T
    550 

~/.local/lib/python3.6/site-packages/networkx/classes/graph.py in add_edges_from(self, ebunch_to_add, **attr)
    958         >>> G.add_edges_from([(3, 4), (1, 4)], label='WN2898')
    959         """
--> 960         for e in ebunch_to_add:
    961             ne = len(e)
    962             if ne == 3:

~/.local/lib/python3.6/site-packages/networkx/algorithms/tree/mst.py in prim_mst_edges(G, minimum, weight, keys, data, ignore_nan)
    284             # update frontier
    285             visited.append(v)
--> 286             nodes.remove(v)
    287             if is_multigraph:
    288                 for w, keydict in G.adj[v].items():

ValueError: list.remove(x): x not in list
```

Here, the are two kinds of bugs :

1. Prim and Kruskal algorithms don't return the same result
2. In some cases (as you explained), Kruskal returns a result and Prim raises an exception.

If it could be useful, I can try to spot where the problem comes from.

**Comment by dschult** [comment]
Thanks for that!  I found the error... nodes should discard(v) instead of remove(v) and then we need to check if v is in visited or not in nodes. This is only an issue if there is a node with a single edge with weight NaN.

**Pull request merged**
