### PR TITLE
Developing function to calculate path cost for any user-specified path

### PR DESCRIPTION
**Pull request by DNiquette16**
Hello! 

So I wrote a function called "path_weight" to calculate the cost of a specific path with respect to a specified edge attribute (e.g. cost, weight, distance). I believe I have a function that works properly with graphs as well as multigraphs and throws an error if the path does not exist. However, this is my first time submitting work to a project like this so I would love any feedback as I am sure this is far from being ready to merge. 

Also, this is connected to issue #3357

Thanks!

### CODE REVIEW

**Comment by DNiquette16** [comment]
Hey,

Thanks for all the great feedback!

I believe that I address all of the comments except for the use of the _weight_function(). I had a question about that. If my understanding is correct, I don't believe that single underscore functions are imported by default when using `from module import *`. Do you have any advice on how to approach this one? I have tried to modify the __init__.py in networkx/algorithms/shortest_paths and tried various import statements in networkx/classes/function.py but I haven't been able to import the function. I am sure there is an easy fix to this, I just haven't found it.

Thanks!

**Comment by dschult** [comment]
Good question. The underscore functions usually are not imported if you use ```from shortest_path import *```
But so long as shortest_path has been imported, we can still get the "private" functions by explicitly listing them.
The file at ```networkx/algorithms/shortest_path/astar.py``` provides as example:

```python
from networkx.algorithms.shortest_paths.weighted import _weight_function
```
It's a little convoluted, but it works.

**Comment by dschult** [comment]
I'm not sure why the third Appveyor test is failing to start. Hopefully it will be fixed for your next commit -- don't worry about it.

The loop for ```is_path``` creates a potentially long list. So it might be better to switch to a lower footprint approach, something like (not tested):
```python
for node, nbr in nx.utils.pairwise(path):
    if nbr not in G[node]:
        return False
return True
```

**Comment by DNiquette16** [comment]
Hmm, okay that is kind of the track that I was headed down. However when I import the following at the top of networks/classes/functions.py:
`from networkx.algorithms.shortest_paths.weighted import _weight_function`
And then use it with a dummy test in my path_weight function to see if I can call it:
`x = _weight_function(G,weight)`
I get the following error:
image

However, I didn't make any changes to networkx/algorithms/d_separated.py

That's also a very good point about is_path, I will make that change as well!

**Comment by dschult** [comment]
Looks like this is running into an import order issue where ```function.py``` is imported before enough of the classes are imported that it is too soon to import stuff from ```algorithms```.  Looks like it might be time to move _weight_function into a different module (perhaps utils?)

Let's just implement this with weight being a string (attribute name).  There is another issue #4085 for working toward using _weight_function wherever possible in the package.  That's the place to change its location and we'll update this code as part of that anyway.

**Comment by DNiquette16** [comment]
Okay, thanks for helping me figure out what was going wrong with that import. Definitely sounds like a good idea to make that a separate issue. I just pushed my changes to `is_path()` and I believe I incorporated the rest of the changes that you had mentioned initially. Let me know if there is more to fix and I'll be happy to make more adjustments!

**Comment by jarrodmillman** [comment]
@DNiquette16 This branch has conflicts that need to be resolved.  Also if you haven't already, please run black to format the code:
```
pip install -r requirements/developer.txt 
pre-commit install
```
before making your final commit and black will be run automatically for you.  You can also run it manually:
```
black .
```

If you don't have time to take care of this, no worries.  I will do it before merging your PR later tonight or tomorrow.

Thanks!

PS.  If you haven't already, you may want to look over ``CONTRIBUTING.rst`` (also available here:  https://networkx.github.io/documentation/latest/developer/contribute.html) at some point.

**Pull request merged**
