### PR TITLE
Integration of Ben Edwards' GSoC project 2011 on community detection

### PR DESCRIPTION
**Pull request by Midnighter**
## Incomplete Pull Request

This pull request is incomplete and it's meant to discuss pulling @bjedwards'
GSoC project on community finding and other related code into the main networkx repository.
## General Remark

There have been several discussions on the mailing list showing interest in
replacing the basic Graph data structure with custom ones, e.g., using a
database instead of the dict of dict model. Should we rely on particular class
interfaces, for example, Graph.adjacency_iter or DiGraph.predecessors_iter,
instead of accessing the dictionary structures directly in order to facilitate
other data models?

Direct access of the dictionary structure is extremely
widespread throughout networkx; one could argue that any customized data
structure would have to expose a dictionary-like interface anyway because a
rewrite of networkx is not worth the time and effort.
## Observations
- spectrum.py and laplacian_spectral.py are disorganized and seem to serve
  similar purposes. Can we reorganize it?
- similarly quality.py and community_quality.py isn't all the code community
  related?
## Related Issues

The GSoC project issue #549 (used to be Trac 557), other related issues are an algorithm based on Newman(2006) PNAS #160 (Trac 158),
the Louvain method #239 (same on Trac), and a fast detection algorithm #245
(same on Trac).

### CODE REVIEW

**Comment by MridulS** [comment]
@hagberg @Midnighter @bjedwards What is the current status of this project?

**Comment by harrymvr** [comment]
Just a heads up (particularly for spectrum.py) . The matrices should be handled as scipy.sparse, as in #1021 . Also, the way that linear algebra is coded will be super extra slow.

**Comment by bjedwards** [comment]
@MridulS, About the same as it was 2.5 years ago?

#1035 added some of the community graph generators in December of 2013, but I haven't had much time to work on the other stuff.

@harrymvr initially we were avoiding the scipy.sparse dependency, or at least tried to implement it in such a way that we could use either. I am not sure what the current thoughts requiring scipy.sparse. My thought is if you want to do spectral graph theory, it's probably not unreasonable to assume that you have scipy.sparse installed.

**Comment by Midnighter** [comment]
I don't have a good overview right now but I know I stopped the merging effort back then because there were some spectral functions being written. So those could probably be used.

**Comment by MridulS** [comment]
Went through this PR to see the current status, a lot of code has been merged into NetworkX by new PRs.

Some bits of code that is left over:
networkx/algorithms/community/community_utils.py
- community_performance
- community_coverage

networkx/algorithms/community/divisive.py
- divisive_partition
- edge_betweenness_partition
- edge_current_flow_betweenness_partition


networkx/algorithms/community/laplacian_spectral.py
- spectral_bisection
- simple_directed_laplacian
- lazy_directed_laplacian
- pagerank_directed_laplacian

networkx/algorithms/community/partition.py
- spectral_modularity_partition -> https://github.com/networkx/networkx/pull/1733
- greedy_max_modularity_partition -> https://github.com/networkx/networkx/pull/1733 (this could also be closed as we already have a greedy algorithm for maximum modularity implemented in https://github.com/networkx/networkx/pull/2871)
- recursive_partition

networkx/algorithms/community/random_community.py
- random_partition -> https://github.com/networkx/networkx/pull/1733
- random_p_community
- random_m_community

networkx/algorithms/community/spectrum.py
- stationary_distribution
- lazy_stationary_distribution
- pagerank_stationary_distribution

We don't necessarily have to add all of the other bits of code. I'll go through the remaining bits and open a new PR so we an review it again and get this in NetworkX :)

**Comment by dschult** [comment]
Nice!!   There are a lot of pieces there -- but at least we can make a list now. :}

I believe the `simple/lazy/pagerank_directed_laplacian` are all available now in `directed_laplacian_matrix` with a keyword argument for which version you might want. (looked at that earlier today while reviewing a different PR).  It is not in the community subpackage, but I think is where it should be especially since the proposed laplacian centrality would use it also.

**Comment by MridulS** [comment]
I have updated the [above comment](https://github.com/networkx/networkx/pull/764/#issuecomment-1130147447 ) with the current state and some opinions about some bits that I don't think we should add to networkx today. I am tagging this with a `close ?`. We can continue reviews in other open PRs.

**Comment by Midnighter** [comment]
Blast from the past 😄

**Comment by rossbar** [comment]
+1 for focusing on the separate PRs. For anything that isn't already pulled out, it might be easier to cherry-pick and resubmit that try to wrangle them in this PR. Thanks all!

**Pull request closed without merging**
