### PR TITLE
Drawing arrow heads when drawing digraphs.

### PR DESCRIPTION
**Pull request by emilienkofman**
Fixed the arrow hack when displaying directed graphs (or it's at least a better hack). It might be necessary to get the edge radius to adjust the arrowhead.

### CODE REVIEW

**Comment by hagberg** [comment]
Thanks for the suggestion.  Unfortunately it's hard to get the arrows right. Your approach isn't quite enough.  E.g. with this code 

```python
In [1]: import networkx as nx

In [2]: G = nx.DiGraph()

In [3]: G.add_path([1,2,3])

In [4]: nx.draw(G)
```
you get an interesting but not so pretty drawing
foo

**Comment by emilienkofman** [comment]
Ok. For some reason mine is not so ugly... I may try again to do that properly.

    import matplotlib.pyplot as plt
    import networkx as nx
    G = nx.DiGraph()
    G.add_path([1,2,3])
    nx.draw(G)
    plt.show()


image

**Comment by chebee7i** [comment]
Why isn't the base of the arrowhead perpendicular to the line of the edge connecting the nodes?

**Comment by MridulS** [comment]
@chebee7i I guess it has something to do with pyplot. It gives a weird plot for me too.

**Comment by hagberg** [comment]
Unfortunately, not a general solution for arrow drawing.

**Pull request closed without merging**
