### PR TITLE
Support pydotplus as a (Python 3 compatible) replacement for pydot

### PR DESCRIPTION
**Pull request by pfmoore**
pydotplus is a replacement for pydot that works on Python 3. This PR uses pydotplus if pydot isn't available. Tests pass for me (Python 3.4, Windows 64-bit).

### CODE REVIEW

**Comment by chebee7i** [comment]
There's a number of these Python 3.x `pydot` around. For example, I'm including one in [nxpd](https://github.com/chebee7i/nxpd). Has the community settled on pydotplus as being the "official" replacement? If not, I'd rather wait a bit longer.

**Comment by pfmoore** [comment]
Not that I know of, I just wanted something that worked on Python 3, and a search for pydot brought this up. I just did another search and found nothing else (at least nothing on PyPI that could be installed as a drop-in replacement for pydot, which this is). Honestly, I don't care what replacement is supported, but I think something should be.

I suppose an alternative would be to create a dummy package that wrapped pydotplus as pydot. But that seems like a bit of a hack. I'll probably just do that for now if this PR isn't acceptable.

**Comment by hagberg** [comment]
Also PyGraphviz works with Python3 and provides the same (or pretty similar anyway) functionality.  Windows users often have difficulty installing it though.

**Comment by pfmoore** [comment]
Well, yes. As a Windows user I can confirm, it's non-trivial to install (at least, it didn't work when I tried it). Maybe you could provide binary wheels for Windows on PyPI?

Actually, looking at https://github.com/pygraphviz/pygraphviz/issues/16 it seems that it's not working on Python 3 on Windows yet. Or am I misunderstanding?

**Comment by hagberg** [comment]
Good question.  Maybe it isn't working properly on Windows with Python3.  I have no access to Windows or developer tools so I can't make wheels.  In the past others have done so.

**Comment by pfmoore** [comment]
Maybe I'll take a look at getting PyGraphviz built on Windows. Not sure if I'll have the time, but I can certainly give it a go if I do :-)

**Comment by chebee7i** [comment]
@pfmoore True that there doesn't appear to be anything on PyPI. Here are two others that I know of, which are Python 3 compatible:

https://bitbucket.org/prologic/pydot
https://github.com/nlhepler/pydot

This PR is pretty straightforward, so its not going to be a big maintenance issue if merged. Anyone else want to chime in?

**Comment by pfmoore** [comment]
@chebee7i Yes, I tend not to look for non-PyPI stuff, as it's not easily installable via pip.

Anyway, I created https://pypi.python.org/pypi/nxpydot as a wrapper that makes pydotplus "look like" pydot for the purposes of NetworkX. It wasn't really that hard. So if you prefer to hold off on "blessing" pydotplus, that's fine with me.

**Comment by hagberg** [comment]
FYI - you can install from github and bitbucket with pip https://pip.pypa.io/en/latest/reference/pip_install.html#vcs-support

**Comment by pfmoore** [comment]
@hagberg Yeah, I know. But I'm lazy - remembering a project name is easier than remembering a VCS URL ;-)

BTW, the check for ```dot_parser``` in the tests should be removed regardless - it's unneeded and it means the tests get skipped for https://github.com/nlhepler/pydot (which doesn't provide it).

**Pull request merged**
