### PR TITLE
Add 3.2rc0 release notes

### PR DESCRIPTION
**Pull request by jarrodmillman**
This was generated via:
```
export VERSION=3.2rc0
export PREVIOUS=3.1
export ORG="networkx"
export REPO="networkx"
changelist ${ORG}/${REPO} networkx-${PREVIOUS} main --version ${VERSION}  --out doc/release/release_dev.rst --format rst
```

If we want to change something in the release notes, we should update the relevant GH PR.

### CODE REVIEW

**Review by dschult — COMMENTED** [review]
It looks like we are losing the deprecations section.
Is that intentional? If so, where should people look for deprecations?

**Comment by jarrodmillman** [comment]
We could put it in `API Changes` section. That is what scikit-image does and I think that is what we've been "labeling" them. Does that seem reasonable? We could add a `Deprecation` label and section to changelist. (I personally think it is reasonable to put both API deprecations and API changes in the `API Changes` section. But I don't feel strongly about it.)

I just went through the list and added the `type: API` to these PRS: #6651, #6942, #6908. I haven't run `changelist` again, but when I do it will add entries for those three PRs to the  `API Changes` section. Did I miss anything?

**Comment by jarrodmillman** [comment]
I am going to merge this. This is just for the rc0, so we can fix the release notes when we release 0.22.0. This will let folks test the upcoming release and we can discuss the release notes in the next dev meeting.

**Review by dschult — APPROVED** [review]
Thanks @jarrodmillman !

I think putting the deprecations into the API changes should be good.

I guess this also means that we don't have to put a line into `release_dev.py` when we add a deprecation. So we should update the `CONTRIBUTING.rst` file to tell people where to put comments about API changes and deprecations -- e.g. to make sure the title describes it and the label includes `type: api`. Let's do that after we go through a round of this script so we know all the changes to make.

**Pull request merged**
