### PR TITLE
Length check added to simple_cycles

### PR DESCRIPTION
**Pull request by vakker**
Adding a `max_len` parameter to `simple_cycles` according to #4797 
Johnson's algorithm needs to be checked to see if this interferes with it.

### CODE REVIEW

**Comment by dschult** [comment]
Are you going to check whether this interferes with Johnson's algorithm?

**Comment by vakker** [comment]
So it's been discussed [here](https://github.com/networkx/networkx/discussions/4797) but we haven't really reached a conclusion on how to combine the two.

**Comment by dschult** [comment]
It looks like that discussion ended [here](https://github.com/networkx/networkx/discussions/4797#discussioncomment-740900) with a request that you construct a separate function for the length check version so that it wouldn't affect the runtime of the case `max_len is None`.  Perhaps as a first check that this is true, you could time some graphs with your version and having `max_len=None` and the existing networkx version.  Is there a difference in runtime?

If there is a difference, you could in-line the function call (python can be slow to call functions)
`if nbrs and max_check_len(path):` becomes:
```python
if nbrs and (max_len is None or len(path) < max_len):
```

**Comment by rossbar** [comment]
Gentle ping @vakker have you had a chance to investigate the suggestion above? I suspect that the version without the function call overhead would indeed be more performant, though it'd be interesting to see what the practical effects are (if any).

**Comment by vakker** [comment]
@rossbar sorry for the delay, it didn't really have time to investigate this further. Probably during the holidays or early next year I can wrap this up.

**Comment by vakker** [comment]
@rossbar sorry, I don't have the bandwidth at the moment to further investigate this thoroughly, but if anyone comes along it should be straight forward to pick it up. Maybe @boothby has something to add here?

**Comment by dschult** [comment]
Fixed in #6461  :)

**Pull request closed without merging**
