### PR TITLE
Lexicographic BFS and chordal graph algorithms

### PR DESCRIPTION
**Pull request by willjmax**
This PR includes a linear time, O(|V| + |E|), implementation of lexicographic BFS and uses it as a subroutine for chordal graph algorithms. For a chordal graph, the reverse of a lexicographic BFS order is always a perfect elimination order. The following functions are added to `chordal.py`:

1. `reverse_lexBFS_order(G)`, this function returns a dict containing a reverse lexBFS order of the input graph `G`
2. `is_perfect_elim_order(G, order)`, this function returns a boolean indicating whether or not `order` is a perfect elimination order of `G`
3. `perfect_elim_order(G)`, uses `reverse_lexBFS_order` to compute a perfect elimination order, or raises an exception if `G` is not chordal

In addition, the `is_chordal` function has been rewritten to compute an order with `reverse_lexBFS_order` and determine whether or not it is a perfect elimination order by calling `is_perfect_elim_order`. When `G` is not chordal this implementation is about as efficient as the previous one, however when `G` is chordal it is much faster.

### CODE REVIEW

**Comment by dschult** [comment]
I used to know the specific defn of lexicographic BFS, but I have recalled my innocence. :)
I think it might be that the order of the nodes within each level of the BFS are sorted in a lexicographic order.  If this is true, can we use the `sort_neighbors` feature of the NetworkX bread_first_search functions?

Also, I'm not convinced this should replace the existing method for `is_chordal`. I get that it should work. But the old method worked too. Is there some reference or computation that claims this is a better method for computing `is_chordal`? I'm fine with making this PR just be about the `perfect_elimination_order` stuff -- and having the change to `is_chordal` be considered in a separate PR. The first functions will almost certainly get merged faster that way.

Thanks for this!

**Comment by willjmax** [comment]
The reference for lexicographic BFS is [here](https://doi.org/10.1137/0205021). It's not as simple as using a fixed lexicographic order to set the order at each level. In lexicographic BFS each vertex is initialized with the empty string as a label, and the labels are updated after each iteration. Unless I'm mistaken, it doesn't look like the sort function within the existing BFS implementations can accomplish this.

However, the implementation in this PR doesn't actually computed the labels. Instead it is based on a technique called partition refinement, and is based on the pseudo code given on [Wikipedia](https://en.wikipedia.org/wiki/Lexicographic_breadth-first_search#Algorithm).

I am happy to split this into two separate PRs for `is_chordal`, but here is some justification for its inclusion. I compared my new implementation vs the old one on several graphs and their chordal completions. The new version is substantially faster in the case where `G` is chodal, and roughly the same speed when `G` is not chordal.

| Graph                                             | old implementation    | new implementation    |
|---------------------------------------------------|-----------------------|-----------------------|
| wheel_graph(1000)                                 | 0.5157210826873779s   | 0.012179851531982422s |
| wheel_graph(1000) (chordal completion)            | 0.5563259124755859s   | 0.013802766799926758s |
| erdos_renyi_graph(1000, .25)                      | 0.051645517349243164s | 0.14466261863708496s  |
| erdos_renyi_graph(1000, .25) (chordal completion) | 172.06441378593445s   | 1.8320093154907227s   |
| erdos_renyi_graph(500, .5)                        | 0.04425621032714844s  | 0.08078670501708984s  |
| erdos_renyi_graph(500, .5) (chordal completion)   | 22.637152910232544s   | 0.3413357734680176s   |
| complete_graph(1000)                              | 169.57221913337708s   | 1.4036500453948975    |

**Comment by rossbar** [comment]
> I'm fine with making this PR just be about the perfect_elimination_order stuff -- and having the change to is_chordal be considered in a separate PR. The first functions will almost certainly get merged faster that way.

I second this - I think moving the `is_chordal` changes out of this PR to a followup will help focus the discussion and move this forward!

**Comment by MaxPotters** [comment]
When will this be implemented? I am actually quite keen on using this for an interval graph problem I have. Could this be a `strategy` that is then also available in the `greedy_coloring` algorithm?

**Comment by willjmax** [comment]
I'm working on a new PR to address the comments in this thread. I intend to replace `reverse_lexBFS_order` with a new function `lexicographic_bfs` that will be located in `traversals/breadth_first_search.py`. The new function will also implement a few variants of LexBFS (including the reverse order) that can be used by passing optional arguments. These variants are used as subroutines in some algorithms that I'd like to implement sometime in the future.

**Pull request closed without merging**
