### PR TITLE
Add SPQR tree for finding triconnected components

### PR DESCRIPTION
**Pull request by JamesClough**
As described in #2315 
This addition is reasonably complex and not yet finished but I will push incremental progress to this pull request as I go so that anyone interested in helping can do so, and so that mistakes I make can be seen earlier.
This commit contains just the function to calculate the palm tree of a graph, which is a precursor step for the SPQR tree but is perhaps useful in its own right (or for other algorithms).

### CODE REVIEW

**Comment by jfinkels** [comment]
This sounds similar to the "chain decomposition" I added in pull request #2284; what is the relationship between the chain decomposition and the palm tree? (I've been out of the mindset for a while so I don't remember.) Just trying to avoid duplicating code.

**Comment by JamesClough** [comment]
They do certainly seem similar - I think if you already had the chain decomposition you could find a palm tree more easily. It's probably not worth taking that approach here though since in this case there are other things needed for the SPQR tree which are calculated in the same depth-first-search the palm tree uses.

**Comment by jfinkels** [comment]
Can we extend the chain decomposition function so that it computes the
extra information you need?

**Comment by JamesClough** [comment]
So to merge these would I guess involve having chains.py call `palm_tree` to do its DFS, instead of the `_dfs_cycle_forest` function in chains.py and then ignore the extra information its getting. 
But most of the logic in `palm_tree_dfs` worrying about these other attributes (like the lowpoint1, lowpoint2 functions) - so chains.py would be wasting quite a bit of time doing all of that.
I think that will turn out to be a lot more trouble than its worth. The only repeated code is really just the DFS which is very simple. But to combine everything would make chains.py quite a bit more complicated, especially as I'm trying to stick to the notation used in the algorithm in the paper linked in #2315. So I'd recommend keeping them separate.

As an aside though - is the recommended practice for this kind of function to define the dfs function (like `_dfs_cycle_forest` or  `palm_tree_dfs`) inside the main function that users would call from the outside? Or does it not matter too much?

**Comment by sjackman** [comment]
Here's my poor-man's version of `triconnected_components`, in case anyone else stumbles on this issue.

```python
    def triconnected_components(g):
        "Return the triconnected components of the graph."
        components = []
        for component in nx.biconnected_components(g):
            if len(component) < 3:
                components.append(component)
                continue
            try:
                cuts = next(nx.all_node_cuts(
                    g.subgraph(component),
                    k=2, flow_func=nx.algorithms.flow.shortest_augmenting_path))
                if len(cuts) > 2:
                    components.append(component)
                    continue
                assert len(cuts) == 2
                subcomponents = list(nx.connected_components(g.subgraph(component - cuts)))
                if len(subcomponents) == 1:
                    components.append(component)
                    continue
                components += subcomponents
                components.append(cuts)
            except StopIteration:
                components.append(component)
        return components
```

**Pull request closed without merging**
