### PR TITLE
Update install documentation

### PR DESCRIPTION
**Pull request by MridulS**
Add conda update/conda install to install documentation

### CODE REVIEW

**Comment by MridulS** [comment]
@dschult

**Comment by dschult** [comment]
There's no separation here between pip install and conda install.
If we add this information we need some structure to make it easy to find/follow.

**Comment by MridulS** [comment]
I think we should move this info to README and add more structure to the file. We can take inspiration  from https://github.com/scipy/scipy https://github.com/scikit-learn/scikit-learn https://github.com/sympy/sympy

**Comment by dschult** [comment]
There are currently two headings: ```quick install``` and ```installing from source```. Maybe they should be changed: ```Installing with pip``` then ```Installing with conda``` then ```Installing from source```.

I'm not sure what you mean by take inspiration from...    They seem to have very different approaches. Only the first uses INSTALL.rst.txt, but maybe I'm missing something.  Anyway, this addition is good -- just need some headings/structure.

**Comment by MridulS** [comment]
By inspiration I meant a more detailed README file something more like sympy.

**Pull request merged**
