### PR TITLE
DOC: Add docstrings to filter view functions  

### PR DESCRIPTION
**Pull request by akshayamadhuri**
issue no: #4433

### CODE REVIEW

**Comment by dschult** [comment]
To get the "style" check to pass, click on the associated "Details" link and it will show you what the style programs think you should change. In this case, a space appears starting the doc_string some of the functions.  Similar style "failures" show in the `cores.py` PR as well.

**Review by rossbar — APPROVED** [review]
LGTM, thanks @akshayamadhuri ! I took the liberty of applying `black` and pushed up those changes to get CI passing.

**Comment by akshayamadhuri** [comment]
thanks @rossbar  for the commits

**Comment by MridulS** [comment]
Thanks @akshayamadhuri!

**Pull request merged**
