### PR TITLE
Split communicability_alg to subgraph.py and communicability.py

### PR DESCRIPTION
**Pull request by Michael-E-Rose**
This commit is via #1239:
- Split `communicability_alg.py`, because it wrongly confused subgraph centrality and communicability centrality:
    - Since communicability is not a centrality, the respective part is in `networkx/algorithms`
    - The part on subgraph centrality and communicability betweenness centrality together with the Estrada index forms the new `subgraph.py` in `networkx/algorithms/centrality`
- (Hopefully) all docs updated

### CODE REVIEW

**Comment by dschult** [comment]
You'll need to change the ```__init__.py``` files in both affected directories to load the appropriate modules due to the name change.

**Comment by Michael-E-Rose** [comment]
I knew I forgot something... `init` files updated.

**Comment by hagberg** [comment]
It looks like there is a name issue with the imports of communicability and communicability_exp.  Note that the name of the module and functions should be different to avoid name collisions.  This is why the module was called communicability_alg.py before.

If you haven't already it is a good idea to install python-nose and run the tests on your code (and the whole package) to see that everything is working as expected.  Not sure what your operating system is but 'pip install nose', then run `nosetests -v networkx` in the source treet.

**Comment by Michael-E-Rose** [comment]
Thanks @hagberg, the nosetest was a good hint. The file names wasn't the only issue.

**Comment by hagberg** [comment]
Looks like there are still some issues.  Note that your creation and import of a subgraph.py module collides with an existing module name and causes some errors.  I suggest changing that.

**Comment by Michael-E-Rose** [comment]
Hmm, AppVeyor and Travis CI tests are still failing. But according my local nosetest all is fine. Can it be `test_subgraph.py` in folder tests, which I just discovered (and obviously forget to update/split)?

**Comment by hagberg** [comment]
If you follow the details link in the travis-ci report above you can see the errors.

**Comment by Michael-E-Rose** [comment]
So finally all checks have passed. It was indeed the test files, along with a problem that was already present in the original code. The commit history of this pull request is quite ugly now, I guess...

**Comment by dschult** [comment]
:)  Perseverance!!

You can clan up the commit history using a git feature called "squash"ing the commits. Basically you use ```git rebase -i origin master``` and an editor lists all your commits--you can choose which to squash by switching the first word from "pick" to "squash".  Then when you save the editor reopens and you can combine/edit the commit messages.  When you save the messages, your history has been rewritten! Don't overuse this feature. :)  Since tis rewrites the history you have to use ```git push --force``` to update the branch that the PR is on.

Here's a post [describing the process](http://stackoverflow.com/questions/14534397/squash-all-my-commits-into-one-for-github-pull-request). As always it's possible to create a small test repo to play it with before actually doing it, but so long as you don't push you can mess it all up and then re-clone it.

**Comment by Michael-E-Rose** [comment]
The lengthy commit history is partly the result of three mergers, which I probably handled wrong: Somehow, the previous commit history for my branch got copied. rebaseing is therefore not so easy. Is it maybe easier to delete my fork, close this pull request and start a new one, which works from the very beginning?

**Comment by OrkoHunter** [comment]
@Michael-E-Rose At some point of time, for updating your branch you prefered `merge` instead of `rebase` against master, hence those merge commits got included. I would prefer creating a new branch with the same changes but new commits and a new PR. :)

**Pull request closed without merging**
