### PR TITLE
added extra condition for fancy arrow colors

### PR DESCRIPTION
**Pull request by blokhinnv**
While working with edge colors I found the following problem.

Suppose we have a simple undirected graph with loops. We want to draw it with specified `edge_color` argument as follows:

```python
edges = [(1, 3), (1, 2), (2, 3), (1, 1), (3, 3), (2, 2)]
edge_colors = ['pink', 'cyan', 'black', 'red', 'blue', 'green']
H = nx.Graph()
H.add_edges_from(edges)
nx.draw(H, edgelist=edges, edge_color=edge_colors, with_labels=True)
```
With `networkx` version `2.7.2rc1.dev0` we will have quite a strange result (colors of loops do not match the declared colors):

image

The problem is [this part of ](https://github.com/networkx/networkx/blob/6a0b4faf09ec9d3d40ad93e2ec9b431d6bab5dc4/networkx/drawing/nx_pylab.py#L885) the `draw_networkx_edges`  function where we redefine `edge_pos`. So when we call the function `_draw_networkx_edges_fancy_arrow_patch` we skip both conditions `len(arrow_colors) == len(edge_pos)` and `len(arrow_colors) == 1` and cycle through colors. This wouldn't have been a problem if we hadn't defined colors for those loops but if we do, the result seems to be incorrect.

I suggest to change the function so we get the result like this:
image

### CODE REVIEW

**Comment by rossbar** [comment]
Thanks for this! This behavior was reported in #5106 and it'd be great to have a fix for it. At first glance this looks like a nice solution - I'd like to add some test cases both from the original issue and the discussion in #5106 to evaluate those corner cases. As [I noted in the discussion there](https://github.com/networkx/networkx/issues/5106#issuecomment-1051215243) I think the problem mapping sequences of edge colors to edges extends beyond the self-loop case and was a sticking point for the solutions I tried to come up with. I wonder if we can take the turning-edge-color-into-a-mapping approach and apply it more generally not only to the fancy edges.

**Comment by blokhinnv** [comment]
Thanks for the reply! I'm sorry I didn't find that issue.
Now I see that the problem is kinda trickier than just edge coloring. You're correct that the same problem happens when we pass other arguments. As far as I see, we only have to fix the behaviour for the `style` and `width` arguments.

I thought it would be simplier just to keep these fancy edges indices and then to access the corresponding value if possible. I've checked this both on my example and examples from the issue, for me, it seems to be correct, but who knows. I'll attach some images to demonstrate that.

Example:
```python
g = nx.Graph()
node_pos = {0:(0,0),1:(1,1),2:(0,1)}
g.add_edges_from([(0,0), (0,1), (1,1), (2,2), (2,1)])
print(g.edges())
nx.draw_networkx_labels(g, node_pos)
nx.draw_networkx_edges(g, node_pos, 
                       edge_color=["red", "green", "orange", "blue", "pink"], 
                       width=[5,10,1,50,100])
```
q drawio

```python
import networkx as nx
g = nx.Graph()
node_pos = {0:(0,0),1:(1,1),2:(0,1)}
g.add_edges_from([(0,0), (0,1), (1,1), (2,2), (2,1)])
print(g.edges())
nx.draw_networkx_labels(g, node_pos)
nx.draw_networkx_edges(g, node_pos, 
                       edge_color=["red", "green", "orange", "blue", "pink"], 
                       width=5,
                       style=['--', '-', '--', ':', ':'])
```
q drawio (1)

You also mentioned the problem of mapping colors to edge not only for loops. From my perspective, I don't see any major problems. As you mentioned [here ](https://github.com/networkx/networkx/issues/5106#issuecomment-1051215243) the default edgelist might have a different ordering than a user expects. In my opinion, this wouldn't be a problem if we had a little bit more clear description of the function parameters. 

For example, the description of the `edge_color` parameter says "Can be a single color or a sequence of colors with the same length as edgelist", but the problem is  `edge_color` could be a sequence of any size, actually. If the sequence's length is less than the length of edgelist, colors are cycled, but you can only find this out, if you will look through the code.
So we can highligth those tricky moments in the docs so that it would be clear for users.

**Comment by rossbar** [comment]
> For example, the description of the edge_color parameter says "Can be a single color or a sequence of colors with the same length as edgelist", but the problem is edge_color could be a sequence of any size, actually. If the sequence's length is less than the length of edgelist, colors are cycled, but you can only find this out, if you will look through the code.

It's not only when the attribute lists are different sizes than the edgelist; for example, take a closer look at the pink/blue edges in the [example from your previous comment](https://github.com/networkx/networkx/pull/5407#issuecomment-1078925909) (thanks for testing those BTW!) - notice that the properties of the (2, 2) and (2, 1) edges are swapped (e.g. `(2, 2)` is supposed to be blue, not pink). This is a result of the *ordering* of the edges being different when you call `list(G.edges)` vs. the ordering of the edge list used to create the Graph. Currently, the only way to *guarantee* that you are getting the mapping you expect between edges and their viz attributes (colors, widths, etc.) is to explicitly specify `edgelist` as well.

That's beyond the scope of the issue here though: correcting the handling of the self-loop edge drawing is also important!

**Review by rossbar — APPROVED** [review]
I went ahead and converted the example from the OP into an explicit test of the self-loop color mapping behavior. It's a nice example as the test fails on `main` but passed on this branch, clearly demonstrating that the PR improves the situation for drawing self-loops with undirected graphs.

The changes LGTM, though as always with the `nx_pylab` module, there isn't enough testing to make me very confident that this won't have *some* unintended side effect. I did a visual comparison between the current published gallery and the gallery generated with these changes and didn't notice any glaring differences, so that's a good sign. Given that this fixes an obvious issue with relatively straightforward code that doesn't introduce too much extra complexity I think this should go in. Thanks @blokhinnv !

**Review by jarrodmillman — APPROVED** [review]

**Pull request merged**
