### PR TITLE
Directed laplacian

### PR DESCRIPTION
**Pull request by aweinstein**
I added a function to get the laplacian of a directed graph. It is based on Ben Edwards' code.

### CODE REVIEW

**Comment by antoniopugliese** [comment]
Question:

Shouldn't the directed_laplacian_matrix function be a normalized_directed_laplacian_matrix function?
This function uses the normalized formula
L = I - (\Phi^{1/2} P \Phi^{-1/2} + \Phi^{-1/2} P^T \Phi^{1/2} ) / 2

For a directed_laplacian_matrix the combinatorial (non normalized) formula should be used
L = \Phi - (\Phi P + P^T \Phi) / 2

What do you people think about this modification? I am also new to Github, so sorry if there is another way to have you notice this.

**Comment by jfinkels** [comment]
Hi @antoniopugliese, thanks for contributing. Can you please create a new issue containing your question so that we can track its resolution separately from this pull request? (Feel free to reference this pull request when you create the issue.)

**Comment by aweinstein** [comment]
@antoniopugliese @jfinkels We used the definition given in the paper

Fan Chung (2005). Laplacians and the Cheeger inequality for directed graphs. Annals of Combinatorics, 9(1), 2005 (available here http://www.math.ucsd.edu/~fan/wp/dichee.pdf).

This paper just call it "Laplacian".  I would call a function returning L = \Phi - (\Phi P + P^T \Phi) / 2 `directed_combinatorial_laplacian_matrix`.

**Comment by antoniopugliese** [comment]
@aweinstein @jfinkels 
The paper just calls it "Laplacian", but as you can see the formula has a "L" in math cursive, which is used for the normalized Laplacian. Also, in the documentation of the function is reported that the function returns a normalized matrix.

I like the `directed_combinatorial_laplacian_matrix` name. I used this name in the issue I just created.

**Pull request merged**
