### PR TITLE
use dict comprehensions instead of dict()

### PR DESCRIPTION
**Pull request by SanketDG**
#1640

### CODE REVIEW

**Comment by SanketDG** [comment]
This is good to go, could someone review this?

**Comment by hagberg** [comment]
It's tedious to review because
1) All of the pep-8 changes create diff noise
2) The tests are also changed so everything needs to be inspected more carefully to make sure the tests are still OK

**Comment by SanketDG** [comment]
Oh. I didn't realize that. Should I redo this by closing this and opening a
new one, or just reset back and push new commits again?

There are only changes of dict comprehensions and pep8.

**Comment by OrkoHunter** [comment]
Splitting the commit into two/three, seems to create less noise.

**Comment by SanketDG** [comment]
@dschult is this okay now to be reviewed?

**Comment by MisterSheik** [comment]
Not to make this longer, but looking through other networkx code, I noticed a lot of `dict(zip(`, which almost always unpythonic.  E.g., 

`mapping=dict(zip(range(m+1),range(m+1)))` should be `{x: x for x in range(m + 1)}`
`b=dict(zip(range(0,lena),[0]*lena))` should be `b = {x: 0 for x in range(0, lena)}`
`sc = dict(zip(nodelist,map(float,expA.diagonal())))` should be `sc = {x: float(y) for x, y in zip(nodelist, expA.diagonal()}`
`dict(zip(ordering,range(n)))` should be `{x: i for i, x in enumerate(ordering)}`

etc.

**Comment by SanketDG** [comment]
@MisterSheik thanks. I will update these too, once these commits are dealt with.

**Comment by hagberg** [comment]
It most certainly is pythonic to use dict(). It was the only way to do it before Python 2.7.
So let's not get so hung up on "code cleanup."

**Comment by chebee7i** [comment]
@SanketDG the title says WIP? Is this WIP still?

**Comment by SanketDG** [comment]
@chebee7i I need consent on updating the rest of the codebase where there is `dict(zip(`, as @MisterSheik has pointed out. If those can be set aside for another PR, then this is good to go. If not, then I'll update them here.

**Comment by NeilGirdhar** [comment]
Any luck with this?

**Comment by jfinkels** [comment]
Based on past experience, blanket code style changes are usually not accepted as pull requests. The maintainers have expressed a preference for making small style changes, if necessary, alongside pull requests that fix other issues.

**Comment by NeilGirdhar** [comment]
Fair enough.

**Comment by dschult** [comment]
See #2768   (and #1640)

**Pull request closed without merging**
