### PR TITLE
Doc fixes in iter_refactor branch

### PR DESCRIPTION
**Pull request by MridulS**

### CODE REVIEW

**Comment by dschult** [comment]
Is this waiting for more commits, or ready for review? 
There are a lot of other mentions of lists where it should be iterators.
Basically, the docs need to be read through and updated. 
I can do that, but I don't want to duplicate efforts.

**Comment by MridulS** [comment]
@dschult I'll do it :)

**Comment by MridulS** [comment]
@dschult @hagberg Should we keep both tutorial.rst and tutorial.ipynb https://github.com/networkx/networkx/pull/1663 ? I don't think we can render a ipython notebook in sphinx. We can create a html version of the ipython notebook with nbconvert and probably hack a way to render it in documentation, or we can host it on nbviewer and give a link to it in the documentation and README file. IPython notebooks works on github.

**Comment by dschult** [comment]
My understanding is that ipython and jupyter use ipynb files with nbconvert
to create the sphinx generated documentation for their webpages on
readthedocs. But my evidence is wording like "we can convert this notebook
to restructured text for use with sphinx" on the readthedocs webpage. I
haven't actually looked at the source. I also don't see obvious links to
the notebooks themselves.

Probably worth playing with on a small example to make sure it all works
before diving in to rework more than the tutorial.

**Comment by MridulS** [comment]
@dschult nbconvert works https://github.com/MridulS/networkx/blob/bf7e7fd835fd3bec18a83c4e3c96d8e23fdaea9f/doc/source/tutorial/tutorial1.rst

**Comment by hagberg** [comment]
Could we just use the notebook as the tutorial with it rendered on github?

**Comment by MridulS** [comment]
@hagberg Sure we can do that. We can also add a link to nbviewer, not a lot of work and it looks pretty there.

**Comment by MridulS** [comment]
Should I start porting examples to ipython notebooks?
Can someone review the notebook I made https://github.com/MridulS/networkx/blob/tut/doc/source/tutorial/tutorial1.ipynb ? Its a copy of the already present tutorial.
And what are current issues blocking the merge of iter_refactor branch except documentation?

**Comment by MridulS** [comment]
Should we leave out the .rst versions and just keep the notebooks?

**Comment by hagberg** [comment]
These changes are fine.  More suggestions at #1665.

**Pull request merged**
