### PR TITLE
Initial implementation of weight function wherever edge weight is used

### PR DESCRIPTION
**Pull request by adnanmuttaleb**
Add support for either direct access or computable attributes such as, `weight`, `capacity`, ..etc. For more info check a #4085. This PR is in draft phase.

### CODE REVIEW

**Comment by jarrodmillman** [comment]
We use ``black`` for formatting now:
  https://github.com/psf/black

This means you don't need to manually deal with PEP8 issues anymore---just run black.  You can read more in our contributor guide:  https://networkx.github.io/documentation/latest/developer/contribute.html

**Comment by adnanmuttaleb** [comment]
@jarrodmillman thank you for letting me know.

**Comment by dschult** [comment]
I see the ```local_bridges``` function is using ```weight=None``` to indicate a function that always returns 1, but there's got to be a better way to do that. It does always return 1, but edge attribute lookups are usually inner loop items where performance matters. I'll try to figure out a good way to improve local_bridges to avoid this issue.

Similarly for ```shortest_simple_paths```.  
And I think ```_bidirectional_shortest_path``` just ignores the weight argument so no decorator needed.

Looks like the remaining 2 errors are for ```nx.johnson```.

The title of the PR is "initial implementation".  Is there more to be done? How much of the codebase did you look through to find appropriate functions?  Looking elsewhere can be a different PR.

**Comment by adnanmuttaleb** [comment]
@dschult sorry for being late, but I was really busy, I have changed naming to `edge_attribute` which is much better, since we may create something similar as `node_attribute`, `path_attribute` in the future. Also for the functions that has `None` as default for `weight`  but they expecting `_weight_function` to return function, I changed the default to `"weight"`. Still we have to fix the errors related to `nx.johnson`, and decide what to do if the wrapped attribute (e.g `weight`) does not have a default value (e.g `_dijkstra_multisource`), should I raise an error?.

**Comment by adnanmuttaleb** [comment]
Regarding the `is_weighted` check, can we modify it behavior, so that the `weight` parameter is a function, that should return non `None` for all edges in the graph `G`.  And for any function the works only on weighted graph, we could decorate it as follow:

```
@edge_attribute("weight", default=None)
def johnson(G, weight="weight"):
    ...
```

**Pull request closed without merging**
