### PR TITLE
Activate Appveyor-CI

### LINKED ISSUE #1650: Setting up appveyor
Travis is capable of running tests for Linux, but we also support Windows. So should we use something like https://ci.appveyor.com for testing the package over windows.
@OrkoHunter did this for `networkx-metis`

### PR DESCRIPTION
**Pull request by OrkoHunter**
Fix #1650 

This PR adds necessary files for starting CI based builds over [AppVeyor](https://ci.appveyor.com). AppVeyor helps ensure that the code is *really* OS independent by testing it over a Windows based platform.

### CODE REVIEW

**Comment by OrkoHunter** [comment]
I have AppVeyor activated for my fork. One of the major issue in building occurs while installing NumPy and SciPy ([Build Log](https://ci.appveyor.com/project/OrkoHunter/networkx/build/1.0.17)). I think the best possible solution is to use miniconda as we do over Travis.

**Comment by ysitu** [comment]
For this initial attempt, can we not install NumPy and SciPy?

**Comment by OrkoHunter** [comment]
Yeah sure. We can manage that later.

**Comment by OrkoHunter** [comment]
@chebee7i Everything is set for the AppVeyor. It needs is just to be triggered to run on the PRs.

**Pull request merged**
