### PR TITLE
Port tutorial to ipython notebook

### PR DESCRIPTION
**Pull request by MridulS**
The internal links are broken, I need to fix them

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Will it be available on the readthedocs.org? I don't know about it. However, http://nbviewer.ipython.org/ is good to display these notebooks.

**Comment by MridulS** [comment]
As far as I know, it won't be available on readthedocs.org . But it will be rendered by github and yes nbviewer is a good option to display notebooks

**Comment by MridulS** [comment]
We can add something like this http://nbviewer.ipython.org/github/MridulS/networkx/blob/tut/doc/source/tutorial/tutorial.ipynb to the README.md file

**Comment by SanketDG** [comment]
@MridulS 
We could use [nbconvert](http://ipython.org/ipython-doc/1/interactive/nbconvert.html) if having this on readthedocs is preferrable. But that could be overkill.

Also, probably remove all the Sphinx reference stuff for method and class references and add some links to external stuff(like `see Matplotlib FAQ`)

**Comment by MridulS** [comment]
@SanketDG Yeah will do that

**Comment by hagberg** [comment]
I'm not sure what the best practice is here.  But I like the idea of the tutorial be a notebook only.  That way it can be downloaded by new users to get started.  One approach would be to put it in it's own repository and remove it completely from the source code repository.  Opinions?

**Comment by MridulS** [comment]
I think hosting a separate repo for tutorial and examples sounds like good plan.

**Comment by dschult** [comment]
I'm fine either way -- what are the advantages of a separate repository over a separate directory as the examples are now?

**Comment by hagberg** [comment]
Here are some possible advantages:
 - not tied to any release schedule, continuous updating and evolving
 - separate issues and  pull requests from the source repository
 - simpler and more obvious naming so easier to find and navigate
 - slightly smaller source code repository for networkx 

I am hoping we can collect many notebooks with examples.

Are there disadvantages?

**Comment by Midnighter** [comment]
You can always pull in the tutorial repository using git subtree or sub-module if you're worried it will be missed otherwise. I think it's an excellent idea because it also makes contributing much less daunting than working with the main repository.

**Comment by dschult** [comment]
Sounds like a lot of good reasons to put them in separate repositories.

**Comment by MridulS** [comment]
I will add this and examples to https://github.com/MridulS/nx-examples

**Pull request closed without merging**
