### PR TITLE
Update clique.py enqumerate_all_clique with min_length

### PR DESCRIPTION
**Pull request by arunmathaisk**

### CODE REVIEW

**Comment by dschult** [comment]
But the current code is a generator, so it shouldn't take much time (over the suggested code) to use:
```python
(c for c in enumerate_all_cliques(G) if len(c) >= min_length)
```

**Comment by arunmathaisk** [comment]
> But the current code is a generator, so it shouldn't take much time (over the suggested code) to use:
> 
> ```python
> (c for c in enumerate_all_cliques(G) if len(c) >= min_length)
> ```

Absolutely, I get your point.
But don't you think it would be a nice extra filter option to have in the function itself 😬 ?

**Comment by rossbar** [comment]
> But don't you think it would be a nice extra filter option to have in the function itself

IMO it's much nicer to leverage Python's language features (i.e. comprehensions), which allow this to be expressed in an extremely clear, concise way that will be immediately understandable to anyone who knows Python. Adding a new kwarg loses this advanatage. Of course, everything's a tradeoff - if there were a significant performance gain (say >2x) from doing so, then it'd be more compelling. Absent that though, I'd be -1 on adding the kwarg.

I would however be +1 on adding an example to the docstring demonstrating the filtering!

**Comment by arunmathaisk** [comment]
> > But don't you think it would be a nice extra filter option to have in the function itself
> 
> IMO it's much nicer to leverage Python's language features (i.e. comprehensions), which allow this to be expressed in an extremely clear, concise way that will be immediately understandable to anyone who knows Python. Adding a new kwarg loses this advanatage. Of course, everything's a tradeoff - if there were a significant performance gain (say >2x) from doing so, then it'd be more compelling. Absent that though, I'd be -1 on adding the kwarg.
> 
> I would however be +1 on adding an example to the docstring demonstrating the filtering!

Hey yes, you are right ! :)

**Review by rossbar — COMMENTED** [review]
The consensus here seems to be -1 on adding the keyword, but +1 for adding the example to the docstring. @arunmathaisk if you want to take a stab at updating the docstring, feel free to do so in this PR. Otherwise we can close this and tackle that in a separate PR!

**Comment by arunmathaisk** [comment]
> The consensus here seems to be -1 on adding the keyword, but +1 for adding the example to the docstring. @arunmathaisk if you want to take a stab at updating the docstring, feel free to do so in this PR. Otherwise we can close this and tackle that in a separate PR!

hey sure, will do :)

**Comment by rossbar** [comment]
I'll go ahead and close this one here - @arunmathaisk if you'd like to update the docstring examples please feel free to do so by opening a new PR! That will make the discussion more clear anyways (and it can always link back to the discussion here)

**Pull request closed without merging**
