### PR TITLE
DOC: geospatial example using lines

### PR DESCRIPTION
**Pull request by martinfleis**
Adding geospatial example illustrating conversion of line-based geometry data (any file format via GeoPandas) to primal and dual graphs (in street network analysis jargon) using momepy and PySAL.

This should replace `plot_lines.py` @ljwolf has in #4366.

cc @NicolasCadieux (xref #4323)

### CODE REVIEW

**Comment by jarrodmillman** [comment]
@martinfleis I am not sure what the error means, but I am getting the same error on my laptop
```
Traceback (most recent call last):
  File "plot_lines.py", line 76, in <module>
    add_basemap(facet, crs=streets.crs)
  File "/home/jarrod/.venv/nx/lib64/python3.8/site-packages/contextily/plotting.py", line 139, in add_basemap
    left, right, bottom, top = _reproj_bb(
  File "/home/jarrod/.venv/nx/lib64/python3.8/site-packages/contextily/plotting.py", line 225, in _reproj_bb
    n_l, n_b, n_r, n_t = transform_bounds(s_crs, t_crs, left, bottom, right, top)
  File "/home/jarrod/.venv/nx/lib64/python3.8/site-packages/rasterio/warp.py", line 176, in transform_bounds
    xs, ys = transform(src_crs, dst_crs, in_xs, in_ys)
  File "/home/jarrod/.venv/nx/lib64/python3.8/site-packages/rasterio/env.py", line 385, in wrapper
    return f(*args, **kwds)
  File "/home/jarrod/.venv/nx/lib64/python3.8/site-packages/rasterio/warp.py", line 61, in transform
    return _transform(src_crs, dst_crs, xs, ys, zs)
  File "rasterio/_base.pyx", line 1302, in rasterio._base._transform
  File "rasterio/_base.pyx", line 1366, in rasterio._base._osr_from_crs
rasterio.errors.CRSError: Invalid CRS: CRS.from_wkt('PROJCRS["WGS 84 / Pseudo-Mercator",BASEGEOGCRS["WGS 84",DATUM["World Geodetic System 1984",ELLIPSOID["WGS 84",6378137,298.257223563,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4326]],CONVERSION["Popular Visualisation Pseudo-Mercator",METHOD["Popular Visualisation Pseudo Mercator",ID["EPSG",1024]],PARAMETER["Latitude of natural origin",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8801]],PARAMETER["Longitude of natural origin",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8802]],PARAMETER["False easting",0,LENGTHUNIT["metre",1],ID["EPSG",8806]],PARAMETER["False northing",0,LENGTHUNIT["metre",1],ID["EPSG",8807]]],CS["Cartesian",2],AXIS["easting (X)",east,ORDER[1],LENGTHUNIT["metre",1]],AXIS["northing (Y)",north,ORDER[2],LENGTHUNIT["metre",1]],USAGE[SCOPE["Web mapping and visualisation."],AREA["World between 85.06°S and 85.06°N."],BBOX[-85.06,-180,85.06,180]],ID["EPSG",3857]]')
```
as the CI is.

**Comment by jarrodmillman** [comment]
I fixed some typos: https://github.com/martinfleis/networkx/pull/1

**Comment by martinfleis** [comment]
@jarrodmillman thanks! Merged in.

**Review by rossbar — APPROVED** [review]
Thanks for this @martinfleis , this looks like a really nice example!

Since this example has more narrative text, I suggest using `sphinx-gallery`'s rST embedding feature. Basically, adding the `# %%` lines at certain locations turns the comments immediately under that marker into rST and intersperses the text (and generated figures) with the code in the rendered html. I thought that might be nice given that there are really multiple different sub-examples in the same file here. I added the rST blocks in such a way that I thought fit the narrative well, but please feel free to adjust as you see fit.

Just a suggestion though, otherwise this LGTM!

**Review by jarrodmillman — APPROVED** [review]

**Pull request merged**
