### PR TITLE
Make all_pairs_dijkstra_path return an iterator

### PR DESCRIPTION
**Pull request by MridulS**

### CODE REVIEW

**Comment by dschult** [comment]
Is single_source_dijkstra_path going to become an iterator? If not, I think this all_pair_... version is ready to go. If single_source_dijkstra_path will be an iterator, maybe we should think more about how to package the iterator of iterators objects like this one.

**Comment by MridulS** [comment]
@dschult Yes, I think `single_source_dijkstra_path` should return an iterator but to make it return iterator in a neat way we have to reimplement `_dijsktra` in an iterator friendly way . `single_source_dijkstra_path` depends on `single_source_dijkstra` which returns two dictionaries (which I think is not an iterator friendly return value).

I guess a solution is to just change return value of `single_source_dijkstra_path` to iterator using `iter()`. Yes, this kills the whole point but at least it consistency is maintained.

Pleas have a look https://github.com/networkx/networkx/pull/1893 :)

**Comment by dschult** [comment]
I think the right approach here is (unfortunately) not the easy one. We need to go all the way down past ```single_source_dijkstra``` to ```_dijsktra``` and make that an iterator.  

Changing all the top-level routines to use iterators puts the facade of iterators in front of a non-iterator. We get all the pain of dealing with an iterator without the benefits.  In my opinion iterators are a pain to work with (--I want the whole list now--) so the reason I want iterators is to get the benefits of iterators (delay computation I might not need and shrink memory usage). 

That's going to require digging into the guts of the method.  Once the guts are re-configured we can hopefully build the top-level stuff in a natural way. :)

The point where yielding should take place is when ```v``` comes off the fringe. Look for ```dist[v]=d```. Before that line the distance, path and pred might change, but once v comes off the fringe all three are known. What we yield will depend on what was requested in a similar fashion to how the code is currently built. More on that in the next comment.

**Comment by dschult** [comment]
I think the ```_dijkstra``` workhorse should just yield ```(node, dist, pred)``` for each node as it is removed from the fringe. Then the individual routines can use the data as needed to build paths or whatever. e.g.

For ```single_source_dijsktra_path_length``` we strip the 3rd quantity ```return ( (n,d) for (n,d,p) in _dijkstra(...) )```

For ```single_source_dijkstra_path``` we have to build the paths

    paths = {source: [source]}
    for (n, d, p) in _dijkstra(...):
        # p holds a list of predecessors, empty list if n==source
        pred = p[:1]   # p[:1] is a list of one entry or [] if n==source
        paths[n] = paths[pred]+[n]
        yield (n, paths[n])

It looks like most of the functions in this module will become iterators instead of returning dicts. I would say that any routines that return two dicts like (dist, paths) each keyed by node ought be changed to ```yield (n, dist, path)``` 3-tuples. But I could be persuaded otherwise if people prefer something else.

**Comment by dschult** [comment]
Also see #1851 ...  looks like we need dijkstra_path_length to call _dijkstra directly and also the whole business with returning pred and paths, etc is not needed.

Bottom line... let's focus on getting _dijkstra right and then build out from there. It'll be an iterator of ```(node, dist, pred)```. We can build the rest from that.

**Pull request closed without merging**
