### PR TITLE
Prufer with linear complexity

### PR DESCRIPTION
**Pull request by Pascal-Ortiz**
This pull request solves the issue #3521. The new implementation has linear complexity and his based on the paper [Linear-time Algorithms for Encoding Trees as Sequences of Node Labels](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.70.5052&rank=1). 

Time execution has been tested. Some results for a tree with 50,000 vertices:

| Functions | Previous implementation | New implementation |
| :---:         | :---      | :---      |
| `to_prufer_sequence`  |  44.30s    |   0.29s       |
| `from_prufer_sequence`  |   83.65s    |   0.21s       |

### CODE REVIEW

**Comment by Pascal-Ortiz** [comment]
Hi 
I notice that all my pull requests always reference my previous pull requests, don't know how undesirable it is.  How do I avoid this without cloning again and again the NetworkX repository? 

Every time i make a PR, I upgrade the initial fork I done for my first PR with the following command:

`git pull upstream master`

**Comment by dschult** [comment]
Can you rebase to remove the Floyd-wasserman optimization stuff? that's a different PR.

**Comment by dschult** [comment]
When you pull from master it gets new commits added to the upstream master. But it doesn't get rid of any commits you have made locally. That means if your local branch has commits from previous pull requests they will still be there.

To start a new branch for a PR, use:

    git checkout master   # switches you to the local master branch 
    git pull upstream master   # update to latest upstream commits
    git checkout -b new-pull-request   # create (and switch to) a new branch based on local master

**Comment by Pascal-Ortiz** [comment]
OK, thanks for the explanantions, I will try this for the next PR.

**Comment by Pascal-Ortiz** [comment]
> Can you rebase to remove the Floyd-wasserman optimization stuff? that's a different PR.

As a git beginner, seems complicated for me to rebase. Could you provide the git command please (I suppose the command begins with `git rebase` but don't know how to provide the arguments) or more explanations? is there an easier alternative to rebase?

**Comment by dschult** [comment]
The commands are something like what follows. If you do this on a local clone of your github repository and it gets messed up you can just delete it, re-clone and change to the right branch and try again. It will only affect your github repository if you push the changes. If you've got other stuff un-pushed in your local repository you can make a new one cloned from github and start "fresh".

Navigate to your ```prufer-with-linear-complexity``` branch. I'm assuming you have a branch named ```master``` with the networkx commits pulled from upstream.

    git rebase -i HEAD~10     # start an interactive(-i) rebase from 10 commits before current commit.

I put the number 10 in this example, because I counted 10 commits on the pull request page. The idea is to start the rebase from when this branch deviated from the master branch. There may be other (better) ways of doing this that I don't know about, such as replacing "HEAD~10" with "master". But I'm not a git expert. This is just the way I know how to do it.

The result is an editor with a page like a commit message only at the top it lists all 10 commits between the start of the rebase and the current commit. Instructions appear below that. Basically you want to "drop" the commits that you don't want in the pull request; and you want to "pick" the commits you want to keep.  You've got a couple of commits which merge master into this branch. I'm not sure how to handle those, but if they were easy merges to make, it's probably best to drop them too. So long as they don't make changes to the code you change in your latest commit the pull request will be OK (I think)

After you save quit from that editor, git will attempt to complete the changes you indicated and then if it detects a confusing action, stops at that point and has you correct and then ```git rebase --continue``` (or something similar to that -- it tells you the command you need to use to continue). If it doesn't find any conflicts it opens an editor asking you to create/edit a commit message and then commit the changes. That completes the rebase and hopefully the difference between your branch and the master is only the commits you "pick"ed.

**Comment by dschult** [comment]
See #3535

**Pull request closed without merging**
