### PR TITLE
Lazy load top-level namespace

### PR DESCRIPTION
**Pull request by stefanv**
@dschult This removes the vendored version of `lazy_loader` in preference of the package.

I can also refactor deeper levels of imports, but I thought I'd get some feedback first.

### CODE REVIEW

**Comment by stefanv** [comment]
One thing I noticed is that networkx has an *insanely* large root namespace. Perhaps we can start by hiding everything but the Graph classes and subpackages via `__dir__`, and start directing users to, e.g., `nx.linalg.*` instead of `nx.*`?

**Comment by dschult** [comment]
I'm not sure I understand this change completely.
It looks like a stub file is added... But I'm not sure what it's purpose is for lazy-loading. 
Does the lazy-loader package use stub files to identify subpackages to import?

The next thing I don't recall/understand is how the namespace structure of the library affects the lazy-loading. Are we trying to lazy-load everything in the library? Or only the subpackages? Or only the external dependencies? What's the goal and what's our strategy?

Hiding the networkx functions from the top namespace is a pretty big change. Every user will have to learn the directory structure of NetworkX in order to use it. In that sense it reduces the usability of the library. Additionally, if the directory structure is to be learned by the users, we better make it worth learning. The current structure was designed for ease of developers, not users. 

Are there positive tradeoffs to deepening the namespace which offset these concerns? (Other than making the lazy-loading easier to configure?)

**Comment by stefanv** [comment]
> I'm not sure I understand this change completely. It looks like a stub file is added... But I'm not sure what it's purpose is for lazy-loading. Does the lazy-loader package use stub files to identify subpackages to import?

The stub file is (a) an easier way to specify imports (more similar to existing `__init__.py` and (b) allows checkers like pyright to correct infer module structure (which it can't with the classic `lazy_loader.attach` mechanism).

> The next thing I don't recall/understand is how the namespace structure of the library affects the lazy-loading. Are we trying to lazy-load everything in the library? Or only the subpackages? Or only the external dependencies? What's the goal and what's our strategy?

The root namespace is enormous, so I'm simply lazy loading everything directly under `nx`. We could choose only to lazy load the 100+ submodules, I suppose, but not sure that would be any easier, or have any added benefit.

> Hiding the networkx functions from the top namespace is a pretty big change. Every user will have to learn the directory structure of NetworkX in order to use it. In that sense it reduces the usability of the library. Additionally, if the directory structure is to be learned by the users, we better make it worth learning. The current structure was designed for ease of developers, not users.

I agree it is a big change, but right now it is impossible to find anything in `nx` with inspection. NumPy is well known as an egregious "way too big of a root namespace" offender, and it only has ~600 members compared to nx's 800+. There is no sensible structure to the root namespace, and therefore users have to read the manual to figure out what function names are.

It makes sense that the current sub-package namespace is perhaps not ideal for users, but perhaps we should design it so it is for nx 4.0?

> Are there positive tradeoffs to deepening the namespace which offset these concerns? (Other than making the lazy-loading easier to configure?)

It doesn't make lazy loading easier to configure.  But I think there's a massive usability improvement for users when functions are organized so you can find them.  I think skimage is not a bad example. This is `dir(skimage)`:

```
['__version__',
 'color',
 'data',
 'draw',
 'exposure',
 'feature',
 'filters',
 'future',
 'graph',
 'io',
 'measure',
 'metrics',
 'morphology',
 'registration',
 'restoration',
 'segmentation',
 'transform',
 'util']
```

**Comment by stefanv** [comment]
I suppose one conclusion may be that there *is* no sensible way to arrange the API into smaller namespaces, and that a flat namespace is indeed the best user experience. That'd be fine, but then I think we should consistently use the flat namespace throughout. Right now, functions are sometimes call via submodules, sometimes from the root namespace.

**Comment by dschult** [comment]
Yeah -- it's rather confusing and a little annoying that some of the functions require being called via the subpackages/sub modules and others don't.  I can understand why it is that way for e.g. `bipartite` functions where the names can be the same -- just a bipartite version. But even with that case, we could easily make sure the names don't collide to enable a flat namespace, or we could make a tree of namespaces for all functions.  What is a good criteria for when to subdivide a namespace?

You example of skimage and the 18 subpackages is helpful for me with this discussion. It clarified for me that you are looking to be able to get the function quickly via `dir` and presumably tab-completion. It also helps me see my problem with using such a system: If I want to find `circle_perimeter`, I don't have an easy way to find that function in skimage using `dir` or tab-completion. I would have to search each subpackage's namespace and presumably there are subpackages of those subpackages. The names of the subpackages are not sufficiently revealing for me as a novice user to know where to go. With a flat namespace, I can hit tab, get 900 options, type `circl` and probably get only 5 options and pick the one I want.

Of course, that's assuming I know the name -- and I found that from a google search to the docs so probably on the documentation page it says which subpackage that function is in.

In any case, as far as I know, no one has looked at the namespace/package/subpackage organization of NetworkX in a long while. That's perhaps a testament to Aric's good design choices, and probably also to a lack of attention/maintenance. It's certainly reasonable to open that can of worms for a discussion. :)

**Comment by stefanv** [comment]
> Of course, that's assuming I know the name -- and I found that from a google search to the docs so probably on the documentation page it says which subpackage that function is in.

This is the crux of it, and what made me realize that the namespace organization is not that important: users have to write code with the API reference open in another window anyway.

> In any case, as far as I know, no one has looked at the namespace/package/subpackage organization of NetworkX in a long while. That's perhaps a testament to Aric's good design choices, and probably also to a lack of attention/maintenance. It's certainly reasonable to open that can of worms for a discussion. :)

I'd be happy to help think about this more (NetworkX 3000!). Meanwhile, in this PR I've tried to change as little as possible. Let me know which direction you'd like me to take it.

**Comment by stefanv** [comment]
Here's the diff between `__all__` before and `__all__` now:

```
{'__annotations__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'adjacency',
 'all',
 'astar',
 'attracting',
 'beamsearch',
 'betweenness',
 'betweenness_subset',
 'biconnected',
 'binary',
 'breadth_first_search',
 'closeness',
 'connected',
 'correlation',
 'current_flow_betweenness',
 'current_flow_betweenness_subset',
 'current_flow_closeness',
 'cytoscape',
 'degree_alg',
 'dense',
 'depth_first_search',
 'edgebfs',
 'edgedfs',
 'eigenvector',
 'exception',
 'flow_matrix',
 'generic',
 'group',
 'harmonic',
 'hits_alg',
 'katz',
 'lazy_imports',
 'load',
 'mixing',
 'neighbor_degree',
 'node_link',
 'pagerank_alg',
 'pairs',
 'percolation',
 'product',
 'reaching',
 'second_order',
 'semiconnected',
 'strongly_connected',
 'subgraph_alg',
 'triads',
 'trophic',
 'unary',
 'unweighted',
 'vf2pp_all_isomorphisms',
 'voterank_alg',
 'weakly_connected'}
```

The test suite passes, but should any of these modules be included?

**Comment by dschult** [comment]
I think all of those modules can safely be removed. If someone wants a module from a subpackage they should be able to specify the subpackage and the module. That at least reduces the top level from "all functions and all modules/subpackages throughout the entire code tree" to "all functions and the primary subpackages". I did not check whether there were more that could be removed. I only looked at the listed ones being removed. It looks good to me.

**Comment by dschult** [comment]
The impact of this change for developers reviewing PRs is that new functions or modules will need to be added to `networkx/__init__.pyi` as well as (`<whatever subpackage>/__init__.py` or an `__all__` from a module that is imported).
Is that the only change in how to make a new function for networkx?

Should we add something to `CONTRIBUTING.rst` about how the import system works? We don't have anything there that I could find at the moment.  But this will make it non-standard -- whatever that means -- and  maybe a description is helpful.   :)

**Review by jarrodmillman — CHANGES_REQUESTED** [review]
LGTM with two minor additions:

1. Update the release notes:
https://github.com/networkx/networkx/blob/main/doc/release/release_dev.rst
2. Update the CONTRIBUTING guide:
https://github.com/networkx/networkx/blob/main/CONTRIBUTING.rst

Longer term, it would be great if we could automate the updates with @Erotemic's mkinit tool:
https://github.com/Erotemic/mkinit

**Comment by stefanv** [comment]
I've just done a speed comparison between this branch and main, and while the import time is about double, it is extremely short (0.03 vs 0.06s).  I think this is because nx is careful never to import libraries like SciPy outside of functions!

So, that leaves me wondering whether this lazy loader is the right fit for NetworkX.

**Comment by Erotemic** [comment]
While not the most important, a 300 vs 600 milliseconds seems like a non-trivial difference if a system is calling a small python program very often.

**Comment by stefanv** [comment]
30 vs 60ms ;)

**Comment by rossbar** [comment]
FWIW I see a much more significant difference in import time: ~270 ms on `main` vs. ~12 ms on this branch. This is using `python -X importtime -c "import networkx"`.

Note that there is a significant difference between the *first* time networkx is imported vs. subsequent times due to caching. Try a `git clean -xdf` prior to testing the import time and you will likely see a factor of 3-4x increase in the import time for the current importing scheme.

**Comment by rossbar** [comment]
> The test suite passes, but should any of these modules be included?

The dunders aren't really excluded, right? In other words, users should still have access to e.g. `nx.__version__`? AFAICT this still works, though tab completion no longer works for the dunders - it'd be nice to recover that.

**Comment by stefanv** [comment]
I added back `__version__`. Any others we need to be explicitly listed?

**Pull request closed without merging**
