### PR TITLE
Enumerate all topological sorts of a digraph

### PR DESCRIPTION
**Pull request by aweltsch**
Issue #2720 
Implementation of an enumeration algorithm for topological sorts. Based on https://doi.org/10.1016/0020-0190(74)90001-5

### CODE REVIEW

**Comment by aweltsch** [comment]
I felt like I checked everything, but I just saw that I remoevd 2 lines from dag.py
Should I add one of the ugly "Fix flake8 formatting"-commits, or is there another way now that I have already published these changes in my repo?

**Comment by dschult** [comment]
You should just change them back and make another commit with those changes.  It is true that this makes more total commits -- and there are ways to "squash commits" together if you want to search for that -- but it undoes what you already did as if nothing happened. And when github merges it squashes all your commits by default anyway -- so the long term history is just one commit for the entire PR.

Other items of note:
- Check the PEP8 style of your changes (perhaps using the convenient program pep8 available as 
  ```pip install pep8```) 
- Line 342: ```q = current_sort[-1]``` and the next line . ---  Isn't this just ```q=current_sort.pop()```?
- Line 380:   isn't that just an ```append```?
- Add space after the first line of the docstring. The first line gets used as a short description and the rest should appear as a paragraph, but separated from the first line with a blank line
- Probably good to add an example to the doc_string.

:)

**Comment by aweltsch** [comment]
I readded the lines and improved the docstring alittle.
concerning lines 342 and 380 (now 357 and 395): This is neither a `pop` nor `append`, as both `pop` and `append` change `current_sort` in-place. We do not want this, because we yield current sort.
Actually it might make more sense to return immutable tuples instead of a list, this would make it possible to apply use `pop`/`append`. Either way, it makes sens to include a comment to explain this issue. The way it's done now, does not seem to be obvious.

**Comment by dschult** [comment]
You could ```yield list(current_sort)``` to make/yield a copy of the list. 
That clarifies the separation of the list in the algorithm from the lists that have been released.
tuple would work too of course.

Does this algorithm work for MultiGraph? We should either have a not_implemented_for, or include tests to ensure it does what we expect.

**Comment by aweltsch** [comment]
Ok, I changed the code to yield a copy of the list.
I adjusted the code to work for multigraphs, by iterating over all out_edges of a node to decrease the degrees correctly when "removing" the node from the graph.

**Comment by dschult** [comment]
This looks good to me.  Anything else before I merge?

**Comment by aweltsch** [comment]
I have nothing else, I'd say it's finished.
Thanks for reviewing :+1:

**Comment by dschult** [comment]
Thanks for submitting!!! :)

**Pull request merged**
