### PR TITLE
Gallery example: composite plot

### PR DESCRIPTION
**Pull request by sharwinbobde**
The following code is intended to address issue number #4623 

Draw a composite plot on matplotlib showing the distribution of nodes' features and the network topology at the same time.

This can be useful when you have a dataset with feature information for different items and some links between different
items.

### CODE REVIEW

**Comment by sharwinbobde** [comment]
image
Here is the resulting plot so that you don't have to run it to see the output :)

**Comment by rossbar** [comment]
Note that if you place the example in one of the existing directories, e.g. `examples/drawing/plot_composite_feature_network.py`, it will be built automatically by CI and can be previewed via the build artifact link in CI summary (you may have to click "Show all checks" to see it).

**Comment by sharwinbobde** [comment]
thnx @rossbar :)
moved it to the `drawing` directory.

**Comment by MridulS** [comment]
@sharwinbobde is this ready to be reviewed? It's still in "Draft" mode :)

**Pull request closed without merging**
