### PR TITLE
Add shortest_simple_paths function.

### PR DESCRIPTION
**Pull request by jtorrents**
This function is based on Yen's algorithm for finding k shortest paths.
It generates all simple paths between source and target starting from
the shortest one. See #762 and #793 for prior work on this and discussion.

This implementation is based on Andrey's work on #762. It generalizes his
approach there to the weighted case, as in Greg's implementation posted
on #793.

Regarding the discussion on #762 about how to do the filtering of nodes
and edges efficiently, this PR adds private modifications of the functions
`bidirectional_shortest_path` and `bidirectional_dijkstra` (that accept
containers with nodes and edges to exclude during the SP search) for its
exclusive use.

This still needs work, especially on documentation and tests. I'm pushing
it so we can have the discussion with the code available.

One thing to discuss is whether or not to include an one liner function
to get the k shortest paths. Could be something like this:

```python
from itertools import islice
def k_shortest_paths(G, source, target, k, weight=None):
        return list(islice(nx.shortest_simple_paths(G, source, target, weight=weight), k))
```

I think that, given that `all_simple_paths` is way faster in computing
all paths, the principal use of `shortest_simple_paths` will be to get
the k best/shortest paths. So it will be a more user friendly interface
if we add it. However, we could also add this function as example in the
`shortest_simple_paths` docstring. I'm ok either way. Thoughts?

### CODE REVIEW

**Comment by jtorrents** [comment]
Some benchmarks of this function against `all_simple_paths` and @Wind4Greg implementation (which also cares about capacity of the edges, so it's doing more work). Note that `shortest_simple_paths` supports both weighted and unweighed, `all_simple_paths` only unweighted, and @Wind4Greg implementation also works for both cases but it always uses Dijkstra's algorithm; `shortest_simple_paths` uses a simple bidirectional BFS for the unweighted case.

Note that because the number of simple paths in graphs gets very big very quickly when increasing the number of nodes and edges we can only test for very small graphs.

```
In [31]: G = nx.complete_graph(5)

In [32]: weight = {(u, v): random.random() for (u, v) in G.edges()}

In [33]: nx.set_edge_attributes(G, 'weight', weight)

In [34]: # This is necessary to test Greg's code

In [35]: nx.set_edge_attributes(G, 'capacity', {k:10*v for k, v in weight.items()})

In [36]: %timeit list(YenKShortestPaths(G, 0, 3))
100 loops, best of 3: 4.06 ms per loop

In [38]: %timeit list(nx.shortest_simple_paths(G, 0, 3, weight='weight'))
1000 loops, best of 3: 683 µs per loop

In [39]: %timeit list(nx.shortest_simple_paths(G, 0, 3))
1000 loops, best of 3: 395 µs per loop

In [40]: %timeit list(nx.all_simple_paths(G, 0, 3))
10000 loops, best of 3: 22.1 µs per loop
```

**Comment by jtorrents** [comment]
@aparamon Do you think that the asserts in `shorest_simple_paths` are worth keeping? I was about to remove them, but I thought it was better to ask first.

**Comment by aparamon** [comment]
2015-04-08 6:00 GMT+03:00 Jordi Torrents <notifications@github.com>:

> @aparamon <https://github.com/aparamon> Do you think that the asserts in
> shorest_simple_paths are worth keeping? I was about to remove them, but I
> thought it was better to ask first.
>
I think it's safe to remove them. I've used the implementation for quite
some years by this time and didn't hit it.

Best wishes,
Andrey Paramonov

**Comment by Wind4Greg** [comment]
This sounds very good.  Andrey performance numbers are impressive!
Cheers
Greg B.

**Comment by jtorrents** [comment]
This last commit removes the asserts, fixes the inability to use an arbitrary edge attribute as a weight, and speeds it up by computing separately the length/cost of the root and then adding it to the newly found partial path instead of computing the length/cost of the whole path when we push it to PathBuffer.

More tests are still needed to cover the private function `_bidirectional_dijkstra` and its ability to exclude nodes and edges. 

I'm leaning towards not including the (almost) one liner function for getting the  k shortest paths and add it to the docstrings as an example. One of the reasons for that is that having a `k_shortest_paths` function outside of the shortest paths package is not very nice. If we end up including it, then I think we should move `shortest_simple_paths` to the SP package instead of the `simple_paths` module in which now is. Comments on this are very welcomed.

**Comment by jtorrents** [comment]
Hmm, the test on configuration model for `all_node_cuts` failed out of the blue again (it happened at least one time before). This is not related to this PR, I'm tracking it down at #1421

**Comment by aparamon** [comment]
Thank you Jordi for your work!

2015-04-09 2:56 GMT+03:00 Jordi Torrents <notifications@github.com>:

> I think we should move shortest_simple_paths to the SP package instead of
> the simple_paths module in which now is. Comments on this are very
> welcomed.
>
 +1 on move to SP package, if it means "Simple Paths" :-)

Probably the function can be named just simple_paths, because in fact it
returns all simple paths (if not terminated), not k shortest. I think it
should be the recommended interface for simple paths problem. However, this
naming issue seems minor.

Best wishes,
Andrey Paramonov

**Comment by chebee7i** [comment]
Can you update the api/release notes too?

**Comment by jtorrents** [comment]
In the last commits I've added as example an efficient function to compute k shortest paths
in the example section of `shortest_simple_paths` docstrings. Also added more tests and added this function to the documentation and to the API 2.0 doc.

@aparamon would you like to appear in the credits file of NetworkX? If so, you can add a link to your webpage/github user/whatever (see #1444 for a recent change in this). Let me know and I'll add you to that file.

Regarding the name, I think that `shortest_simple_paths` is more informative that just `simple_paths`, and given that `all_simple_paths` is faster I think that it will still be the most used function for getting all simple paths between two nodes.

**Comment by Wind4Greg** [comment]
I took a quick peek at the code in @jtorrents fork it looks good.  I saw comments about more tests and examples.  In the Zip that I previously posted there were two different JSON example networks (in addition to the very simple code constructed network). One with 17 nodes & 27 edges, and one with 54 nodes & 102 edges along with a script to read these and compute some of the k-shortest paths (would need to change the call to use the new alg rather than mine). There are also SVGs of the networks that could be used in documentation.

**Comment by chebee7i** [comment]
@jtorrents Good idea on actively suggesting that people update the credits. In addition to the release notes, I'll start mentioning that more regularly.

**Comment by jtorrents** [comment]
@Wind4Greg thanks for looking at this. In general we prefer to build the test graphs using code rather than loading them from files. Note that I've added your simple test to the tests of this function. I think that with the last commits we already have enough tests.

However I'm seeing some mismatch between the coverage reported in the Travis builds compared to my local system. I think that the one I'm getting locally is the correct one. For instance the coverage at Travis says that, among others, line 219 of `simple_paths.py` is not covered:

https://travis-ci.org/networkx/networkx/jobs/58298277#L3439

That line corresponds to the [exception raised if source node is not in G](https://github.com/networkx/networkx/pull/1447/files#diff-6771e790e5503c870ac198bf9c32f84cR219) . Which is covered by a test [here](https://github.com/networkx/networkx/pull/1447/files#diff-d13b637e9a39f00dc2e92f2d3af57316R143). Locally I'm seeing that that line is covered, but not in Travis.

@chebee7i yes we should do that. In the case of @aparamon I can add him and his link myself in this PR if he wants.

**Comment by aparamon** [comment]
2015-04-13 19:35 GMT+03:00 Jordi Torrents <notifications@github.com>:

> @aparamon <https://github.com/aparamon> would you like to appear in the
> credits file of NetworkX? If so, you can add a link to your webpage/github
> user/whatever (see #1444 <https://github.com/networkx/networkx/pull/1444>
> for a recent change in this). Let me know and I'll add you to that file.
>
Please use the following information:
Andrey Paramonov
http://aparamon.msk.ru (currently down, but whatever :-) )

> Regarding the name, I think that shortest_simple_paths is more
> informative that just simple_paths, and given that all_simple_paths is
> faster I think that it will still be the most used function for getting all
> simple paths between two nodes.
>
I still disagree, but I trust your decision :-)

Thank you for your work on NetworkX -- it is one awesome library!

Best wishes,
Andrey Paramonov

**Comment by jtorrents** [comment]
Sorry, I had to rebase to solve the conflicts in API changes documentation. Also added @aparamon to the credits. Thanks Andrey for you work, and also thanks @Wind4Greg for looking into this and proposing an implementation.

If there are no more comments, I think this is ready to merge.

**Comment by muzixing** [comment]
Nice, I just need this API. When I finally understand the Yen's algorithm, and was planning to implement it, I come here!  Thanks for your awesome work!@Wind4Greg

**Comment by muzixing** [comment]
But we can not find any information of this API in https://networkx.github.io/documentation/latest/reference/algorithms.shortest_paths.html

Look forward to add relative information.  @jtorrents

**Comment by dschult** [comment]
Try here:
https://networkx.github.io/documentation/latest/reference/algorithms.simple_paths.html

**Comment by MridulS** [comment]
@dschult That's the same link. I guess this is what we are looking for

http://networkx.readthedocs.org/en/latest/reference/algorithms.simple_paths.html
:)

**Comment by muzixing** [comment]
Thank you for your help @dschult @MridulS

**Pull request merged**
