### PR TITLE
Uses correct graph class when copying without data

### PR DESCRIPTION
**Pull request by jfinkels**
Fixes issue #1916.

### CODE REVIEW

**Comment by dschult** [comment]
I think you can use ```assert_equals(G.edge, self.k3adj)``` and the tests should work for all classes.
(maybe ```G.adj``` instead of ```G.edge``` though they should be equal)

**Comment by dschult** [comment]
This isn't actually testing the ```without_data``` feature. A deepcopy would pass this test.
Think about using the helper functions ```is_shallow_copy``` and ```is_deep_copy```.
It should probably also use the self.k3edge and self.k3nodes created in ```SetUp```.

Also keep in mind that the resulting dict for G[u][v] must be the same object as the dict for G[v][u], so the constructions to compare to aren't quite right.

This brings up a bigger question though:  When would you want to ignore the current edge attributes, yet still create new dicts for them? It saves memory (and probably cpu time) to use a shallow copy which simply points to the already existing attribute dicts in the original graph. We've got (at least) three types of graph_copy possible:  a deepcopy, a new graph structure with same attribute dicts (shallow copy), and a new graph structure with new attribute dicts. In the existing codebase ```G.copy()``` provides a deepcopy and ```nx.Graph(G)``` provides a shallow copy. At some point when we last discussed this we decided not to implement the "new graph with new attribute dicts" version because it isn't a common need (and isn't efficient). It's use-case is only when you've got existing data attributes that you want to throw out and start over fresh with new data attributes.

Let's figure out what we want here before we jump in too far. I think #1876 actually takes longer and uses more memory than a shallow copy... when its intention (in my understanding) is to save time and memory. Perhaps we could solve these issues (#1126, #1152, #1164, #1876, #1916, #1917) by figuring out what it is that we actually need in terms of:

1) Do we copy existing data attributes to the new graph?
2) Do we provide independent data attribute dicts in the new graph?

Yes/Yes -> deepcopy     G.copy()

Yes/No -> shallow copy      ```nx.Graph(G)```

No/No   -> doesn't matter but shallow copy is most efficient in terms of memory and cpu.

No/Yes   ->  not provided.... (and not needed?)

The fourth combination is to ignore existing data attr and create new data attribute dicts for the new graph. Do we need that? I don't think we do...

**Comment by hagberg** [comment]
For the fourth combination isn't it just e.g. for a graph G: 
`H = nx.Graph(G.edges()); H.add_nodes_from(G)`

**Comment by dschult** [comment]
Yes, that provides the fourth combination.

Should we change ```.copy()``` to provide these 3 options? They are not documented well.

We could put your recipe for new datadicts in the copy() docstring and only provide ```G.copy(deepdata=True/False)``` in the method.

Or similar to #1164 we could use:  ```G.copy(with_data=True/'shallow'/False)```

**Comment by hagberg** [comment]
I generally prefer

We could put your recipe for new datadicts in the copy() docstring and only provide G.copy(deepdata=True/False) in the method.

Did we already discuss the option of making two methods?  `G.copy()`, `G.deepcopy()`

**Comment by dschult** [comment]
I don't recall a discussion of ```G.deepcopy()```.  I think that would tend to make ```G.copy()``` used more than ```G.deepcopy()``` (similarly we could create two methods ```G.copy()``` and ```G.shallow_copy()``` if we want more people to use the deep version.)  I think people will find the ```copy()``` more easily. Maybe its better to have it in one place with a good docstring that lays it all out.

As far as the code goes it sounds like we want:

    def copy(self, deepcopy=True):
        if deepcopy is True:
            return deepcopy(self)
        return self.__class__(self)

With the docstring providing the idiom:

    H = nx.Graph()
    H.add_nodes_from(G)
    H.add_edges_from(G.edges())

**Comment by hagberg** [comment]
I agree with you @dschult.  Let's implement it that way.

**Comment by dschult** [comment]
@jfinkels do you want to take this on or should I open a different PR?

**Comment by hagberg** [comment]
Does #1957 close this too?

**Comment by dschult** [comment]
That was my intent in #1957.  Reopen if there are other issues.

**Pull request closed without merging**
