### PR TITLE
Fix sphinx

### PR DESCRIPTION
**Pull request by jarrodmillman**
Minor edits to improve readability, make sure everything is in rst format (not md format), and to make sure tutorial follows pep8.  There are a few other cleanups I may make, but I wanted to get some feedback as I go.

I also wondered if the following statement from the tutorial is still true:
```
Note that the drawing package in NetworkX is not yet compatible with
Python versions 3.0 and above.
```
I assume this is out-of-date and should be removed. @dschult , @hagberg

### CODE REVIEW

**Comment by dschult** [comment]
These are important files to work through and get right.
You should also take a look at #2054 which takes a stab at restructuring the files in the /doc directory to make it easier for people to find and hopefully contribute to them.  Another focus of  that effort was to move the examples into the documentation so that they would be automatically built without a separate script. It looks like we are moving to have them housed in a separate repository, so maybe that isn't necessary. Anyway, it might be helpful to look through the list of commits made for #2054. They are a good framework for improving the docs.

**Comment by jarrodmillman** [comment]
I looked over #2054 and I am not sure how I should proceed.    Should I incorporate those changes in my PR?

Or is that pull request going to be merged?  If so, should I wait and then make changes to that?  Or should I submit changes to https://github.com/jfinkels/networkx/tree/newdoc?

**Comment by dschult** [comment]
I don't think #2054 will be merged without a lot of work -- and then probably in a different PR. It has been a long time and there are many conflicts at this point. So I think you should proceed to make changes as you are. But there are some good ideas in those old commits so incorporate them wherever you think they are helpful. 

I think the examples don't need to be moved to rst files -- so long as we get the notebooks repository to automatically hook in with the testing system we should keep the examples there. But restructuring the current ```/doc``` would be good.

**Comment by jarrodmillman** [comment]
Sounds good.  I have a lot of Sphinx experience and there is a lot of discussion and work on this already, so I should have something ready for comment later today.  I have time over the next week to make sure this PR is ready and merged.

**Comment by MridulS** [comment]
Regarding example notebooks should we test against the latest release or
the master branch?
I think the master(the default one) branch of networkx/notebooks should be
tested against the latest release i.e. 1.11 currently [it's better to
directly work on 2.0 as we are planning this to be a part of 2.0 release]
 And we can have a Dev branch which is tested against networkx master
branch.

**Comment by MridulS** [comment]
Not the right thread for discussion. I'll open a new issue so we can move the discussion regarding example notebooks there.

**Comment by jarrodmillman** [comment]
@MridulS please ping me on the new discussion.  I would like to make sure I am following things.  I am starting to work on this PR now and will push new commits sometime soon (in a couple of hours or sooner).

**Comment by jarrodmillman** [comment]
@dschult , @hagberg I've pushed some more changes.  Before making more substantial changes, I wanted to check with you regarding how I intend to handle the example gallery.

I started by seeing how much work it would take to use the sphinx-gallery extension for auto-generating the examples:
  https://github.com/sphinx-gallery/sphinx-gallery
And I am now confident that I could finish this with out much effort and that it will work as expected on readthedocs.

sphinx-gallery was originally developed as part of the scikit-learn project, but is now a very nice stand-alone project used by several projects including scikit-learn, scikit-image, and astropy.  So we would be in good company and it will be supported for some time to come.  If necessary, I can also submit PRs upstream to them for any functionality or bug-fixes we need.  I hadn't used it before, but it has been straightforward to use so far.

For example, here is the scikit-image examples directory:
  https://github.com/scikit-image/scikit-image/tree/master/doc/examples
And here is the auto-generated gallery:
  http://scikit-image.org/docs/stable/auto_examples/
You will notice that it also provides links to download the examples as `*.py` files or `*.ipynb` files.

I noticed that there was some discussion about moving examples to a notebooks in a separate directory:
  https://github.com/networkx/notebooks
I think that is fine for additional examples, but I strongly recommend leaving at least some of the examples here.  Personally, I find it **much easier** to edit `*.py` files.  It is also much easier to integrate them into the releases and to make sure they are part of the testing infrastructure this way.  And by using sphinx-gallery, all the examples will be available for download as `*.ipynb` files.

I am happy to put time into getting the sphinx-gallery stuff working.  If you don't like the end result, I am happy to remove it.  If this seems reasonable, I can finish this off by tomorrow sometime and you can see if you like how it looks/works.

Also I am holding off on the restructuring the `doc` directory for now.  It is easier for me to track the changes I am making if I don't change file names until the last minute.  I also assume it will be easier for you to see the changes I am making this way.  Once things are in reasonable shape for merging, I can restructure the directory or we can do the restructuring after this is merged.  Either way, that is straightforward.

**Comment by hagberg** [comment]
The sphinx-gallery looks great.  +1 from me and thanks a lot for taking all of this on.  It is much appreciated.

I have to admit I agree with @jarrodmillman that examples that are stand-alone are easier (for me) to  handle with testing, integration, etc.   I assumed everyone else had just started using notebooks while I've not been paying attention.   For sure I would use Jupyter for everything if it ran inside Emacs.  

So let's do both - examples in the source tree that autogenerate a gallery (and notebooks) and also a separate repository for notebooks.  In the notebook repository it will be easier to write more expository examples with references and figures and formatting, etc.

**Comment by dschult** [comment]
I agree with both your comments.  Let's go with Sphinx-gallery and also get the notebooks repository going.

**Comment by jarrodmillman** [comment]
@hagberg , @dschult The sphinx-gallery stuff is working as expected except for a minor issue with `unix_email`, which I need to fix.

Is there a way to test this on readthedocs other than to have this merged?  Everything works fine on my local machine.  I have more I want to do, but I wonder if it would make sense to merge this and then for me to finalize the changes in a second PR.  If that makes sense, feel free to merge this as is.  (I rebased on master so the CI system is running again, but they should pass.)  I will have time to work on this later today and tomorrow, so if there is a problem on readthedocs I will fix it soon.

The main thing left to do is the directory reorganization and minor cleanups.  If I keep working on this PR, I am afraid it will be hard to see any additional changes I make.  I also may need to make small fixes after I see how it behaves on readthedocs anyway.  Suggestions?

**Comment by dschult** [comment]
Let's go ahead and merge and open another PR for tweaks and probably another for moving the files. 

The way to test on ReadTheDocs is to create an account and start a project for your repository.
When you go to your project site click on the "Admin" link (with a settings gear next to it) and then on "Advanced Settings" on the left sidebar.  

  - Check the box for: "Install your project inside a virtualenv using setup.py install"
  - Add "doc/requirements.txt" to the requirements file textbox
  - scroll down to uncheck the "enable epub build"
  - Check the box for "Give the virtual environment access to the global site-packages dir."
  - So far we have left the python version for the build as "CPython 2.x"  you can try other options there.

Submit the configuration using the button at the bottom.

Then go to "Versions" in the left sidebar. It lists every tag and branch for your repository. It also has "stable" and "latest" which automatically pick master and the "most recent" tag.  Those are the only two selected by default. You can uncheck them and check your **Fix-sphinx** branch to build that branch...  Press submit when done selecting which branches to build

The Builds tab (at the top) shows the most recent builds and you can click on them to see what happened.

**Comment by hagberg** [comment]
Yes, merge ASAP.

**Comment by dschult** [comment]
I've set up a project on readthedocs to build your branch. I have read-only access so can't add the hooks to make it automatic, but you can at least see what they look like.
http://testfixsphinx.readthedocs.io/en/fix-sphinx/

**Pull request merged**
