### PR TITLE
edge_cases

### PR DESCRIPTION
**Pull request by khushishikhu**
bugfix-for-issue-5562
#5562

### CODE REVIEW

**Review by rossbar — COMMENTED** [review]
Thanks @khushishikhu !

There is already a PR open for this one in #6973 which has the fix in place, the only thing that is missing is the tests. If you're interested, it may be better to focus effort there!

To generate the necessary test cases, you'd want to come up with tests that *fail* with the current version of networkx but *pass* once the fix is in place.

**Comment by khushishikhu** [comment]
@rossbar thank you for your suggestion. I tried to add tests also in this PR. Could you please review it and tell me what further modifications it requires

**Comment by rossbar** [comment]
> Could you please review it and tell me, what further modifications it requires

The best way to do so would be to follow the procedure outlined above: 

> To generate the necessary test cases, you'd want to come up with tests that fail with the current version of networkx but pass once the fix is in place.

The OP in the corresponding issue are a good place to start.

**Comment by MridulS** [comment]
This was addressed in https://github.com/networkx/networkx/pull/6973, thanks for the PR @khushishikhu

**Pull request closed without merging**
