### PR TITLE
Exact algorithm for maximum clique set

### PR DESCRIPTION
**Pull request by feifeipeng**
This implements exact algorithms to find a maximum independent set, a maximum clique set, a minimum vertex cover and a minimum dominating set for an undirected graph. I find that there is a module which is called Approximation to tackle these problems, but it always returns a approximation result. With fast computers we can do exponential-time computations of moderate and increasing size to seek  exact answers which will undoubtedly help to explore the interesting gap between theory and practice.

Looking forward to your comments. Thanks.

### CODE REVIEW

**Comment by chebee7i** [comment]
@jtorrents thoughts?

**Comment by jtorrents** [comment]
I took a quick look and have some comments. First, about some general conventions. There is no need for an `exact` package, all algorithms in NetworkX are, except for the ones in the `approximation` package. Each module (ie `.py` file) should have the corresponding test file with a set of tests using the `nose` package. See the tests for other modules in NetworkX for examples. The tests should test only, on the one hand, for the correctness of the algorithm you implemented, and on the other hand, the interface of the function (eg what happens if the input is not correct, are the exceptions raised when expected, etc ...).

Regarding the implementation of the algorithm, I did not check the paper that you reference but I think that the code is not doing what you intended. Adding some tests will help looking into this. A problem that I see is that you are generating nested lists using the `*` operator and then updating what you think are different inner lists. The thing is that they are the same! See for example:

```python
In [29]: ADJ = [[]]*4

In [30]: ADJ
Out[30]: [[], [], [], []]

In [31]: ADJ[0].append('OMG!') 

In [32]: ADJ
Out[32]: [['OMG!'], ['OMG!'], ['OMG!'], ['OMG!']]
``` 

Take a look at the `clique.py` module to see how to use NetworkX interface and also the functionality that provides. You should explain in the pull request how the algorithm you are implementing relates that what is already implemented in NetworkX. Also, a short explanation of the algorithm in your own words will help the readers of your code.

Finally, for getting a sorted list of nodes by degree, you can use something like:
```python
sorted_nodes = sorted(G, key=G.degree)
```
You are copying the graph and removing the nodes one by one. This makes tings go slow, especially for large graphs. Not sure if this is what you intended.

**Comment by feifeipeng** [comment]
@jtorrents Many Thanks for your valuable comments and suggestions. I will check and update. As for  the  * operator. I use ADJ[0]=ADJ[0]+['OMG!'] instead of ADJ[0].append('OMG!') which will not cause this problem.

**Comment by feifeipeng** [comment]
@jtorrents
I found nothing wrong with the implementation by adding some specific tests. :)
The new commit adds the corresponding test file and implementations for minimum vertex 
cover and minimum dominating set.

The process of  computing the sorted list list nodes {v_1,v_2,...,v_n} is can be rewritten as:
find the vertex v_k of smallest degree in G; 
repeat the step for graph G'=G\{v_1,...,v_k}.

Thus, there is no other choice as far as I know.

Hope this is the correct way to contribute to network. Apologize if I did anything stupid.

**Comment by ysitu** [comment]
Please follow PEP8 in formatting your code. The dominant variable naming style is lowercase_with_underscores. Please also adopt that.

**Comment by jfinkels** [comment]
`networkx.algorithms.clique`, `networkx.algorithms.dominating`, and `networkx.algorithms.mis` modules already exist; the functions suggested here should be incorporated into those existing modules.

**Comment by feifeipeng** [comment]
@jfinkels Thanks for your comments. However,  networkx.algorithms.mis aims to find a maximal (not maximum) independent set,  networkx.algorithms.dominating finds some dominating set, not necessarily the smallest one and networkx.algorithms.clique searches for all maximal cliques in a graph. 

There is slight difference.

**Comment by jtorrents** [comment]
@feifeipeng I see. I read the paper and checked your implementation, I see now that it gives correct results. However the implementation it's not idiomatic in python, it's confusing because of the use of the huge nested lists with the maximum possible levels of depth that only hold place-holders most of the time (try to put some prints in the while loop to see how `ADJ`,'start' and `last` look like at each iteration to see what I mean). I see that this is because you translated the Fortran code provided by the authors to python (including variable names).

Here is a quick attempt to use more sane data structures but still being very close to the authors implementation. Note that I'm sorting the nodes by core number and degree, which I think is very close (maybe the same?) to the ordering of nodes as described in the paper (removing each time the node with minimum degree). Anyway, according to the authors, sorting nodes is not necessary for the correctness of the algorithm but it helps in high density graphs.

```python
from collections import defaultdict
def maximum_clique_set(G):
    # Order nodes by core number and degree
    core_number = nx.core_number(G)
    nodes = sorted(G, key=lambda n: (core_number.get(n), G.degree(n)))

    # Data structures
    best_clique = set()
    levels = defaultdict(list)
    start = {}
    last = {}

    # Initial values
    depth = 1
    start[depth] = 0
    last[depth] = len(nodes)
    levels[depth] = nodes

    while True:
        start[depth] += 1
        if depth == 1 and depth + last[depth] - start[depth] <= len(best_clique):
            break

        if depth + last[depth] - start[depth] > len(best_clique):
            level = depth
            depth += 1
            start[depth] = 0
            last[depth] = 0
            #print depth, level, start, last, dict(levels), best_clique
            for i in levels[level]:
                if levels[level][start[level]-1] in G[i]:
                    levels[depth].append(i)
                    last[depth] += 1

            if last[depth] == 0:
                levels[depth] = []
                depth -= 1
                if depth > len(best_clique):
                    best_clique = {levels[i][start[i]-1] for i in range(1, depth+1)}
        else:
            levels[depth] = []
            depth -= 1

    return best_clique
```

This is way faster (about one order of magnitude) than the fortran-like approach mostly because we avoid copying and removing nodes nodes one by one when initially sorting nodes. The thing is, the more pythonic function above is another order of magnitude slower than just:

```python
def plain_max_clique(G):
    return max(list(nx.find_cliques(G)), key=len)
```

Which computes all cliques in the graph and picks one of the largest ones. I think that you should read through the very nice `networkx.algorithms.clique` module to see how it does that. Here are some test in my machine to illustrate:

```python
In [49]: %paste
import networkx as nx
from networkx.utils import powerlaw_sequence, create_degree_sequence

def build_power_law(n):
    deg_seq = create_degree_sequence(n, powerlaw_sequence, 100)
    G = nx.Graph(nx.configuration_model(deg_seq))
    G.remove_edges_from(G.selfloop_edges())
    G = max(nx.connected_component_subgraphs(G), key=len)
    G.name = 'Power law configuration model: {0}'.format(n)
    return G

def plain_max_clique(G):
    return max(list(nx.find_cliques(G)), key=len)
## -- End pasted text --

In [50]: G = build_power_law(5000)

In [51]: print(nx.info(G))
Name: Power law configuration model: 5000
Type: Graph
Number of nodes: 4928
Number of edges: 15760
Average degree:   6.3961

In [52]: %timeit plain_max_clique(G)
10 loops, best of 3: 59.3 ms per loop

In [53]: %timeit maximum_clique_set(G)
1 loops, best of 3: 8.96 s per loop

In [54]: G = nx.gnp_random_graph(100, 0.5)

In [55]: %timeit plain_max_clique(G)
10 loops, best of 3: 106 ms per loop

In [56]: %timeit maximum_clique_set(G)
1 loops, best of 3: 3.85 s per loop
``` 

I think that we should look to other algorithms for the maximum clique set problem to find something that will be faster that using what we already have in `networkx.algorithms.clique`. This paper seems very useful but I only took a quick look.

http://arxiv.org/abs/1207.4616

Also, please note @jfinkels and @ysitu comments.

**Comment by feifeipeng** [comment]
@ysitu Many thanks. Adopted  and will always remember.

**Comment by ysitu** [comment]
@feifeipeng You need to resolve the performance problems pointed out by @jtorrents. Unless it is much faster than `max(nx.find_cliques(G), key=len)` for moderate-sized problems, the new code is not very useful.

**Comment by feifeipeng** [comment]
@jtorrents @ysitu Yes, I see it. The paper I referred to is really "old". I will read through `networkx.algorithms.clique` module and some new paper to find a faster solution. Thanks

**Comment by jtorrents** [comment]
@feifeipeng , great! Could you please make a separate pull request for the exact algorithm for minimum dominating set? We can leave this one open to follow up with the maximum clique work/investigation. As @jfinkels says, the `minimum_dominating_set` function should be in `networkx.algorithms.dominating`. The function currently there is mostly to get a relatively small dominating set fast to solve edge connectivity problems. The exact algorithm for a minimum one is a nice addition, even if not practical for not so large graphs, and very related to what is already there.

By the way, there is some weird indentation thing with your code. In mi editor locally I see it as in github diff (in `Files changed`), sometimes it seems that an indentation level is two spaces, sometimes they seem of 8 or 4 spaces, which makes difficult to read the code (seems to run fine though). It's a good practice to set your text editor to use 4 spaces as a tab for indentation for python code.

**Comment by feifeipeng** [comment]
@jfinkels Apologize! I realize now that I have made some mistake with the previous reply.:)

**Comment by jamestrimble** [comment]
I wonder if the max clique function in this PR is still useful compared to `nx.max_weight_clique(G, weight=None)` and `nx.graph_clique_number()`. I did timings for a few random graphs:

```
def time():
    print("maximum_clique_set    ", timeit.timeit("maximum_clique_set(G)", number=1, globals=globals()))
    print("nx.max_weight_clique  ", timeit.timeit("nx.max_weight_clique(G, weight=None)", number=1, globals=globals()))
    print("nx.graph_clique_number", timeit.timeit("nx.graph_clique_number(G)", number=1, globals=globals()))
    print()


G = nx.gnp_random_graph(250, .1)
time()
G = nx.gnp_random_graph(50, .5)
time()
G = nx.gnp_random_graph(30, .9)
time()
```

with  these results:

```
maximum_clique_set     0.39374078999389894
nx.max_weight_clique   0.019198676993255503
nx.graph_clique_number 0.014624504998209886

maximum_clique_set     0.24361919799412135
nx.max_weight_clique   0.0033190690010087565
nx.graph_clique_number 0.006590124990907498

maximum_clique_set     0.9121223280089907
nx.max_weight_clique   0.004532831997494213
nx.graph_clique_number 0.006706512998789549
```

(This uses the version of the function by @jtorrents).

For these three graphs at least, the functions that are in NetworkX already are much faster.

I can still see the usefulness of having separate functions for max independent set and minimum vertex cover. It's also very possible that there are some graphs for which the `maximum_clique_set` function is fast.

**Comment by dschult** [comment]
This PR proposes 4 functions. 
- minimum_dominating_set has been refactored into PR #1464
- 2 of the other 3 are 2-3 line use of the 3rd (maximum_clique) (a max independent set is the max clique of the complement of G, and the minimum vertex cover is all nodes not in the max independent set)
- the  maximum_clique algorithm used here is an order of magnitude slower (as reported above) than computing all the cliques and finding the largest one -- which we can do with existing nx functions.

So I think we should close this PR in favor of the PR for minimum_dominating set.
If someone wants to reopen it, leave a comment.

**Pull request closed without merging**
