### PR TITLE
Doc infrastructure: replace `nb2plot` with `myst-nb`

### PR DESCRIPTION
**Pull request by rossbar**
This is a re-submission of #5221 - the changes are the same (more or less) but the order of git operations used to do the conversion was different in order to preserve git blame across the two files that were converted from `.rst` -> `.md`.

To demonstrate that the blame is preserved, here are links to the blame from the two converted files (on my fork - you may have to click the `blame` button):

- [introduction](https://github.com/rossbar/networkx/blame/mystnb-preserve-blame/doc/reference/introduction.md)
- [tutorial](https://github.com/rossbar/networkx/blame/mystnb-preserve-blame/doc/tutorial.md)

Unfortunately the summary diffs for the PR still aren't very useful for reviewing, since per-line changes are lost in the file extension change. **However** - I've intentionally structured the commits so that the individual changes from both the auto-converter (`rst2myst`) and the subsequent manual tweaks I made are still visible. The commits whose messages start with `WIP` comprise the outputs from the autoconversion (c04d227 and 3ff8997 for the tutorial and introduction, respectively). Similarly, the additional changes I made to each file after the conversion are captured in 9448144 and a5cdbc4, respectively. If you click on those commits individually, you should see a nice line-by-line diff of the changes from each step in the conversion process!

Now, there's still a question about whether we want to ignore some of the changes in the blame, e.g. changes from the linters. One option might be to temporarily disable the auto-squashing just for this PR, as it might actually be worth preserving each commit here so that it's possible to discern exactly how the conversion took place. The linting commit (323616e) could also then be added to `.git-blame-ignore-revs`. This isn't necessarily a show-stopper, but it's a rare instance where preserving the history may be worthwhile!

### CODE REVIEW

**Comment by jarrodmillman** [comment]
Does `myst-nb` allow you to test the code doesn't produce different results like `nb2plots`?

**Comment by dschult** [comment]
It looks like one option given by the github interface (triangle menu on the green "Squash and merge" button) is "rebase and merge". Does that look like it does what you want to preserve the history?

I'm fine with you setting up testing here in this PR, unless that is more difficult for you. I'm fine with wading through the commits for review.

**Comment by rossbar** [comment]
> rebase and merge". Does that look like it does what you want to preserve the history?

Yes, this would be the right selection, though it's currently disabled for the repo so it'd require an admin to temporarily enable that, merge, then re-disable it!

> I'm fine with you setting up testing here in this PR, unless that is more difficult for you.

I'll go ahead and add this too. I suppose there's a question of whether the tutorial/introduction really benefit that much from doctest-style (i.e. exact repr matching) tests since all of the operations used in the tutorials are covered in the test suite. The operations will never be incorrect, because they are regenerated at every build - all tests would check for is whether they were character-consistent with previous runs.

**Comment by dschult** [comment]
Hmmm...  I see what you mean about the option being disabled -- not sure why I didn't see that before. Anyway, easy to do when the time comes.

Also -- I get what you are saying -- the code in the tutorial/introduction may not need tests.  Would that still be true in the notebook format? It seems like it would.  I guess the tests just check that we haven't changed the main repo results and just forgotten about updating the tutorial. I don't think having character-consistent output is a motivating factor though.

@jarrodmillman what are your thoughts about whether the tutorial needs testing since that functionality is tested elsewhere?

**Comment by rossbar** [comment]
> Hmmm... I see what you mean about the option being disabled -- not sure why I didn't see that before. Anyway, easy to do when the time comes.

:+1: 

> I get what you are saying -- the code in the tutorial/introduction may not need tests. Would that still be true in the notebook format?

Yeah, switching to executable notebooks means that the notebooks (i.e. tutorial.md and introduction.md) are executed for each new doc build. So in that sense the notebooks are smoke-tested each time the docs are built - if execution fails you will get SphinxWarnings (which we may want to elevate to errors).

>  I guess the tests just check that we haven't changed the main repo results and just forgotten about updating the tutorial.

The good news here is that the results in the tutorial wouldn't need updating since outputs are now generated by executing the code during the docs build. **If** however you wanted to verify that the results haven't *changed* between doc builds, then additional testing would be required.

**Review by jarrodmillman — APPROVED** [review]

**Comment by rossbar** [comment]
I just rebased to bump this up - IMO it's ready to go!

I went ahead and did a (rudimentary) benchmarking of the doc build to make sure there is no significant difference in the build times between the current version and the myst-nb version. Indeed, the build times are the same. Results of `time make html-noplot`:

### On main

```
Build finished. The HTML pages are in build/html.

real    1m14.299s
user    1m12.111s
sys     0m9.739s
```

### This PR

```
Build finished. The HTML pages are in build/html.

real    1m13.966s
user    1m11.785s
sys     0m8.567s
```

**Pull request merged**
