### PR TITLE
Generalize statistics to disconnected graphs

### PR DESCRIPTION
**Pull request by matiasmorant**

### CODE REVIEW

**Comment by dschult** [comment]
This may seem like a simple change, but the impact is hard to ferret out.
Can you add tests to show what you expect to happen. In particular, we need tests that provide (for simple cases) assurance of what the outcome should be when the graph is disconnected. It would be great to have a reference to some published description of this, and where discrepancies of how to do it exist, a note in the docs about the differences and which this method produces.
Thanks!

**Comment by MridulS** [comment]
@matiasmorant let us know if you are still interested in working on this, thanks for opening up the PR!

**Comment by rossbar** [comment]
This hasn't seen any updates in a while, and IMO still has a lot of work, namely: 1) what do all of the distance measures mean in the context of disconnected graphs, and 2) formalizing that behavior with extensive testing.

**Comment by dschult** [comment]
I'm going to close this PR based on this discussion.
We can still post to this if desired and we'll all see it.

**Pull request closed without merging**
