### PR TITLE
Update doc with changes in iter_refactor and update iter_refactor branch

### PR DESCRIPTION
**Pull request by MridulS**
Update doc fa82e79. 
Update iter_refactor branch with recent commits in the master branch.

### CODE REVIEW

**Comment by MridulS** [comment]
@chebee7i @dschult @hagberg @ysitu @jfinkels

**Comment by dschult** [comment]
I might be wrong on this (or out of date), but I think when merging branches with git,
we should identify the conflicts and change them in the branch to be merged. This looks
like you are rebasing to pull the branch up to master before merging.  Again, I'm not
a git expert (still spend too much time figuring out how to do things with git than I should).
But what is the best way to get ready for such a merge?

It looks to me like the only conflicts are with mst.py and test_mst.py.  The old files need to be removed and the new file needs ```list(G.nodes()) -> list(G)``` and ```G.degree_iter() -> G.degree()```.

With this single commit to prepare for the merge I think the merge would then be a clean merge and we wouldn't have to check through this very large PR.   comments welcome.

**Comment by MridulS** [comment]
The easiest way I can think of is to solve the merge conflicts and push a commit to the iter_refactor branch. We can create a pull request directly from github.
screen shot 2015-07-07 at 6 29 18 pm
the pull request will effectively do the same thing as this PR.

In this pull request I just want to keep iter_refactor branch updated with master, and avoid solving multiple merge conflicts if anything is committed to the master branch in near future.

If we merge this pull request, the status above iter_refactor will read something like `This branch is 42 commits ahead, 0 commits behind`

We can review the changes by clicking on these last three commits made by me.

screen shot 2015-07-07 at 6 35 56 pm

No need to review the changes made before that because they are probably reviewed before merging with master.

**Comment by dschult** [comment]
I guess this is a question of whether we should merge master into iter_refactor
or rebase iter_refactor so that its commits apply to the head of master.
Rebasing gives a "linear" history. 
One description is at https://www.atlassian.com/git/tutorials/merging-vs-rebasing

I think we are close to being ready to merge iter_refactor into master. It seems like it might be messy if we include a bunch of commits in this branch that are already on the master branch. Then when we merge, we have double commits in some sense...

What are the disadvantages of rebasing the iter_refactor branch?

**Comment by MridulS** [comment]
I went through this https://www.atlassian.com/git/articles/git-team-workflows-merge-or-rebase/ ,
and I am leaning towards a merge. What do you think @dschult ?

**Comment by MridulS** [comment]
@dschult Any more updates?

**Comment by hagberg** [comment]
Shouldn't we rebase this branch to the latest changes in master and fix any conflicts?

**Comment by dschult** [comment]
@MridulS can you open a new PR which rebases to master and fixes any conflicts. Then I think a separate PR to apply changes from the last 3 commits that aren't related to fixing conflicts. 
Thanks

**Comment by MridulS** [comment]
@dschult @hagberg I am closing this PR. #1659

**Pull request closed without merging**
