### PR TITLE
Ensure `digraph.reverse` respects hashable objects

### PR DESCRIPTION
**Pull request by jarrodmillman**
I more or less implemented the suggested test and fix from #2442.  I changed the test from this

```
self.assertCountEqual(G.nodes(), G.reverse().nodes())
self.assertCountEqual(map(reversed, G.edges()), G.reverse().edges())
```

to

```
assert_items_equal(G.nodes(), G.reverse().nodes())
assert (y, x) in G.reverse().edges()
```

Let me know if you have a better idea.

### CODE REVIEW

**Comment by dschult** [comment]
It looks like self.assertCountEqual isn't available in python2.  Your assert_count_equal looks good. 
for the tests, can we use 

    assert_equal([(y, x)], list(G.reverse().edges()))
    assert_count_equal(G.nodes(), G.reverse().nodes())

The current code should pass the edges test and fail the nodes.  Your fix should pass both.  
It's basically the same as your proposal, but tests the edges for equality instead of one-way inclusion. 
If you have other ideas that is fine; I'm just making suggestions.

**Comment by hagberg** [comment]
Do any of the functions in https://github.com/networkx/networkx/blob/master/networkx/testing/utils.py
help? (assert_nodes_equal)

**Comment by jarrodmillman** [comment]
@dschult Ready to merge.

**Comment by dschult** [comment]
Thanks!!

**Pull request merged**
