### PR TITLE
Update nx_shp.py

### PR DESCRIPTION
**Pull request by IOWq750**
Reading and writing coordinate system from/to shapefile

### CODE REVIEW

**Comment by rossbar** [comment]
Thanks for the interest @IOWq750 , a couple comments:

The proposed changes are tripping the tests. You can see details by either following the link in the CI checks below, or running the tests locally.

Also, you may be interested in the discussions in #4107 & geopandas/geopandas#1592 which deal with how best to include shp support for the wider ecosystem.

**Comment by IOWq750** [comment]
> Thanks for the interest @IOWq750 , a couple comments:
> 
> The proposed changes are tripping the tests. You can see details by either following the link in the CI checks below, or running the tests locally.
> 
> Also, you may be interested in the discussions in #4107 & [geopandas/geopandas#1592](https://github.com/geopandas/geopandas/issues/1592) which deal with how best to include shp support for the wider ecosystem.

Hello! Yes, I see an issue with testing but yet haven't managed it :(

**Comment by jarrodmillman** [comment]
@IOWq750 NetworkX is deprecating read/write functionality for shapefiles (#4298) and providing gallery examples for working with geospatial data using the main packages for geospatial data analysis for Python (#4366). We are interested in making sure our gallery examples provide the recommended way to read/write geospatial data and converting them back and forth to NetworkX. We would love feedback and additional gallery examples! One of our main goals is to make it clear to our users how to get started and where to go for questions regarding geospatial data formats since we (the NetworkX developers) don't work with geospatial data and don't know how to provide guidance for users.

**Comment by jarrodmillman** [comment]
See #4298 and #4366.

**Pull request closed without merging**
