### PR TITLE
Updating average_clustering() documentation - Issue #4734

### PR DESCRIPTION
**Pull request by DebarghaG**

### CODE REVIEW

**Comment by MridulS** [comment]
Thanks for this @DebarghaG!
As part of our tests we run the examples too, so could you update the code to define a graph `G`?
``` python
>>> import networkx as nx
>>> from networkx.algorithms import approximation
>>> G = nx.erdos_renyi_graph(10, 0.2)
>>> approximation.average_clustering(G, trials=1000, seed=None)
```

**Comment by DebarghaG** [comment]
@MridulS A little confused here. What's going wrong here?

**Comment by MridulS** [comment]
ahh, it expects to check the output too, so do put in the output too and change the seed from `None` otherwise we can't guarantee the reproducibility of the output.

``` python
>>> import networkx as nx
>>> from networkx.algorithms import approximation
>>> G = nx.erdos_renyi_graph(10, 0.2)
>>> approximation.average_clustering(G, trials=1000, seed=42)
0.085
```

**Comment by DebarghaG** [comment]
Hey @MridulS , Thanks for all the handholding! :hugs: :smiley:

**Review by MridulS — APPROVED** [review]

**Review by dschult — APPROVED** [review]
Very Nice!
Thank you!

**Pull request merged**
