### PR TITLE
simple change to make single shortest path length linear instead of quadratic

### PR DESCRIPTION
**Pull request by jpcmorais16**

### CODE REVIEW

**Comment by dschult** [comment]
We'll need more from you before we consider this change.

**Review by rossbar — COMMENTED** [review]
I suppose the argument here is that `len(seen)` scales with the number of elements in the set. I'm not convinced that's the case: a couple simple tests with `timeit` (without caching) show constant time for `len(s)` for `s` with increasing number of elements[^1].

All that said - IMO the boundedness isn't even particularly relevant. The real motivation for introducing another variable to track would be whether this significantly improves performance in practice. From simple testing, I don't think this does:

```python
import networkx as nx
G = nx.path_graph(1_000_000)
%timeit nx.single_source_shortest_path_length(G, 0)
```

At face value, the path graph strikes me as a good example to probe this change as it should result in relatively large `seen` sets. When I run this on `main` and on this branch I see no appreciable difference.

Now - this is all very preliminary analysis on my part; if you'd like to address these points to advocate for this going in I'd be happy to learn something new! Otherwise I'd vote to close this one.

[^1]: the definitive way to investigate this would be to look at the CPython implementation of sets!

**Comment by jpcmorais16** [comment]
> I suppose the argument here is that `len(seen)` scales with the number of elements in the set. I'm not convinced that's the case: a couple simple tests with `timeit` (without caching) show constant time for `len(s)` for `s` with increasing number of elements[1](#user-content-fn-1-4031056a24229d79dab9cc2924a1f6a7).
> 
> All that said - IMO the boundedness isn't even particularly relevant. The real motivation for introducing another variable to track would be whether this significantly improves performance in practice. From simple testing, I don't think this does:
> 
> ```python
> import networkx as nx
> G = nx.path_graph(1_000_000)
> %timeit nx.single_source_shortest_path_length(G, 0)
> ```
> 
> At face value, the path graph strikes me as a good example to probe this change as it should result in relatively large `seen` sets. When I run this on `main` and on this branch I see no appreciable difference.
> 
> Now - this is all very preliminary analysis on my part; if you'd like to address these points to advocate for this going in I'd be happy to learn something new! Otherwise I'd vote to close this one.
> 
> ## Footnotes
> 1. the definitive way to investigate this would be to look at the CPython implementation of sets! [↩](#user-content-fnref-1-4031056a24229d79dab9cc2924a1f6a7)

**Comment by jpcmorais16** [comment]
Sorry, was trying to make the comment and closed by accident. The reason I found this piece of code was because I couldn't explain why "average_shortest_path_length" was taking time proportional to V^3 in the networks that I am studying (unweighted, undirected and with number of nodes between 10K and 90K), since, from what I understood, it just runs a BFS for each node of the network (I know BFS is O(V+E), but the number of edges in these networks grows linearly with the number of nodes). So I found this implementation of single_source_shortest_path_length, copied it to my code, did the exact same change I did here, and the time got proportional to V^2, which is the normal I suppose.

**Comment by jpcmorais16** [comment]
I used python's "time" to measure the times, and found out that the plotting of time/n^2 (y) by n (x) was linear (and time/n^3 by n remained basically constant) for 10 different networks with the number of nodes in between 10K and 90K.

**Comment by dschult** [comment]
Are you **sure** there aren't other changes that are causing the speedups you see?
Because `len(a_set)` is an O(1) operation. So it is hard to see how this small change speeds things up -- and apparently the speed relative to `main` branch is not showing the speedup.

**Comment by jpcmorais16** [comment]
Unfortunately I won't have time to gather evidence for it at the moment (and I lost the data I had used for the plots). If you are sure that it's not making any difference, feel free to close this PR. In the future I will dive deeper and find out if it was a mistake. In the meantime, if possible, please do the plottings and see if "average_shortest_path_length" isn't O(V^3) for the case I mentioned. Possibly there is something wrong somewhere else.

**Comment by jpcmorais16** [comment]
Unfortunately I won't have time to gather evidence for it at the moment (and I lost the data I had used for the plots). If you are sure that it's not making any difference, feel free to close this PR. In the future I will dive deeper and find out if it was a mistake. In the meantime, if possible, please do the plottings and see if "average_shortest_path_length" isn't O(V^3) for the case I mentioned. Possibly there is something wrong somewhere else.

**Comment by rossbar** [comment]
Thanks @jpcmorais16 , I will go ahead and close for now as I strongly suspect this was not the bottleneck in performance that you had experienced. However, if you can find/regenerate a minimum reproducing example that captures the behavior you were seeing, please feel free to reopen!

**Pull request closed without merging**
