### PR TITLE
Read/write/generate a basic graph using UCINET DL format

### PR DESCRIPTION
**Pull request by Temigo**
Functions and tests for UCINET DL format. 
(Currently supports only 'fullmatrix' format for data. There are many variants for UCINET DL format, this implementation only covers the basic one for now.)

This is related to issue  #2051. Thanks !

### CODE REVIEW

**Comment by jfinkels** [comment]
There are already some functions for reading and writing e.g. adjacency matrices, perhaps those can be used so you don't need to reimplement an adjacency matrix reader/writer?

**Comment by dschult** [comment]
The test errors all seem to relate to a print statement left in place.
Could you also add line breaks to keep the code below 80 chars per line?

How likely are people to want the "variant" forms of the UCINET DL format? What is the best way to handle that? Are there easy converters from one variant to another?

**Comment by Temigo** [comment]
Sorry, I cleaned the code and I hope the test will pass now. 

I was thinking of two kind of "variants" : 
- variants in the way options are given (for example labels can be specified before the data or directly with the data, the latter isn't handled yet). 
- variants in the way of formatting data (`fullmatrix` is the adjacency matrix, `upper half` is only half of the symmetric matrix, etc)
However until now I have only encountered data formatted in `fullmatrix`. I will have a look at functions for adjacency matrices, thanks.

I plan to implement all of these variants in a near future. Maybe you would prefer to wait for the whole and complete implementation ?

**Comment by hagberg** [comment]
@jfinkels has a good idea here to use existing readers to help make writing this easier.

I looked at the formats for UCINET DL
 - www.analytictech.com/ucinet/documentation/usersguide.doc
 - https://gephi.org/users/supported-graph-formats/ucinet-dl-format/

They all are basic text files with a header and then data.  Perhaps the simplest approach is to write a function that will parse the header and dispatch based on that.  

e.g. for
```
DL n=5
format = edgelist1
labels:
george, sally, jim, billy, jane
data:
1 2
1 3
2 3
3 1
4 3
```
The steps would be
- Parse the lines before "data" - e.g. create label mapping made {1: george, 2:sally, ...}
- Call parse_edgelist() on the rest of the file
- Relabel nodes with the mapping

In that case we already have an edgelist reader. 

For matrix formats we could fairly simply use either one of 
- http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.loadtxt.html
- http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.genfromtxt.html
and then do a little manipulation depending on the header (fill in diagonal, fill in lower part, etc).

For writing data a similar approach could be used.

**Comment by Temigo** [comment]
Thank you for your advices. I committed some changes according to this. However the checks failed because of Numpy's import : how should I import it ?

**Comment by dschult** [comment]
Since the pypy standard build doesn't include numpy, you'll have to make the tests skip your module when numpy is not available. Any module that uses numpy should have the code to skip tests at the bottom, for example the [bottom of graphmatrix.py](https://github.com/networkx/networkx/blob/master/networkx/linalg/graphmatrix.py)

**Comment by MridulS** [comment]
Thanks for your work on this @Temigo!

Unfortunately we haven't reviewed this in a long time, sorry about that! A lot of things have changed in networkx in the last 7 years so we would need to put in some effort to make this PR mergeable.

I think we also need to be a bit conservative in adding new I/O formats in networkx, so the code can be maintainable. I have added this to #7099 that tracks future wishlist/good ideas/maybes and once we have a decision we can move forward with the implementation bits. Thanks again!

**Pull request closed without merging**
