### PR TITLE
MAINT: Cleanup link analysis module, remove unused variables

### PR DESCRIPTION
**Pull request by MridulS**
Remove more characters from our codebase.
Make linters like pylint, isort a bit more happier.

Tiny subjective nitpicks around the code.

### CODE REVIEW

**Review by rossbar — COMMENTED** [review]
Most of the changes looke good, but I think we need to be careful about the in-place division operators on numpy arrays. If we're absolutely sure that the dtypes of the arrays being operated on are floating point then it's fine, but if not then you can run into the following situation:

```python
>>> a = np.array([1, 2, 3], dtype=int)
>>> a /= 2
Traceback (most recent call last)
   ...
UFuncTypeError: Cannot cast ufunc 'true_divide' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

FWIW this was my main hesitation back when that bot suggested we switch to in-place operators everywhere in the codebase :joy: I'm not confident that most linters are aware of these subtleties.

**Comment by MridulS** [comment]
Stupid bots indeed. Atleast in this case I guess we can be sure that everything is `float`. Everything starts with a numpy float array `A`.

**Comment by dschult** [comment]
Would the dtype error be avoided using:
```
a = np.array([1, 2, 3], dtype=int) / 2
```

**Comment by MridulS** [comment]
Yeah the following bits of operation on `a` shouldn't be a problem as after `a = np.array([1, 2, 3], dtype=int) / 2` the `dtype` is `float`.

[In this bit of code we are explicit about the `float` dtype while creating the array]

**Review by rossbar — APPROVED** [review]
LGTM - the in-place division on ndarray's look good in these cases as it does seem they're always guaranteed to have floating point dtypes. The rest of the cleanups are obvious improvements IMO - thanks @MridulS !

**Review by jarrodmillman — APPROVED** [review]

**Pull request merged**
