### PR TITLE
Re-submission of gh-7087 with better file provenance

### PR DESCRIPTION
**Pull request by rossbar**
The state of the files in this PR (as of fd27267) are identical to 8452290 in #7087 . The main difference is I've re-applied the changes in a different way to better preserve attribution and make the changes more easily reviewable in github. See [this comment](https://github.com/networkx/networkx/pull/7087#issuecomment-2418511909) for details.

Now, the big payoff of all this reorg is that the *content changes* are now diff-able in the GitHub UI by reviewing the diff for commit fd27267 .

### CODE REVIEW

**Comment by rossbar** [comment]
As a reminder: the main motivation of this PR is to improve the animation performance, primarily to reduce doc CI burden. This PR does reduce the total time on the 3D animations by about 2x:

Both examples run in about 12.5 seconds with these changes (excerpted from the [circleci build log for this PR](https://app.circleci.com/pipelines/github/networkx/networkx/10122/workflows/1f05c7e8-428e-4ea5-b06c-8ce6dfe7df2c/jobs/16990)):

```
    - ../examples/3d_drawing/plot_3d_animation_walk.py:                              6.29 sec   0.0 MB
    - ../examples/3d_drawing/plot_3d_animation_basic.py:                             6.17 sec   0.0 MB
```

vs. the current runtime for the example, which is about 25 seconds (excerpted from an [arbitrary circleci build log](https://app.circleci.com/pipelines/github/networkx/networkx/10118/workflows/3ece9dad-8d34-472e-b590-60db0954943c/jobs/16982)):

```
    - ../examples/3d_drawing/plot_3d_rotation_animation.py:                         25.92 sec   0.0 MB
```

**Comment by lobpcg** [comment]
@rossbar maybe you could address my previous suggestions please: https://github.com/networkx/networkx/pull/7087#issuecomment-1793738680

>  A few suggestions:
> 
> - keep both references in the basic example;
> - keep 3d spectral rather than spring in both examples - I would like to see it popularized.
> 
> Do you think that a frame redraw is never needed i.e. can always be avoided?
> 
> For a new follow up PR I would like to see a new hopefully similar example but which utilities
> blit=True as in https://matplotlib.org/stable/api/animation_api.html

**Comment by rossbar** [comment]
> keep both references in the basic example;

The removal of the reference to sphinx-gallery was intentional - that's more of a tooling consideration that is more likely to be of interest to gallery authors, rather than the typical reader of gallery examples.

The reference to matplotlib animations is still there in the original example - the external link has just been replaced with an intersphinx link for better maintainability.

> keep 3d spectral rather than spring in both examples - I would like to see it popularized.

This was simply an aesthetic choice on my part. For whatever reason, the 3D spectral layout [appears "compressed" in the depth dimension](https://networkx.org/documentation/stable/auto_examples/3d_drawing/plot_3d_rotation_animation.html#sphx-glr-auto-examples-3d-drawing-plot-3d-rotation-animation-py) as opposed to the force-directed layout(s) which [do a better job of recovering the "classic" dodecahedron](https://output.circle-artifacts.com/output/job/c8121261-49cc-4d7d-9779-c29ae0c12e64/artifacts/0/doc/build/html/auto_examples/3d_drawing/plot_3d_animation_basic.html#sphx-glr-auto-examples-3d-drawing-plot-3d-animation-basic-py).

In practice, this doesn't matter. I will switch back to the spectral layout to avoid bikeshedding.

> Do you think that a frame redraw is never needed i.e. can always be avoided?

I'm no expert in the matplotlib animation API, but the resulting animation is consistent with the original example.

> For a new follow up PR I would like to see a new hopefully similar example but which utilities blit=True

Agreed - let's leave it for a follow-up to hopefully get this one un-stuck!

**Review by MridulS — APPROVED** [review]

**Review by ruidazeng — APPROVED** [review]

**Review by dschult — COMMENTED** [review]
This looks good.
I have a suggestion for the docs intro on the second example, but change it as you see fit.

And it's too bad to have to use `global node` to pass the node value into the anmiation function. But I don't see an easy way around it.

**Review by dschult — APPROVED** [review]

**Pull request merged**
