### PR TITLE
fix small index iteration bug in kernighan_lin algorithm

### PR DESCRIPTION
**Pull request by jelgun**
The algorithm works incorrectly because of that bug as min_i in line 124 always gets 0.

### CODE REVIEW

**Comment by dschult** [comment]
Thank You!!

**Review by dschult — APPROVED** [review]

**Review by rossbar — COMMENTED** [review]
IMO the chained assignments made this difficult to read. I think it would make things more clear (and make errors like this less likely) to rewrite e.g. `i = totcost = 0` either as `i, totcost = 0, 0` or

```python
i = 0
totcost = 0
```
One other quick question just to double-check: the increment on `i` should happen after the yield, not before?

**Comment by jarrodmillman** [comment]
It would be nice to have a test for this, if you have the time.

**Comment by jelgun** [comment]
> IMO the chained assignments made this difficult to read. I think it would make things more clear (and make errors like this less likely) to rewrite e.g. `i = totcost = 0` either as `i, totcost = 0, 0` or
> 
> ```python
> i = 0
> totcost = 0
> ```
> 
> One other quick question just to double-check: the increment on `i` should happen after the yield, not before?

I agree. Did some refactoring. Incrementing 'i' before the yield actually was not a bug as it was handled differently on return.

**Review by rossbar — APPROVED** [review]
I agree that adding a test (or tests) for `_kernighan_lin_sweep` would be a big improvement, though this is a clear bug so +1 for fixing and not letting tests be a blocker.

**Pull request merged**
