### PR TITLE
Simplifies two community test for asyn-lpa.

### PR DESCRIPTION
**Pull request by jfinkels**
I'm hoping this should help with the occasional test failures while maintaining the spirit of the test.

### CODE REVIEW

**Comment by dschult** [comment]
The current failure occurs sometimes when a single community (all nodes) is found.
Is that still possible with this graph and this algorithm?  I'm not sure if this commit is making it less likely to occur or impossible to occur.

**Comment by jfinkels** [comment]
I was assuming it would make it much less likely, but I'm not familiar enough with the algorithm to say.

**Comment by dschult** [comment]
It can still fail the test -- the algorithm chooses nodes at random and they "vote" (change their label) to the label that is the majority of their neighbors (or arbitrarily for ties). The order in which nodes are chosen determines the outcome. So I think we should include both possible outcomes in our test.

I'll try to put together a PR leaving the old test, but including both possible answers.  What do you think?

    -    assert_equal(result, ground_truth)
    +    # probabilitistic result could be all nodes in one community. So test result is either.
    +    assert(result in [ground_truth, set(frozenset(range(16)))])

**Comment by dschult** [comment]
I merged #2339 which is an alternate version of this.

**Pull request closed without merging**
