### PR TITLE
Remove symlinks

### LINKED ISSUE #1695: Symbolic links cause test failures on AppVeyor
Symbolic links introduced in #1467 cause breakage when installing with Python 3 on Windows. Found this problem when testing `networkx-metis`: https://ci.appveyor.com/project/chebee7i/networkx-metis-1lf0f/build/1.0.91/job/4ifakb2gfdgakvoy

@hagberg The problem is present in 1.10. We should consider a 1.10.1 release since this affects installation.

### PR DESCRIPTION
**Pull request by OrkoHunter**
Fix #1695 

To remove the duplication of `atlas.py` in `examples/` a symbolic link was created in #1467. But that was in examples directory which is different from the `networkx` directory. So, I guess this is different case than the duplication in the package code. I'm not sure about this.

We may wait for #1699 to verify in this PR that the bug in installation in over. However [here](https://ci.appveyor.com/project/OrkoHunter/networkx/build/1.0.24) is the build log of this commit on my fork, over a [different branch](https://github.com/OrkoHunter/networkx/tree/symlink) which also has the required files to trigger a build on AppVeyor.

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Well yes, it passed the builds.

**Comment by ysitu** [comment]
`examples/drawing/chess_masters.py` is also a symbolic link. Why is it not breaking you build? Can you check if there are more symbolic links?

**Comment by OrkoHunter** [comment]
There are actually 5 symbolic links (2 modules) all in the same directory.
```
examples/drawing/atlas.py
examples/drawing/chess_masters.py
examples/drawing/chess_masters_WCC.pgn.bz2
examples/drawing/knuth_miles.txt.gz
examples/drawing/unix_email.mbox
```

**Comment by OrkoHunter** [comment]
I suspected an ambiguity in the installation and hence I tested builds on two different commits. One using
```
pip install .
```
and the other
```
pip install networkx
```
in `appveyor.yml`. There is not any problem of symbolic link in the case when we install NetworkX using `.` i.e. clone. But when we install it from pip, during `install_lib` there is `copying` of files into `build/`. The problem is with the copying of a symlink.

So, I think along with `atlas.py`, `chess_masters.py` and probably other ones also need fixing. Also, to be clear, there is no way of testing it other than releasing to pypi and then testing.

Sources: [Commit with `pip install .`](https://ci.appveyor.com/project/OrkoHunter/networkx/build/1.0.31)
[Commit with `pip install networkx`](https://ci.appveyor.com/project/OrkoHunter/networkx/build/1.0.32)

**Comment by ysitu** [comment]
I changed the issue subject to emphasize that the intention was to remove all symlinks.

**Comment by OrkoHunter** [comment]
Yes, this one's better actually. Thanks.

**Pull request merged**
