### PR TITLE
Use version 1.2draft by default and apply PEP8 to gexf.py

### PR DESCRIPTION
**Pull request by Michael-E-Rose**
Addresses #2312 (not sure if it fixes all of it).

* Use 1.2draft as default xml version
* Apply PEP8 were useful

### CODE REVIEW

**Comment by Michael-E-Rose** [comment]
The first two commits are not mine - how do I get rid of them?

**Comment by OrkoHunter** [comment]
@Michael-E-Rose You could try rebasing with the updated master. Probably that would help.

**Comment by Michael-E-Rose** [comment]
No it doesn't look like this solved the issue...

**Comment by OrkoHunter** [comment]
@Michael-E-Rose I only see one commit now :)

**Comment by Michael-E-Rose** [comment]
Oh great! So this PR is ready to be merged :)

**Comment by dschult** [comment]
I think this (#2355) is ready to go. 
There were other GML fixes recently that made two small conflicts.  
@Michael-E-Rose do you have time to fix them? If not I can do it.
Thanks.

**Comment by Michael-E-Rose** [comment]
The checks fail.  Seems I did something wrong in the merge. Is there a way to undo the merge and try again?

**Comment by dschult** [comment]
Based on #2436 I think you need to remove the ```viz``` part of line 293. 
You undid the change from #2436 when you merged. That change in a new commit might be easier than undoing the merge and redoing it.  But git allows you to revert and try again (google git revert).  You can also start a new branch from just before the merge with ```git checkout HEAD~1``` followed by ```git checkout -b new_name``` and try thr merge again...   still seems easier to change line 293 in ```test_gexf.py```

**Comment by Michael-E-Rose** [comment]
I pushed again with a minor change and thus could merge again. Hope this time I made no errors.

**Comment by Michael-E-Rose** [comment]
Thanks! I tested above merge solution on nosetests, but while they worked there, they did not work here. Maybe wrong branch...

**Pull request merged**
