### PR TITLE
Add pajek communities

### PR DESCRIPTION
**Pull request by joaquincabezas**
Pajek allows to define communities in a CLU file

In this PR we add support for reading and writing CLU files following:
- CLU format from Pajek specification
- Communities style following networkx's communities

Tests have been added for simple scenarios

### CODE REVIEW

**Comment by MridulS** [comment]
Thanks for this @joaquincabezas, this should close https://github.com/networkx/networkx/issues/3931 right?

**Comment by joaquincabezas** [comment]
yes, right!! In fact I've just remembered about the suggestion from @dschult of using read_pajek_clu as a better name. I will modify this right now

Next PR will create the VEC and PER, then proceed with the alias suggestion as well.

**Comment by dschult** [comment]
The failing CI test is not related to this (nightly build isn't available for cugraph).

This looks like the right approach.  I haven't had a chance to look at the details yet, but the big picture looks ok

**Comment by joaquincabezas** [comment]
> The failing CI test is not related to this (nightly build isn't available for cugraph).
> 
> This looks like the right approach. I haven't had a chance to look at the details yet, but the big picture looks ok

Good! Should I retrigger the CI/CD again once cugraph is available?

**Comment by dschult** [comment]
Could you merge or rebase to the current `main` branch?  If you don't have the resources to do that, let me know and I should be able to get to doing it in the next day or two. This error required us to change where we were looking for the cugraph stuff.

**Comment by joaquincabezas** [comment]
> Could you merge or rebase to the current `main` branch? If you don't have the resources to do that, let me know and I should be able to get to doing it in the next day or two. This error required us to change where we were looking for the cugraph stuff.

@dschult I don't have write access so I've just rebased it and now it passes al checks :)

**Comment by dschult** [comment]
The Pajek manual describes the CLU, VEC and PER file formats. It basically says that a CLU file has a single header line (with the number of lines in the file) followed by a community identifier for each node each on it's own line. It seems like this could be read by something like this:
```python
with open("filename.clu") as file:
    communities = {i: int(c) for i, c in enumerate(file.readlines()) if i > 0}

nx.set_node_attributes(G, communities, "community")
```

For writing a clu file, we write each node's community on a separate line.
```python
comm = nx.get_node_attributes(G, "community")
header = f"*vertices {len(G)}\r\n"
values = "\r\n".join(str(comm[n]) for n in range(1, len(G) + 1))

with open("filename.clu", 'w') as file:
    file.write((header + values).encode(encoding))
```

If this is correct, I'm -0.5 on including this functionality in NetworkX because it seems like something that users can do easily with basic python and doing so avoids having to maintain 4 more functions. The VEC and PER formats are similarly describing node attributes with a list of values in order from 1 to len(G). So, we would be avoiding 12 new functions.

We already support the Pajek network files. Should we support the node-attribute files, CLU, PER, VEC?

**Comment by joaquincabezas** [comment]
Hi! The whole idea of this is supporting the PAJ format, but without a monolithic function or duplicating code. I use the PAJ format because it includes the NET, CLU, VEC and PER into a single file with all of them aligned.

But you are right, maybe it’s too much adding lots of functions for a feature of little use, and in many docs and websites the Pajek format is associated just with the subformat NET, so this could even create confusion.

**Comment by dschult** [comment]
I think we should go ahead and close this PR.  Thanks for the effort you put into it!
But I think we will just include the network reading information to keep it simple and avoid maintenance headaches.

**Pull request closed without merging**
