### PR TITLE
`contracted_nodes` copy flag added

### PR DESCRIPTION
**Pull request by KanishkT123**
Added a copy switch to the function contracted_nodes that allows the passed in graph G to be changed in place as compared to having it be copied into a new graph first. 

This should significantly allow for some more efficient memory utilization with larger graphs, the caveat being that contracted_nodes now needs to store the edge values from the graph as a list in case of the original graph being changed in place, as the generators reflect the current state of the graph at all times.

### CODE REVIEW

**Comment by KanishkT123** [comment]
This is for #3607

**Comment by KanishkT123** [comment]
@dschult I also wanted to ask: The unit tests for contracted_nodes() seem to be using the complete_graph(3) instead of cyclic_graph(3). While this is correct theoretically, would it maybe be better practice to have the test still make comparisons between two cyclic graphs instead, to make it more clear what the test is doing? Just a thought, please ignore if I'm wrong.

**Comment by dschult** [comment]
Seems reasonable to change the expected test result to ```cyclic_graph(3)``` instead of the complete graph. Both are right, but cyclic shows what is being tested.

**Comment by dschult** [comment]
This looks good.  Can you check the PEP8 style guides using pycodestyle?
It mostly shows spacing irregularities: <80 chars per line, spaces after commas and around operators.

Thanks for this!

**Comment by KanishkT123** [comment]
Done!

**Comment by KanishkT123** [comment]
@dschult I think this is ready for merge, unless there are other changes I need to make? Let me know!

**Comment by dschult** [comment]
Yup -- ready to go...  Been a busy week.  Thanks for the gentle nudge. :)

**Pull request merged**
