### PR TITLE
Add triangular and hexagonal lattice generators

### PR DESCRIPTION
**Pull request by dschult**
Fixes #1489 conflicts and adds pep8 and comments and smoke tests.
Changed proposed name from triangle_lattice to triangular_lattice.

### CODE REVIEW

**Comment by jfinkels** [comment]
I objected to the suggested implementation and provided a simpler one in #1549. There I separated the graph generator from the layout code.

**Comment by dschult** [comment]
There seem to be two questions under discussion here:
- what to "name" the nodes
- whether to separate the graph creation from the layout

Our other grid graph generators name the nodes using tuples that hold coordinates (as embedded in a geometry). Can you (@jfinkels) explain the motivation behind the tuples used in #1549 for nodes in, say, ```triangle_lattice_graph```?

It looks like the separated layout functions can ONLY work with the specific lattice graphs -- that is, ```nx.triangular_lattice_layout(G, m, n)``` doesn't really need the input ```G``` as the only graph it works for is the graph created by ```nx.triangular_lattice_graph(m, n)```.  Is this correct?

Without good justifications for the node names in #1549 and a reason to separate the functions, I lean toward the approach from #1489. It reduces the number of functions overall and removes the need to translate between the "standard" coordinate names and the tuples stemming from a rectangular grid. comments?

**Comment by jfinkels** [comment]
> Our other grid graph generators name the nodes using tuples that hold coordinates (as embedded in a geometry). Can you (@jfinkels) explain the motivation behind the tuples used in #1549 for nodes in, say, ```triangle_lattice_graph```?

Sure. In terms of edge structure, the triangular lattice is just the grid graph with some edges added to the diagonals:

```text
o----o----o
| \  | \  |
|  \ |  \ |
o----o----o
| \  | \  |
|  \ |  \ |
o----o----o
```

The plain old 2D grid graph has simple (i, j) node labels, so I thought the triangular lattice would benefit from these simple names as well. The user can then access individual nodes directly by doing `G[(i, j)]`, where *i* and *j* are just integers, instead of having to use floating point numbers.

The hexagonal grid graph is similar, in that it is a subgraph (instead of a supergraph) of the 2D grid graph:

```text
o----o    o----o
|    |    |    |
o    o----o    o
|    |    |    |
o----o    o----o
|    |    |    |
o    o----o    o
|    |    |    |
o----o    o----o
```

> It looks like the separated layout functions can ONLY work with the specific lattice graphs -- that is, ```nx.triangular_lattice_layout(G, m, n)``` doesn't really need the input ```G``` as the only graph it works for is the graph created by ```nx.triangular_lattice_graph(m, n)```.  Is this correct?

Following the idea above, the triangular lattice layout really works for any graph with nodes labeled like the 2D grid graph. It is just a linear transformation of the grid layout. The hexagonal layout function is a different but still fairly simple transformation.

> Without good justifications for the node names in #1549 and a reason to separate the functions, I lean toward the approach from #1489. It reduces the number of functions overall and removes the need to translate between the "standard" coordinate names and the tuples stemming from a rectangular grid. comments?

If you do this, please consider concatenating the code from my two functions (the graph generator and the layout function) together into a single function. It avoids a lot of unnecessary code!

**Comment by dschult** [comment]
Two links to discussions and definitions:
[Amit's thoughts on grids](http://www-cs-students.stanford.edu/~amitp/game-programming/grids/)
[Wikipedia on Triangular Tiling](https://en.wikipedia.org/wiki/Triangular_tiling)

I think its best to name the vertices according to a coordinate system the way #1549 has it, but add the positions as an attribute the way #1489 has it. I'll see what I can put together.

**Comment by dschult** [comment]
This PR on triangular and hexagonal is ready.

I stuck with rows and columns referring to how many grid units rather than how many nodes.
The embedding is standard.  For the periodic case I shifted the y-coordinate slightly in a nonlinear way so that the edges show. Periodic isn't a planar embedding anyway. 

Nodes are integer 2-tuples named using coordinates starting from the lower left.

Positions are stored on the graph by default but can be turned off with optional argument.
I did not provide options for side-length or offset. Perhaps some layout utility functions can be created for that sort of thing.

A new module called ```lattice.py``` and corresponding tests are now separated from ```classic.py``` and include grid_graphs and these new lattice graphs.

**Pull request merged**
