### PR TITLE
remove usage of 'tempfile.mkstemp' in favour of a 'NamedTemporaryFile'

### PR DESCRIPTION
**Pull request by danieleades**
replaces a low-level API with a context manager

### CODE REVIEW

**Comment by danieleades** [comment]
> _ No description provided. _

**Review by rossbar — COMMENTED** [review]
I'd vote for the replacements in the test suite to use the `tmp_path` pytest fixture rather than using `tempfile` directly. IIRC `tempfile` has some unfortunately platform-dependent behavior.

**Comment by danieleades** [comment]
> I'd vote for the replacements in the test suite to use the `tmp_path` pytest fixture rather than using `tempfile` directly. IIRC `tempfile` has some unfortunately platform-dependent behavior.

the only platform-dependent behaviour i'm familiar with is obviated by the `delete=True` flag. Are you aware of any other platform-dependent behaviour?

i'm afraid i'm not familiar enough with `pytest` to migrate to a fixture

**Comment by MridulS** [comment]
Closing this as https://github.com/networkx/networkx/pull/7221 uses the pytest native fixture to remove tempfile. Thanks for your work on this @danieleades !

**Pull request closed without merging**
