### PR TITLE
Added example script for GOT

### PR DESCRIPTION
**Pull request by PurviChaurasia**
This script helps visualize the character relationships in the series game of thrones. The output is as follows - 
image

This is in reference to issue #6482

### CODE REVIEW

**Comment by PurviChaurasia** [comment]
@MridulS @dschult I was downloading the dataset in my local machine and using it but that gives an error for the documentation. How should I resolve it?

**Comment by MridulS** [comment]
Examples are good but we shouldn't be adding everything as an example :)

I'm not too sure if this adds anything new, that isn't already in other examples. Drawing and coloring networks seems to be covered well by https://networkx.org/documentation/latest/auto_examples/index.html#drawing

**Comment by PurviChaurasia** [comment]
Alright :) I just thought a more relatable example like this would help people outside the scientific community as well to get interested in exploring networkX :)

**Comment by PurviChaurasia** [comment]
In the notebook, I'll be covering other analysis as well such as important characters based on degree centrality and the character arcs across various books. I understand if this doesn't match with NetworkX expectations from the interns so feel free to let me know!

**Comment by MridulS** [comment]
Well I'll be biased as I made this very notebook a long time back (~ 6 years I think now 😅) https://ericmjl.github.io/Network-Analysis-Made-Simple/05-casestudies/01-gameofthrones/ and it's already out there 😅 

But it would be nice to get more real world "academic" datasets like protein networks, interactome, sociological networks. As this is one of often requested examples. Showing users how to use networkx in more (and new) research areas and helping them giving a basic overview of networkx is one of the aims of nx-guides.

**Comment by PurviChaurasia** [comment]
Oh really! That's a coincidence, I guess interests don't change 😅. But sure I'll look into other real world examples as well!

**Pull request closed without merging**
