### PR TITLE
Add support of Sugiyama layout through [Microsoft Automatic Graph Layout](https://github.com/microsoft/automatic-graph-layout)

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Review by rossbar — COMMENTED** [review]
Thanks for the bringing this up @KOLANICH . I'm -1 on adding this as a dependency. It'd be +1 for adding the sugiyama layout, but a native implementation would be a better fit for networkx.

**Comment by MridulS** [comment]
Maybe this could go as an example in the gallery?

**Comment by rossbar** [comment]
> Maybe this could go as an example in the gallery?

Even within the example gallery this adds a (seemingly) large dependency footprint; my two cents is this is not a good fit for upstreaming in networkx. Just my two cents though!

**Comment by KOLANICH** [comment]
OK, I can move it into a separate package.

**Pull request closed without merging**
