### PR TITLE
Optimize multipartite_layout

### LINKED ISSUE #4061: Tighten partite_layout if/else code.
Tighten up the bipartite_layout and multipartite_layout  if/else as describes in #3815

### PR DESCRIPTION
**Pull request by z3y50n**
Fixes #4061 

Since the logic for drawing the graph in both `vertical` and `horizontal` alignment is the same we can use one loop and just flip the positions.

Results are the same as before.

### CODE REVIEW

**Review by dschult — APPROVED** [review]
Nice!   That certainly reduces the duplicated code. :)

**Review by rossbar — COMMENTED** [review]
Looks good - there is a similar pattern in `bipartite_layout` that would be good to fix in this PR as well if you have the time. If not, we can merge this one but leave the issue open.

**Comment by z3y50n** [comment]
Yes I was thinking the same thing, I will work on fixing `bipartite_layout` as well

**Review by rossbar — APPROVED** [review]
Awesome, thanks @z3y50n , LGTM!

**Pull request merged**
