### PR TITLE
Adding an Example Map for GSoC Proposal

### PR DESCRIPTION
**Pull request by stanyas**
I am addressing the issue [5510](https://github.com/networkx/networkx/issues/5510).

Please, disregard the first two commits, this is my first time making a pull request, and I experimented.

### CODE REVIEW

**Comment by stanyas** [comment]
graphs

This is how the example graph looks

**Comment by MridulS** [comment]
Before the review just wanted to point out that the GSoC application deadline is under 4 hours so please submit the application before that, Google is pretty strict with deadlines :)

**Comment by stanyas** [comment]
> Before the review just wanted to point out that the GSoC application deadline is under 4 hours so please submit the application before that, Google is pretty strict with deadlines :)

Thanks, I was working on it. I submitted.

**Comment by NikitaSharma1** [comment]
@stanyas I faced a similar issue in style in the start as you are facing now. I was told to make the following changes and it worked for me. 
 `One thing that will need to be done is to ensure that the docstring examples are properly formatted, i.e. the code in the examples follows the black formatting rules. Since these examples are small, it may be easy enough to fix up the formatting manually. Alternatively, I believe a pre-commit hook has been recently added to handle doc formatting automatically, so updating your development environment with the latest pre-commit hooks would likely work too`
I think you should try this too. 
Please correct me if I'm wrong.

**Comment by NikitaSharma1** [comment]
@stanyas I faced a similar issue in style in the start as you are facing now. I was told to make the following changes and it worked for me. 
 `One thing that will need to be done is to ensure that the docstring examples are properly formatted, i.e. the code in the examples follows the black formatting rules. Since these examples are small, it may be easy enough to fix up the formatting manually. Alternatively, I believe a pre-commit hook has been recently added to handle doc formatting automatically, so updating your development environment with the latest pre-commit hooks would likely work too`
I think you should try this too. 
Please correct me if I'm wrong.

**Comment by stanyas** [comment]
> @stanyas I faced a similar issue in style in the start as you are facing now. I was told to make the following changes and it worked for me. `One thing that will need to be done is to ensure that the docstring examples are properly formatted, i.e. the code in the examples follows the black formatting rules. Since these examples are small, it may be easy enough to fix up the formatting manually. Alternatively, I believe a pre-commit hook has been recently added to handle doc formatting automatically, so updating your development environment with the latest pre-commit hooks would likely work too` I think you should try this too. Please correct me if I'm wrong.

Thanks, you were right!

**Comment by MridulS** [comment]
Thanks for starting discussion on this one @stanyas, we can use https://github.com/networkx/networkx/issues/5824 for further discussion on this one :)

**Pull request closed without merging**
