### PR TITLE
Updating contributors for GSoC 2021

### PR DESCRIPTION
**Pull request by mjschwenne**
Hello!

I am one of the Google Summer of Code students this year and my project is quickly drawing to a close, I just need to ensure that my updates to the documentation are correctly shown in the NetworkX documentation. At my mentor meeting yesterday @dschult suggested that I create a new PR with this change so that I am no longer considered a first time contributor. This will cause my commits to automatically create the documentation build artifact  on my main PR so I know that my changes are correct.

### CODE REVIEW

**Comment by dschult** [comment]
This has a lot of commits that I don't think you intended.
Can you try again (perhaps easiest to start with a new branch and PR).
Go to your main branch, pull from the upstream networkx repo to ensure you are starting from the current version.
Just change the one file for contributors and the commit, push, create the PR.

**Comment by mjschwenne** [comment]
So there are a lot more commits here than I would like, but I'm not sure how to fix it. 

Over the course of the summer I've been keeping my main branch up to date which is what all of the  `Merge branch 'networkx:main' into main` commits are from. The early ones talking about the minimum spanning trees are commits that I erroneously put on main rather than my GSoC PR and all of the merge stuff was me trying to write those changes out of my main so that it matched the networkx main. 

This PR was created from a new branch off of my main branch just like you suggested in your comment. If there is something else I can try to clean up this mess, that would be awesome.

**Comment by mjschwenne** [comment]
All of those earlier changes are gone and the only change left should be the contributor update.

**Comment by dschult** [comment]
The "files changed" tab still lists 15 files as being changed.

Maybe try this: 
```
git branch move main original_main
git ch upstream/main   # will warn about being in a headless state and tell you to do something like the following
git ch -b main
#  now you can fix you github repo's main branch if you want... but you don't have to. You probably never use it.
#  then make the changes in a new branch off this new main
git ch -b update-contributors
# make the change, commit, push to your repo, create a new PR, delete this PR.
```

**Comment by mjschwenne** [comment]
When I run `git ch` I am given

```
git: 'ch' is not a git command. See 'git --help'.

The most similar command is
	fetch
```

**Comment by MridulS** [comment]
try with ch -> checkout ?

**Comment by MridulS** [comment]
`git checkout upstream/main` to be precise.

**Comment by mjschwenne** [comment]
New PR is #5020

**Comment by dschult** [comment]
Sorry for the `ch` -> `checkout`   
I made `ch` an alias in my git config file so I don't have to type checkout so often.  Similarly for `br` -> branch, but I don't think I left any `br` in the examples I typed above. :}

Anyway, if you are interested and want to explore git more, check out their aliases... :}

**Pull request closed without merging**
