### PR TITLE
Remove http server example

### PR DESCRIPTION
**Pull request by intrepidlemon**
The HTTP Server script in the examples does not demonstrate any `networkx` functionality and seems irrelevant and confusing in the context of the rest of the package. This PR simply removes the script and edits the one other script that depends on it.

### CODE REVIEW

**Comment by hagberg** [comment]
It's not the first time I've gotten such a compliment but usually it is for my research papers not code :smile:.
I think I wrote that since I figured people might not run e.g. chrome with -disable-web-security etc. in order to see the results.  But we could suggest that if is more relevant and understandable.  It still doesn't work with lynx though.

**Comment by intrepidlemon** [comment]
Ah forgive my ignorance. I have added in a simple flask server into `force.py` to host the example with a clear comment about why it is necessary.

**Comment by hagberg** [comment]
That could work.  But it adds another dependency (flask).

**Comment by intrepidlemon** [comment]
While it is annoying to have to add another dependency, the example gains clarity. This modification will hopefully prevent users from experiencing the same confusion that I experienced when I first tried to use this example.

**Pull request merged**
