### PR TITLE
Add weight function for shortest simple paths for #3948

### PR DESCRIPTION
**Pull request by cmkpl**
Add this function for aligning the weight function in shortest paths class.

### CODE REVIEW

**Comment by dschult** [comment]
Thanks for this! 
Can we use the [utility function currently](https://github.com/networkx/networkx/blob/master/networkx/algorithms/shortest_paths/weighted.py#L40) in ```algorithms/shortest_paths/weighted.py``` called ```_weight_function```? 

I think that could remove a lot of the extra code that is deciding which way to compute weights. It might even be faster, though that is hard to predict in Python. The idea would be to call this centrally defined function on the input ```weight``` and then use the returned value as a function that computes the weight for each edge. The checking for multigraph is done once when ```weight``` is defined.  It's also possible it doesn't work for this case, but I think it does work.

I guess you'd have to import with a long name like: 
```python
from networkx.algorithms.shortest_paths.weighted import _weight_function
```

**Comment by cmkpl** [comment]
Thanks for your suggestion.  Please find the updated commit in this request.

**Comment by dschult** [comment]
This looks good... Thanks!!
While I've got your attention, I've been thinking that a better name of this function would be something like ```simple_paths_by_length```. Does this make sense to you?  
I don't want to do it in this PR.  I'll talk to more people and do it as part of prep for v2.5.
But do you think of the old name? of  the proposed name?

**Comment by cmkpl** [comment]
It seems like `simple_paths_by_length` implies that length is a `parameter` to be used which is optional.  How about something like `simple_paths_sorted_by_length`? But it is a bit long and not aligned with the conventions like `lexicographical_topological_sort`.

What concerned me the most is whether it will break the backward compatibility.

**Comment by dschult** [comment]
Yes, I agree that backward compatibility is important.   Maybe when we go to v3.0...
The problem with ```shortest_simple_paths``` is that it yields paths that aren't the shortest.

**Pull request merged**
