### PR TITLE
Add Mypy type checking infrastructure

### PR DESCRIPTION
**Pull request by rossbar**
The purpose of this PR is to evaluate the impact of adding the static type checker Mypy to the development workflow of NetworkX. This PR **does not add any type annotations**! The goal is to see what impact the static type checker has on the existing code base. Adding this infrastructure is the first step in enabling support for type annotations moving forward. This PR also aims to focus the discussion in #5073 and provide an objective accounting of what sort of things `mypy` catches in the NX codebase and how these issues can be fixed.

## Mypy errors in the existing code

The first step in the analysis is to ascertain what mypy reports on the existing codebase, which doesn't contain any type annotations (with the exception of one function). This can be done on `main` in an existing development environment as follows:

```bash
pip install mypy
pip install -e .  # A development install of networkx
mypy --ignore-missing-imports -p networkx
```

Note: the `--ignore-missing-imports` flag is necessary to suppress mypy errors from missing type annotations in dependencies (e.g. scipy). Note also that the `-p networkx` flag is preferable as it only runs the type checking on the installed `p`ackage, ignoring things like `setup.py`. The above incantation will limit the reported errors to those found specifically within the networkx codebase.

On a50c8e6d, this results in 53 mypy errors:

<details>
  <summary>Mypy errors (added lineno for convenience)</summary>
<pre>
<ol>
<li>networkx/readwrite/nx_shp.py:330: error: Assignment to variable "e" outside except: block</li>
<li>networkx/classes/reportviews.py:1327: error: Incompatible types in assignment (expression has type "Type[OutMultiEdgeDataView]", base class "OutEdgeView" defined the type as "Type[OutEdgeDataView]")</li>
<li>networkx/classes/reportviews.py:1379: error: Incompatible types in assignment (expression has type "Type[MultiEdgeDataView]", base class "OutEdgeView" defined the type as "Type[OutEdgeDataView]")</li>
<li>networkx/classes/reportviews.py:1405: error: Incompatible types in assignment (expression has type "Type[InMultiEdgeDataView]", base class "OutEdgeView" defined the type as "Type[OutEdgeDataView]")</li>
<li>networkx/utils/decorators.py:95: error: Need type annotation for "_dispatch_dict"</li>
<li>networkx/utils/decorators.py:96: error: Incompatible types in assignment (expression has type overloaded function, target has type overloaded function)</li>
<li>networkx/utils/decorators.py:97: error: Incompatible types in assignment (expression has type "Type[BZ2File]", target has type overloaded function)</li>
<li>networkx/utils/decorators.py:98: error: Incompatible types in assignment (expression has type overloaded function, target has type overloaded function)</li>
<li>networkx/readwrite/graphml.py:1002: error: Assignment to variable "e" outside except: block</li>
<li>networkx/generators/line.py:122: error: All conditional function variants must have identical signatures</li>
<li>networkx/classes/graphviews.py:162: error: All conditional function variants must have identical signatures</li>
<li>networkx/algorithms/d_separation.py:109: error: "AbstractSet[Any]" has no attribute "union"</li>
<li>networkx/algorithms/community/lukes.py:186: error: Need type annotation for "bp_buffer" (hint: "bp_buffer: Dict[<type>, <type>] = ...")</li>
<li>networkx/algorithms/bipartite/edgelist.py:136: error: Assignment to variable "e" outside except: block</li>
<li>networkx/algorithms/bipartite/edgelist.py:141: error: Assignment to variable "e" outside except: block</li>
<li>networkx/algorithms/approximation/kcomponents.py:216: error: Incompatible types in assignment (expression has type "Callable[[_AntiGraph], Any]", base class "Graph" defined the type as "Type[Dict[Any, Any]]")</li>
<li>networkx/algorithms/connectivity/__init__.py:13: error: Need type annotation for "__all__"</li>
<li>networkx/algorithms/connectivity/__init__.py:15: error: Name "connectivity" is not defined</li>
<li>networkx/algorithms/connectivity/__init__.py:16: error: Name "cuts" is not defined</li>
<li>networkx/algorithms/connectivity/__init__.py:17: error: Name "edge_augmentation" is not defined</li>
<li>networkx/algorithms/connectivity/__init__.py:18: error: Name "edge_kcomponents" is not defined</li>
<li>networkx/algorithms/connectivity/__init__.py:19: error: Name "disjoint_paths" is not defined</li>
<li>networkx/algorithms/connectivity/__init__.py:20: error: Name "kcomponents" is not defined</li>
<li>networkx/algorithms/connectivity/__init__.py:21: error: Name "kcutsets" is not defined</li>
<li>networkx/algorithms/connectivity/__init__.py:22: error: Name "stoerwagner" is not defined</li>
<li>networkx/algorithms/connectivity/__init__.py:23: error: Name "utils" is not defined</li>
<li>networkx/readwrite/tests/test_gml.py:291: error: Name "test_float_label" already defined on line 274</li>
<li>networkx/classes/tests/test_subgraphviews.py:196: error: List item 0 has incompatible type "Tuple[int, int, int]"; expected "Tuple[int, int]"</li>
<li>networkx/classes/tests/test_subgraphviews.py:196: error: List item 1 has incompatible type "Tuple[int, int, int]"; expected "Tuple[int, int]"</li>
<li>networkx/classes/tests/test_subgraphviews.py:196: error: List item 2 has incompatible type "Tuple[int, int, int]"; expected "Tuple[int, int]"</li>
<li>networkx/classes/tests/test_subgraphviews.py:197: error: Argument 1 to <set> has incompatible type "Tuple[int, int, int]"; expected "Tuple[int, int]"</li>
<li>networkx/classes/tests/test_subgraphviews.py:197: error: Argument 2 to <set> has incompatible type "Tuple[int, int, int]"; expected "Tuple[int, int]"</li>
<li>networkx/classes/tests/test_subgraphviews.py:197: error: Argument 3 to <set> has incompatible type "Tuple[int, int, int]"; expected "Tuple[int, int]"</li>
<li>networkx/classes/tests/test_subgraphviews.py:197: error: Argument 4 to <set> has incompatible type "Tuple[int, int, int]"; expected "Tuple[int, int]"</li>
<li>networkx/classes/tests/test_reportviews.py:1100: error: Incompatible types in assignment (expression has type "Type[DiDegreeView]", base class "TestDegreeView" defined the type as "Type[DegreeView]")</li>
<li>networkx/classes/tests/test_reportviews.py:1110: error: Incompatible types in assignment (expression has type "Type[OutDegreeView]", base class "TestDegreeView" defined the type as "Type[DegreeView]")</li>
<li>networkx/classes/tests/test_reportviews.py:1160: error: Incompatible types in assignment (expression has type "Type[InDegreeView]", base class "TestDegreeView" defined the type as "Type[DegreeView]")</li>
<li>networkx/classes/tests/test_reportviews.py:1210: error: Incompatible types in assignment (expression has type "Type[MultiDegreeView]", base class "TestDegreeView" defined the type as "Type[DegreeView]")</li>
<li>networkx/classes/tests/test_reportviews.py:1260: error: Incompatible types in assignment (expression has type "Type[DiMultiDegreeView]", base class "TestDegreeView" defined the type as "Type[DegreeView]")</li>
<li>networkx/classes/tests/test_reportviews.py:1270: error: Incompatible types in assignment (expression has type "Type[OutMultiDegreeView]", base class "TestDegreeView" defined the type as "Type[DegreeView]")</li>
<li>networkx/classes/tests/test_reportviews.py:1320: error: Incompatible types in assignment (expression has type "Type[InMultiDegreeView]", base class "TestDegreeView" defined the type as "Type[DegreeView]")</li>
<li>networkx/algorithms/traversal/tests/test_edgedfs.py:7: error: Module has no attribute "edgedfs"; maybe "edge_dfs" or "edge_bfs"?</li>
<li>networkx/algorithms/traversal/tests/test_edgedfs.py:8: error: Module has no attribute "edgedfs"; maybe "edge_dfs" or "edge_bfs"?</li>
<li>networkx/algorithms/traversal/tests/test_edgebfs.py:7: error: Module has no attribute "edgedfs"; maybe "edge_dfs" or "edge_bfs"?</li>
<li>networkx/algorithms/traversal/tests/test_edgebfs.py:8: error: Module has no attribute "edgedfs"; maybe "edge_dfs" or "edge_bfs"?</li>
<li>networkx/algorithms/tests/test_smallworld.py:11: error: Incompatible types in assignment (expression has type "int", variable has type "Random")</li>
<li>networkx/algorithms/tests/test_graph_hashing.py:458: error: Name "test_isomorphic_edge_attr_and_node_attr" already defined on line 184</li>
<li>networkx/algorithms/tests/test_cycles.py:8: error: Module has no attribute "edgedfs"; maybe "edge_dfs" or "edge_bfs"?</li>
<li>networkx/algorithms/tests/test_cycles.py:9: error: Module has no attribute "edgedfs"; maybe "edge_dfs" or "edge_bfs"?</li>
<li>networkx/algorithms/flow/tests/test_maxflow.py:22: error: Need type annotation for "interface_funcs"</li>
<li>networkx/algorithms/flow/tests/test_maxflow.py:23: error: Need type annotation for "all_funcs"</li>
<li>networkx/algorithms/approximation/tests/test_traveling_salesman.py:42: error: "classmethod" used with a non-method</li>
<li>networkx/classes/tests/test_multigraph.py:220: error: Need type annotation for "single_edge"</li>
</ol>
Found 53 errors in 22 files (checked 560 source files)
</pre>
</details>

Some of these errors are obvious bugs with easy fixes, some are the result of mypy having some style checking baked in, and others seem to be deeper issues related to some design patterns in NetworkX not necessarily agreeing with rules enforced by mypy, or issues surrounding inheritance. The remainder of the commits in this PR address the errors individually.

## Resolving MyPy errors

It should be noted that the universal way to suppress mypy errors is to ignore type checks on individual objects using `# type: ignore`. I tried my best to minimize this usage here and address errors directly rather than ignoring them.

Below is a table that maps the commit hash to which mypy error(s) the patches fix. Below the table is a bit more discussion on the various mypy errors.

### Summary

| commit | mypy err no | note |
| ------ | ----------- | ---- |
| c2b8061 | 42-45 |  Properly import sentinels from traversal.edgedfs. |
| 4cda3fd | 1, 9, 14, 15 |  mypy doesn't like variables named \"e\".  |
| 832cd96 | 12 |  Rm annotations from single function. |
| 9f282da | 27, 47 |  Fix name collisions in test suite. |
| 2b8bfc8 | 46 |  Rm unused random seed in test setup. |
| f0c1c87 | 17-26 |  Rm redundant __all__ specification. |
| 1e4a262 | 50, 51 |  Silence mypy error from sum(). Mypy bug? |
| 4276842 | 52 | Fix tsp test instantiation nit. |
| 8600277 | 10, 11 |  \"type: ignore\" to suppress conditional fn sigature errors. |
| 81bbe5b | 5-8, 13, 16, 53 |  Remaining \"type: ignore\" to appease mypy. |
| 7607f8c | 2-4, 28-41 | Configure mypy to ignore inheritance issues. |

I've broken down the errors in the `details` section into two categories: those that require minor changes, and those that might be more involved. I've also set the history so that each commit deals with a particular type of mypy error.

### Minor fixups
 -  c2b8061 fixes some import patterns, switching to importing objects from the correct module directly rather than making local variables that point to objects in a different namespace. A minor improvement IMO.
 - 4cda3fd: `mypy` doesn't allow `e` as a variable name unless it is bound to an exception in a try/except statement. IMO this is more of a style consideration than type-checking, and I'm a little surprised `mypy` is so opinionated about it. Nevertheless, it's easy enough to change to a more descriptive variable name.
 - 832cd96: It turns out there was at least [one function in NetworkX](https://github.com/networkx/networkx/blob/ead0e65bda59862e329f2e6f1da47919c6b07ca9/networkx/algorithms/d_separation.py#L70) that already had inline type annotations. The mypy errors could be fixed by `AbstractSet` -> `Set`, but I just removed them in this PR so that we're starting from a clean slate.
 - 9f282da: `mypy` identified a couple instances in the test suite where different tests had the same name. Fixed these here, which is an obvious minor improvement.
 - 2b8bfc8: The type checking also identified an unused local variable (in this case, an unused random number seed) in the test suite.
 - f0c1c87: There's [some discussion in 5073](https://github.com/networkx/networkx/pull/5073#discussion_r725312949) about a limitation in mypy in handling imported objects. However; AFAICT the `__all__` definition here is redundant so I just removed it.
 - 1e4a262: Not sure what's going on here - `mypy` complains about some lists that are defined by combining other lists using the `sum([l1, l2], [])` pattern. For whatever reason `mypy` stops complaining if I modify one of these definitions (but not the other). Maybe this is a mypy bug?
 - 4276842: Mypy identified a usage of the `@classmethod` decorator outside of a class. Fixed this by slightly reorganizing the TSP tests.
 - 81bbe5b: This represents the final set of mypy errors that I couldn't figure out how to "fix" without typing, so I ended up adding the `# type: ignore` to suppress them.

### Larger issues

There was a second class of mypy errors related to larger issues where potential paths forward were less obvious than the above. These were largely related to two things:
 1. Class inheritance.
 2. Mypy disallows conditionals that define functions with the same name but different signatures.

I'll start with the second point. Mypy disallows conditionally defining a function that has a different signature, e.g.

```python
if True:
    def myfunc(a):
        pass
else:
    def myfunc(a, b):
        pass
```
NetworkX uses this pattern in at least a couple places to deal with e.g. difference in edge lookup for graphs and multigraphs: 

https://github.com/networkx/networkx/blob/44680a2466c3c429d9c01f55d71952efbb09b25c/networkx/generators/line.py#L115-L123

There are ways to "hack" around this by restructuring the conditionals and/or renaming to get rid of the mypy errors, but they make the code less readable. There is already some discussion on how best to fix one of these instances in #4459 . Fixing these generically in a way that doesn't reduce the readability of the code wasn't immediately obvious to me, so I kicked the can by marking these with `# type: ignore` in 8600277

The last set of mypy errors were related to (implied) type collisions when overriding members of child classes. Some of these occur in the test suite and would be remedied by switching from a class-based structure to a more pytest-y/fixture-based design (which IMO is a good idea regardless of mypy). Others are related to core structures like those in `reportviews.py`. #5073 proposes one solution for solving these issues by tweaking the initialization of some of the view objects, pulling it out of `__init__` methods and into a `_create_attributes` method, but I'm not sure it improves the readability of the code. Since dealing with these inheritance-based typing issues struck me as more complicated than some of the others, I proposed to ignore them by `excluding` the files where they are defined from type checking in 4918c7e.

## Adding type checking to workflow

Finally, this PR adds `mypy` to the GH workflow: 737ebe3 and 4918c7e.

### CODE REVIEW

**Comment by stefanv** [comment]
The error in `lukes.py` originates from it being partially, but not fully, annotated.  Removing the existing type annotations silences the `bp_buffer` error.

**Comment by NeilGirdhar** [comment]
> Also, the mypy.ini is 3 lines long, so no big issue to port it later :)

Yeah, but it shouldn't be 3 lines long either.  It should be something like
```toml
[tool.mypy]
warn_redundant_casts = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ['scipy', 'scipy.sparse', 'scipy.optimize', 'scipy.linalg', 'scipy.sparse.linalg',
       'pandas', 'osgeo', 'pygraphviz', 'pydot', 'ogr', 'lxml', 'lxml.etree', 'PIL',
       'matplotlib', 'matplotlib.pyplot', 'matplotlib', 'matplotlib.collections',
       'matplotlib.colors', 'matplotlib.patches', 'matplotlib.path', 'matplotlib.cm', 'scipy.stats',
       'scipy.linalg.blas', 'scipy.spatial', 'scipy.special']
ignore_missing_imports = true
```

**Comment by NeilGirdhar** [comment]
This looks amazing so far.  Any progress on getting this pushed?

**Comment by rossbar** [comment]
Okay, I've rebased to resolve the merge conflicts and patched up the few additional `mypy` errors that cropped up since the last review.

**Review by jarrodmillman — APPROVED** [review]

**Comment by stefanv** [comment]
I am going to take the liberty of merging this pull request.  I think @rossbar has done a stellar job at researching and addressing each individual issue. This PR satisfies MyPy, ensures that we don't breach MyPy typing rules in the future, and leaves us with the opportunity to more explicitly address typing at a time of our choosing.

**Comment by stefanv** [comment]
I notice now that creating a merge commit is disabled, so I'll go with "Squash and merge" since "Rebase and merge" feels like the wrong option.

**Comment by NeilGirdhar** [comment]
Woohoo!  Congrats and thank you for finishing this up!

**Pull request merged**
