### PR TITLE
Add preserve_all_attrs to convert_from_nx to make it concise

### PR DESCRIPTION
**Pull request by MridulS**
implements the idea by @eriknw in https://github.com/networkx/networkx/pull/6688/files#issuecomment-1652314158

### CODE REVIEW

**Review by dschult — COMMENTED** [review]
This looks great!   :tada:

Minor nit:  Can you make one line decorators e.g. where we only have arguments `graphs` and `preserve_all_attrs`?

**Comment by MridulS** [comment]
The addition of `preserve_all_attrs` made the local variable scope unhappy, so went with another implementation.

**Comment by eriknw** [comment]
Yeah, I think the scoping thing will be better if we made `_dispatch` a class instead of using closures.

LGTM!

**Review by dschult — APPROVED** [review]
This looks good!  Thanks!

**Comment by MridulS** [comment]
Merging this as Erik LGTM'd

**Pull request merged**
