### PR TITLE
Remove *iter functions

### PR DESCRIPTION
**Pull request by MridulS**
This PR builds up on https://github.com/networkx/networkx/pull/1537 by @jfinkels . In this PR I have removed
* `edges_iter` for Di/Multi/Graphs
* `out_edges_iter` and `in_edges_iter` for Multi/Digraphs
* `neighbors_iter` for Di/Multi/Graphs [UPDATE 1] 
* `predecessors_iter` and `successors_iter` for Multi/DiGraphs [UPDATE 2]

Now `edges`, `out_edges`, `in_edges` , `neighbors` return iterators instead of lists.
@dschult @hagberg @ysitu 
Related issues: https://github.com/networkx/networkx/issues/1485 https://github.com/networkx/networkx/issues/572
NOTE: To be merged after release of 1.10

### CODE REVIEW

**Comment by ysitu** [comment]
It seems that you are are outright removing them. That is okay, but that is not what deprecation means.

**Comment by MridulS** [comment]
Yeah, I wanted to ask about that and the functions in timingclass.py .

**Comment by ysitu** [comment]
The commit message still contains "Deprecate". Normally you should not modify published stuff, but I think that it is okay in this case since this is code in review. BTW, please document those functions as deprecated in `api_1.10.rst` (rename from `api_2.0.rst`).

**Comment by dschult** [comment]
I think the point of the timing classes is to see how timing changes over the revisions, so I naively think they should not be changed. Once the changes are clear and we're comfortable with the timing of them we can update the timingclasses.

**Comment by MridulS** [comment]
@dschult So should I revert the changes that I made in timing classes?
@ysitu I think this has been discussed before that changes in API (removing `*iter` functions) will be a part of 2.0 rather than 1.10

**Comment by ysitu** [comment]
You seem to be confused. Removal is in 2.0, but deprecation is in 1.10. So what I said was correct. They should documented as such in `api_1.10.rst`.

**Comment by MridulS** [comment]
Yeah, got it. So, I should send in a different PR regarding it right?

**Comment by ysitu** [comment]
I figure that we should handle this PR as is so that you do not have to roll back your work. But for the remaining functions, please remove exactly one of them at a time so that we can have easier reviews.

**Comment by MridulS** [comment]
@dschult The doctests in timingclasses.py depend on the original classes of Di/Multi/Graphs rather than timing classes so they are failing in this case. What do you suggest?

**Comment by dschult** [comment]
I think the easiest way to skip the doctests in timingclasses.py is to add a few lines at the bottom of the module.


    # Only to make the doctest feature of nosetests skip testing doctests
    def setup_module(module):
        from nose import SkipTest
        raise SkipTest("Skip nose doctests for timingclasses module")

**Comment by MridulS** [comment]
The latest commit has passed all tests on travis but it is not showing the green tick. Please someone restart it. @dschult @ysitu

**Comment by jfinkels** [comment]
One way to retrigger a Travis build if necessary is to close and reopen the
pull request.

**Comment by MridulS** [comment]
@jfinkels True, but that creates a lot of unnecessary noise in the PR :)

**Comment by chebee7i** [comment]
Weird. Travis finished, but Coverall's didn't get the info. I've restarted the two relevant jobs within that build. Maybe it will go this time.

**Comment by MridulS** [comment]
Removed neighbors_iter(), updated the PR.

**Comment by ysitu** [comment]
Please split the PR into one PR per function. Removing everything at a time is going to make the PR unreviewable.

**Comment by MridulS** [comment]
@ysitu You can always use https://github.com/networkx/networkx/pull/1546/commits to navigate and review different commits (functions) :) I am working on splitting them up.

**Comment by OrkoHunter** [comment]
@MridulS One single commit in this PR is large enough altering several classes and modules. You should not only split the commit into relevant ones but also make different PRs for them which can give way for separate discussions for the functions. This helps in maintaining a clean git history.

**Comment by MridulS** [comment]
@ysitu I tried splitting the changes, but I couldn't find a good way to have different Pull Requests from same branch. 
I think we should keep all the changes in one branch (in one PR) because they will cause a lot of merge conflicts as there are many commits in one file and these changes should be merged to the master repo at one go as they touch a lot of files. 
I can split up commits for one function in many different commits if that helps in reviewing this PR. :) What do you suggest?

@dschult @jfinkels @hagberg @chebee7i

**Comment by debugger22** [comment]
I think you can have only one PR from one branch. Why not use `git cherry-pick`?

**Comment by MridulS** [comment]
@debugger22 I think we should keep all the changes in one PR and should be merged at once. It will create a lot of merge conflicts if we keep functions in different PRs.

**Comment by chebee7i** [comment]
Would it make review easier to create a new branch and push it upstream. Then you coukd submit multiple PRs to it. Once ready, we could merge back into master.

**Comment by MridulS** [comment]
@chebee7i That sounds good. :)

**Comment by MridulS** [comment]
@chebee7i can you create a new branch for the same

**Comment by chebee7i** [comment]
Sure thing. I'll base it off current master?

**Comment by MridulS** [comment]
@chebee7i  Yeah sure.

**Comment by chebee7i** [comment]
It is up now:  iter_refactor

**Comment by chebee7i** [comment]
Let's close this now then. Look for multiple PRs to https://github.com/networkx/networkx/tree/iter_refactor from here on out. @MridulS feel free to re-open if necessary, but I suspect all the info you need is on your own fork.

**Comment by MridulS** [comment]
@chebee7i Thanks :)

**Pull request closed without merging**
