### PR TITLE
Adds functions for computing cycle space basis

### PR DESCRIPTION
**Pull request by jfinkels**
This pull request supercedes pull request #1067 to fix issue #1046. As stated in my comment on the former, a fix to #330 would greatly simplify the `chords()` algorithm below.

### CODE REVIEW

**Comment by jfinkels** [comment]
There is an algorithm for finding a directed cycle basis [here][1].

[1]: http://dx.doi.org/10.1007/s00224-006-1319-6

**Comment by kakila** [comment]
Thanks for all the work. In #1067 you gave two suggestions for `chords()` and `fundamental_cycles()` are those still in force? 
Is #330 being resolved? making `chords()` simpler would be great.

**Comment by jfinkels** [comment]
My three comments were, briefly, as follows.

1. `chords()` would be simpler if there were a `edge_subgraph()` function. I don't think anyone is working on creating an `edge_subgraph()` function, but the comment I left on #330 seems to indicate that one may exist already. It would be great if someone could take that code, add some tests and documentation and create a pull request for it. If an `edge_subgraph()` gets merged before this code does, then this pull request should be updated to incorporate it, but if no `edge_subgraph()` function appears in time, it's fine without it.
2.  There should be a function for computing fundamental cycles. This can come later as a separate pull request that depends on this one.
3. Allow specifying a pre-computed spanning tree. This seems to be done already for two of the functions; I'm not sure if it makes sense for the other ones.

To make changes on top of these commits, you can checkout the `cycle_basis_matrix` branch of my repository, `jfinkels/networkx`. I believe you can also make a separate pull request to that branch on my repository if you want to suggest changes to be incorporated into this pull request.

**Comment by jfinkels** [comment]
The `chords()` function introduced in this pull request would simplify pull request #1649, in which the `_min_cycle_basis()` function computes chords manually.

**Comment by kakila** [comment]
Regarding your suggestions.
1. I am working on this.
2. Isn't `cycle_basis` doing this?
3. Since `cycle_basis` calls `chords` when the input is a multigraph. It makes sense to accept an optional tree (I've done this). The other functions, in their current implementation do not seem to rely on a tree of the graph.

There is a TODO asking whether `chords` should return a graph of a list of edges. My logic was that on the chords graph one would like to have graph methods available, like edges_iter in `cycle_basis_matrix`. It also allows the user to directly operate on graphs, instead of first creating it from the edges. So if you are not against it I would remove that TODO.

I sent a pull request to add these minimal changes.

**Comment by kakila** [comment]
It seems that #1740 covers comment 1.

**Comment by kakila** [comment]
@jfinkels if you merge branch edge-subgraph with this branch I can reduce chords to a simpler function. Provided there is no negative impact in performance (which I think it wont).

**Comment by dschult** [comment]
Cycle_basis_matrix can use features from #1740.
Also the add_path changes seem to have caused conflicts.

**Comment by kakila** [comment]
@dschult where would you use #1740. In the function chords to return the subgraph?

**Comment by dschult** [comment]
This has been superceded by #2069

**Pull request closed without merging**
