### PR TITLE
Updates structure of documentation to facilitate automatic building

### PR DESCRIPTION
**Pull request by jfinkels**
This is a large change so here is the summary.

Check out the documentation generated from this branch at https://jfinkels-networkx.readthedocs.org/en/latest/.

This pull request fixes issue #2030. In doing so it makes unnecessary the "manual" scripts required to generate the examples from the `examples/drawing` directory and the gallery (which seems to be a page with just the images generated by the drawing examples). This means the documentation can be built easily by readthedocs with no additional configuration, simply by doing `pip install -r requirements-doc.txt && python setup.py build_sphinx`. I hope that this can one day be the sole documentation home.

However, this pull request also changes the structure of the documentation in several ways.

I regenerated a new `doc/conf.py`, using the most recent version of Sphinx and `sphinx-quickstart`.

The main `doc/index.rst` is reorganized in a way that makes a little more sense (for example, "License" and "Citing" are no longer listed under the API reference).

The `doc/reference/` directory now (mostly) mirrors the matching `networkx/` Python package. Specifically, there is now a `doc/reference/algorithms` directory, a `doc/reference/generators` directory, etc. This makes it much easier to navigate the directory structure and to find the .rst file corresponding to a particular .py file.

I made some small changes to the documentation here and there as well, removing outdated information or unnecessary formatting.

_What this pull request doesn't do:_
- This branch uses the default Sphinx theme that comes with the most recent version of Sphinx and the default templates, styles, etc.; I don't really know how to change it, so please let me know if you want it to look like the current "black and blue" theme on https://networkx.readthedocs.org/en/latest/.
- Some of the settings in `doc/conf.py` may be a little off, feel free to compare them with the current settings and let me know what needs to be changed.
- The gallery doesn't match exactly what is there now. The `plot` directive is not very flexible in how the images are placed on the page.
- The "Overview" page has some citations that appear in the middle of the page. They should move to the end of the page.
- I would like to drop 99% of the "Developer Guide" and simply link to the appropriate help pages on GitHub (or wherever), but I didn't do that because I suspect it would meet some resistance.
- It doesn't have a "landing page", as appears at https://networkx.github.io. That can be added.

### CODE REVIEW

**Comment by hagberg** [comment]
OK, whew.  248 files.  Thanks for taking this on.   Fixing documentation is hard to get to the top of anyone's list but it is important.  I'll help you get this finished.

In general this seems like it is a good idea.  There was matplotlib plot directive  when we started and sphinx was just a baby.  So some technical editing and updating is certainly in order.  And there are also some easy opportunities to make the documentation structure and layout easier for people to navigate. I see you are also working to improve that too which is great.   

I would advocate to organize the documentation (eventually) as follows.  We may not want to take this all on right away but it might be good to make sure we know where we are headed.

 - Landing page: networkx.github.io - Landing page with pointers to everything similar to current page.  Perhaps the "Overview" info in the reference guide could go here? (Could also be updated for more modern style...)

- Reference: readthedocs.github.io    (in some organizational structure we like)
   - Detailed API reference, Release Log, API changes    
   - License, Installing, Credits, Citing, Glossary

- Tutorial: I think ideally this is a Jupyter notebook hosted at Github

- Examples/Gallery: Jupyter notebooks at Github - we started here https://github.com/networkx/notebooks

- Developer info: https://github.com/networkx/networkx/wiki - Whatever we want to keep from what we are calling "Testing" and "Working with NetworkX source code"

**Comment by jfinkels** [comment]
> Landing page: networkx.github.io - Landing page with pointers to everything similar to current page.  Perhaps the "Overview" info in the reference guide could go here? (Could also be updated for more modern style...)

Okay, the source for the "landing page" seems to be stored in the https://github.com/networkx/networkx-website repository, and the generated HTML is stored in the https://github.com/networkx/networkx.github.com repository it seems. Since this is fairly simple and static, why not just have a single repository at https://github.com/networkx/networkx.github.com with just the HTML and CSS?

> Reference: readthedocs.github.io    (in some organizational structure we like)
>   - Detailed API reference, Release Log, API changes    
>   - License, Installing, Credits, Citing, Glossary

Makes sense.

> Tutorial: I think ideally this is a Jupyter notebook hosted at Github

So this would be in a repository like https://github.com/networkx/tutorial?

> Examples/Gallery: Jupyter notebooks at Github - we started here https://github.com/networkx/notebooks

Makes sense.

> Developer info: https://github.com/networkx/networkx/wiki - Whatever we want to keep from what we are calling "Testing" and "Working with NetworkX source code"

Good, I think the landing page should be able to direct people to the right place. Just have to make sure that most links for NetworkX (the PyPI page, the Github source repository, etc.) point to https://networkx.github.io.

-----

Should I modify this pull request so that it handles only the "Reference" part, which is the only part that will be built on readthedocs? In other words, should I remove the overview, the tutorial, the examples, the gallery, and the developer info? I can of course leave some explanatory text directing the reader to the correct other website when appropriate.

**Comment by hagberg** [comment]
On Fri, Apr 1, 2016 at 11:23 PM jfinkels <notifications@github.com> wrote:

> Landing page: networkx.github.io - Landing page with pointers to
> everything similar to current page. Perhaps the "Overview" info in the
> reference guide could go here? (Could also be updated for more modern
> style...)
>
> Okay, the source for the "landing page" seems to be stored in the
> https://github.com/networkx/networkx-website repository, and the
> generated HTML is stored in the
> https://github.com/networkx/networkx.github.com repository it seems.
> Since this is fairly simple and static, why not just have a single
> repository at https://github.com/networkx/networkx.github.com with just
> the HTML and CSS?
>
Yes.   We can just use one repository for that with master and source
branches.  We might consider using networkx.github.io since that is the
current way github is using for site naming.

> Reference: readthedocs.github.io (in some organizational structure we
> like)
>
>    - Detailed API reference, Release Log, API changes
>    - License, Installing, Credits, Citing, Glossary
>
> Makes sense.
>
> Tutorial: I think ideally this is a Jupyter notebook hosted at Github
>
> So this would be in a repository like https://github.com/networkx/tutorial
> ?
>
Sure, that seems clear.

> Examples/Gallery: Jupyter notebooks at Github - we started here
> https://github.com/networkx/notebooks
>
> Makes sense.
>
> Developer info: https://github.com/networkx/networkx/wiki - Whatever we
> want to keep from what we are calling "Testing" and "Working with NetworkX
> source code"
>
> Good, I think the landing page should be able to direct people to the
> right place. Just have to make sure that most links for NetworkX (the PyPI
> page, the Github source repository, etc.) point to
> https://networkx.github.io.
> ------------------------------
>
> Should I modify this pull request so that it handles only the "Reference"
> part, which is the only part that will be built on readthedocs? In other
> words, should I remove the overview, the tutorial, the examples, the
> gallery, and the developer info? I can of course leave some explanatory
> text directing the reader to the correct other website when appropriate.
>
Yes, that would be great.

**Comment by jfinkels** [comment]
> Yes.   We can just use one repository for [the landing page] with master and source
branches.

It may be easier to just have a single HTML file on the master branch, since it is really just one page and it won't change very much. Basically I'm proposing just combining all the files from https://github.com/networkx/networkx-website/tree/master/_templates into a single file, and placing that at the root directory of the repository on the master branch.

**Comment by hagberg** [comment]
I'd suggest we use some simple Jekyll templating of some kind and let github make the static html when we push changes.  It's a personal goal of mine to never again edit html.

**Comment by MridulS** [comment]
@jfinkels let me know if you want to handle these conflicts or I can pull this PR and update it.

I have also made a boilerplate website https://nxtestweb.github.io , let me know if this makes sense!

**Comment by dschult** [comment]
Since the tutorial will be a notebook, maybe we can house it in the notebooks repository instead of its own repository?

https://github.com/networkx/notebooks/blob/master/tutorial.ipynb

**Comment by hagberg** [comment]
Yes, the notebook examples are generally a kind of tutorial anyway.

**Comment by dschult** [comment]
**What does having the examples in a separate repo gain for us?**  
(This might be of interest to people at #2462 SciPy working on the docs)

With the examples in a separate repository ```networkx/notebooks``` is there an easy way to still include them as part of the Travis testing?  Appveyor?

Is there an easy way to have PRs to ```networkx/notebooks``` be tested in Travis?  Appveyor?

I'm concerned that moving to separate repositories makes at least the testing harder to maintain?

I know that the examples being Jupyter notebooks is nice. I think github.com displays the notebooks whether they are in their own repository or in an examples folder. So jupyter notebooks is a separate issue from moving them to a separate repository.

**Comment by hagberg** [comment]
Are there test hooks for automatically testing jupyter notebooks?   Someone must have worked that out by now.  

I suggested a separate repository to reduce the amount of code burden in the library repository.  Of course that adds some complexity in versioning and testing a notebook repository as you suggest.  That could possibly be done by different people than the library developers (though practically may not be).

**Comment by MridulS** [comment]
@hagberg the closet thing to that would be https://github.com/computationalmodelling/nbval . I have a built a rudimentary setup with binder and travis for the tutorial notebook at https://github.com/MridulS/test-tut . For more discussions regarding notebooks I have opened a new issue https://github.com/networkx/networkx/issues/2518

**Comment by dschult** [comment]
This has been a real help!  
Other PRs and issues have taken over for the ideas here so I'm closing it now.

**Pull request closed without merging**
