### PR TITLE
Image (3D RGB data) segmentation by spectral clustering with 3D illustrations 

### PR DESCRIPTION
**Pull request by lobpcg**
Motivated by https://github.com/networkx/networkx/pull/4643

If https://github.com/networkx/networkx/pull/7025 is merged first, I could add animation by rotating the 3D graphs.

### CODE REVIEW

**Comment by lobpcg** [comment]
There are not plots shown in the docs for this example and the run time of the example is 0, so it has not ran. But the errors appear only in style so I am unsure why.

**Comment by dschult** [comment]
The doc build is failing silently. I'm not sure why it isn't failing loudly.
The problem is that the `extendability.rst` file has the wrong function name in it.  My mistake in #4890 
Will fix that soon. I don't know why that would affect animation, but who knows at this point.

**Comment by lobpcg** [comment]
> The doc build is failing silently. I'm not sure why it isn't failing loudly. The problem is that the `extendability.rst` file has the wrong function name in it. My mistake in #4890 Will fix that soon. I don't know why that would affect animation, but who knows at this point.

This PR has no animation, still fails to generate any new static images. Please ping me after you fix the issue.

**Comment by lobpcg** [comment]
> > The doc build is failing silently. I'm not sure why it isn't failing loudly. The problem is that the `extendability.rst` file has the wrong function name in it. My mistake in #4890 Will fix that soon. I don't know why that would affect animation, but who knows at this point.
> 
> This PR has no animation, still fails to generate any new static images. Please ping me after you fix the issue.

@dschult my silly mistake - a module must be named plot_ to be processed for plotting.

**Comment by lobpcg** [comment]
The example does not run since
`ModuleNotFoundError: No module named 'sklearn'`
but illustrating `sklearn` is the core goal of this example. Any suggestions?

**Comment by dschult** [comment]
You will need to add the package `scikit-learn` to the requirements file `requirements/example.txt`.

**Comment by lobpcg** [comment]
CircleCI just went down.

**Comment by lobpcg** [comment]
Ready for review/merge, please

**Comment by lobpcg** [comment]
image
image

**Review by dschult — APPROVED** [review]
This looks good. Other than turning on animations in the docs, are there other code changes you would need to make the animations turn on?

I'm going to approve this -- but it'd be nice to get the animations going before it is merged. If turning them on globally is all that is needed, you could add that same line to the `doc/conf.py` file that the other PR has. So long as they are identical they won't conflict.

**Comment by lobpcg** [comment]
The animation here needs to be an extra block in the code. Let's merge it as is, and I can add an animation here as separate PR.

**Comment by lobpcg** [comment]
I think it's better to move to Algorithms from 3d plots, so will do next.

**Comment by lobpcg** [comment]
While waiting for the second review, I have added two 3D animations: of the clustered data and of the partitioned graph. Ready for final review/merge, please

**Comment by MridulS** [comment]
This looks great! Thanks @lobpcg :)

**Pull request merged**
