### PR TITLE
make plots less dense, enable plotting for igraph

### PR DESCRIPTION
**Pull request by MridulS**

### CODE REVIEW

**Comment by rossbar** [comment]
Hm, there's a `NotImplementedError` for igraph plotting on linux... maybe a version needs to be bumped somewhere?

**Comment by MridulS** [comment]
It's installing the latest available version of igraph (0.9.1) but it looks like they will be removing plotting to a temp file soon which `ig.plot` uses without any target, https://github.com/igraph/python-igraph/blob/52df5180289cfe916766dab4022fc6cc35caf86b/src/igraph/drawing/__init__.py#L434

I'm trying this with a matplotlib backend now.

**Comment by MridulS** [comment]
Plotting preview: https://1847-890377-gh.circle-artifacts.com/0/doc/build/html/auto_examples/external/plot_igraph.html#sphx-glr-auto-examples-external-plot-igraph-py

**Comment by jarrodmillman** [comment]
@MridulS Could you update the igraph dependency to
```
python-igraph>=0.9
```

I am pretty sure this doesn't work on < 0.9.  (You may also want to rebase on main.)

**Comment by jarrodmillman** [comment]
I believe the documentation build error is fixed on the main branch.

**Review by jarrodmillman — APPROVED** [review]

**Review by rossbar — APPROVED** [review]
Looks great, thanks Mridul!

**Pull request merged**
