### PR TITLE
Improve test coverage for multigraph class

### LINKED ISSUE #6088: Improve test coverage for multigraph class
I discovered there are still some red spots in this link https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/classes/multigraph.py and will like to work on it. 

The tests will be added in https://github.com/networkx/networkx/blob/main/networkx/classes/tests/test_multigraph.py

Current Behavior
We don't test all the paths the code can take us.

Expected Behavior
We should be testing everything so there aren't any surprises.

Steps to Reproduce
Visit https://app.codecov.io/gh/networkx/networkx/blob/main//networkx/classes/multigraph.py

### PR DESCRIPTION
**Pull request by Qudirah**
fixes #6088

### CODE REVIEW

**Comment by Qudirah** [comment]
@MridulS please can you point to me what I'm doing wrong for some of the tests to be failing

**Comment by MridulS** [comment]
Also you can check this by running `pytest` locally before submitting a pull request. It will catch something like this :)

You can also click on "Details" next to a red crossed failed test to get more details. It should take you to exact place it failed.

**Comment by Qudirah** [comment]
> A video which explains.
> 
>  Screen.Recording.2022-10-19.at.7.13.17.PM.mov

Thank you.

**Comment by rossbar** [comment]
I think there's a similar issue here - it looks like multiple unrelated changes have been made in the same branch. It'd be best to split out the dispersion test updates and the multigraph test updates into separate branches, since they are unrelated changes!

**Pull request merged**
