### PR TITLE
Moves unit tests out of main networkx/ package

### PR DESCRIPTION
**Pull request by jfinkels**
Before, unit tests were distributed within the `networkx` package, with
a distinct directory containing unit tests for each sub-package. Doing
this adds a great number of files that do not need to be distributed
with the NetworkX code.

This commit moves those test files to the `tests/` directory, which is
outside the `networkx` package, so they will no longer be distributed
(for example, in PyPI) with NetworkX.

This also helps to clarify the codebase: only the library code is in the
`networkx` package, and all the test code can be found in its own
directory, if a developer is looking specifically for test code.

### CODE REVIEW

**Comment by hagberg** [comment]
But don't we want to distribute the tests - so users can say  python -c "import networkx; networkx.test()" to make sure the installation is OK?

**Comment by jfinkels** [comment]
I guess this is a matter of opinion. I believe that test code is important for developers and not important for end users. Therefore end users should not receive it. Users should not need to access test code by default, although they should be able to get it if necessary (by getting the code from GitHub, for example). They should get exactly what they need for NetworkX to work; unit test code is never run by end users during their use of NetworkX. I suspect since this is a pure Python library, it is extremely unlikely that running `networkx.test()` on a user's machine will be different from the test results in Travis CI.

**Comment by jfinkels** [comment]
I think maybe distributing the tests with the code is a leftover from distributing C programs and having users run `make test`, etc.

**Comment by jfinkels** [comment]
I just rebased because I had forgotten to move some tests. I'm pretty sure I've got them all now.

The build failure is due to coveralls, which seems to not understand where the unit tests are. I don't know how to fix that, so if someone else knows, I can gladly change the appropriate configuration files.

**Comment by chebee7i** [comment]
I can see the argument for moving the tests out of the package. Happy to go with the majority on this one.

**Comment by dschult** [comment]
I'm not seeing the advantage of the separation. I guess we distribute a 12MB package instead of an 18MB package. Is that the positive impact of doing this? Others I am missing?

I am not so sure that users don't care about the test code. Even if 10% of them do, isn't it worth keeping it in the package? 

Finally, looking at the other packages in the scientific python community they all seem to keep the tests close to the code. In fact they use the same structure we are using.

So I'm seeing 1 small reason to move (less space in Pypi package), 1 small reason to keep (users who want tests) and 1 larger reason to keep (same as other packages in scientific python ecosystem).
Overall (-1) without more reason to move.

**Comment by chebee7i** [comment]
I just thought of another reason to keep them (at least for developers). It is often the case that you develop code and run the subset of tests related to your changes reguarly. This is a pain if the tests are in another directory.

**Comment by chebee7i** [comment]
Though I could just have two terminals open...man, life is tough. Geez.

**Comment by MridulS** [comment]
I think we should go by the pythonic standard and keep the unit tests in the package. As mentioned by @dschult most of the packages in scientific python community uses the same structure.

**Comment by jfinkels** [comment]
@MridulS There is no consensus on a sole "Pythonic" place for unit tests. However, most (though not all) of the top 20 or so most popular Python repositories on GitHub do it my way: one directory containing the source code and a neighboring directory containing the tests. Also, "because the scientific community does this..." is not a very convincing argument for writing good Python code; I would be more convinced by an appeal to a Python authority, like "because well-known good Python programmers X, Y, and Z do it this way...".

@dschult Other than distributing a smaller package, which is certainly a benefit not only for users but also for PyPI, readability is important (a tenet of Python): mixing test directories with source code makes it difficult to "read" directory listings, for example, when looking for only source code modules.

@chebee7i Depending on how you work, seems like not much of a pain.

**Comment by ysitu** [comment]
Regardless of whether you move the tests, we should distribute them with the main code. Tests can make up for where documentation comes short.

PRs that break coverage and/or continuous integration badly are not mergeable.

**Comment by Midnighter** [comment]
I'm with @jfinkels on this one. There's a [nice blog post](http://blog.ionelmc.ro/2014/05/25/python-packaging/) that has a lot of the details of the points that have come up here. The author also [created a repository](https://github.com/ionelmc/cookiecutter-pylibrary) that can be used with `cookiecutter` in order to set up a package structure. It's a lot to take in at first with the integration of travis, coverage, bumpversion and appveyor but networkx has most of these set up and running already, so it wouldn't be too deep of a dive.

Anyways, have a read of the blog post, it convinced me, at least.

**Comment by jfinkels** [comment]
@ysitu Documentation should not come up short, period, and unit tests should certainly not "fill in the gaps" of documentation. They serve a completely different purpose. There should be plenty of human-readable examples in the documentation, and for users, reading source code should be an absolute last resort.

As for the test failures, I think the PyPy Travis failure is due to #1351 and I mentioned above that I don't really understand how to fix the coveralls failures, since test coverage shows about 91% on my local machine. I definitely need some help with that.

**Comment by dschult** [comment]
Reading source code is definitely not a last resort for many of our users. We're providing tools and code; and some users won't want to look at the code. But some users are quite adept at reading code and tests. I don't think we should make it harder for either users or developers UNLESS there is a good reason for doing so. I still haven't seen (include the blog @midnighter pointed to) a justification for separating tests from code that resonates for me.

**Comment by hagberg** [comment]
Maybe nobody else but me does,  but I use 

```
python -c "import networkx; networkx.test()"
```
and sometimes ask others to do that to verify that the installation is correct and that the expected extra packages are installed.  So I like having the tests distributed with the code. 

I read the blog post and arguments about moving the tests but it doesn't convince me this is the right thing to do now.

**Comment by hagberg** [comment]
No strong practical arguments for moving tests out of source tree at this point.

**Pull request closed without merging**
