### PR TITLE
added implementation of VoteRank

### PR DESCRIPTION
**Pull request by fredrike**
VoteRank computes a ranking of the nodes in the graph G based on a voting
    scheme. With VoteRank, all nodes vote for each neighbours and the node with
    the highest score is elected iteratively. The voting ability of neighbors of
    elected nodes will be decreased in subsequent turnself.

### CODE REVIEW

**Comment by fredrike** [comment]
Thank you for considering this @dschult, I've added description to the `doc_string`. 

Also, @pbrodka should be included in this conversation.

**Comment by dschult** [comment]
@fredrike Thanks for the nudge.  Are we waiting for feedback from @pbrodka?
I am having a crazy month, but will try to get to it soon.

**Comment by fredrike** [comment]
> @fredrike Thanks for the nudge. Are we waiting for feedback from @pbrodka?
> I am having a crazy month, but will try to get to it soon.

I just added @pbrodka to keep him in the loop, everything is good from his side. Take it easy and thank you for getting back to me.

**Comment by fredrike** [comment]
@dschult what is the holdup for this PR?

**Comment by dschult** [comment]
Lack of time and focus I believe is the only real hold up. 
I ask for you to check the spelling of ```influetial``` and ```turnself```
Could you also replace ```list()``` with ```[]``` in the code?
Everything else is ready to merge as far as I'm concerned.

Thanks --

**Comment by dschult** [comment]
Thanks for this!

**Pull request merged**
