### PR TITLE
Allow custom keys for multiedges in from_pandas_edgelist

### PR DESCRIPTION
**Pull request by Daniel-Davies**
Adding PR for feature stated in issue #4065, regarding the ability to provide a custom key for multigraphs in the from_pandas_edgelist function. Code currently (as stated in issue) deals with duplicate keys by overwriting them, and I will look into better mechanisms in future PRs. Tests have been added and code was run through black.

### CODE REVIEW

**Comment by jarrodmillman** [comment]
We use psf/black to format code now.  So you don't need to manually fix all the pep8 issues.  Instead install and run black and it will fix these issues for you:  https://github.com/psf/black

**Comment by dschult** [comment]
This looks pretty good. Almost ready.  Some comments:

Could you inline the 3 helper functions? They are only used once and the namespace is already pretty big in this module.

Could you add documentation of the new feature into the docstring?

Thanks!

**Comment by dschult** [comment]
The Travis-CI is failing on a new OSX test platform just put in place yesterday. It is not your code so don't worry about getting that test environment to pass. The others are all passing.

This looks good -- here's some last bits to clean up:
- is the ```key = -1``` needed? what is its purpose?
- can you make the msg on line 386 avoid the white space and newline by concating strings like this"
```python
msg = ("first part"
               f"second part {with formating}")
```
- change the name of one of the first two tests (same name) so they both run.
- can you remove the "as excinfo" in the with statement for pytest.raises? PEP8 complains because excinfo is defined but isn't used.

**Comment by Daniel-Davies** [comment]
Hello
Thank you very much for supporting my first pull request to NetworkX- i really appreciate it. I have made the changes requested, and blackened the code. 

I also took a look into the issue of multigraph repeating keys- there wasn't a great deal of information I could find for existing use cases in which multigraph keys can conflict, and after thinking about the issue in general, I don't think NetworkX should handle a user-created duplicate key, for two main reasons:

- Resolving the issue would either need a 'log of changes', which implies a list return type for each edge (conflicting with the existing use cases of the multigraph), or something like a max-value protocol, which could cause the user more trouble in debugging if the duplicated key was an accident.
- In my opinion at least, the NetworkX code base shouldn't grow in complexity (and hence add a barrier to future contributors) by having to deal with these kinds of 'edge cases', which are quite easily configurable on the user side, before entering the dataframe.

On the other hand, if this is a feature that you think would be important, I think the best way to handle it would be by having the user input take the following formats:

edge_key :: string => normal, overwrite behaviour
edge_key :: tuple (string, string) => the first string is the key, and the second string would be the method to deal with duplicate keys (e.g. 'save_all' to output edges as a list, 'most_common' etc)

Thoughts?

Thank you again for all the help!

**Pull request merged**
