### PR TITLE
Improve is_path

### PR DESCRIPTION
**Pull request by pmlpm1986**
## Description

is_path currently raises a KeyError if a node in the path provided does not exist.

The more appropriate outcome would be a False output, since the path provided is not, in fact, a path.

## Example to trigger the problem

import networkx as nx

G = nx.MultiDiGraph()

assert nx.is_path(G,[0,1]) == False

## Solution

To address this, I revised the is_path method to check if each element on the tentative path is a nodem namely by calling has_node on each iteration.

### CODE REVIEW

**Review by dschult — COMMENTED** [review]
This looks like an improvement to me. 
I would use `if node not in G:`, but I think that is a style issue and so I'm fine either way with it.

I'm +1 for returning False instead of raising an error when a node is not in G.

**Comment by rossbar** [comment]
I agree with @dschult that `if node not in G` reads nicer, so +1 for that suggestion.

It's probably also worth adding a blurb to the [release notes](https://github.com/networkx/networkx/blob/main/doc/release/release_dev.rst) to notify users of the change in behavior (I'd be happy to add this if you'd prefer).

**Comment by pmlpm1986** [comment]
I introduced the changes suggested by @dschult  and @rossbar and described the condititions for a True output in the documentation. There appears to be some issue with 'black' though I am not privy to why this happens.

**Review by rossbar — COMMENTED** [review]
Thanks @pmlpm1986 We'll also need to add a test case for the new behavior.

Re: the problems with black, the easiest way to resolve them is to use the `pre-commit` hooks - see [the contributor guide](https://networkx.org/documentation/latest/developer/contribute.html#development-workflow)

**Comment by dschult** [comment]
I liked the paragraph that you included in the doc_string. It looks like `black` didnb't like the blank line -- probably because it had a whitespace character in it. If you could add back that paragraph change, but make sure the blank line has no characters in it, I think it should work.

**Review by dschult — APPROVED** [review]
This looks good to me!

**Review by rossbar — APPROVED** [review]
Thanks @pmlpm1986 !

**Pull request merged**
