### PR TITLE
added networkx.__bibtex__ attribute

### PR DESCRIPTION
**Pull request by Tafkas**
Added a bibtex attribute for quick command-line access to the recommended citation info. Idea by @jakevdp: https://twitter.com/jakevdp/status/524329573580697600

### CODE REVIEW

**Comment by hagberg** [comment]
I don't think it helps much either.  If this becomes a Python standard then we can do it.

**Comment by jakevdp** [comment]
I still think a uniform interface across all packages would be more useful than a non-uniform paragraph somewhere on each package's web page. It would not be obscure if everyone were used to using it.

But yes, I agree that no momentum has built behind the idea. When the perfect is the enemy of the good, the status quo will always reign.

**Comment by hagberg** [comment]
Hi @jakevdp - All you need to do is check the networkx code base to see that we have no concerns about 'perfect being the enemy of good' :-)

If you want to advocate for this widely - let's go for it.

**Comment by jakevdp** [comment]
Ha :smile:

**Comment by jakevdp** [comment]
I tried advocating, but everywhere it's been discussed the discussion has become a flurry of competing suggestions, with everyone finding fault with everyone else's ideas. After a while, the discussion peters out and nothing happens. So I'm not sure if this idea or something like it will be adopted more widely...

**Pull request merged**
