### PR TITLE
Add matrix market to readwrite reference

### PR DESCRIPTION
**Pull request by rossbar**
Adds an .rst stub to the readwrite docs in the reference guide to provide background and examples for I/O with the Matrix Market format using SciPy's built-in parsers.

Related to the discussion in https://github.com/networkx/networkx/pull/4922#issuecomment-866651631.

### CODE REVIEW

**Comment by dschult** [comment]
Nice!  

Should it be titled "Matrix Market Exchange" rather than "Matrix Market Graph Format"?
The other formats are titled:  GML or GEXF or "Adjacency List", so the "Format" seems out of place. And the NIST site uses "Matrix Market Exchange" without any discussion of Graph at all.  I'm guessing "Market Exchange" is a qualifier NIST added to "Matrix" when constructing a universal matrix storage standard.  The name "Matrix Market" doesn't have the same meaning somehow.

Anyway, I'm not sure what the right heading is here.

**Comment by dschult** [comment]
OK. I looked at [the Scipy.io page](https://docs.scipy.org/doc/scipy/reference/io.html) and [the NIST page](https://math.nist.gov/MatrixMarket/) more closely.  Matrix Market is exactly the term they use.  So let’s go with that.  I think that means my only suggestion is that the first heading be shortened to “Matrix Market” instead of having “Graph Format” at the end.  But I’m also open to other ideas.

**Review by dschult — APPROVED** [review]
Looks good!  Thanks @rossbar !!

**Review by MridulS — APPROVED** [review]
This is prefect! I guess we should pretty much do this for all the I/O formats which are thin wrappers.

**Pull request merged**
