### PR TITLE
Rename and move total_spanning_tree_weight

### PR DESCRIPTION
**Pull request by peijenburg**
**Old suggestion:**

Implements a formula for computation the number of spanning trees of a graph (https://en.wikipedia.org/wiki/Kirchhoff%27s_theorem)

**Update:**

The function already existed under the name `total_spanning_tree_weight`. Instead, I updated that function with additional functionality, see #7098 and #7100.

**Further suggestions in this PR (or perhaps a new PR is better):**

- Rename from `total_spanning_tree_weight` to `number_of_spanning_trees`
- Move from `Laplacian` subfolder to `Tree` subfolder

### CODE REVIEW

**Comment by dschult** [comment]
See also [this function.](https://github.com/networkx/networkx/blob/f9170cc404bd4bd1c482e976f8f7677b1b60a1cd/networkx/linalg/laplacianmatrix.py#L150).   I think this might be a place where improving the doc_string of the existing function (and maybe even its name) could be better than the new function.

We can get the number of spanning trees by using the existing function with unweighted edges.

If that is really true and works, then an example in the doc_string of the existing function could show people how to get the number of spanning trees. It discusses it already, but maybe it could be made more clear.

**Comment by peijenburg** [comment]
@dschult Thanks! I wasn't aware of the function `total_spanning_tree_weight` and in fact, I cannot find it in the documentation. It is also located in the `Laplacian` subfolder, which is a little weird, right?

I'd suggest the following (but I'd love your opinion before I'll start);

- Merge the existing `total_spanning_tree_weight` and my proposed `number_of_spanning_trees` into one function, which I would call `number_of_spanning_trees`. 
- Move the function from `Laplacian` subfolder to the `Tree` subfolder.
- The merged function is able to consider directed and weighted graphs, whereas `total_spanning_tree_weight` cannot handle directed graphs and `number_of_spanning_trees` cannot handle weighted graphs.

**Comment by rossbar** [comment]
@peijenburg your proposal has a lot of moving parts - if you'd like to pursue it I'd recommend splitting it up into multiple PRs to make review easier. As @dschult points out, the easiest thing to start with is to add docstring examples showing how to compute the number of spanning trees with `total_spanning_tree_weight`. The next two points in your proposed plan are trickier as they involve API changes (thus require a warnings cycle), so those should definitely be in a separate PR!

**Comment by peijenburg** [comment]
@rossbar Thanks a lot! Based on your suggestion, I have separated this PR into #7098 and #7100.

I'll leave this PR open to discuss the proposed name change:

- Rename from `total_spanning_tree_weight` to `number_of_spanning_trees`
- Move from `Laplacian` subfolder to `Tree` subfolder

**Comment by dschult** [comment]
Another way to get this in place perhaps quicker would be to add a new function `number_of_spanning_trees` with the code. and keep the deprecated function `total_spanning_tree_weight` around with a deprecation warning on it. People can use the new function name and when the deprecation ends we remove the old name.  The code should be in the new functions location with the old location's function simply calling the new one (perhaps with some restrictions on parameters if the new one adds features that the old one doesn't provide.

Maybe this comment should have gone into #7100 but I think this PR is the nexus for all these comments.
@peijenburg are you interested in changing #7100 to adding a new function and changing the old function to a shell that does what the only old one did by calling the new one?  I could try to help with that if you need it.

**Comment by peijenburg** [comment]
@dschult I'm fine with either approach, but I don't know what is common use in networkx. 
But I do need some help with the shell, please @dschult :)

**Comment by dschult** [comment]
See #7100

**Pull request closed without merging**
