### PR TITLE
Make to_pandas_edgelist behave consistent across py2 and py3

### PR DESCRIPTION
**Pull request by wuhaochen**
Address #2977. Using OrderedDict here might be an overkill though.

### CODE REVIEW

**Comment by dschult** [comment]
hee hee -- looks like we were both working on this at the same time.  (see #2984)

What do you think?  My fix specifies the order of the columns in the doctest.
Your change uses an OrderedDict so that the default column order is the same as expected.
I believe the DataFrame can also be created with a list instead of a dict to constrain the order.

**Comment by wuhaochen** [comment]
Ha, what a coincidence. I feel like using OrderedDict is reasonable here since the original change in pandas is because of dict is ordered by default in py3. The performance should actually be better with OrderedDict since it makes pandas avoid sorting the dict keys.

My overkill concerning is purely aesthetic since we don't really care about the order here. In such sense I guess I would prefer mine to #2984.

**Comment by wuhaochen** [comment]
Whee, it seems the order still need some more tweak.

**Comment by dschult** [comment]
I think the new error indicates that OrderedDict will be harder to maintain long term.
And I also appreciate your sense of aesthetics about having source and target printed first in the examples.

I'll put the order as you created it (source, target, cost, weight), but not add dependence on OrderedDict in this part of the code.  I suspect that in N years (as N -> infinity) we won't have OrderedDict anymore.

**Comment by wuhaochen** [comment]
Yes, we should all use python 3 in the end. I'm ok with whatever works here.

**Comment by dschult** [comment]
see #2984

**Pull request closed without merging**
