### PR TITLE
Revised api_2.0.rst and added some major contributions

### PR DESCRIPTION
**Pull request by OrkoHunter**
@ysitu I revised the file as you said and checked the commits since last November. I found 3 changes worth adding. Please see them.

### CODE REVIEW

**Comment by MridulS** [comment]
@OrkoHunter looks fine, squash the commits and you should always work on a new branch 
```
$ git checkout -b some_new_branch
```
you should keep your local master branch clean and do changes in the new branch.

**Comment by OrkoHunter** [comment]
> @OrkoHunter looks fine, squash the commits and you should always work on a new branch

Thanks for the review!

> you should keep your local master branch clean and do changes in the new branch. It is a good practice.

Actually, I wasn't working on other things right now so made changes directly in master. From now on I'll send PR from different branches.

I'll squash the commits into one.

**Comment by OrkoHunter** [comment]
@MridulS Updated the PR. Are you +1 to this change?

**Comment by OrkoHunter** [comment]
I don't know why test coverage decreased.

**Comment by ysitu** [comment]
You do not have to worry about coverage as you are not touching code. Will take a look at your changes later today.

**Comment by OrkoHunter** [comment]
Cool.

**Comment by ysitu** [comment]
I think that #1314, #1321 and #1360 are also worth mentioning. In particular, #1314 is a major new feature IMO.

**Comment by OrkoHunter** [comment]
@ysitu #1314 is really worth mentioning. I'm sorry I didn't see that. I added #1314 and #1321 in the PR. #1360 is already mentioned in api_2.0.rst

Anything more?

**Comment by chebee7i** [comment]
Probably #1356 as well.

**Comment by ysitu** [comment]
Things get forgotten. We should make it a policy that PR authors are responsible modifying api_x.x.rst.

**Comment by chebee7i** [comment]
Yeah, that or the merger should add it at merge time.

**Comment by OrkoHunter** [comment]
@ysitu @chebee7i Yeah I was thinking that too. It should get updated as soon as changes are merged.

**Comment by OrkoHunter** [comment]
@chebee7i Added #1356 
@ysitu Ping.

**Comment by chebee7i** [comment]
I'm going to merge this now. If we missed anymore, we can add them later.

**Pull request merged**
