### PR TITLE
Gml read fix.

### PR DESCRIPTION
**Pull request by wuhaochen**
Deal with the issue #1783. Also change the variable name from type to category to avoid confusion.

### CODE REVIEW

**Comment by wuhaochen** [comment]
Possible issue here: '\b' matches the end of a word, so it won't behave exactly the same as (\s+|$), but the latter one will introduce another group and changed the category index.

**Comment by hagberg** [comment]
Looks reasonable.   Perhaps we should add a test  so we can verify that this does manage to read files with extra whitespace like
```
graph
  [
  directed 0
  node
  [
    id 3
    label "a"
  ]
  node
  [
    id 8
    label "b"
  ]
  edge
  [
    source 8
    target 3
  ]
]
```

**Comment by wuhaochen** [comment]
I already tested on the data from the original issue. The problem here is that non space ending character could be matched, like .!? etc. Those characters are not allowed in the old code anyway, but here they could be silently truncated without error. Alternately I could use the pattern I suggested in the original issue(\s+|$) and change all the index used in code. I'm not sure which one is better.

**Comment by hagberg** [comment]
I don't have an opinion on which way is better.  

For testing I was suggesting adding a test function to test_gml.py to cover this case.

**Pull request merged**
