### PR TITLE
Deprecate strongly_connected_components_recursive

### LINKED ISSUE #6897: Discrepancy in 'strongly_connected_components_recursive' for Detecting SCCs
Hey NetworkX team! 👋
### Description:
While attempting to identify strongly connected components (SCCs) of a graph using the `strongly_connected_components`, `strongly_connected_components_recursive`, and `kosaraju_strongly_connected_components` methods provided by `networkx`, inconsistent SCCs were observed. Notably, the `strongly_connected_components_recursive` method identified node `8` as a separate SCC, while the other two methods included node `8` in a larger SCC.\
For context, I've minimized my original, much larger graph to a smaller version to isolate and highlight the issue. 

### Observed Behavior:
- Using `strongly_connected_components`: [{0, 2, 3, 5, 6, 7, 8, 10}, {1}, {4}, {9}]
- Using `strongly_connected_components_recursive`: [{8}, {0, 2, 3, 5, 6, 7, 10}, {1}, {4}, {9}]
- Using `kosaraju_strongly_connected_components`: [{1}, {0, 2, 3, 5, 6, 7, 8, 10}, {9}, {4}]

### Expected Behavior:
All three methods should produce consistent SCCs. Node `8` should be part of the larger SCC `{0, 2, 3, 5, 6, 7, 8, 10}` based on the provided edges.

### Steps to Reproduce:
1. Create a directed graph with the provided nodes and edges.
2. Compute SCCs using the `strongly_connected_components`, `strongly_connected_components_recursive`, and `kosaraju_strongly_connected_components` methods.

### Environment:
Python version: 3.8.10
NetworkX version: 3.1

```python
import networkx as nx
from matplotlib import pyplot as plt


class Graph:
    def __init__(self):
        self.graph = nx.DiGraph()

    def add_nodes(self, nodes):
        for node in nodes:
            self.graph.add_node(node)

    def add_edges(self, edges):
        for edge in edges:
            self.graph.add_edge(edge[0], edge[1])

    def compute_scc(self):
        """Compute the result using three functions and print them"""
        result1 = list(nx.strongly_connected_components(self.graph))
        result2 = list(nx.strongly_connected_components_recursive(self.graph))
        result3 = list(nx.kosaraju_strongly_connected_components(self.graph))

        print("Using strongly_connected_components:", result1)
        print("Using strongly_connected_components_recursive:", result2)
        print("Using kosaraju_strongly_connected_components:", result3)

if __name__ == "__main__":
    nodes = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    edges = [
        (0, 2), (0, 8), (0, 10), (2, 3), (3, 10),
        (3, 0), (4, 6), (4, 1), (5, 6), (5, 7),
        (6, 2), (6, 5), (7, 10), (8, 7), (9, 8),
        (10, 6)
    ]

    graph_instance = Graph()
    graph_instance.add_nodes(nodes)
    graph_instance.add_edges(edges)
    graph_instance.compute_scc()

### PR DESCRIPTION
**Pull request by rossbar**
Alternative to #6898 , see https://github.com/networkx/networkx/pull/6898#issuecomment-1734207080.

Deprecates the `strongly_connected_components_recursive` function in favor of the non-recursive implementation.

Closes #6897

### CODE REVIEW

**Review by MridulS — APPROVED** [review]
Yeah, I think I'm +1 on deprecating this unless someone wants to take it up and maintain this recursive implementation.

**Comment by dschult** [comment]
Don't we need to fix the bug in the code if we leave this as deprecated. It currently returns incorrect results. I'd prefer just to get rid of it -- or perhaps to deprecate it but call the non-recursive function during the deprecation cycle.

The example from #6897 shows that the recursive version of the code gives incorrect results. And [#6897(comment)](https://github.com/networkx/networkx/issues/6897#issuecomment-1704320361) points out the error.  This error has been there for a very long time -- suggesting that people are not using this function (which they shouldn't).

**Comment by MridulS** [comment]
Yes, I guess we should just straight out remove this function? We can raise an informative error which tells the user about the buggy behavior?

**Comment by rossbar** [comment]
> Don't we need to fix the bug in the code if we leave this as deprecated. It currently returns incorrect results. I'd prefer just to get rid of it -- or perhaps to deprecate it but call the non-recursive function during the deprecation cycle.

Good point - just an oversight on my part! The latest update 8acbacb replaces the buggy recursive implementation with a thin wrapper around `strongly_connected_components`.

**Review by dschult — APPROVED** [review]
I rebased due to conflicts in `deprecations.rst`.  This should be ready to merge after a green check.

**Pull request merged**
