### PR TITLE
Add frozen attribute and freeze method onto graph+digraph

### PR DESCRIPTION
**Pull request by harlowja**
It can be useful to introspect if a graph is frozen and to
be able to easily freeze it, so to make this possible add
a simple freeze method onto the graph and expose whether the
graph is frozen (or not) as a graph attribute.

### CODE REVIEW

**Comment by jfinkels** [comment]
The attributes should be called `is_frozen` because they are Booleans.

**Comment by harlowja** [comment]
Sure, the existing problem is that they've always been called `frozen`, so I didn't want to be break that usage.

https://github.com/networkx/networkx/blob/master/networkx/classes/function.py#L198 (sets a frozen attribute on the graph dynamically).

**Comment by hagberg** [comment]
I'm not in favor of adding this as a method.  The "freeze" concept is not a real way to protect the data structure from modification.  It may be useful to some users but I don't like the implication that the graph or data is fixed if you use this.

**Comment by harlowja** [comment]
Ok, why does networkx have a freeze concept then (genuine question)?

**Comment by hagberg** [comment]
@chebee7i suggested it 7 years ago https://networkx.lanl.gov/trac/ticket/176

**Comment by chebee7i** [comment]
I think it was a half-baked idea :) But we quickly agreed that it would be a second class citizen (e.g. functions only, and not part of the main graph classes).

**Comment by harlowja** [comment]
Fair enough :-P

**Comment by harlowja** [comment]
Is there any list maintained somewhere of things that should be removed for 2.0? This would seem to fit in that category. If not I can start one on etherpad somewhere...

**Comment by MridulS** [comment]
@harlowja You can add this to https://github.com/networkx/networkx/wiki/NetworkX-2.0-API-~-DRAFT

**Pull request closed without merging**
