### PR TITLE
extend convert_bool in gexf.py and graphml.py to all valid boolean 

### PR DESCRIPTION
**Pull request by chebee7i**
Follow-up to pull request #971 - recommend extending ``convert_bool`` to include true/false support for literal 0/1 and the string variants.

1. [graphml.py:224](https://github.com/networkx/networkx/blob/7d9682a07dcae30acab3c4841e33d31f727a3fb2/networkx/readwrite/graphml.py#L224)
1. [gexf.py:215](https://github.com/networkx/networkx/blob/87764469941cfa52a5aefc1b1b381a614b484c8d/networkx/readwrite/gexf.py#L215)

E.g., in [graphml.py:224](https://github.com/networkx/networkx/blob/7d9682a07dcae30acab3c4841e33d31f727a3fb2/networkx/readwrite/graphml.py#L224):

Old:
```python
convert_bool={'true':True,'false':False,
              'True': True, 'False': False}
```

New:
```python
convert_bool={'true':True,'false':False,
              'True': True, 'False': False
              '0': False, 0: False,
              '1': True, 1: True}
```

For reference, the [XML Schema Datatypes](http://www.w3.org/TR/xmlschema-2/#boolean) section on booleans.

### CODE REVIEW

**Comment by ysitu** [comment]
We should reject 0 and 1 as boolean in GraphML. http://graphml.graphdrawing.org/primer/graphml-primer.html#AttributesValues clearly says "This value *must* be of the type declared in the corresponding key definition". 0 and 1 are not booleans.

**Comment by hagberg** [comment]
Well, that might be True.  But we could be more liberal in what we accept.

After all:

```python
In [1]: True==1
Out[1]: True

In [2]: False==0
Out[2]: True
```

**Comment by hagberg** [comment]
I am happy with this.  Merge?

**Comment by ysitu** [comment]
@hagberg You can also do

```python
>>> False==0.0
True
>>> True==1.0
True
```

Are we going to allow 0.0 and 1.0 then?

**Comment by rhuitl** [comment]
I opened a ticket at Boost (https://svn.boost.org/trac/boost/ticket/11092), it really should be fixed there. Meanwhile, I think NetworkX as a library "to get work done" should accept these slightly malformed GraphML documents. It should write perfect ones, of course, but after all it's not a GraphML validator so the benefits of recognizing 0 and 1 will probably outweigh the cons.

**Comment by hagberg** [comment]
Yes I suggest we allow reading 0 and 1 as booleans.

**Comment by hagberg** [comment]
This just needs a merge conflict resolution.

**Comment by chebee7i** [comment]
Ugh, just tried a rebase. Didn't work like I wanted. Hang on.

**Pull request merged**
