### PR TITLE
[WIP] Graph edit distance 2361

### PR DESCRIPTION
**Pull request by aparamon**
An implementation of https://github.com/networkx/networkx/issues/2361 .
On my system this works terribly slow on not-so-similar graphs, but hopefully this serves as initial step.

### CODE REVIEW

**Comment by dschult** [comment]
I see you have added new changes fairly recently.  What is the status of this effort?
and Thanks!

**Comment by aparamon** [comment]
I believe initial implementation can be considered finished. I was planning to run more extensive tests shortly (next week) and confirm the code. But even in current state it should be considered stable in my feelings (there are a lot of helpful `assert`s).

What is left is support for `DiGraph` and `MultiGraph` (which is in principle easy, but currently I have no motivation/test cases), and further performance optimizations. Hopefully, the latter can be developed off the existing interface. I see that GED theory is under active development by "French school" (Université de Tours), so faster computation approaches might emerge, -- but I'm pretty sure those still would be based on `optimize` paradigm due to unavoidable combinatorial explosion.

I called the module `similarity` to encourage adding of other, possibly computationally cheaper measures of graph similarity.

Please review the docs/tests/code, and tell me if you feel something could be improved to get it included.

**Comment by dschult** [comment]
Would you be willing to add a short paragraph to each docstring -- after the one-line description and before the parameters section -- defining what the graph-edit-distance is and what that function computes?  I think it is ready to merge otherwise... please continue to add things after the merge. It seems there is a fair amount of interest in this feature.

**Comment by aparamon** [comment]
@dschult Done, please review and merge!

**Pull request merged**
