### PR TITLE
Fix: Update louvain_partitions for threshold (update mod to new_mod in each level)

### PR DESCRIPTION
**Pull request by cirusthenter**
Currently `threshold` in `louvain_partitions` does not work. This is because `mod` in the while loop (lines 181-191) is not updated since it is initialized with the modularity of the first partition (where each node is in a community that only has the node).

### CODE REVIEW

**Comment by cirusthenter** [comment]
It seems that the PyPy failure comes from `LFR_benchmark_graph` and `louvain_communities` under PyPy have different results from under Python. Simply changing `assert mod1 < 0.512 < mod2` to `assert mod1 <  mod2` in `test_louvain.py` line 124 works?

By the way I am a first-time contributor and any comments or suggestions are appreciated.
Thanks!

**Comment by z3y50n** [comment]
Nice catch, thank you!
You are right regarding the tests, depending on the python version you might get some slightly different results so you should change it to `assert mod1 < mod2`.

**Comment by cirusthenter** [comment]
Thank you @z3y50n. FIixed!

**Review by z3y50n — APPROVED** [review]

**Review by dschult — APPROVED** [review]
Thanks for this bug report -- and the fix -- and for the test!!
This looks good to me.

**Pull request merged**
