### PR TITLE
CI: add pytest-randomly workflow.

### PR DESCRIPTION
**Pull request by rossbar**
Adds a single workflow that runs the test suite with the tests executed in random order. This can help identify problems with poorly-designed tests.

On the one hand, adding this to CI can help improve the robustness of the test suite. OTOH, it can also introduce failures to PRs that are not related to the submitted changes.

One alternative could be to de-couple this from submitted PRs and just have a time or status-based workflow (e.g. run the workflow once a day). LMK if you think this is worthwhile to pursue!

### CODE REVIEW

**Comment by rossbar** [comment]
Note that the failing test for 2d3f598 is an example of the type of problems that this sort of meta-testing catches. Proposed fix in #4554

**Comment by MridulS** [comment]
This is really interesting! +1 on having this run as a cron-job or something on the master branch.

**Comment by rossbar** [comment]
Okay, I moved the workflow from being triggered on PR/push events to a scheduled one. The only problem is that [the GH workflow docs](https://docs.github.com/en/actions/guides/about-continuous-integration#notifications-for-workflow-runs) make it seem like I will be the only one who sees notifications about failures (since I'm creating the action). It would be nice if there were a way for other people to subscribe to such notifications, but if I read these docs right it seems like it only goes to the person who last modified the scheduled workflow.

**Comment by stefanv** [comment]
We may have to add a manual notification step a-la https://github.com/marketplace/actions/send-email

**Review by MridulS — APPROVED** [review]
Let's get this in 🎉 
The circleci failure seems unrelated.

**Review by dschult — APPROVED** [review]

**Comment by MridulS** [comment]
I'll go ahead and merge this and get the cron job up and running on github actions. Let's see if we find more test failures :)

**Pull request merged**
