### PR TITLE
`weisfeiler_lehman_graph_hash`: add `not_implemented_for("multigraph")` decorator

### PR DESCRIPTION
**Pull request by PhilippvK**
See Issue #7593 for context
CC @dschult

### CODE REVIEW

**Review by rossbar — APPROVED** [review]
+1 for this change given the discussion in #7593 . Thanks @PhilippvK !

**Comment by dschult** [comment]
The Issue talks about nx.Graph working and nx.MultiDiGraph not working. The PR checks for multigraphs. But what about directed graphs?  If we want to rule those out until we find an algorithm, we should put two `not_implemented_for` decorators, one for "directed" and one for "multigraph". ([examples here](https://networkx.org/documentation/stable/reference/generated/networkx.utils.decorators.not_implemented_for.html))

Of course, if this algorithm "just works" for directed graphs then we don't need to do that. I haven't checked if DiGraph makes something that works.

**Comment by PhilippvK** [comment]
@dschult It seems like the algorithm just uses `G.neighbors(node)` (aka. `successors`) to build the neighborhood hashes. In-edges are ignored making it somehow aware of directions. I did some quick tests and it seems like the resulting hashes for DiGraphs are meaningful.

**Comment by PhilippvK** [comment]
I realized that `weisfeiler_lehman_subgraph_hashes` needs the decorator as well, hence I pushed another commit to that PR just now.

**Review by dschult — APPROVED** [review]
Thanks very much for this @PhilippvK !!

**Pull request merged**
