### PR TITLE
Add release notes

### PR DESCRIPTION
**Pull request by mlissner**
A huge reason people come to your repo is to find the release notes. I see that you're using the Releases feature of Github, but it seems to be just a summary of fixed bugs and note release notes, per se. The website seems a lot better, but takes some hunting to find, so I put the link here.

I hope this helps!

### CODE REVIEW

**Comment by mlissner** [comment]
Looks like circle CI is broken, but that shouldn't affect this PR>

**Comment by jarrodmillman** [comment]
If we are going to have a link to the release notes, should we link to the developer release notes? If so, we should manually edit the README when we make releases, since the PyPI page will link to README and that means if we don't update this link during releases the link will be incorrect. I would prefer not needing to manually updating the README for every release (we are trying to make the release process less complicated). But if we are going to merge this PR, we should update the release process notes.

The list of links is already getting long for me taste. The release notes are prominently linked on the homepage and documentation. But I don't have a strong objection if others think it is too difficult to find the release notes.

**Comment by dschult** [comment]
It seems to me that the documentation pages have a "Releases" tab at the top of each page. So maybe this isn't needed?

One downside (as I understand it) is that linking in Readme.rst to the stable (or latest) version of the release notes adds an extra step when uploading to Pypi so that the link on resulting page on Pypi (built from info on Readme.rst) goes to a specific version's release notes instead of the generic "stable" version which changes over time.

Another downside is the more crowded Readme page.

I think this PR does show that the Github Releases feature is suboptimal because it doesn't give the full release notes -- only the list of commits and contributors. Maybe we should stop using that feature? Or maybe we should make it provide the full release notes as stored in the repo. (I don't know if that is possible and I'm reluctant to spend dev time on it.)

**Review by rossbar — COMMENTED** [review]
I'm -1 on this - I prefer a minimal README and we certainly don't want to encourage anyone to pay *more* attention to the github releases feature. The release notes are featured very prominently in the [documentation](https://networkx.org/documentation/latest/) (see the `Releases` tab in the navbar, which is always visible), and I think the documentation is a much preferred portal for users than the info in github.

**Comment by rossbar** [comment]
I will go ahead and close this since most reviewers are against the proposed change. Thanks for the suggestion @mlissner !

**Pull request closed without merging**
