### PR TITLE
#6571 laplacian_centrality not working for graphs with single nodes

### PR DESCRIPTION
**Pull request by pkuppens**
My first pull request, so I fixed a simple issue to get acquainted with contributing.

It seems to be an issue that A_2 becomes degenerate, and the new_energy formula fails.
A simple if check prevents this failure and provides a default value of 0.0.

I provided test cases to validate that the error was still present before the fix and that the problem was solved with the fix.

@rossbar @PurviChaurasia @Qudirah @navyagarwal - I hope this helps and does not get in your way - I would love to become an official contributor to networkx!

### CODE REVIEW

**Comment by navyagarwal** [comment]
This issue has been discussed in #6626 

When `normalized=True` and `full_energy=0`, I'm not sure if it is a good idea to return a zero value for Laplacian centrality since the mathematical formula does not provide a valid value for the given graph. I suggested to raise an exception that explains the behavior.

BUT if we consider the definition that Laplacian centrality is a _measure of drop in Laplacian Energy of graph when the particular node is removed_, it can be reasoned that since the initial energy of graph is zero, removing any node of the graph will have no effect whatsoever on the Laplacian Energy, thus zero values for Laplacian centrality make sense.

For the case with single nodes, there is a suggestion [here](https://github.com/networkx/networkx/issues/6626#issuecomment-1512170299) that is consistent with the changes made in this PR, but the reasoning behind it is different.

**Comment by pkuppens** [comment]
> This issue has been discussed in #6626
> 
> ...

Thanks, I wasn't aware of this discussion yet, and have made some changes to the code to reflect the remarks.

1. I added a test case for the empty graph, raising an exception NetworkXPointlessConcept
2. I also raised this exception - not finding/wanting to implement a better one - for the edgeless graphs with normalization
3. I think that returning 0.0 when normalized=False should be OK for all unconnected/edgeless graphs, including the single node one, in line with Aaronzo's remark.

**Comment by pkuppens** [comment]
Fixes #6571, #6626, #6565

**Comment by pkuppens** [comment]
Thought a 'Close' would kick off a final CI/CD pipeline before merging to main, but apparently not.
This PR is replaced with: [https://github.com/networkx/networkx/pull/6664](https://github.com/networkx/networkx/pull/6664)

**Pull request closed without merging**
