### PR TITLE
Fixed wrong dict factory usage on MultiDiGraph

### PR DESCRIPTION
**Pull request by FabianBall**
Fixed the issue that the wrong dict factory on a MultiDiGraph was used for edge attributes (edge_key_dict_factory instead of edge_attr_dict_factory)

Extended tests to typecheck the dict factories and added a test that incorporates custom dict factories on a MultiDiGraph

### CODE REVIEW

**Review by dschult — APPROVED** [review]
This looks great @FabianBall !   Thanks very much!

The test for Mypy relates to changing the type of the default factories and following #5127 shows that mypy doesn't deal with these well. I'll leave it to @rossbar @stefanv and @NeilGirdhar to figure out whether we should set this up to be ignored or perhaps there is a better way to finesse the type checking rules. 

I believe this is ready to go other than mypy -- so I'm approving it.

**Review by rossbar — APPROVED** [review]
I spent some time looking at this and couldn't find any obvious, non-invasive way to make mypy happy so I went with the solution in #5127 and added `# type: ignore` to all the subclass `_factory` attributes. There may be a way to "turn off" the attribute-type-inference-from-parent feature in mypy globally, but it shouldn't be a blocker here.

Everything else LGTM, thanks @FabianBall that was a very nice catch and the updated/new tests are excellent!

**Comment by FabianBall** [comment]
Perfect, glad I could help. I surely would not have stumbled across the issue if I had not have used the feature...

**Comment by NeilGirdhar** [comment]
> I spent some time looking at this and couldn't find any obvious, non-invasive way to make mypy happy so I went with the solution in https://github.com/networkx/networkx/pull/5127 and adde

I annotated them here: https://github.com/neilgirdhar/networkx/tree/annotations

However, the real problem is that callable class variables is just awkward design.  And setting those class variables as member variables is the constructor is even more awkward.  The ordinary way to accomplish this is with ordinary methods that subclasses can overload.  This seems to me like over-optimization, but perhaps there examples where it makes a significant difference.

**Comment by danieleades** [comment]
see #5890

**Pull request merged**
