### PR TITLE
use issue templates to redirect to discussions tab, add a bug report template

### PR DESCRIPTION
**Pull request by MridulS**
Users will see a screen which asks them to make a choice between `Bug Report`, `Q-A`, `Discussions`, `Blank Issue` when they click on the `new issue` button on GitHub.

### CODE REVIEW

**Comment by dschult** [comment]
It would be nice to have them triage in this way.
Do we need to change our email notifications to see the new posting locations?

**Comment by jarrodmillman** [comment]
Does ``.github/ISSUE_TEMPLATE/bug_report.md`` replace ``.github/PULL_REQUEST_TEMPLATE.md``.  I thought we decided to keep this short and focused on black.  My experience is that most people (me included) just delete longer forms like ``.github/ISSUE_TEMPLATE/bug_report.md``.  If we do decide to use a longer form, I think we should still include the statement about formatting the code using black.

**Comment by jarrodmillman** [comment]
Is there a way to see what this is like before merging?  For example, if you enable issues on your networkx fork, would we be able to test the new functionality on this page:
- https://github.com/MridulS/networkx/tree/issue_template

?

**Comment by MridulS** [comment]
`.github/ISSUE_TEMPLATE/bug_report.md` is to control the `new issue` button.
`.github/PULL_REQUEST_TEMPLATE.md` is encountered when a user creates a new PR.

This is how this will look like: https://github.com/MridulS/networkx/issues/new/choose

@dschult discussions notifications should be turned on by default by people who are `watching` the repo for all activities?

**Comment by jarrodmillman** [comment]
(Sorry, I was confused about the PR vs issue thing.)

I like https://github.com/MridulS/networkx/issues/new/choose!  I am curious what folks think about the bug report template.  Of course it may be best to just try it and see how often it filled in.  Once we get some experience with how useful it is, we can review the template/form for bug reports.  So I am tentatively +1 on this PR as is.  Before officially "appoving" this, I will wait a few hours to see if you get anymore feedback.

**Comment by stefanv** [comment]
I like the choosing page too!

With bug templates, a lot of reporters will just delete it---but I guess it's helpful for people who are not used to filing bugs.  It's hard to set up a template that fits all scenarios: sometimes you need to know very little about a bug (yeap, that's a segfault) and other times you really need much more information.  I think Python and NX version are very reasonable to include, though.

**Review by jarrodmillman — APPROVED** [review]

**Review by rossbar — APPROVED** [review]
I also like the choosing page - funneling Q&A etc. to the discussions is really nice. Overall I think this is a really nice improvement, thanks @MridulS !

**Pull request merged**
