### PR TITLE
Optimize _plain_bfs functions

### PR DESCRIPTION
**Pull request by Tortar**
Optimization of _plain_bfs for undirected graphs through the same principles described in #6299 and #6337.

This is a table which summarizes the new times in relation to the old ones for some graphs, as you can see there are some huge improvements in performance :-)

```
+--------------------------------------------------------+--------------------+---------------+--------------+
|                         graph                          | time: current main | time: this pr | times faster |
+--------------------------------------------------------+--------------------+---------------+--------------+
|     nx.random_regular_graph(d=1, n=10, seed=4241)      |        0.0         |      0.0      |     2.91     |
|     nx.random_regular_graph(d=9, n=10, seed=4241)      |        0.03        |      0.0      |     12.3     |
|    nx.random_regular_graph(d=10, n=100, seed=4241)     |        0.29        |      0.03     |     9.94     |
|    nx.random_regular_graph(d=99, n=100, seed=4241)     |        1.67        |      0.02     |    109.89    |
|    nx.random_regular_graph(d=1, n=1000, seed=4241)     |        0.0         |      0.0      |     2.7      |
|    nx.random_regular_graph(d=3, n=1000, seed=4241)     |        1.75        |      0.31     |     5.7      |
|    nx.random_regular_graph(d=10, n=1000, seed=4241)    |        2.91        |      0.28     |    10.58     |
|    nx.random_regular_graph(d=50, n=1000, seed=4241)    |        6.94        |      0.27     |    25.98     |
|   nx.random_regular_graph(d=100, n=1000, seed=4241)    |       13.59        |      0.26     |    52.84     |
|   nx.random_regular_graph(d=200, n=1000, seed=4241)    |       29.19        |      0.25     |    118.5     |
|   nx.random_regular_graph(d=500, n=1000, seed=4241)    |        85.0        |      0.21     |    405.64    |
|   nx.random_regular_graph(d=700, n=1000, seed=4241)    |       121.13       |      0.18     |    667.0     |
|     nx.erdos_renyi_graph(n=100, p=0.9, seed=4241)      |        1.09        |      0.01     |    95.36     |
|     nx.erdos_renyi_graph(n=1000, p=0.8, seed=4241)     |       107.46       |      0.17     |    624.35    |
| nx.watts_strogatz_graph(n=100, k=10, p=0.3, seed=4241) |        0.2         |      0.02     |     8.34     |
|           nx.connected_caveman_graph(100,10)           |        1.92        |      0.43     |     4.52     |
|                nx.caveman_graph(100,10)                |        0.02        |      0.01     |     3.99     |
|               nx.windmill_graph(10, 10)                |        0.18        |      0.01     |    18.01     |
|               nx.full_rary_tree(3, 1000)               |        1.09        |      0.14     |     7.86     |
|                 nx.complete_graph(100)                 |        1.2         |      0.01     |    110.49    |
|                 nx.complete_graph(10)                  |        0.02        |      0.0      |    11.63     |
|                  nx.cycle_graph(100)                   |        0.11        |      0.02     |     6.25     |
|                   nx.cycle_graph(10)                   |        0.01        |      0.0      |     5.44     |
+--------------------------------------------------------+--------------------+---------------+--------------+
```

<details> <summary> Code to recreate the benchmark table</summary>

```python
import timeit, prettytable

def _plain_bfs(G, source):
    """A fast BFS node generator

    The direction of the edge between nodes is ignored.

    For directed graphs only.

    """
    Gsucc = G.succ
    Gpred = G.pred
    seen = set()
    nextlevel = {source}
    while nextlevel:
        thislevel = nextlevel
        nextlevel = {}
        for v in thislevel:
            if v not in seen:
                seen.add(v)
                nextlevel.update(Gsucc[v])
                nextlevel.update(Gpred[v])
                yield v

def _plain_bfs_2(G, source):
    """A fast BFS node generator

    The direction of the edge between nodes is ignored.

    For directed graphs only.
    """
    Gsucc = G._succ
    Gpred = G._pred
    n = len(G)
    seen = set()
    nextlevel = [source]
    yield source
    while nextlevel:
        thislevel = nextlevel
        nextlevel = []
        for v in thislevel:
            for w in Gsucc[v]:
                if w not in seen:
                    seen.add(w)
                    nextlevel.append(w)
                    yield w
            for w in Gpred[v]:
                if w not in seen:
                    seen.add(w)
                    nextlevel.append(w)
                    yield w
            if len(seen) == n:
                return

graphs = [  "nx.random_regular_graph(d=1, n=10, seed=4241)", "nx.random_regular_graph(d=9, n=10, seed=4241)",
            "nx.random_regular_graph(d=10, n=100, seed=4241)", "nx.random_regular_graph(d=99, n=100, seed=4241)",
            "nx.random_regular_graph(d=1, n=1000, seed=4241)", "nx.random_regular_graph(d=3, n=1000, seed=4241)",
            "nx.random_regular_graph(d=10, n=1000, seed=4241)", "nx.random_regular_graph(d=50, n=1000, seed=4241)",
            "nx.random_regular_graph(d=100, n=1000, seed=4241)", "nx.random_regular_graph(d=200, n=1000, seed=4241)",
            "nx.random_regular_graph(d=500, n=1000, seed=4241)", "nx.random_regular_graph(d=700, n=1000, seed=4241)",
            "nx.erdos_renyi_graph(n=100, p=0.9, seed=4241)", "nx.erdos_renyi_graph(n=1000, p=0.8, seed=4241)",
            "nx.watts_strogatz_graph(n=100, k=10, p=0.3, seed=4241)", "nx.connected_caveman_graph(100,10)",  
            "nx.caveman_graph(100,10)",  "nx.windmill_graph(10, 10)", "nx.full_rary_tree(3, 1000)",  
            "nx.complete_graph(100)", "nx.complete_graph(10)",  "nx.cycle_graph(100)", "nx.cycle_graph(10)" ]

stmt_1 = "a = list(_plain_bfs(G, random.randrange(len(G)-1)))"
stmt_2 = "b = list(_plain_bfs_2(G, random.randrange(len(G)-1)))"
table = prettytable.PrettyTable()
table.field_names = ["graph", "time: current main", "time: this pr", "times faster"]

for graph in graphs:
    setup_1 = "import networkx as nx; import collections, random; from __main__ import _plain_bfs; random.seed(4241); G = {}".format("nx.DiGraph(" +graph+")")
    setup_2 = "import networkx as nx; import collections, random; from __main__ import _plain_bfs_2; random.seed(4241); G = {}".format("nx.DiGraph(" +graph+")")
    main_time = timeit.timeit(stmt_1, setup_1, number=500)
    pr_time = timeit.timeit(stmt_2, setup_2, number=500)
    a, b, c, d = graph, round(main_time,2), round(pr_time,2), round(main_time/pr_time, 2)
    table.add_row([a, b, c, d])
    print(d)
print(table)
```

</details>

### CODE REVIEW

**Comment by Tortar** [comment]
Implemented the same thing for the other `_plain_bfs` function for undirected graphs in `connected.py`, the corresponding benchmark table is

```
+--------------------------------------------------------+--------------------+---------------+--------------+
|                         graph                          | time: current main | time: this pr | times faster |
+--------------------------------------------------------+--------------------+---------------+--------------+
|     nx.random_regular_graph(d=1, n=10, seed=4241)      |        0.0         |      0.0      |     1.17     |
|     nx.random_regular_graph(d=9, n=10, seed=4241)      |        0.01        |      0.0      |     2.67     |
|    nx.random_regular_graph(d=10, n=100, seed=4241)     |        0.09        |      0.05     |     1.71     |
|    nx.random_regular_graph(d=99, n=100, seed=4241)     |        0.17        |      0.02     |     9.97     |
|    nx.random_regular_graph(d=1, n=1000, seed=4241)     |        0.0         |      0.0      |     1.17     |
|    nx.random_regular_graph(d=3, n=1000, seed=4241)     |        0.84        |      0.72     |     1.16     |
|    nx.random_regular_graph(d=10, n=1000, seed=4241)    |        0.86        |      0.65     |     1.31     |
|    nx.random_regular_graph(d=50, n=1000, seed=4241)    |        1.38        |      0.5      |     2.75     |
|   nx.random_regular_graph(d=100, n=1000, seed=4241)    |        1.94        |      0.34     |     5.76     |
|   nx.random_regular_graph(d=200, n=1000, seed=4241)    |        2.37        |      0.31     |     7.65     |
|   nx.random_regular_graph(d=500, n=1000, seed=4241)    |        5.1         |      0.26     |    19.43     |
|   nx.random_regular_graph(d=700, n=1000, seed=4241)    |        6.97        |      0.23     |    30.47     |
|     nx.erdos_renyi_graph(n=100, p=0.9, seed=4241)      |        0.12        |      0.02     |     7.26     |
|     nx.erdos_renyi_graph(n=1000, p=0.8, seed=4241)     |        7.34        |      0.21     |    35.41     |
| nx.watts_strogatz_graph(n=100, k=10, p=0.3, seed=4241) |        0.06        |      0.04     |     1.43     |
|           nx.connected_caveman_graph(100,10)           |        0.63        |      0.74     |     0.85     |
|                nx.caveman_graph(100,10)                |        0.01        |      0.01     |     0.85     |
|               nx.windmill_graph(10, 10)                |        0.05        |      0.02     |     2.87     |
|               nx.full_rary_tree(3, 1000)               |        0.48        |      0.33     |     1.47     |
|                 nx.complete_graph(100)                 |        0.13        |      0.01     |    10.34     |
|                 nx.complete_graph(10)                  |        0.01        |      0.0      |     1.9      |
|                  nx.cycle_graph(100)                   |        0.06        |      0.05     |     1.1      |
|                   nx.cycle_graph(10)                   |        0.01        |      0.01     |     1.21     |
+--------------------------------------------------------+--------------------+---------------+--------------+
```

**Comment by dschult** [comment]
This might be better with inputs `_plain_bfs(adj, source)` rather than `(G, source)`. That way functions that need to search a directed graph backwards can use it by inputing `G.pred`.  It does mean each place we call it we'll have to use update the call from using `G`.  

I'd be interested in seeing a comparison between calling it with `G.adj` and calling it with `G._adj`. `G.adj` is a view on `G._adj` so is perhaps slower, and since this function never updates G there is no risk of exposing the internal data structure to corruption.  (See #4895)

**Comment by Tortar** [comment]
Regarding your first observation, but then we should run two different bfs with the two inputs (G.pred, G.succ) right? This could have some performance degradation effects, what do you think?

Regarding `G._adj` I think that the comparison should be more or less the same as the one in #6299, so it should be very good to call `G._adj`! Is there something equivalent for `G.pred`?

**Comment by dschult** [comment]
I was wrong --- These functions are already restricted to being undirected (the one in connected.py) and directed (the one in weakly_connected.py).  So we should just input G as we currently do. As you point out, we'd have to call it twice (or with a `UnionAtlasView` of both G.pred and G.succ) and this is a better interface.

Looking at the `DiGraph.__init__` method you'll see that G.succ and G.pred are views of the dicts G._succ and G._pred.  So, to implementing this idea of using `G._adj` internally will amount to replacing `G.adj[u]` or `G[u]` with `G._adj[u]` and similarly replacing `G.succ[u]` with `G._succ[u]` and `G.pred[u]` with `G._pred[u]`.

The views are nice because they protect the user from messing up the data structure, but they are slower.

**Comment by Tortar** [comment]
oh didn't know about that (actually I'm new to Newtworkx internals :-)). Anyway I updated all the PRs reflecting your suggestions, I also updated the tables, all show other boost in performance!

**Comment by Tortar** [comment]
Is there something else to do in these PRs @dschult?

**Comment by Tortar** [comment]
bump

**Review by boothby — APPROVED** [review]

**Review by dschult — APPROVED** [review]
Thanks for this!  
Glad its finally getting the review time it deserves! :}

**Comment by boothby** [comment]
Agreed, I applaud the effort to improve the performance of these functions in specific.  They form the backbone of so many algorithms throughout the library; a little elbow grease here goes a long way!

**Pull request merged**
