### PR TITLE
Add functions to compute Schultz and Gutman Index

### PR DESCRIPTION
**Pull request by jangwon-yie**
It contains implementations of first, second kinds of Schultz index and their unit cases. Please give me any comments so that it will be merged to the main branch. Thanks.

### CODE REVIEW

**Comment by dschult** [comment]
The Schultz index, and Gutman index (second type of schultz index) are related to the Wiener Index and Kirchoff Index (https://hrcak.srce.hr/132323).  All four (and others) are used as markers of chemicals based on the molecular network of atoms connected by chemical bonds. 

The functions provided here can be improved and updated. The file structure, doc_strings and tests seem pretty good. I think they should be moved into the module `wiener.py` and probably connected to the kirchoff index if we ever get that.  Maybe they should all go into a distance module as suggested in #6975 but for now we can put these into `wiener.py`.

**Review by dschult — APPROVED** [review]
I'll go ahead and approve this -- mostly to let you know that it is ready to be reviewed.
Do we want these functions? Is this the right place?

**Comment by peijenburg** [comment]
The functions seem useful and appropriate for NX.
I would advocate to move all functions to Distance measures.

**Comment by dschult** [comment]
These measures involve both distances between nodes and the degree of the nodes. Can you say why you tink they should all be contained within the ditance_measures.py module?

**Comment by rossbar** [comment]
IMO adding these actually motivates keeping a separate module for the related indices. From the user perspective it should be a moot point as users are encouraged to call indices from the top level namespace rather than go spelunking through the package hierarchy. In other words, it's largely an implementation detail that shouldn't hold anything up in this PR!

**Review by rossbar — APPROVED** [review]
I took the liberty of pushing up a few minor docstring tweaks, but otherwise LGTM. Thanks @jangwon-yie !

I'm certainly no expert, but I'm in favor of adding these indices - they're straightforward computations and seem to be generic measures of graph properties!

**Pull request merged**
