### PR TITLE
Coappearance network of characters in the novel Les Miserables

### PR DESCRIPTION
**Pull request by Moradnejad**
This is a pull request to add a new real famous social network: Coappearance network of characters in the novel Les Miserables.
I added it to the list too, alongside its reference. Please review.

I was doing a research and wanted to use real networks. Although the other ones have been used largely, but they were all small-sized networks. This is not so big either, but somehow more compelling.

### CODE REVIEW

**Comment by Moradnejad** [comment]
I can write add the regression tests for this graph, too. I wanted to wait for an initial response.

@dschult

**Comment by dschult** [comment]
I'm fine for adding this graph to that module. Looks good.  Add a note that you're ready to merge when that's the case.  Thanks!

**Comment by ericmjl** [comment]
@Moradnejad thank you for the contribution! Yes, could you please add a regression test for this graph?

**Comment by Moradnejad** [comment]
@ericmjl  @dschult Thanks. I will.

**Comment by Moradnejad** [comment]
I added a few tests similar to other real-life graphs. @dschult @ericmjl 

This test is failing: `test_from_edgelist_invalid_attr`. I don't know why!
> AssertionError: NetworkXError not raised by from_pandas_edgelist

**Comment by ericmjl** [comment]
@dschult I'm not quite familiar with this part of the code base, so this is a learning opportunity for me as well. Is a NetworkXError supposed to be raised somewhere here?

**Comment by ericmjl** [comment]
Ok, thanks a lot, @dschult! Just to double-check, I restarted the build job to see if it'll consistently error the same way. I'll double-check according to your instructions.

**Comment by ericmjl** [comment]
@dschult, confirming that the aforementioned error is the only error in the test suite. Merging in.

**Comment by ericmjl** [comment]
Thank you, @Moradnejad, for the contribution! I am also sure that other real-world graphs are welcome too!

**Pull request merged**
