### PR TITLE
Curved lines in loops for digraphs

### PR DESCRIPTION
**Pull request by ferdavid1**
added the boolean parameter 'draw_loop' to nx.draw() that uses simple_cycles() to find cycles in a directed graph, then makes curves the edges that make up the cycle, for aesthetic purposes. first PR, let me know how I can improve! 
Example:
circ

### CODE REVIEW

**Comment by ferdavid1** [comment]
Not sure why codecov/patch is failing, didn't change anything other than nx_pylab.py

**Comment by dschult** [comment]
That just means that the tests only covered 88% of the code (well...  88% of the code was actually run while doing the tests).  The drawing routines often have lower coverage than the rest of the codebase. I guess you could add tests for "corner cases" to make sure more code is reached during the tests. But I wouldn't worry about it too much.  We can review and merge even with the coverage goals not passing.

**Comment by ferdavid1** [comment]
@dschult that makes sense, thank you!

**Comment by ferdavid1** [comment]
@dschult excess files removed from this one too.

**Comment by dschult** [comment]
The drawloop PR now has the Betti number change in it.

**Comment by ferdavid1** [comment]
@dschult thanks, fixed part 2.

**Comment by dschult** [comment]
This needs tests and thoughts of how universal the choice of angles on the loop work.

**Comment by dschult** [comment]
Does #3307 make this obsolete/unnecessary?  If not, open it up again.

**Pull request closed without merging**
