### PR TITLE
#1849 add with_data to create_empty_copy

### PR DESCRIPTION
**Pull request by varun-kr**
Please review.

### CODE REVIEW

**Comment by dschult** [comment]
Can you please test changing a node attribute in G and seeing that it doesn't change the attribute in self.G? That's the most common bug I've run into with copying data attributes--that the containers end up being the same rather than copies. As currently written I suspect that the G.graph and self.G.graph are actually pointing to the same dict.

It looks like the nodes get added twice...  but I think there is a way to add nodes with data using ```G.nodes()```

    H.add_nodes_from(G.nodes(data = with_data))
    if with_data:
        H.graph.update(G.graph)

**Comment by varun-kr** [comment]
Apologies . I had pushed the incorrect code. 

I can think of 3 ways to achieve this . 

def create_empty_copy1(G, with_data= True):
    H = G.__class__()
    H.add_nodes_from(G)
    if with_data:
        H.node = deepcopy(G.node)
        H.graph = deepcopy(G.graph)
    return H

def create_empty_copy2(G, with_data= True):
    H = G.__class__()
    if with_data:
        H.add_nodes_from([(node, G.node[node]) for node in G.nodes()])
        H.graph = deepcopy(G.graph)
    else:
        H.add_nodes_from(G)
    return H

def create_empty_copy3(G, with_data= True):
    H = G.__class__()
    if with_data:
        H.add_nodes_from([(node, G.node[node]) for node in G.nodes()])
        H.graph = {k:v for k,v in G.graph.items()}
    else:
        H.add_nodes_from(G)
    return H

Third one is the fastest among these 3 methods. And I have pushed the same . 
Request you to please review.

**Comment by dschult** [comment]
Did you try a version with the methods I suggested above? It avoids creating any lists or dicts explicitly (so might be faster) and it avoids re-assigning the H.graph attribute by updating the existing one. These suggestions might be worse... but I think you should at least try them.

    def create_empty_copy3(G, with_data= True):
        H = G.__class__()
        H.add_nodes_from(G.nodes(data = with_data))
        if with_data:
            H.graph.update(G.graph)
        return H

**Comment by varun-kr** [comment]
Your solution seems more elegant to me. Though it is a little slower than the third solution but it looks nice.  I am pushing the solution suggested by you. Thanks for suggestions.

**Comment by varun-kr** [comment]
@dschult  Please review.

**Comment by varun-kr** [comment]
Thanks .

**Pull request merged**
