### PR TITLE
Docstrings for the small.py module

### LINKED ISSUE #5213: Graph generators in the `small` module need docstrings
There are a number of named graphs defined in `networkx.generators.small` that are not well-documented:

https://github.com/networkx/networkx/blob/766becc132eda01c9d0d458de2d75ab763f83493/networkx/generators/small.py#L183-L575

Each of these functions should have a more extensive docstring with at least a `Parameters`, `Returns`, and `Examples` section, and preferably also a reference to the corresponding paper or wiki page that describes the graph.

### PR DESCRIPTION
**Pull request by aramasethu**
Added docstrings in small.py with `Description`, `Parameters`, `Returns`, `References`  sections explaining the graphs.

Fixes #5213

### CODE REVIEW

**Comment by aramasethu** [comment]
The branch name is: docstrings-for-issue-5123 but the issue it is fixing is 5213. Apologies for the mix up in the branch name

**Review by dschult — COMMENTED** [review]
This looks good!  Thanks!!

Here's a very minor question.  For the return type should it be `networkx Graph` or `networkx graph`.  I know that the capital letter is not much. But does `Graph` mean specifically the Graph class, while `graph` means any of the graph classes? Thoughts?

**Comment by aramasethu** [comment]
Sorry about the mix up in the `networkx  Graph` and `networkx  graph`. I agree that it should be made uniform and should be changed to `networkx  graph` instead.

**Review by rossbar — APPROVED** [review]
Thanks very much for this @aramasethu - the updates to the docstrings are universally an improvement IMO and sufficient to close #5213. I took the liberty of pushing up a few additional changes (e.g. some minor grammatical nits, fixing the syntax for references) but this LGTM to go in as-is. Thanks!

**Review by MridulS — APPROVED** [review]
Thanks @aramasethu!

**Pull request merged**
