### PR TITLE
Updated formatting for __init__.py

### LINKED ISSUE #2189: Formatting doesn't comply with PEP 8
I'll try to submit some PR's for this. It's fine if you don't accept them.

### PR DESCRIPTION
**Pull request by CrazyPython**
Updated formatting to conform with PEP 8 .

`Using` -> `Usage`; grammar (?) correction.

Helps fix #2189

### CODE REVIEW

**Comment by CrazyPython** [comment]
It appears that it may be interfering with Coveralls a bit. I don't know how Coveralls works, so I could use some help patching my PR a bit.

**Comment by hagberg** [comment]
Please don't change the copyright dates without reason.

**Comment by CrazyPython** [comment]
@hagberg I didn't. That was an automatic change.

**Comment by CrazyPython** [comment]
and that's no reason to close the PR

**Comment by CrazyPython** [comment]
@hagberg  fixed it

**Comment by hagberg** [comment]
This kind of pull request just generates work for reviewers with very little benefit so I closed it.

**Comment by CrazyPython** [comment]
@hagberg agreed.

**Pull request closed without merging**
