### PR TITLE
updated cutoff def in weighted.py

### PR DESCRIPTION
**Pull request by AbhayGoyal**
The changes were made to the definition of cutoff param in the weighted.py file

### CODE REVIEW

**Comment by dschult** [comment]
For the failing style / format test, you just need to install black
```
pip install black
```
and run it on the files you are changing. You can automate this using a pre-commit hook
```
pip install -r requirements/developer.txt
pre-commit install
```
More details about contributing to NX are available here:
https://networkx.org/documentation/latest/developer/contribute.html

**Comment by AbhayGoyal** [comment]
> and run it on the files you are changing. You can automate this using a pre-commit hook
> 
> ```
> pip install -r requirements/developer.txt
> pre-commit install
> ```
> 
Could you please tell me how to use the hook? I am trying to understand where should I use it so that it can automatically be taken care of.
Thanks

**Comment by dschult** [comment]
After installing `pre-commit`, each time you use `git commit` it will run black before accepting the changes. If black finds the style acceptable the commit completes as usual. If black finds style issues, it automatically makes the changes and stops the commit process. You can check (or not) the changes and then commit again. 

Personally I like to use `black --diff filename` to see what is being suggested before I rely on the pre-commit hook. But that's my personality more than any specific reason for doing it. I just don't like black changing things and not telling me what it changed. :}

**Comment by AbhayGoyal** [comment]
I installed black and then tried to commit again. It still shows the styling error

**Comment by dschult** [comment]
Hmmm...  Something is strange

It looks like you commit still has two lines with spaces and no letters. `black` replaces those with blank lines.  But it should do this as you commit... 

It's hard to know what is going on without more info.  So try running black locally:  `black weighted.py`
The commit that change (if there is one).

**Comment by MridulS** [comment]
`black` seems happy now, failed tests are due to the recent `yaml` issue. Should be fixed after https://github.com/networkx/networkx/pull/4548 is merged.

**Pull request merged**
