### PR TITLE
Fixes #5012 implementation of newman watts strogatz graph inconsistent with model

### LINKED ISSUE #5012: Implementation newman_watts_strogatz_graph
I believe that the `newman_watts_strogatz_graph` function incorrectly implements this network model. In the current implementation, self-loops and multi-edges are not allowed. However the paper by Newman and Watts stated "we also explicitly allow there to be more than one bond between any two vertices, or a bond which connects a vertex to itself." The original contributor seems unsure by commenting "is that the correct NWS model?" 

The problem seemingly comes from an incorrect citation. Right now the reference used is:
Newman, M.E.J., Watts, D.J.: Renormalization group analysis of the small-world network model, Physics Letters A, 263, 341, 1999. https://doi.org/10.1016/S0375-9601(99)00757-4
which in fact uses the original Watts-Strogatz model, not the Newman-Watts variant.
The correct citation in which the Newman-Watts variant was proposed should be:
Newman, M.E.J., Watts, D.J.: Scaling and percolation in the small-world network model. Phys.Rev. E60(6), 7332–7342 (1999). https://doi.org/10.1103/PhysRevE.60.7332
The aforementioned citation is in section II, paragraph 4 of the latter.
I guess the confusion might have come from these papers having the exact same author and year.

To make sure it's not a difference in naming convention, I looked at several publications that uses the Newman-Watts model and confirmed they all uses the version that allows self-loops and multi-edges. But I hope someone can look into the references and double check for me. 

If it's indeed a problem, it would be easy to fix the code: when initializing the graph, set `create_using` to `nx.multigraph()`, and getting rid of the lines that rejects self-loops or multi-edges. I have the code ready, but I'm contributing for the first time and still setting up my fork. 

Thanks to Dan Schult for redirecting me here and for suggestions on setting up git!

### PR DESCRIPTION
**Pull request by mingxuan-he**
This PR fixes issue #5012 by modifying the implementation to allow multi-edges and self-loops in the model. The description for the Newman-Watts-Strogatz algorithm can be found in: Newman, M.E.J., Watts, D.J.: Scaling and percolation in the small-world network model. Phys.Rev. E60(6), 7332–7342 (1999). https://doi.org/10.1103/PhysRevE.60.7332

Also adds a simple test for the other extreme case p=1.

### CODE REVIEW

**Comment by dschult** [comment]
I have looked into this description and agree with many items. The newly cited paper provides a better description of how to handle the question of selfloops and multiedges than the current citation in NetworkX. Unfortunately it is also different from our current function and that will cause backward incompatibility. Note that the current implementation is not incorrect given the less precise description in the currently cited paper.  I also notice that the name involves 3 authors and neither paper is written by `strogatz`.

I suggest that we implement this change as follows:
- retain the current function `newman_watts_strogatz_graph` and add words in the doc_string to describe how self-loops and multiedges are avoided. It should also "see also" the new function described next.
- create a new function (perhaps `newman_watts_graph` ?) that returns a MultiGraph and handles the selfloops and multiedges as in the cited paper suggested by this PR.

What do you think? It avoids backward incompatibility by keeping the simple graph interpretation available, yet makes the analytically tractable version available too.

**Comment by mingxuan-he** [comment]
That's a great suggestion! I'll work on it

**Comment by rossbar** [comment]
Gentle ping @mingxuan-he - are you still working on this one?

**Comment by MridulS** [comment]
@mingxuan-he thanks for the PR!

This hasn't been touched in a while. I'll go ahead and close this. Feel free to send a new PR :)
Thanks!

**Pull request closed without merging**
