### PR TITLE
Add weight functions to bidirectional_dijkstra and astar

### PR DESCRIPTION
**Pull request by boothby**
See discussion in #3754 and #3774.

Knock-on benefits: 
1. Uncovered/fixed an inconsistency in Bellman-Ford (easy 1-line fix)
2. Added support for multigraphs in `astar`

### CODE REVIEW

**Comment by dschult** [comment]
small tweak -- I think this came from bellman-ford, but it is not needed.

```G_succ = G._succ if G.is_directed() else G._adj``` . Should be just ```G_succ = G._adj```

It's not needed because ```G._adj``` is always ```G._succ``` for directed graphs. It was designed that way so you can just use ```G._adj``` for successors whether G is directed or undirected.

**Comment by boothby** [comment]
Thanks for the heads-up!  I'll fix that sometime tonight or tomorrow.

**Comment by dschult** [comment]
This looks good.  Anything else before its merged?

**Comment by boothby** [comment]
Thanks!  I've got nothing else to add

**Comment by boothby** [comment]
Trawling old tickets, I found #717, which is coincidentally addressed by commit d5aa0e8

**Comment by cmkpl** [comment]
I can see from the docs of 2.5rc1.dev_20200420161240, it seems that the function astar_path still only accept string for the parameter weight

**Pull request merged**
