### PR TITLE
Ignore formatting changes with black, pep8 for git blame

### PR DESCRIPTION
**Pull request by MridulS**
I picked up commits from the history of main branch which did a bunch of formatting changes with black. I also added some other commits like https://github.com/networkx/networkx/commit/be23fa0e422b51f4526828cb19b8105c89e5dcbb which was for compliance with PEP8.

We can merge this in and people locally using black with `.git-blame-ignore-revs` configured should be able to use this. We need to wait for GitHub to enable this all public wide to use this on the Github UI.

Closes https://github.com/networkx/networkx/issues/5382

### CODE REVIEW

**Comment by rossbar** [comment]
I'm +1 for this but was just wondering if there was a way to preview the effects before merging? This is probably one of those "doesn't take effect until it's on `main`" type of changes, but just out of curiosity - if you merge this to `main` on your fork and look at the blame in the browser, do you see the difference?

**Review by jarrodmillman — APPROVED** [review]

**Comment by rossbar** [comment]
> Currently this doesn't work on github! it's still under a private "public beta".

Thanks, I hadn't realized :+1: 

Generally this LGTM though I think we may want to start with a smaller subset of commits. For example, `git show 0c503e31ba` (the first one on the list) has a lot of changes from `pyupgrade`, but also includes some test re-organization that got squashed into that PR. When in doubt, I'd vote to keep commits like this off the list because the downside of silently missing "real" changes in the blame outweighs the benefit of ignoring the changes from linters. Just my two cents though - we can always modify the list of commits later as well!

**Review by rossbar — COMMENTED** [review]
Okay, I went through and checked all the commits (or at least skimmed them) - I think 0c503e is the only one I'd advocate to leave off the list due to a bad/weird squash. Everything else looks good!

**Comment by MridulS** [comment]
@rossbar went ahead and removed 0c503e from the commit list.

**Review by rossbar — APPROVED** [review]
Thanks @MridulS !

**Pull request merged**
