### PR TITLE
Improve legibility of labels in plot_labels_and_colors example

### PR DESCRIPTION
**Pull request by rossbar**
Attempt to improve legibility of labels by:
 * Increasing background alpha and background node size
 * Increasing font size
 * Changing to a light font color to contrast with the red/blue bgnds

### CODE REVIEW

**Comment by jarrodmillman** [comment]
It looks like the gallery example had a bad random seed this time.  So the cube is mangled.

We should probably add seeds to all the layout examples that use randomness (making sure the seed we choose provides pleasant output).

**Comment by rossbar** [comment]
[Original example](https://networkx.github.io/documentation/stable/auto_examples/drawing/plot_labels_and_colors.html#sphx-glr-auto-examples-drawing-plot-labels-and-colors-py) | [This version](https://497-890377-gh.circle-artifacts.com/0/doc/build/html/auto_examples/drawing/plot_labels_and_colors.html#sphx-glr-auto-examples-drawing-plot-labels-and-colors-py).

Now seeded so layout should be consistent each time.

**Review by jarrodmillman — CHANGES_REQUESTED** [review]
And use the tab colors for the edges as well.

**Comment by jarrodmillman** [comment]
I just noticed that the docstring doesn't make sense.
```
Draw a graph with matplotlib, color by degree.
```
Should be something like
```
Color edges and nodes as well as label nodes using Matplotlib.
```

**Comment by rossbar** [comment]
Good catch - I had missed that. I updated the docstring to highlight the use of `nodelist` and `edgelist` to apply styling to subcomponents of a graph.

**Pull request merged**
